### ISSUE TITLE
Truffle contract doesn't support string array function args (ABIEncoderV2)

### ISSUE THREAD

**Issue by mushketyk** [trufflesuite/truffle#1013]
Truffle seems to fail to deploy a contract with the following constructor:

```solidity
pragma solidity ^0.4.0;
pragma experimental ABIEncoderV2;

contract Voter {
    string[] public options;

    constructor(string[] _options) public {
        options = _options;
    }
}
```

It throws the following exception:
```
 Error: VM Exception while processing transaction: revert
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:185:15)
    at IncomingMessage.emit (domain.js:439:23)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
```

If I make the constructor parameterless everything works fine.

Here are my solc and Truffle versions:

```
truffle(develop)>  version
Truffle v4.1.11 (core: 4.1.11)
Solidity v0.4.24 (solc-js)
```

Here is the deployment script that I use:

```javascript
 var Voter = artifacts.require("./Voter.sol");

module.exports = function(deployer) {
  deployer.deploy(Voter, ["one"]);
};
```

**Comment by cgewecke** [comment]
@mushketyk Truffle contract uses web3 which is in the middle of adding support for ABIEncoderV2. That work is being tracked [here](https://github.com/ethereum/web3.js/issues/1241). 

The upcoming major Truffle release (about a month away) will use web3 1.0 and contain whatever new ABI support is available then. 

You might be interested in [ethers.js](https://github.com/ethers-io/ethers.js/) - truffle migrate doesn't have an integration with it but you can require your truffle artifacts into a script run by [truffle exec](http://truffleframework.com/docs/getting_started/scripts) and have all the basic information you need to interact with that lib:
```javascript
Voter.abi
Voter.binary
```

Hope you don't mind - I'm going to modify the title of your issue to reflect the underlying problem.

**Comment by cgewecke** [comment]
Just saw a [corresponding issue](https://github.com/trufflesuite/ganache-cli/issues/525) at ganache-cli as well - not clear to me that this problem originates there but leaving a note so we can watch out for it.

**Comment by cgewecke** [comment]
Related issue at [web3](https://github.com/ethereum/web3.js/issues/1738) for 2D arrays
