### ISSUE TITLE
Upgrade to 4.1.12 - Truffle Exception

### ISSUE THREAD

**Issue by djneely** [trufflesuite/truffle#1058]
I had truffle-4.1.8 up and running fine. Did an update today to 4.1.12 and now getting the following error just trying to check the version. All other commands fail as well.

```
$ truffle version
/usr/local/lib/node_modules/truffle/build/cli.bundled.js:60353
!function(e,a){ true?module.exports=a():"function"==typeof define&&define.amd?define("ganache",[],a):"object"==typeof exports?exports.ganache=a():e.ganache=a()}(global,function(){return function(e){var a={};function t(c){if(a[c])return a[c].exports;var n=a[c]={i:c,l:!1,exports:{}};return e[c].call(n.exports,n,n.exports,t),n.l=!0,n.exports}return t.m=e,t.c=a,t.d=function(e,a,c){t.o(e,a)||Object.defineProperty(e,a,{configurable:!1,enumerable:!0,get:c})},t.r=function(e){Object.defineProperty(e,"__esModule",{value:!0})},t.n=function(e){var a=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(a,"a",a),a},t.o=function(e,a){return Object.prototype.hasOwnProperty.call(e,a)},t.p="",t.w={},t(t.s=1036)}([function(e,a,t){try{var c=t(1);if("function"!=typeof c.inherits)throw"";e.exports=c.inherits}catch(a){e.exports=t(1021)}},function(e,a){e.exports=__webpack_require__(3)},function(e,a,t){"use strict";var c="function"==typeof Symbol
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
```

**Comment by djneely** [comment]
If it helps just uninstalled 4.1.12 and re-installed 4.1.8 and everything is back in order and working.

**Comment by cgewecke** [comment]
@djneely It looks like this is Node version related. You shouldn't see this if you update to Node 8 (LTS) - don't know if that's possible for you. We're not supposed to break Node 6 and looks like we might have, sorry. Investigating cause . . .

**Comment by djneely** [comment]
Sounds good thanks!
