### ISSUE TITLE
Error encountered, bailing. Network state unknown. Review successful transactions manually. Error: Contract transaction couldn't be found after 50 blocks

### ISSUE THREAD

**Issue by faizanahmad055** [trufflesuite/truffle#1074]
## Issue

I'm using [this](https://medium.com/@mvmurthy/full-stack-hello-world-voting-ethereum-dapp-tutorial-part-2-30b3d335aa1f) tutorial to develop a voting smart contract. I tested it before a few weeks ago and it was working fine but now it is showing me an error while trying to deploy the smart contract.

## Steps to Reproduce

I'm running below mentioned command to run the ethereum node
`geth --rinkeby --syncmode "fast" --rpc --rpcapi db,eth,net,web3,personal --cache=1024 --rpcport 8545 --rpcaddr 127.0.0.1 --rpccorsdomain "*"`

**truffle.js**
```
module.exports = {
  networks: {
    development: {
      host: '127.0.0.1',
      port: 8545,
      network_id: '*', // Match any network id
      gas: 4712388
    },
    ropsten: {
      host: 'localhost',
      port: 8545,
      gas: 6700000,
      network_id: '3' // Match any network id
    },
    kovan: {
      host: 'localhost',
      port: 8545,
      gas: 6700000,
      network_id: '5' // Match any network id
    },
    mocha: {
      enableTimeouts: false
    }
  }
}
```

When I run truffle **migrate --reset**

it shows below error
```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Contract transaction couldn't be found after 50 blocks
```

## Expected Behavior

Smart contract should be deployed.

## Actual Results

```
Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x4bad5e37538025f35e48eb95d7448a910c2c9b5e7c822e9c5fd310446219f62a
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Contract transaction couldn't be found after 50 blocks
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:112:1
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:128:1
    at Array.forEach (native)
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:127:1
    at Array.forEach (native)
    at Object.onMessage [as callback] (/home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/filter.js:125:1)
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:259:1
    at Array.forEach (native)
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:258:10
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:225:1
    at /home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/home/faizan/.nvm/versions/node/v7.8.0/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

## Environment

* Operating System:  Ubuntu 16.04
* Ethereum client: Geth Version: 1.8.11-stable
* Truffle version (`truffle version`): v4.1.13 (core: 4.1.13)
* Solidity: v0.4.24 (solc-js)
* node version (`node --version`): v7.8.0
* npm version (`npm --version`):  v4.2.0

**Comment by faizanahmad055** [comment]
Duplicate of https://github.com/trufflesuite/truffle/issues/677
