### ISSUE TITLE
truffle debug error: "RangeError: Invalid array length"

### ISSUE THREAD

**Issue by carbonnetwork** [trufflesuite/truffle#1097]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

truffle debug got exception: 
```
RangeError: Invalid array length
    at printWatchExpressionResult (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/debug.js:214:1)
    at evalAndPrintExpression (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/debug.js:269:1)
    at Session.view (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:2236:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
    at args (/usr/local/lib/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:209:1)
    at Function.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:90:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:76:1
    at data.current.identifiers.decoded (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1689:148)
    at Array.map (<anonymous>)
    at map (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1690:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1592:1
    at decode (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:3847:1)
    at decodeStorageReference (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:3777:1)
```

## Steps to Reproduce
```
$ truffle debug <xxxxxx>

...
...
...
Index.sol:

53:     uint length = _collection.length;
54:     for (uint i = 0; i < length; i++) {
55:       if(_collection[i] == 0){
                       ^^^^^^^^^^^

debug(development:0xd96e02f7...)> +:length
RangeError: Invalid array length
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
```
## Expected Behavior

Print the value of the variable "length"

## Actual Results

Throw the exception above

## Environment

* Operating System: Mac OS high Sierra
* Ethereum client: ganache-cli
* Truffle version (`truffle version`): 4.1.13

**Comment by gnidan** [comment]
What type is `_collection`? And can you tell me the value of `_collection` before the exception? Thanks!

**Comment by carbonnetwork** [comment]
@gnidan. Sorry for the missing information, the code is: 
```
contract Index is Manager {

 	mapping (uint8 => uint[]) statusIndex;

 	constructor() public{

 	}

 	function addStatusIndex (uint8 _status, uint _id) public onlyLicensee returns(bool res) {
		require (_status < 3);
		
		uint[] storage ids = statusIndex[_status];
		addIndex(ids, _id);
		return true;
	}

        function addIndex(uint[] storage _collection, uint _id) internal returns(bool _res) {
		uint length = _collection.length;
		for (uint i = 0; i < length; i++) {
			if(_collection[i] == 0){
				_collection[i] = _id;
				return true;
			}
		}

		_collection.push(_id);
		return true;
	}
}
```

**Comment by gnidan** [comment]
@carbonnetwork the problem might be that `mapping` is not currently supported in truffle-debugger. Just curious, are you able to see the value of `_collection` before the for-loop?

**Comment by carbonnetwork** [comment]
@gnidan The ``_collection`` should be empty. At this time I had not put data in it. And when I  watched the value of ``_collection`` by truffle-debugger got the same error：
``
debug(development:0xe44f64f0...)> +:_collection
RangeError: Invalid array length
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:86:1
    at args (/usr/local/lib/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:209:1)
    at Function.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:90:1
``
