### ISSUE TITLE
Truffle compile fails with Truffle v5 (Beta)

### ISSUE THREAD

**Issue by thekevinbrown** [trufflesuite/truffle#1259]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When using Truffle v5 and running `truffle compile` I get this stack trace:

```
$ truffle compile
ReferenceError: url is not defined
    at request.then.catch.err (/Users/kevin/.config/yarn/global/node_modules/truffle/build/webpack:/packages/truffle-compile/compilerSupplier.js:169:20)
    at tryCatcher (/Users/kevin/.config/yarn/global/node_modules/truffle/build/webpack:/~/bluebird/js/release/util.js:16:1)
    at Promise._settlePromiseFromHandler (/Users/kevin/.config/yarn/global/node_modules/truffle/build/webpack:/~/bluebird/js/release/promise.js:512:1)
    at Promise._settlePromise (/Users/kevin/.config/yarn/global/node_modules/truffle/build/webpack:/~/bluebird/js/release/promise.js:569:1)
    at Promise._settlePromise0 (/Users/kevin/.config/yarn/global/node_modules/truffle/build/webpack:/~/bluebird/js/release/promise.js:614:1)
    at Promise._settlePromises (/Users/kevin/.config/yarn/global/node_modules/truffle/build/webpack:/~/bluebird/js/release/promise.js:689:1)
    at Async._drainQueue (/Users/kevin/.config/yarn/global/node_modules/truffle/build/webpack:/~/bluebird/js/release/async.js:133:1)
    at Async._drainQueues (/Users/kevin/.config/yarn/global/node_modules/truffle/build/webpack:/~/bluebird/js/release/async.js:143:1)
    at Immediate.Async.drainQueues (/Users/kevin/.config/yarn/global/node_modules/truffle/build/webpack:/~/bluebird/js/release/async.js:17:1)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

## Steps to Reproduce

1. `yarn global add truffle@beta`
2. `truffle compile`

## Expected Behavior

I expect the `truffle compile` command to work.

## Actual Results

`truffle compile` does not compile my contracts

## Environment

* Operating System: Mac OS X 10.13.6 (17G65)
* Ethereum client: ganache-cli 6.1.8
* Truffle version (`truffle version`): 

Truffle v5.0.0-beta.0 (core: 5.0.0-beta.0)
Solidity v0.4.24 (solc-js)

* node version (`node --version`): v8.11.3
* npm version (`npm --version`): 5.6.0
* yarn version (`yarn --version`): 1.9.4

**Comment by thekevinbrown** [comment]
Also, when trying to use a local solc-js to work around this, it doesn't work how I'd expect it to. The release notes say I can use a relative path, so I did:

* `yarn add solc`
* Edited `truffle.js` to have this section:

```
	compilers: {
		solc: {
			version: './node_modules/solc', // Version is managed in package.json as an NPM dependency.
			optimizer: {
				enabled: true,
			},
		},
	},
```

But then I get: `Error: Could not find compiler at: ./node_modules/solc`, even though that appears to be the path where solc is living relative to `truffle.js`:

```
$ ls truffle.js
truffle.js
$ ls node_modules/solc
LICENSE		index.js	package.json	translate.js
README.md	linker.js	solcjs		wrapper.js
abi.js		node_modules	soljson.js
```

What am I doing wrong here?

**Comment by cgewecke** [comment]
@thekevinbrown Thanks for both of these...

Going to open a fix for the first part of this issue shortly. Out of curiosity - are you still having problems getting that url to resolve? Clicking the link shows results and curl also works fine on my end. Are you behind a proxy or were you off the internet?

**Comment by cgewecke** [comment]
@thekevinbrown The relative path is also a bug - very sorry. Getting fixed in the same PR. . .

**Comment by cgewecke** [comment]
Both of these issues should now be fixed on `truffle@next` if you need these changes sooner than the next time we publish the beta.

**Comment by thekevinbrown** [comment]
Awesome, thanks so much @cgewecke!

I was definitely connected to the internet when I was doing this and could get all sorts of other sites to resolve, just not that one. It's working for me this morning though, so not sure what changed (maybe my ISP did something), but looks all good now.

Appreciate your help!

**Comment by kartojal** [comment]
Hitting this again with truffle@next:

```

**Comment by kartojal** [comment]
This is strange. Now i can see the json file at https://solc-bin.ethereum.org/bin/list.json with the Chrome browser but can't `curl` it via the terminal or running truffle commands.

**Comment by roderik** [comment]
I had intermittent failures today.

**Comment by roderik** [comment]
It is down again, and it tries to call this url even when using the docker version
