### ISSUE TITLE
error message for calling missing function did not show where the problem was.

### ISSUE THREAD

**Issue by branaway** [trufflesuite/truffle#1315]
- [ x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

My contract had this line:

_erc721.symbol(), where is the symbol() was missing from the contract. I was calling the relevant code from a test script. 

The error message was not helping:

    Error: Returned error: VM Exception while processing transaction: revert
      at Object.ErrorResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-core-helpers/src/errors.js:29:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-core-requestmanager/src/index.js:140:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:101:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:79:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:289:47)
      at IncomingMessage.EventEmitter.emit (domain.js:460:23)
      at endReadableNT (_stream_readable.js:1092:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

## Expected Behavior

should let me what really happend.

## Environment

* Operating System: 0SX
* Ethereum client: ganache
* Truffle version (`truffle version`): 5.0 beta1

**Comment by gnidan** [comment]
To summarize: it seems like it'd be a nice feature if Truffle could report the original _test line_ in the stacktrace for exceptions.

Might be challenging to do this because of the way promises are handled in a separate event loop, but there might be some support for this in mocha somewhere that we could use.
