### ISSUE TITLE
Truffle migrate fails on parity:v2.1.1 

### ISSUE THREAD

**Issue by kikoncuo** [trufflesuite/truffle#1323]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

truffle migrate on parity node fails with generic message

## Steps to Reproduce

1. Install truffle globally 
2. Check migration to ganache works fine by executing truffle migrate with ganache running on the default port
3. Define partity's IP inside truffle.js
4. Check that parity's RPC port is accesible and needed apis are available (eth, web3, personal)
5. Execute truffle migrate

## Expected Behavior

Transactions should arrive to parity node

## Actual Results

truffle returns
`Error: Method not found
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)`

## Environment

* Operating System: OSX
* Ethereum client: parity:v2.1.1
* Truffle version v4.1.14
* node version v8.12.0
* npm version 6.4.1

**Comment by kikoncuo** [comment]
Confirmed, I'm not the only one with this problem

**Comment by gnidan** [comment]
@kikoncuo can you please run this in Truffle v5 and paste the stack trace? It will be easier to track down the problem. Thank you!
