### ISSUE TITLE
Error encountered, bailing. Network state unknown. Review successful transactions manually. Error: The contract code couldn't be stored, please check your gas amount.

### ISSUE THREAD

**Issue by ryanliu285** [trufflesuite/truffle#1342]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Whenever I run truffle migrate I get the following line: Error encountered, bailing. Network state unknown. Review successful transactions manually. Error: The contract code couldn't be stored, please check your gas amount.

This is the repository: [](https://github.com/ryanliu285/ikomo/tree/master/Crypto/Truffle)

## Steps to Reproduce

truf migrate or truf migrate --reset

## Expected Behavior

I expect the migrate to work successfully

## Actual Results

`C:\Users\ryanl\Desktop\ikomo\Crypto\Truffle>truf migrate
Using network 'development'.

Running migration: 2_deploy_contract.js
  Deploying KomoCoin...
  ... 0x04eb6e6a42c65b2dda37432dc9fbfd036c2e4b2c09b443e87d7757c0c3567668
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (C:\Users\ryanl\Desktop\ikomo\Crypto\Truffle\node_modules\truffle\build\webpack:\~\web3\lib\web3\contract.js:147:1)
    at C:\Users\ryanl\Desktop\ikomo\Crypto\Truffle\node_modules\truffle\build\webpack:\~\web3\lib\web3\method.js:142:1
    at C:\Users\ryanl\Desktop\ikomo\Crypto\Truffle\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:89:1
    at C:\Users\ryanl\Desktop\ikomo\Crypto\Truffle\node_modules\truffle\build\webpack:\packages\truffle-migrate\index.js:225:1
    at C:\Users\ryanl\Desktop\ikomo\Crypto\Truffle\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\ryanl\Desktop\ikomo\Crypto\Truffle\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\ryanl\Desktop\ikomo\Crypto\Truffle\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (C:\Users\ryanl\Desktop\ikomo\Crypto\Truffle\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\ryanl\Desktop\ikomo\Crypto\Truffle\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
    at IncomingMessage.<anonymous> (C:\Users\ryanl\Desktop\ikomo\Crypto\Truffle\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)`

## Environment

* Operating System: Windows 10
* Ethereum client: Ganache
* Truffle version (`truffle version`): Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)
* node version (`node --version`): node: '8.12.0',
* npm version (`npm --version`):  npm: '6.4.1',

**Comment by eggplantzzz** [comment]
Does anything change when you adjust your gas values?

**Comment by ryanliu285** [comment]
No, nothing happens

**Comment by m-chrzan** [comment]
The build artifact for KomoCoin appears to have empty bytecode. Are you sure you implement all functions declared but not implemented in interfaces/abstract contracts you inherit from?

**Comment by ryanliu285** [comment]
I don't really know what to do at this point, I tried to implement every function in Ownable.sol and ERC721Token.Sol, and I still end up with the same problem
