### ISSUE TITLE
Error: Invalid JSON RPC response: {"id":3,"jsonrpc":"2.0"}

### ISSUE THREAD

**Issue by rrubo** [trufflesuite/truffle#1353]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When trying to migrate the contract, I am receiving the jsonRPC error. Can't seem to understand what is the reason of this error, since the contract works just fine when deploying from the Remix browser.

Results:

`$ truffle migrate
Using network 'development'.

Error: Invalid JSON RPC response: {"id":3,"jsonrpc":"2.0"}
    at Object.InvalidResponse (C:\Users\ruham\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\errors.js:38:1)
    at C:\Users\ruham\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1
    at C:\Users\ruham\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\ruham\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\ruham\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xh_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (C:\Users\ruham\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:le\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\ruham\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:ruffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
    at IncomingMessage.<anonymous> (C:\Users\ruham\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)\build\webpack:\~\xhr2\lib\xhr2.js:469:1)    at IncomingMessage.emit (events.js:165:20)    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)`

## Environment

* Operating System: Windows x64
* Ethereum client: Ganache / Ethereum-bridge
* Truffle version (`truffle version`): Truffle v4.1.14
* node version (`node --version`): v9.4.0
* npm version (`npm --version`):  6.4.1

**Comment by wassimbenregaya1** [comment]
try truffle migrate  --reset
