### ISSUE TITLE
Error on test when call a function of contract

### ISSUE THREAD

**Issue by loreberti89** [trufflesuite/truffle#1360]
version : Truffle v4.1.14 
node: 8.12.0
ganache-cli : Ganache CLI v6.1.8 (ganache-core: 2.2.1)
Windows: 10
npm : 6.4.1

## Issue

Hello I'm trying to test a simple contract:
```
pragma solidity ^0.4.4;
contract SimpleContract {
  bytes32  hello = "hello";
  function getHello() public view returns (bytes32){
    return hello;
  }
}
```
I have this migrations:

```
var SimpleContract = artifacts.require("SimpleContract");
module.exports = function(deployer) {
  deployer.deploy(Simple);
};

```

And I have this test:

```
pragma solidity ^0.4.4;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";

import "../contracts/SimpleContract.sol";


contract TestSimpleContract {

  function testGetHello() public {
    SimpleContract w = SimpleContract(DeployedAddresses.SimpleContract());
    bytes32  expected = "hello";
    bytes32  hello = w.getHello();

    Assert.equal(hello,expected, "SHould hello!");
  }
```
I can't undestand Why it return:

> 1) TestSimpleContract testGetHello: Error: VM Exception while processing transaction: revert at Object.InvalidResponse (C:\Users\Lorenzo\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\errors.js:38:1) at C:\Users\Lorenzo\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1 at C:\Users\Lorenzo\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:134:1 at XMLHttpRequest.request.onreadystatechange (C:\Users\Lorenzo\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1) at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\Lorenzo\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1) at XMLHttpRequest._setReadyState (C:\Users\Lorenzo\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1) at XMLHttpRequest._onHttpResponseEnd (C:\Users\Lorenzo\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1) at IncomingMessage. (C:\Users\Lorenzo\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:139:11) at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by loreberti89** [comment]
My error, for a lack of extension "Js" on migration file
