### ISSUE TITLE
Truffle migrate/compile fails; "Cannot find module './js'"

### ISSUE THREAD

**Issue by ayanez17** [trufflesuite/truffle#1400]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
When I try to run truffle compile or truffle migrate I get the following error:
`Error: Cannot find module './js'`

## Steps to Reproduce
While inside the contracts folder, I run `truffle compile` or `truffle migrate --network rinkeby` and I get the error above.

## Expected Behavior

I expect the contracts to compile.

## Actual Results

`Error: Cannot find module './js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/my_name/Desktop/Projects/Blockchain/project_name/node_modules/keccak/index.js:9:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/my_name/Desktop/Projects/Blockchain/project_name/node_modules/web3-provider-engine/node_modules/ethereumjs-util/dist/index.js:5:24)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/my_name/Desktop/Projects/Blockchain/project_name/node_modules/web3-provider-engine/index.js:3:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/my_name/Desktop/Projects/Blockchain/project_name/node_modules/truffle-hdwallet-provider/index.js:3:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/my_name/Desktop/Projects/Blockchain/project_name/ethereum/truffle.js:1:26)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (`

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): Truffle v5.0.0-beta.1 (core: 5.0.0-beta.1)
* node version (`node --version`): v8.9.4
* npm version (`npm --version`):  6.4.1

**Comment by kyriediculous** [comment]
On windows use truffle-config.js instead of truffle.js

**Comment by ayanez17** [comment]
> On windows use truffle-config.js instead of truffle.js for your truffle configuration file, delete truffle.js .

I’m in a Mac

**Comment by eggplantzzz** [comment]
@ayanez17 Is your code available somewhere?
