### ISSUE TITLE
Random "Could not connect to your Ethereum client"

### ISSUE THREAD

**Issue by elenadimitrova** [trufflesuite/truffle#1461]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
We encounter a client disconnect issue at seemingly random points when running our test suite. Tests pass when run individually.

The following issues appear related:
https://github.com/trufflesuite/truffle/issues/729
https://github.com/trufflesuite/truffle/issues/1260
https://github.com/trufflesuite/ganache-core/commit/312902f25e6581c7aee900497ff5146ea217cd4a

## Steps to Reproduce

It has been really difficult to reproduce this issue as it is likely due to a race condition.  

## Expected Behavior

Test suite to complete 

## Actual Results

```
 Error: Could not connect to your Ethereum client. Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle.js)
```
Sample CI builds failing
https://circleci.com/gh/JoinColony/colonyNetwork/4940
https://circleci.com/gh/JoinColony/colonyNetwork/4930

## Environment

* Operating System: OSX
* Ethereum client: `ganache-cli@6.1.6` https://github.com/area/ganache-cli/commits/fakefix/eth_call_selfdestruct
* Truffle version (`truffle version`): `5.0.0-beta.2`
* node version (`node --version`): `9.11.2`
* npm version (`npm --version`): `5.6.0`

**Comment by gnidan** [comment]
Seems like this is resolved*. Closing, but let us know if the problem starts happening again!

* https://github.com/JoinColony/colonyNetwork/pull/461

**Comment by Jonybang** [comment]
@gnidan Solved by what, downgrading and using custom release? When fix of this error will appeared in regular release? on 5.0.3 release?

**Comment by dzarezenko** [comment]
I still have the same problem with Ganache.

```
ProviderError: 
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 8545
    - network_id > 5777
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)

      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:73:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:102:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/src/index.js:111:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpRequestError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:252:47)
      at Socket.socketErrorListener (_http_client.js:469:9)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by hgouveia** [comment]
same here, it shows me that same error randomly, when i check the ganache-cli, is all fine, is not down

> I still have the same problem with Ganache. Some parts of tests passed and this error message after that:
> 
> ```
> ProviderError: 
> Could not connect to your Ethereum client with the following parameters:
>     - host       > 127.0.0.1
>     - port       > 8545
>     - network_id > 5777
> Please check that your Ethereum client:
>     - is running
>     - is accepting RPC connections (i.e., "--rpc" option is used in geth)
>     - is accessible over the network
>     - is properly configured in your Truffle configuration file (truffle-config.js)
> 
>       at /usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:73:1
>       at /usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:102:1
>       at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/src/index.js:111:1)
>       at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
>       at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
>       at XMLHttpRequest._onHttpRequestError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
>       at ClientRequest.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:252:47)
>       at Socket.socketErrorListener (_http_client.js:469:9)
>       at emitErrorNT (internal/streams/destroy.js:106:8)
>       at emitErrorCloseNT (internal/streams/destroy.js:74:3)
>       at processTicksAndRejections (internal/process/task_queues.js:80:21)
> ```

**Comment by gordienoye** [comment]
I have had the error show up today on tests that were running correctly last week. I have gotten the same errors using `ganache-cli` as well as running the Ganache OSX application. I am on OSX using Truffle installed in the local project:
```
Truffle v5.4.19 (core: 5.4.19)
Solidity - ^0.8.0 (solc-js)
Node v16.13.0
Web3.js v1.5.3
Ganache CLI v6.12.2 (ganache-core: 2.13.2)
```

I am getting a very similar error but the call stack is slightly different after `provider/wrapper.js`.

```
     ProviderError:
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 8545
    - network_id > 1639344360396
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" or "--http" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)

      at /Users/gordienoye/repositories/three-hippies/indiana/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:73:1
      at /Users/gordienoye/repositories/three-hippies/indiana/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:102:1
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/lib/index.js:98:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpRequestError (node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:252:47)
      at ClientRequest.emit (node:events:390:28)
      at ClientRequest.emit (node:domain:475:12)
      at Socket.socketErrorListener (node:_http_client:447:9)
      at Socket.emit (node:events:390:28)
      at Socket.emit (node:domain:475:12)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by chrisdrifte** [comment]
Fixed this problem by configuring truffle to use a more recent version of web3, as suggested [here](https://github.com/trufflesuite/truffle/issues/3710#issuecomment-1073054526).

Install web3 if not already in your deps (worked for me with `1.7.1`)
```shell
yarn add -D web3
```

Update `truffle-config.js` to include `provider` field:
```js
const Web3 = require("web3");

module.exports = {
  // ...
  networks: {
    development: {
      provider: () => new Web3.providers.HttpProvider("http://127.0.0.1:7545"),
      host: "127.0.0.1",
      port: 7545,
      network_id: "*",
    },
    // ...
  },
  // ...
}
```

**Comment by stuartwk** [comment]
@gordienoye could you find a way to resolve this? I'm running into what looks to be the same thing locally on a Mac...

```
     ProviderError: 
Could not connect to your Ethereum client.
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)

      at webpack:///./packages/provider/wrapper.js:73:1
      at webpack:///./packages/provider/wrapper.js:102:1
      at XMLHttpRequest.request.onreadystatechange (webpack:///./node_modules/web3/node_modules/web3-providers-http/lib/index.js:98:1)
      at XMLHttpRequestEventTarget.dispatchEvent (webpack:///./node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (webpack:///./node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpRequestError (webpack:///./node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (webpack:///./node_modules/xhr2-cookies/dist/xml-http-request.js:252:47)
      at ClientRequest.emit (node:events:526:28)
      at ClientRequest.emit (node:domain:475:12)
      at Socket.socketErrorListener (node:_http_client:442:9)
      at Socket.emit (node:events:526:28)
      at Socket.emit (node:domain:475:12)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
