### ISSUE TITLE
Fix compilerSupplier caret bug 

### ISSUE THREAD

**Issue by CruzMolina** [trufflesuite/truffle#1502]
On `next`, specifying a truffle config to use a caret in compilers.solc.version (like so):

```
module.exports = {
  compilers: {
    solc: {
      version: "^0.5.0", <----
      settings: {
        optimizer: {
          enabled: false,
          runs: 200
        },
      }
    }
  }
};
```

Will result in this error when calling `truffle compile` in a valid truffle directory:

```
Error: Could not find a compiler version matching ^0.5.0. Please ensure you are specifying a valid version, constraint or build in the truffle config. Run `truffle compile --list` to see available versions.
    at CompilerSupplier.errors (/Users/cruzmolina/Code/truffle-projects/truffle/packages/truffle-compile/compilerSupplier.js:533:10)
    at CompilerSupplier.getByUrl (/Users/cruzmolina/Code/truffle-projects/truffle/packages/truffle-compile/compilerSupplier.js:260:25)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by CruzMolina** [comment]
Resolved by #1503
