### ISSUE TITLE
putting php files in the build declaration now causes a build error

### ISSUE THREAD

**Issue by msbachler** [trufflesuite/truffle#151]
I have an older version of truffle (0.3.1) running on a server with dapps that use php as well as html files. This was never an issue. I just declared them in the build of the truffle json. I just got a message saying it didn't recognize the file type or something like that and it was copied to the build folder. Now, on a new server I just built which now has truffle 1.0.2 the same truffle.json causes an error message until I remove the php file declarations and then it works fine. I tried renaming it to truffle.js and adjusting the internal declaration structure to the new format (as far as I understood it), but that still caused the same error. What is the new way of declaring php or other non-html/js files in the build and have then copied appropriately. Having to copy them by hand after truffle build is annoying. The error I am getting is:

TypeError: Cannot read property 'replace' of undefined
    at DefaultBuilder.expect (/usr/local/lib/node_modules/truffle/node_modules/truffle-default-builder/index.js:276:37)
    at DefaultBuilder.process_file (/usr/local/lib/node_modules/truffle/node_modules/truffle-default-builder/index.js:135:8)
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-default-builder/index.js:179:10
    at /usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:375:13
    at iterate (/usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:281:9)
    at Object.async.inject.async.foldl.async.reduce (/usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:374:15)
    at DefaultBuilder.process_files (/usr/local/lib/node_modules/truffle/node_modules/truffle-default-builder/index.js:169:9)
    at DefaultBuilder.process_target (/usr/local/lib/node_modules/truffle/node_modules/truffle-default-builder/index.js:220:8)
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-default-builder/index.js:259:10
    at /usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:181:20
    at iterate (/usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/truffle/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/truffle/node_modules/mocha/node_modules/graceful-fs/graceful-fs.js:104:5
    at /usr/local/lib/node_modules/truffle/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:82:15)
    at Function.module.exports.loopWhile (/usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:72:22)
    at /usr/local/lib/node_modules/truffle/node_modules/deasync/index.js:44:19
    at runTask (/usr/local/lib/node_modules/truffle/cli.js:46:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/cli.js:331:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3

Thanks

Michelle

**Comment by hockeyshooter** [comment]
With Truffle v2.0.6 I'm now getting PHP files copied into the build but they're zero bytes. Does the same with either _build_ or _watch_, but I get an error message of a missing file with _watch_.

**Comment by tcoulter** [comment]
Truffle default builder is no longer supported. Closing for housekeeping.
