### ISSUE TITLE
Truffle5: issue with truffle-hdwallet-provider

### ISSUE THREAD

**Issue by eloudsa** [trufflesuite/truffle#1538]
Hi

I'm using Truffle 5 beta 2 and the Truffle HDWallet Provider. 
For an unknown reason, I'm not able anymore to deploy my contract to Ropsten.

I have the following error:
```
$ truffle migrate --compile-all --reset --network ropsten
Error: Cannot find module 'any-promise'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /Users/eloudsa/ChainSkills/projects/chainlist-truffle5/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/webpack/universalModuleDefinition:3:1
    at Object.<anonymous> (/Users/eloudsa/ChainSkills/projects/chainlist-truffle5/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/webpack/universalModuleDefinition:1:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/eloudsa/ChainSkills/projects/chainlist-truffle5/truffle-config.js:1:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Function.Config.load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:387:1)
    at Function.Config.detect (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:376:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/migrate.js:165:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/command.js:113:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/cli.js:47:1)
    at __webpack_require__ (/usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 1b5412eb3ddc7c8d5561:19:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 1b5412eb3ddc7c8d5561:65:1
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:71:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Truffle v5.0.0-beta.2 (core: 5.0.0-beta.2)
Solidity v0.5.0 (solc-js)
Node v10.14.2
```
I use the following dependencies:
````
"dependencies": {
    "dotenv": "^6.2.0",
    "truffle-hdwallet-provider": "^1.0.0-web3one.4"
  }
````

I have the same problem with `Truffle v5.0.0-next.24`.

Any idea how to fix this issue?

Thanks

**Comment by eloudsa** [comment]
Btw, I fixed the issue by installing "any promise", so I'm not stuck.
Do you plan to include this package in a next version or will we have to install it ourselves in our projects?

**Comment by CruzMolina** [comment]
@eloudsa truffle-hdwallet-provider 1.0.0-web3one.5 just got published. 🎉

**Comment by gjeanmart** [comment]
Just add the same issue with **truffle v5.0.0**

```
$ npm install --save truffle-hdwallet-provider@web3-one
npm WARN kauri-protocol-contracts@1.0.0 No description
npm WARN kauri-protocol-contracts@1.0.0 No repository field.

+ truffle-hdwallet-provider@1.0.0-web3one.5
updated 1 package and audited 163 packages in 0.872s
found 0 vulnerabilities

--------------------------------
$ truffle migrate
Error: Cannot find module 'any-promise'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at require (/home/gjeanmart/workspace/kauri/kauri-protocol/kauri-protocol-contracts/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/webpack/universalModuleDefinition:3:1)
    at Object.<anonymous> (/home/gjeanmart/workspace/kauri/kauri-protocol/kauri-protocol-contracts/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/webpack/universalModuleDefinition:1:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/gjeanmart/workspace/kauri/kauri-protocol/kauri-protocol-contracts/truffle.js:2:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Function.Config.load (/home/gjeanmart/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:381:1)
    at Function.Config.detect (/home/gjeanmart/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:370:1)
    at Object.run (/home/gjeanmart/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/migrate.js:165:1)
    at Command.run (/home/gjeanmart/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/command.js:113:1)
    at Object.<anonymous> (/home/gjeanmart/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-core/cli.js:47:1)
    at __webpack_require__ (/home/gjeanmart/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 10c8e5c48cca88d8ca36:19:1)
    at /home/gjeanmart/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 10c8e5c48cca88d8ca36:65:1
Truffle v5.0.0 (core: 5.0.0)
Node v8.10.0

--------------------------------
$ npm install any-promise
npm WARN kauri-protocol-contracts@1.0.0 No description
npm WARN kauri-protocol-contracts@1.0.0 No repository field.

+ any-promise@1.3.0
added 1 package from 1 contributor and audited 164 packages in 3.047s
found 0 vulnerabilities


--------------------------------
$ truffle migrate --reset
⚠️  Important ⚠️
If you're using an HDWalletProvider, it must be Web3 1.0 enabled or your migration will hang.
Try: npm install --save truffle-hdwallet-provider@web3-one


Starting migrations...
======================
> Network name:    'development'
> Network id:      1545229853622
> Block gas limit: 6721975


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------
   > transaction hash:    0x0f7fe9015eb18c959c40361543401cde895d279e15ea7deeb10a7804bf03ce9b
   > Blocks: 0            Seconds: 0
   > contract address:    0x5bDF1070C75E1697B317f193D59E3882793b10A2
   > account:             0x31661ed38378C8ABDc9b5EE4Cf80961847793292
   > balance:             88.18620056
   > gas used:            284908
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00569816 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00569816 ETH


2_deployment.js
===============

   Replacing 'ContentSpaceRegistry'
   --------------------------------
   > transaction hash:    0x7a159d4a8e6ac9187e913e149aa3846ee166a2c07c64b69eddedb72cfb5c7ca4
   > Blocks: 0            Seconds: 0
   > contract address:    0x2D4852F1Cd970F58da610930C4D2d981497133fF
   > account:             0x31661ed38378C8ABDc9b5EE4Cf80961847793292
   > balance:             88.08768254
   > gas used:            4883867
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.09767734 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.09767734 ETH


Summary
=======
> Total deployments:   2
> Final cost:          0.1033755 ETH
```

**Comment by eloudsa** [comment]
I have just installed the final version of Truffle 5.

I have uninstalled and installed truffle-hdwallet-wrapper (version 1.0).

When I try to migrate on Ropsten , I have another error:
```
$ truffle migrate --reset --compile-all --network ropsten
Error: Cannot find module 'websocket'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at require (/Users/eloudsa/ChainSkills/ChainList/chainlist-truffle5/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/webpack/universalModuleDefinition:3:1)
    at Object.<anonymous> (/Users/eloudsa/ChainSkills/ChainList/chainlist-truffle5/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/webpack/universalModuleDefinition:1:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/eloudsa/ChainSkills/ChainList/chainlist-truffle5/truffle-config.js:1:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Function.Config.load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:381:1)
    at Function.Config.detect (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:370:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/migrate.js:165:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/command.js:113:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/cli.js:47:1)
    at __webpack_require__ (/usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 10c8e5c48cca88d8ca36:19:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 10c8e5c48cca88d8ca36:65:1
Truffle v5.0.0 (core: 5.0.0)
Node v10.14.2
```

My packages:
```
"dependencies": {
    "dotenv": "^6.2.0",
    "truffle-hdwallet-provider": "^1.0.0"
  }
```

**Comment by CruzMolina** [comment]
@gjeanmart @eloudsa truffle-hdwallet-provider 1.0.1 just got published.

`npm i truffle-hdwallet-provider` should default to it. Hopefully got this squared away. I tested manually 🤞

**Comment by eloudsa** [comment]
My problem has been solved thanks to the version 1.0.1.
Thanks @CruzMolina !!!
If issues from @gjeanmart is also solved, we can close this issue.

**Comment by CruzMolina** [comment]
@gjeanmart will happily re-open if there's still an issue.

**Comment by gjeanmart** [comment]
Sure thanks for your reactivity. Will try that later today!

**Comment by kyriediculous** [comment]
@CruzMolina  my dependencies are  still not installing properly when using` npm i  truffle-hdwallet-provider@web3-one -s`  

Same missing dependencies.

**Comment by CruzMolina** [comment]
Hey @kyriediculous , hopefully you were able to resolve this, but since truffle v5 you can simply do `npm i truffle-hdwallet-provider`. Latest should contain the missing dep!

**Comment by BlackPanthar** [comment]
I had this problem. What worked was replacing the "truffle-hdwallet-provider" in the require method argument at here: const HDWalletProvider = require('truffle-hdwallet-provider');

with '@truffle/hdwallet-provider'

const HDWalletProvider = require('@truffle/hdwallet-provider');

and truffle compile finally worked

**Comment by kevinobama** [comment]
I got the same issue.
