### ISSUE TITLE
ERC20-like contract can't take BN for amount parameter

### ISSUE THREAD

**Issue by coventry** [trufflesuite/truffle#1540]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I have an ERC20-like contract, whose `transfer` function doesn't accept a `BN` for the a amount parameter. See [this line](https://github.com/smartcontractkit/chainlink/blob/gnidan-link-transfer-BN-amount/solidity/test/Coordinator_test.js#L271). It results in `Invalid number of arguments to Solidity function`. Incidentally, there may be an opportunity to report a more informative error message, there.

Replacing `paymentAmount` with `paymentAmount.toString()` causes the test to pass.

## Steps to Reproduce

```
$ git clone https://github.com/smartcontractkit/chainlink
$ git checkout gnidan-link-transfer-BN-amount
```
Follow [chainlink install instructions](https://github.com/smartcontractkit/chainlink#install).

```
$ cd ./solidity
$ ../node_modules/.bin/truffle test ./test/Coordinator_test.js
```

## Expected Behavior

Test should pass when passing a `BN`

## Actual Results

Fails with an misinformative error messsage; see above, and

```
~/chainlink/solidity$ ../node_modules/.bin/truffle test test/Coordinator_test.js                                                                                                                                 [2/1851]
Using network 'test'.      
            
Compiling ./contracts/Chainlinked.sol...   
Compiling ./contracts/Oracle.sol...
Compiling ./contracts/examples/BasicConsumer.sol...
Compiling ./contracts/examples/ConcreteChainlinked.sol...
Compiling ./contracts/examples/Consumer.sol...
Compiling ./contracts/examples/EmptyOracle.sol...
Compiling ./contracts/examples/MaliciousChainlinked.sol...
Compiling ./contracts/examples/MaliciousConsumer.sol...
Compiling ./contracts/examples/MaliciousRequester.sol...
Compiling ./contracts/examples/MaliciousServiceAgreementConsumer.sol...
Compiling ./contracts/examples/ServiceAgreementConsumer.sol...
Compiling ./contracts/examples/UpdatableConsumer.sol...
Compiling ./contracts/interfaces/OracleInterface.sol...


  Contract: Coordinator
    #fulfillData
      with a malicious requester
deploying link token
deploying coordinator
deployments complete
        1) cannot cancel before the expiration

    Events emitted during test:
    ---------------------------

    NewServiceAgreement(said: <indexed>, requestDigest: <indexed>)
    RunRequest(specId: <indexed>, requester: <indexed>, amount: <indexed>, internalId: 51221021145469280920240886899259697679533168742687794872310240632940108981165, version: 1, data: null)

    ---------------------------
    
    
  0 passing (3s)
  1 failing

  1) Contract: Coordinator
       #fulfillData
         with a malicious requester
           cannot cancel before the expiration:
     Error: Invalid number of arguments to Solidity function
      at Object.InvalidNumberOfSolidityArgs (/home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/truffle-contract/node_modules/web3/lib/web3/errors.js:25:16)
      at SolidityFunction.validateArgs (/home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/truffle-contract/node_modules/web3/lib/web3/function.js:74:22)
      at SolidityFunction.toPayload (/home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/truffle-contract/node_modules/web3/lib/web3/function.js:90:10)
      at SolidityFunction.sendTransaction (/home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/truffle-contract/node_modules/web3/lib/web3/function.js:163:24)
      at SolidityFunction.execute (/home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/truffle-contract/node_modules/web3/lib/web3/function.js:256:37)
      at /home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/truffle-contract/contract.js:204:16
      at new Promise (<anonymous>)
      at /home/ubuntu/go/src/github.com/smartcontractkit/chainlink/node_modules/truffle-contract/contract.js:155:18
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

Incidentally, it would be very nice if there was a way to tell truffle that it doesn't need to recompile all the solidity contracts on every run.

## Environment

* Operating System: AWS t2.xlarge running ubuntu:

```
$ cat /etc/issue
Ubuntu 18.04.1 LTS \n \l

$ uname -a
Linux ip-172-30-1-65 4.15.0-1029-aws #30-Ubuntu SMP Wed Nov 21 23:58:13 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

* Ethereum client: truffle default
* Truffle version (`truffle version`):
```
$ ../node_modules/.bin/truffle version
Truffle v5.0.0-next.24 (core: 5.0.0-beta.2)
Solidity - 0.4.24 (solc-js)
Node v8.10.0
```

* node version (`node --version`): See above
* npm version (`npm --version`): 

```
$ npm --version
5.10.0
$ yarn --version
1.12.1
```

**Comment by coventry** [comment]
Would you accept a PR to correct this?

**Comment by eggplantzzz** [comment]
Hey @coventry, sorry for the delay in getting around to this. I will try and look into this issue in the next couple of days...if you think it is a bug and have a fix then please do submit a PR! I'll try and get back to you soon.

**Comment by coventry** [comment]
It's not exactly a bug, more like an oversight in the API. If you get back a BN, and want to use that in an amount, currently you need to explicitly convert it to a hex string or some similar solution, which is a bit of a pain.

**Comment by gnidan** [comment]
@coventry you (reasonably so) deleted your branch for reproducing this. Do you know if it's still a problem? Doing issue maintenance and wondering what's going here.

**Comment by coventry** [comment]
Seems to be fixed now, thanks.

**Comment by gnidan** [comment]
Glad to hear, thank you!
