### ISSUE TITLE
Error: insufficient funds for gas * price + value

### ISSUE THREAD

**Issue by kk412027247** [trufflesuite/truffle#1541]
---------------------------

## Issue

Error: insufficient funds for gas * price + value.
I have read all the issue that is similar to me,  I still can not find the solution.
want some help.

## Steps to Reproduce
when i deploy the my contract to the development network, it success.

```
ganache-cli
truffle migrage --reset
```

## Expected Behavior
```
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x1120e00f84f67f7b464f8d532f2cb9a6aaa9339615789dc8c47c9690e1e45486
  Migrations: 0xc9ab5eb6d7c870262e2c311b82773b783c2f6ecc
Saving successful migration to network...
  ... 0xe2f7a1ced7741e4a8709bbda3ec62ecedf1c0335e0b811c7c760de8e28f7bab6
Saving artifacts...
Running migration: 2_deploy_token.js
  Deploying MyToken...
  ... 0xfd2d6182f6e9ddf0f6c189cdc8f131739f0d44427a61428cc2d5939ed15d2254
  MyToken: 0xdc97f1927bbce8211ebf96123e06d6cdcf6b2c65
Saving successful migration to network...
  ... 0x5119cf6d6ee12fc25853a0d37417beebce8188d18ca6bf4e7ba0b66904a2bf18
Saving artifacts...

```

But when i deploy to the rinkeby, I got an error.
```
geth --unlock  be255696870b84c69f6e2b902177cf2a2cb57b58 --rinkeby --rpc --rpcapi db,eth,net,web3,personal  
truffle migrate --network rinkeby
```
## Actual Results
```
Using network 'rinkeby'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: insufficient funds for gas * price + value
    at Object.InvalidResponse (/Users/tmd/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /Users/tmd/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /Users/tmd/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:225:1
    at /Users/tmd/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/Users/tmd/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/tmd/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/Users/tmd/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/Users/tmd/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/Users/tmd/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

```

### truffle.js
```

module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  networks:{
    development:{
      host:'127.0.0.1',
      port:8545,
      network_id:'*'
    },
    rinkeby: {
      host: "localhost",
      port: 8545,
      from: "0xBe255696870b84C69F6e2b902177Cf2a2cB57B58",
      network_id: 4,
      gas: 4700000,
    }
  },
  solc:{
    optimizer:{
      enabled: true,
      runs: 200
    }
  }
};

```

# Environment

* Operating System: mac ox
* Ethereum client:
* Truffle version (`Truffle v4.1.5 (core: 4.1.5) Solidity v0.4.21 (solc-js)`):
* node version (`v8.9.4`):
* npm version (`6.4.1`):

**Comment by kk412027247** [comment]
It is my fault, the network didn't finish synchronous.
