### ISSUE TITLE
Debug transaction - " TypeError: Cannot destructure property source of 'undefined' or 'null'."

### ISSUE THREAD

**Issue by kalymgr** [trufflesuite/truffle#1574]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I've recently installed the new truffle framework. I succesfully migrate the pet shop tutorial on my development blockchain (deployed using truffle develop) but when I try to debug the last transaction, as shown on my log terminal (truffle console --log), I get the following error message " Cannot destructure property source of 'undefined' or 'null'.
at map (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-debugger\dist\debugger.js:7525:1)". I didn't have this kind of problems with the previous version of truffle.

## Steps to Reproduce

a) Get the pet shop tutorial, according to https://truffleframework.com/tutorials/pet-shop
b) Create the Adoption.sol file creating the Adoption contract. 
c) Change compiler version to 0.5.0 (pragma solidity ^0.5.0)
d) Create the 2_deploy_contracts.js file, in the migrations folder, containing the following:
"""
var Adoption = artifacts.require("Adoption");
module.exports = function(deployer) {
  deployer.deploy(Adoption);
};
"""

e) deploy the contracts on truffle develop console, using migrate command. Open one more console window, to show log (truffle develop --log)
f) debug the last transaction (debug txId)

## Expected Behavior

Start the debugging process.

## Actual Results

I get the following error message " TypeError: Cannot destructure property source of 'undefined' or 'null'.
at map (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-debugger\dist\debugger.js:7525:1)"

## Environment

* Operating System: Windows 10 Pro, 64bit, v1803
* Ethereum client: Ethereum Wallet V. 0.11.1
* Truffle version (`truffle version`):  v5.0.0
* node version (`node --version`): v10.14.2
* npm version (`npm --version`): 6.4.1

**Comment by shinsyotta** [comment]
Me too.  Same issue, I think.
```
Gathering transaction data...

TypeError: Cannot destructure property `source` of 'undefined' or 'null'.
    at map (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:7525:1)
    at Array.map (<anonymous>)
    at session.info.affectedInstances (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:7517:268)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:76:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:90:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/reselect/lib/index.js:36:1
    at Session.view (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:2874:1)
    at printAddressesAffected (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/debug.js:118:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/debug.js:704:1
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by trifist** [comment]
Same here, any solutions?

**Comment by marcushennig** [comment]
Some issue when debugging: 
```
> debug 0x0ed2c73f6c701f052016bf39c4231915a4ac9af05736bb2293c2071c6a65e3a1
Compiling .\contracts\Fibonacci.sol...
Compiling .\contracts\Migrations.sol...

Gathering transaction data...

TypeError: Cannot destructure property `source` of 'undefined' or 'null'.
    at map (C:\Users\d90789\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-debugger\dist\debugger.js:7525:1)
    at Array.map (<anonymous>)
    at session.info.affectedInstances (C:\Users\d90789\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-debugger\dist\debugger.js:7517:268)
    at C:\Users\d90789\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:76:1
    at C:\Users\d90789\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:36:1
    at C:\Users\d90789\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:90:1
    at C:\Users\d90789\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\reselect\lib\index.js:36:1
    at Session.view (C:\Users\d90789\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-debugger\dist\debugger.js:2874:1)
    at printAddressesAffected (C:\Users\d90789\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\commands\debug.js:118:1)
    at C:\Users\d90789\AppData\Roaming\npm\node_modules\truffle\build\webpa
```

**Comment by carlosescom** [comment]
Same here, any solutions yet?

**Comment by hadeelalseni** [comment]
same here. :(

**Comment by haltman-at** [comment]
Oops, this seems to have fallen off my radar somehow.  Is this still happening in the most recent version of Truffle?  Thank you!

**Comment by haltman-at** [comment]
Closing this for issue maintenance.  If anyone is still having an issue with this please let us know!
