### ISSUE TITLE
Migration on Quorum (Azure): Transaction was not mined within 750 seconds

### ISSUE THREAD

**Issue by baermathias** [trufflesuite/truffle#1625]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I am running `Quorum` on `Azure` and would like to use `Truffle` for contract deployment, but getting errors. I have also tried to `geth attach` into a second console and sending an unrelated tx: 
`eth.sendTransaction({from: eth.accounts[0] })`
due to this known issue: https://github.com/jpmorganchase/quorum-examples/issues/148 but in doesn't help in my case. 

My truffle-config:
```
    azure: {
        host: "10.0.0.4",   
        port: 8545, 
        network_id: 10101010,  
        gasPrice: 0,
        gas: 4500000
    }
```
## Expected Behavior

Finish initial migration without errors.

## Actual Results

```
Starting migrations...
======================
> Network name:    'development'
> Network id:      10101010
> Block gas limit: 4712388


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------
   > transaction hash:    0xb4bac016fa2ecc239e205f9f01c1c4d25ae93f3000887c5daa4490317de08fe0
Error:  *** Deployment Failed ***
"Migrations" -- Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!.

    at /home/gethadmin/.nvm/versions/node/v8.15.0/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:364:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Truffle v5.0.1 (core: 5.0.1)
Node v8.15.0
```

## Environment
* Running Quorum using Microsoft Azure (Marketplace: `Quorum Single Member Blockchain Network`)
* Operating System: Ubuntu 16.04.5
* Ethereum client: (`geth --version`): 1.5.0-unstable-6d0bd810
* Truffle version (`truffle version`):  v5.0.1 (core: 5.0.1)
* node version (`node --version`): v8.15.0
* npm version (`npm --version`): 6.4.1

**Comment by baermathias** [comment]
I am closing this, because the Azure marketplace image `Quorum Single Member Blockchain Network` used Quorum v1 with the old consensus QuorumChain. The new version + truffle v4 does actually work
