### ISSUE TITLE
truffle-compile: Better error text needed for "Unexpected end of JSON input"

### ISSUE THREAD

**Issue by wbt** [trufflesuite/truffle#1650]
---------------------------
## Setup:
I have a Truffle project that normally compiles and migrates fine.  I have some background backup processes that occasionally read files and lock them up while doing backup.  For the purpose of this Issue report, let's assume that can't be changed.

## Issue
Here was a recent session, in which I attempted a migration from the start but the process got interrupted, apparently because a file was busy.  The handling of this issue was very far from graceful.  First, it just stopped the migrations process, and the process could not be restarted because the interruption had led to a corrupted JSON file.  Even attempting to re-run 'compile' failed because the JSON file that 'compile' would have replaced was corrupted.  Manually deleting the JSON files and re-compiling worked.  

First session:
```
> truffle migrate --reset
Using network 'development'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0x6a0879a5d38bea2827a3e98fab20222b9158306118109b5b22a0cd65d08a666d
  Migrations: 0x2f56a4a390cbecd3716aaf306c160cb1a38b96f6
Saving successful migration to network...
  ... 0x55686446be32b387b4af3651998fe2d46d4f3fbd1d5885cd9d36d9d7d8022b22
Saving artifacts...
Running migration: 2_first_action.js
Saving successful migration to network...
  ... 0x72c22858638d4b0fec4622e41ee1fd6bdd39cbca0f78a3750fc57aeb6fe7559b
Saving artifacts...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: EBUSY: resource busy or locked, open 'C:\Users\me\projectDir\build\contracts\Migrations.json'
```
An arbitrary time period later (in my example, immediate, but could have been a while later):
```
> truffle migrate --reset
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\packages\truffle-compile\profiler.js:80:1
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:1140:1
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:473:1
    at iteratorCallback (C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:1064:1)
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:969:1
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:1137:1
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\packages\truffle-compile\profiler.js:73:1
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
> truffle migrate --reset
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\packages\truffle-compile\profiler.js:80:1
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:1140:1
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:473:1
    at iteratorCallback (C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:1064:1)
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:969:1
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:1137:1
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\packages\truffle-compile\profiler.js:73:1
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
> truffle compile
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\packages\truffle-compile\profiler.js:80:1
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:1140:1
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:473:1
    at iteratorCallback (C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:1064:1)
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:969:1
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\~\async\dist\async.js:1137:1
    at C:\Users\me\AppData\Local\node\node_modules\truffle\build\webpack:\packages\truffle-compile\profiler.js:73:1
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)
    
> rm -r build/contracts
> truffle compile
Compiling .\contracts\Migrations.sol...
...(This works now)...
```

## Steps to Reproduce

Have a file in the `build/contracts` directory with invalid JSON (e.g. remove a closing brace at the end of the file), and attempt to run `truffle compile` or `truffle migrate`.

## Expected Behavior
1. At the least, an error message that tells me *which* file is being parsed to give an "unexpected end of JSON input."
2. Maybe, an error message suggesting that I delete that file or the `build/contracts` directory and re-compile, to put me on a path towards a solution.
3. Potentially better, if a command is expected to overwrite/replace a file that's producing a parse error, ignore the error as if the corrupt file just were not there at all (maybe print a warning), and just replace the file (optionally deleting it before overwrite if necessary).
 
## Actual Results
A confusing error message that requires me to recall specifics about something odd happening earlier in order to get a clue about how to proceed and address the issue.

## Environment

* Operating System: Windows 10 pro
* Ethereum client: Ganache but irrelevant here
* Truffle version (`truffle version`): 4.1.15
* node version (`node --version`): 9.3.0
* npm version (`npm --version`): 6.5.0

**Comment by gnidan** [comment]
Thanks for raising this! Nice suggestions. I like # 3

**Comment by PyrateAkananto** [comment]
I stumbled about this issue because of a `.gitkeep` file (using Truffle 5.0.9 or 5.0.27).

In the error message please at least output the file name of the file causing trouble. In addition I suggest to ignore all files without a `.json` extension.

**Comment by eggplantzzz** [comment]
Can anyone confirm that this kind of error messaging occurs on `0.5.xx`?

**Comment by PyrateAkananto** [comment]
No, I cannot, sorry. I appreciate you still caring about this issue but I currently don't use Ethereum or Truffle anymore and don't have the time to get all my tools up and running again just for this. 😢
