### ISSUE TITLE
truffle migrate with websocket: TypeError: Cannot read property 'subscription' of undefined

### ISSUE THREAD

**Issue by Bowfish** [trufflesuite/truffle#1699]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
When I run `truffle migrate --network devilnet` with the following network conifguration:
```
devilnet: {
      host: "127.0.0.1",      // Localhost (default: none)
      port: 8546,             // Custom port
      network_id: 639176,     // Custom network
      gas: 8500000,           // Gas sent with each transaction (default: ~6700000)
      gasPrice: 1800000000,  // 20 gwei (in wei) (default: 100 gwei)
      websockets: true,        // Enable EventEmitter interface for web3 (default: false)
      provider: () => new Web3.providers.WebsocketProvider("ws://localhost:8546", {
        headers: {
          origin: "127.0.0.1"
        }
})
```
I get the following error:
```
/home/xxx/node_modules/web3-providers/dist/web3-providers.cjs.js:304
event = this.getSubscriptionEvent(response.params.subscription);
                                                  ^
TypeError: Cannot read property 'subscription' of undefined
at WebsocketProvider.onMessage (/home/xxx/node_modules/web3-providers/dist/web3-providers.cjs.js:304:59)
at WebsocketProvider.onMessage (/home/xxx/node_modules/web3-providers/dist/web3-providers.cjs.js:410:77)
```
## Environment

* Operating System: linux
* Ethereum client: geth version 1.8.22-stable
* Truffle version (`truffle version`): v5.0.3 (core: 5.0.3)
* node version (`node --version`): 8.15.0
* npm version (`npm --version`): 6.7.0

**Comment by eggplantzzz** [comment]
@Bowfish Just a couple of things to try...
Will you make sure that you are using Web3 version 1.0.0-beta.36? The newer versions of web3 recently broke some provider functionality for Truffle and Ganache. Also try removing the `host` and `port` properties from the config and see what happens. I don't think you should need them since you have the `provider` property. Let me know if this helps at all.

**Comment by eggplantzzz** [comment]
Actually I am having success with web3@beta.37 but not web3@beta.38 so you can try that instead of beta.36

**Comment by Bowfish** [comment]
@eggplantzzz That already looks much better with version 1.0.0-beta.36, but it still doesn't connect. What parameters do I have to specify in the geth command? My command line looks like this:

`geth --datadir ./node01 --networkid 1234 --syncmode 'full' --port 30311 --rpc --rpcaddr 'localhost' --rpcport 8601 --rpcapi 'personal,db,eth,net,web3,txpool,miner,clique' --rpccorsdomain 'http://localhost:3000' --ws --wsaddr 'localhost' --wsport 8546  --wsorigins '*' --gasprice '1' --targetgaslimit 94000000 -unlock '0xb2425b2a94332fc3be079a48b9407f04eaaa18dc' --password node01/password.txt --mine`

**Comment by eggplantzzz** [comment]
Oh I was assuming you were using Ganache CLI and not geth so I'm not sure if geth requires any additional configuration. If I come across something helpful I'll try and leave it here. The business above concerning Web3 versions is strictly related to Truffle and Ganache...it might be fine with geth, I'm not sure.

**Comment by Bowfish** [comment]
Here is my latest version of the geth commandline:
```
geth --datadir ./node01 --networkid 56707 --syncmode 'full' --port 30311 --rpc --rpcaddr 'localhost' --rpcport 8601 --rpcapi 'personal,db,eth,net,web3,txpool,miner,clique' --rpccorsdomain 'http://localhost:3000' --ws --wsaddr 'localhost' --wsport 8546 --mine
```

Here is my latest version of the truffle-config.js configuration:
```
poadevnet: {
  network_id: 56707,       // Any network (default: none)
  provider: () => {
    const Web3 = require("./client/node_modules/web3");
    const wsProvider = new Web3.providers.WebsocketProvider("ws://localhost:8546", {
      headers: {
        Origin: "http://localhost"
      }
    })
    console.log(wsProvider);
    return wsProvider;
  },
},
```
Here is the output of console.log(wsProvider) 
```
WebsocketProvider {
  _events: {},
  _eventsCount: 0,
  connection: 
   W3CWebSocket {
     _listeners: 
      { message: [Array],
        open: [Array],
        close: [Array],
        error: [Array] },
     addEventListener: [Function: _addEventListener],
     removeEventListener: [Function: _removeEventListener],
     dispatchEvent: [Function: _dispatchEvent],
     _url: 'ws://localhost:8546',
     _readyState: 0,
     _protocol: undefined,
     _extensions: '',
     _bufferedAmount: 0,
     _binaryType: 'arraybuffer',
     _connection: undefined,
     _client: 
      WebSocketClient {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        config: [Object],
        _req: [Object],
        protocols: [],
        origin: null,
        url: [Object],
        secure: false,
        base64nonce: 'bwZAaBbOZlTo7zVEWuzfqQ==' } },
  timeout: undefined,
  subscriptions: {},
  READY: 'ready',
  CONNECT: 'connect',
  ERROR: 'error',
  CLOSE: 'close',
  SOCKET_MESSAGE: 'socket_message',
  SOCKET_READY: 'socket_ready',
  SOCKET_CLOSE: 'socket_close',
  SOCKET_ERROR: 'socket_error',
  SOCKET_CONNECT: 'socket_connect',
  SOCKET_NETWORK_CHANGED: 'socket_networkChanged',
  SOCKET_ACCOUNTS_CHANGED: 'socket_accountsChanged',
  host: 'ws://localhost:8546' 
}
```

And here is the error message:
```
/home/xyz/src/bd300/client/node_modules/web3-providers/dist/web3-providers.cjs.js:242
        event = this.getSubscriptionEvent(response.params.subscription);
                                                          ^
TypeError: Cannot read property 'subscription' of undefined
    at WebsocketProvider.onMessage (/home/xyz/src/bd300/client/node_modules/web3-providers/dist/web3-providers.cjs.js:242:59)
    at WebsocketProvider.onMessage (/home/xyz/src/bd300/client/node_modules/web3-providers/dist/web3-providers.cjs.js:378:77)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/home/xyz/src/bd300/client/node_modules/yaeti/lib/EventTarget.js:115:12)
    at W3CWebSocket.onMessage (/home/xyz/src/bd300/client/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/home/xyz/src/bd300/client/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.processFrame (/home/xyz/src/bd300/client/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /home/xyz/src/bd300/client/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

web3: 1.0.0-beta.46
Truffle v5.0.4 (core: 5.0.4)
Solidity v0.5.0 (solc-js)
Node v8.15.

**Comment by eggplantzzz** [comment]
Try downgrading Web3 to version 1.0.0-beta.37 and trying again. Let me know what happens.

**Comment by Bowfish** [comment]
@eggplantzzz With Web3 to version 1.0.0-beta.37 it looks a bit better. At least I don't get the error message anymore, but I get the following output, that the connection is not open on send.

```
WebsocketProvider {
  responseCallbacks: {},
  notificationCallbacks: [],
  _customTimeout: undefined,
  connection: 
   W3CWebSocket {
     _listeners: {},
     addEventListener: [Function: _addEventListener],
     removeEventListener: [Function: _removeEventListener],
     dispatchEvent: [Function: _dispatchEvent],
     _url: 'ws://localhost:8546',
     _readyState: 0,
     _protocol: undefined,
     _extensions: '',
     _bufferedAmount: 0,
     _binaryType: 'arraybuffer',
     _connection: undefined,
     _client: 
      WebSocketClient {
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        config: [Object],
        _req: [Object],
        protocols: [],
        origin: undefined,
        url: [Object],
        secure: false,
        base64nonce: '2QeLwQD8V/t8Z33bx5fj3w==' },
     onerror: [Function],
     onclose: [Function],
     onmessage: [Function] },
  connected: [Getter] }
connection not open on send()
connection not open on send()

   Replacing 'MyContracts'
   ------------------------
connection not open on send()
connection not open on send()
connection not open
Truffle v5.0.4 (core: 5.0.4)
Node v8.15.0
```
The 1_initial_migration.js is working fine, but the second part 2_deploy_contracts.js produces the message from above.

**Comment by gabeibarra** [comment]
I was having the same issue as @Bowfish above `connection not open on send()`, and then when changing to many different Truffle / Web3js version pairs, also having the original subscription error.

There are also errors in the HttpProvider provider, preventing an http or https deploy (This is the only way I know to do an https deploy to custom network!!!).

Now I'm doing manual deploys without Truffle, but I'd like to help get to the bottom of it in a PR. Can anyone point us to the source code area as I investigate?

**Comment by n0ke** [comment]
I'm currently having the same issue `connection not open on send()` with Truffle v5.0.5 and Web3 1.0.0-beta.37 when I'm trying to migrate my contracts :disappointed: I re-installed truffle with different versions (both truffle and web3) but it still doesn't work ...

**Comment by eggplantzzz** [comment]
@gabeibarra What part of the code are you interested in investigating?
@Bowfish Were you able to get it working with geth? Were you ever able to get it working if you tried to use Ganache? I would be interested in knowing whether this is geth-specific issue.

**Comment by Bowfish** [comment]
@eggplantzzz I posted some update on spectrum about this and here is the link to the github repo with the code https://github.com/Bowfish/truffle-ws-migrate-test

**Comment by eggplantzzz** [comment]
Turns out this is a geth issue.
https://github.com/ethereum/go-ethereum/issues/16846

**Comment by eggplantzzz** [comment]
@Bowfish I see that they closed that issue over on the Geth. Is that issue resolved?
