### ISSUE TITLE
truffle compile --list fails

### ISSUE THREAD

**Issue by mrwillis** [trufflesuite/truffle#1721]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.
Can't get compiler list. If you look at the error, looks like the URL doesn't even exist

## Steps to Reproduce
Please provide the shortest amount of steps to reproduce your issue.
`truffle compile --list`

## Expected Behavior
What you expected to happen.
Should list compiler versions available for download (solc)

## Actual Results
$ truffle compile --list
> Error: Failed to complete request to: https://solc-bin.ethereum.org/bin/list.json. Are you connected to the internet?

RequestError: Error: getaddrinfo EAI_AGAIN solc-bin.ethereum.org solc-bin.ethereum.org:443
    at VersionRange.errors (C:\Users\julia\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-compile\compilerSupplier\loadingStrategies\LoadingStrategy.js:57:1)
    at request.then.catch.err (C:\Users\julia\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-compile\compilerSupplier\loadingStrategies\VersionRange.js:148:1)
    at tryCatcher (C:\Users\julia\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\bluebird\js\release\util.js:16:1)
    at Promise._settlePromiseFromHandler (C:\Users\julia\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\bluebird\js\release\promise.js:512:1)
    at Promise._settlePromise (C:\Users\julia\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\bluebird\js\release\promise.js:569:1)
    at Promise._settlePromise0 (C:\Users\julia\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\bluebird\js\release\promise.js:614:1)
    at Promise._settlePromises (C:\Users\julia\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\bluebird\js\release\promise.js:690:1)
    at _drainQueueStep (C:\Users\julia\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\bluebird\js\release\async.js:138:1)
    at _drainQueue (C:\Users\julia\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\bluebird\js\release\async.js:131:1)
    at Async._drainQueues (C:\Users\julia\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\bluebird\js\release\async.js:147:1)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\julia\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\bluebird\js\release\async.js:17:1)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Truffle v5.0.4 (core: 5.0.4)
Node v10.15.1

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: Windows 10
* Ethereum client: ganache-cli
* Truffle version (`truffle version`): 5.0.4
* node version (`node --version`): 10.15.1
* npm version (`npm --version`): 6.4.1

**Comment by saturn-network** [comment]
Temporary workaround:

```patch
diff --git a/node_modules/truffle/build/cli.bundled.js b/node_modules/truffle/build/cli.bundled.js
index 89cf161..ed43843 100755
--- a/node_modules/truffle/build/cli.bundled.js
+++ b/node_modules/truffle/build/cli.bundled.js
@@ -120421,8 +120421,8 @@ const fs = __webpack_require__(4);
 class LoadingStrategy {
   constructor(options) {
     const defaultConfig = {
-      versionsUrl: "https://solc-bin.ethereum.org/bin/list.json",
-      compilerUrlRoot: "https://solc-bin.ethereum.org/bin/",
+      versionsUrl: "https://raw.githubusercontent.com/ethereum/solc-bin/gh-pages/bin/list.json",
+      compilerUrlRoot: "https://raw.githubusercontent.com/ethereum/solc-bin/gh-pages/bin/",
       dockerTagsUrl:
         "https://registry.hub.docker.com/v2/repositories/ethereum/solc/tags/"
     };
```

**Comment by eggplantzzz** [comment]
We were having some issues with solc-bin for a while. We updated the urls and it should work now on v5.0.5. Let me know if you still have trouble. Closing this.
