### ISSUE TITLE
Truffle Suite HD-Wallet Providing Errors / Causing Crashes

### ISSUE THREAD

**Issue by lrgeoemtry** [trufflesuite/truffle#1730]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

createPuzzleSecure error Cannot read property 'then' of undefined
POST /api/1.0/createPuzzleSecure/0xf55f45267258efbfcefb795a688630a26576635e/15/undefined/%7B%7D 200 36.717 ms - 50 /home/ubuntu/hipr-restful/node_modules/truffle-hdwallet-provider/dist/index.js:15
*/var n=Object.getOwnPropertySymbols,i=Object.prototype.hasOwnProperty,o=Object.prototype.propertyIsEnumerable;t.ex
ports=function(){try{if(!Object.assign)return!1;var t=new String("abc");if(t[5]="de","5"===Object.getOwnPropertyNam
es(t)[0])return!1;for(var e={},r=0;r<10;r++)e["_"+String.fromCharCode(r)]=r;if("0123456789"!==Object.getOwnPropertyNames(e).map(function(t){return e[t]}).join(""))return!1;var n={};return"abcdefghijklmnopqrst".split("").forEach(fu
nction(t){n[t]=t}),"abcdefghijklmnopqrst"===Object.keys(Object.assign({},n)).join("")}catch(t){return!1}}()?Object.assign:function(t,e){for(var r,a,s=function(t){if(null==t)throw new TypeError("Object.assign cannot be called with
null or undefined");return Object(t)}(t),u=1;u<arguments.length;u++){for(var c in r=Object(arguments[u]))i.call(r,c
)&&(s[c]=r[c]);if(n){a=n(r);for(var l=0;l<a.length;l++)o.call(r,a[l])&&(s[a[l]]=r[a[l]])}}return s}},function(t,e){
t.exports=function(t

TypeError: e is not a function
at /home/ubuntu/hipr-restful/node_modules/truffle-hdwallet-provider/dist/index.js:15:544968
at /home/ubuntu/hipr-restful/node_modules/truffle-hdwallet-provider/dist/index.js:1:150953
at d (/home/ubuntu/hipr-restful/node_modules/truffle-hdwallet-provider/dist/index.js:1:215490)
at /home/ubuntu/hipr-restful/node_modules/truffle-hdwallet-provider/dist/index.js:1:215543
at e.default (/home/ubuntu/hipr-restful/node_modules/truffle-hdwallet-provider/dist/index.js:15:559863)

**Comment by lrgeoemtry** [comment]
as asked by @gnidan 
 truffle version
Truffle v4.0.7(core: 4.0.7)
Solidity v0.4.24 (solc-js)

also the project this is happening in is https://github.com/hercone/restful-hipr

@xen1024 is the lead dev on here

**Comment by gnidan** [comment]
Could you please try upgrading to either to Truffle v5 (breaking changes) or v4.1.15 (no breaking changes)? This way we won't risk chasing down an outdated bug. Thanks!

**Comment by lrgeoemtry** [comment]
@xen1024 
you need to do this in hipr anyway.

**Comment by gnidan** [comment]
Just following up here, is this still an issue? Let us know! Thanks!
