### ISSUE TITLE
The Conosole is not working

### ISSUE THREAD

**Issue by gorojou** [trufflesuite/truffle#1749]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

ReferenceError: Election is not defined
    at evalmachine.<anonymous>:0:1
    at Script.runInContext (vm.js:134:20)
    at runScript (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/console.js:199:1)
    at Console.interpret (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/console.js:213:1)
    at ReplManager.interpret (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/repl.js:118:1)
    at bound (domain.js:395:14)
    at REPLServer.runBound [as eval] (domain.js:408:12)
    at REPLServer.onLine (repl.js:639:10)
    at REPLServer.emit (events.js:188:13)
    at REPLServer.EventEmitter.emit (domain.js:441:20)
truffle(development)> 
---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by gnidan** [comment]
Closing for issue maintenance. If this is still a problem for you, could you fill out the issue template? We'll be happy to re-open this with more information to help us investigate. Thanks!
