### ISSUE TITLE
Differing Results with `truffle test` and `truffle test ./test/...`

### ISSUE THREAD

**Issue by isaacsultan** [trufflesuite/truffle#1785]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When calling `truffle test`, I am getting different results to `truffle test ./test/...` on a specific file. 
The test in question is [here](https://github.com/partial-f/core/blob/b860a9b17b030ad0712af9edf3726d0bc54b160a/test/ProductTeller.test.js#L55), and I am doing the setup in a [separate file](https://github.com/partial-f/core/blob/develop/test/productTellerSetup.js): 

The failure I am receiving on the `truffle test` run mentions 
      `shouldFailWithMessage (node_modules/openzeppelin-test-helpers/src/shouldFail.js:14:10)`
in the `before all` hook. Which is not being called in this file. I have a feeling that there may be some kind of leak from a previous test that is causing this. 

## Steps to Reproduce

```
git clone https://github.com/partial-f/core.git
git checkout develop
npm install
truffle test 
truffle test ./test/ProductTeller.test.js
```

## Expected Behavior

Expected the same results for the contract, regardless if called in isolation or with all of the tests. 

## Actual Results

`truffle test`
```
  6) Contract: ProductTeller
       "before all" hook: prepare suite:
     Uncaught AssertionError: Expected failure not received
      at shouldFailWithMessage (node_modules/openzeppelin-test-helpers/src/shouldFail.js:14:10)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  7) Contract: ProductTeller
       "before each" hook: before test for "should allow an admin to set a product fee":
     TypeError: Cannot read property 'call' of undefined


  8) Contract: ProductTeller
       "after each" hook: after test for "should allow an admin to set a product fee":
     TypeError: Cannot read property 'call' of undefined
```

`truffle test ./test/ProductTeller.test.js`
```
Contract: ProductTeller
...
  12 passing (25s)
  1 pending
  1 failing
...
```
## Environment

- Operating System: 10.14
- Truffle version (truffle version): v5.0.5
- node version (node --version): v10.14.2
- npm version (npm --version): 6.4.1
- ganache-cli: Ganache CLI v6.3.0 (ganache-core: 2.4.0)

**Comment by wTendera** [comment]
I recently run into similar issues with truffle tests

When truffle is running tests it's supposed to have clean room environment for each test, so there should not be a difference if I run a test on it's own or with other tests.

Unluckily that's not the case with my tests. When I run a test file on it's own every test passes nicely, but when I go for 'truffle test' on whole project suddenly the same test starts failing.

Moreover it seems really non-deterministic as with each tests execution I can get different errors, or the test fails at different point.

At first I thought it was because I upgraded to solidity 0.5.4 (and truffle/ganache as well) but even on earlier distributions it works the same.

I tried various setups with different versions of truffle/ganache/node but everytime at some point (usually random) my tests fail.

Currently I'm running everything on

Ganache CLI v6.2.5 (ganache-core: 2.3.3)
Truffle v5.0.3 (core: 5.0.3)
Solidity - 0.5.4 (solc-js)
Node v8.9.4
Any idea why is it happening?

**Comment by wTendera** [comment]
@isaacsultan   Updating ganache-cli to 6.4.1 made it work for me. 

Other issues
https://github.com/trufflesuite/ganache-cli/issues/624
https://github.com/trufflesuite/ganache-core/pull/329
https://github.com/trufflesuite/ganache-core/issues/358

**Comment by isaacsultan** [comment]
@wTendera Thanks, updated and fixed for me too!

**Comment by kseniya292** [comment]
Hello. I'm still running into this issue. When I run `truffle test test/pathToContract` on each of my files, all tests pass. When I run `truffle test` almost half of the tests fail. I've tried: ganache-cli v6.2.4 and v 6.4.1. 

Truffle v5.0.8
Solidity - 0.5.0
Node v11.0.0

Not sure what else to do.

**Comment by dougiebuckets** [comment]
Hi there - @kseniya292 (above) and I are working on the same project. For kicks, I ran all of the tests in the reverse order that they run when we use `truffle test`. I.e., 

`truffle test file1.test.js file2.test.js file3.test.js file4.test.js file5.test.js file6.test.js`

Now, approximately 20 more tests fail vs when we run `truffle test`. Again, when we run each test file independently, all tests pass (e.g., `truffle test test/file1.test.js`).

**Comment by CruzMolina** [comment]
Hey @kseniya292 & @dougiebuckets !

I'm wondering if this is another `ganache-core` specific bug. Can you share a repo so I can reproduce and start isolating the problem?

**Comment by kseniya292** [comment]
@CruzMolina Thanks so much for taking a look! It's a private repo so I added you on as a collaborator.
Command to run ganache:
`ganache-cli --gasLimit=8000029 --gasPrice=30000000000 --defaultBalanceEther=100000000 -a 30`

`truffle test` - 113 tests break

`truffle test test/MultiSigWallet.test.js test/LottoDAO.test.js test/LottoProxyFactory.test.js  test/Governance.test.js test/MasterRegistry.test.js test/LottoToken.test.js` - all the tests pass. This is a random order I tried out that works for some reason.

**Comment by CruzMolina** [comment]
Awesome, thanks for the instructions @kseniya292 . Checking this out now 🧐

**Comment by CruzMolina** [comment]
Ah, okay. Looks like you are in the process of updating from truffle 4 to truffle 5.

I've invited you to a private repo w/ a branch I worked on real quick to help you along (would have just pushed my local branch but I don't think I have proper permissions from your repo). It turns out (at least in v5), we already expose `chai.assert` internally for running js tests, so declaring `const assert = chai.assert` was causing what appears to be an overloading error. Can simply start using `assert()` w/o needing to require the lib.

The other issue I noticed is you're using `bn-chai`, which (for whatever reason) wasn't written to support `should()`. There appears to also be an overloading error happening there as well between `chai` and `bn-chai`.

For replacing the test comparisons, I pushed an example suggestion to get you guys started.

Currently only 34 tests fail on my end, yay! 🎉

**Comment by kseniya292** [comment]
@CruzMolina Omg, thank you so much! We really appreciate you taking the time to look at the repo.
I'll make those updates. 
I wonder why the overloading errors are happening inconsistently? Why is it that when you run in a specific order, they all pass, and then if you switch the order.. some of the tests fail?

**Comment by CruzMolina** [comment]
Np! The errors really threw me for a minute, so I'm glad it wasn't actually something with ganache-core/cli or truffle proper.

My best guess about the inconsistency is that maybe requiring the same libraries within truffle's test running context (mocha) causes the overloading. So maybe calling `truffle test` by itself loads all of the js tests within the same context w/ those requires causing funky things to happen vs creating a more isolated/separate context for each individual file when doing `truffle test <file>`  or `truffle test <file1> <file2>`. I'm not quite sure and would need to look into it some more.

**Comment by CruzMolina** [comment]
Hmm... did a little more testing. I'm really not sure. The only consistency seems to be related to importing `chai.assert` again when it's already globally available and also using `bn-chai` 🤷‍♂️

**Comment by kseniya292** [comment]
@CruzMolina All the tests are finally passing! I removed the `chai.assert` declaration, and removed `bn-chai` and refactored my tests to use `should.equal` rather than `should.eq.BN`. Thanks again for your help!

**Comment by CruzMolina** [comment]
Great! Glad to help!

**Comment by theabdulmateen** [comment]
I had a similar issue with `truffle test` and I was using the `should.eventually.equal()` method and it seems to also be causing such inconsistency with the tests.

Hope this helps.

**Comment by brucdarc** [comment]
Im having a similar problem but reverse, all tests were working with ```truffle test``` but when I try to do an individual test file I get
```Error: Invalid Chai property: rejectedWith```

**Comment by sonika-25** [comment]
> We are facing rather similar issue on `truffle test` on forked ganache.
> 
> The `it()` blocks are passing individually with `it.only()`, but failing when we do all of them together, some of them are passing & some of them are failing.

Hi, did you ever solve this?

**Comment by akcgjc007** [comment]
Yo @sonika-25 
We never did. For the testing purpose, we knew that the tests are passing. So, we skipped this step. 

I debugged it and concluded that `ganache-cli` was not able to handle failed transactions properly and giving unknown behaviour in the exact same conditions.

Link for our repo: [link](https://github.com/chainGers-2021/our-contracts/tree/ganache-error-error)

**Comment by sargue** [comment]
I've created a specific issue that's probably related to this one: https://github.com/trufflesuite/truffle/issues/5155

**Comment by Pafaul** [comment]
Still an issue, enountered it while developing project:
- Runs fine when calling ```test``` command on specific file
- Fails if ```test``` command is called without file specification

Some more info (cannot share code really) - all tests (~6 test files) which all use the same contracts and ```.deployed()``` function for creating instances, heavily relying on instances deployed during migration and clean-room environment

Using ganache (launched in wsl 2.0 ubuntu 20.04) + truffle (tried wsl Ubuntu and Windows):
- ```ganache --version```: ganache v7.0.4 (@ganache/cli: 0.1.5, @ganache/core: 0.1.5)
- ```truffle --version```:
Truffle v5.4.24 (core: 5.4.24)
Solidity - 0.8.6 (solc-js)
Node v14.17.6
Web3.js v1.5.3
