### ISSUE TITLE
debug error - TypeError: Cannot read property 'toTwos' of undefined

### ISSUE THREAD

**Issue by flockonus** [trufflesuite/truffle#1946]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

An error pops up when debugging against a contract in Rinkeby.

Sorry i can't share the source code yet, but the project is unpublished.

## Steps to Reproduce

Running console with:

```
WEB3_URL=<some url> PRIV=<priv key> FROM_ADDRESS=<pub addr> yarn run truffle console --network rinkeby
```

## Expected Behavior

See the whole stack trace as expected from debug.

## Actual Results

```
debug(rinkeby:0x885bcbfc...)>

GateKeeper.sol:

112:         address t = tournament.addr;
113:         // tournament must be open
114:         require(Tournament1(t).isBuyOpen(), "buy must be open");
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^

debug(rinkeby:0x885bcbfc...)>
TypeError: Cannot read property 'toTwos' of undefined
    at Object.toBytes (/workspace/project/node_modules/truffle/build/webpack:/packages/truffle-decode-utils/dist/conversion.js:130:1)
    at /workspace/project/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1871:23
    at Array.map (<anonymous>)
    at /workspace/project/node_modules/truffle/build/webpack:/packages/truffle-debugger/dist/debugger.js:1870:126
    at /workspace/project/node_modules/truffle/build/webpack:/~/reselect/es/index.js:70:1
    at /workspace/project/node_modules/truffle/build/webpack:/~/reselect/es/index.js:30:1
    at /workspace/project/node_modules/truffle/build/webpack:/~/reselect/es/index.js:84:1
    at /workspace/project/node_modules/truffle/build/webpack:/~/reselect/es/index.js:30:1
    at /workspace/project/node_modules/truffle/build/webpack:/~/reselect/es/index.js:80:1
    at Function.<anonymous> (/workspace/project/node_modules/truffle/build/webpack:/~/reselect/es/index.js:30:1)
    at /workspace/project/node_modules/truffle/build/webpack:/~/reselect-tree/index.js:209:1
    at /workspace/project/node_modules/truffle/build/webpack:/~/reselect/es/index.js:80:1
    at /workspace/project/node_modules/truffle/build/webpack:/~/reselect/es/index.js:30:1
    at runSelectEffect (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:730:1)
    at runEffect (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1198:1)
    at digestEffect (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1265:1)
    at next (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1155:1)
    at currCb (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1245:1)
    at runSelectEffect (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:731:1)
    at runEffect (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1198:1)
    at digestEffect (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1265:1)
    at next (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1155:1)
    at proc (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1102:1)
    at /workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:585:1
    at immediately (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:56:1)
    at runForkEffect (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:584:1)
    at runEffect (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1198:1)
    at digestEffect (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1265:1)
    at next (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1155:1)
    at currCb (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1245:1)
    at takeCb (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:503:1)
    at put (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:339:1)
    at Object.chan.put (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:371:1)
    at /workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:1410:1
    at dispatch (/workspace/project/node_modules/truffle/build/webpack:/~/redux/es/applyMiddleware.js:35:1)
    at /workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/chunk-e922c950.js:122:1
    at /workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:472:1
    at exec (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:31:1)
    at flush (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:87:1)
    at asap (/workspace/project/node_modules/truffle/build/webpack:/~/@redux-saga/core/dist/redux-saga-core.esm.js:46:1)
The above error occurred in task tickSaga
    created by takeEvery(TICK, tickSaga)
    created by data.saga
    created by session.saga
Tasks cancelled due to error:
takeEvery(TICK, tickSaga)
controller.saga
evm.saga
solidity.saga
trace.saga
web3.saga

```

## Environment

* Operating System: mac os
* Ethereum client:
```
compilers: {
    solc: {
      // where do we get to know the latest we can use?
      version: '0.5.6',
      settings: {
        evmVersion: 'constantinople',
        optimizer: {
          enabled: true,
          runs: 200,
        },
      },
    },
  },
```
* Truffle version (`truffle version`): 5.0.12
* node version (`node --version`): tried v11.4.0,  v12.0.0
* npm version (`npm --version`):

**Comment by haltman-at** [comment]
So, trying to make sense of what you posted -- I notice the prompt is blank.  What debugger command was it that you ran that caused this error?  What is `n`, step next?  (If you never entered anything, this would be the default.)  Thanks!

Also, while the original project is not public, it would be very helpful if you could perhaps provide a stripped-down example that still results in the bug.  In any case, I'll look into it.  Thanks!

**Comment by haltman-at** [comment]
By the way, in the meantime you might want to try with truffle 5.0.13, just to check if that fixes it.

**Comment by flockonus** [comment]
You guys are shipping at great speed 🚀 

Running it against 5.0.14 made the issue go away and I could debug, thank you 🙇
