### ISSUE TITLE
truffle console doesn't display reason strings from failed transactions

### ISSUE THREAD

**Issue by elenadimitrova** [trufflesuite/truffle#2058]
## Issue

When a transaction triggered via the `truffle console` fails, the reason string, when available is not returned.

## Steps to Reproduce

Fork the [colonyNetwork](https://github.com/JoinColony/colonyNetwork) repo
Open the truffle console, connected to Goerli `yarn run truffle console --network goerli`
Run
```
const colonyNetwork = await IColonyNetwork.at("0x79073fc2117dD054FCEdaCad1E7018C9CbE3ec0B")
```
Then call one of the `auth`-ed functions, e.g. `await colonyNetwork.startNextCycle()`

## Expected Behavior

Surprisingly when using `ganache-cli` to fork Goerli testnet and run the same failing transaction in the console against that, it returns the revert error:
```
 Error: Returned error: VM Exception while processing transaction: revert colony-task-change-execution-failed -- Reason given: colony-task-change-execution-failed.
    at XMLHttpRequest._onHttpResponseEnd (/Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
    at XMLHttpRequest._setReadyState (/Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest.request.onreadystatechange (/Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/~/web3/~/web3-providers-http/src/index.js:96:1)
    at /Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
    at /Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-requestmanager/src/index.js:140:1
    at Object.ErrorResponse (/Users/Elena/colonyNetwork/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-helpers/src/errors.js:29:1) reason: 'colony-task-change-execution-failed' }
```

## Actual Results

```
name: 'StatusError',
  tx:
   '0x8fc69b775fe59305ab53ac00648d6d1f2b274c8b550c67d53048377bfe3e9a4a',
  receipt:
   { blockHash:
      '0x7ccba61113b02d39e4803e0bf5b0c6fd7059152812fecb8c19896f826fed7132',
     blockNumber: 668366,
     contractAddress: null,
     cumulativeGasUsed: 73963,
     from: '0x7492ce19d83b3a0bac1bebc9706ce0df4add105f',
     gasUsed: 73963,
     logs: [],
     logsBloom:
      '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
     status: false,
     to: '0x3858636f27e269d23db2ef1fcca5f93dcaa564cd',
     transactionHash:
      '0x8fc69b775fe59305ab53ac00648d6d1f2b274c8b550c67d53048377bfe3e9a4a',
     transactionIndex: 0,
     rawLogs: [] },
  reason: undefined }
```

## Environment

* Operating System: OSX
* Ethereum client: Infura Goerli
* Truffle version (`truffle version`):
Truffle v5.0.18 (core: 5.0.18)
Solidity - 0.5.8 (solc-js)
Node v10.12.0
Web3.js v1.0.0-beta.37

**Comment by elenadimitrova** [comment]
Actually as @area rightly pointed out, this is probably not truffle's fault but the non-ganache-cli clients that don't yet have revert error strings implemented. What year is this?
