### ISSUE TITLE
Error: components found but type is not tuple; report on GitHub

### ISSUE THREAD

**Issue by Amxx** [trufflesuite/truffle#2085]
I got this error that asked me to report on GitHub:

```
Error: components found but type is not tuple; report on GitHub
    at /home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-utils/src/index.js:119:1
    at Array.forEach (<anonymous>)
    at _flattenTypes (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-utils/src/index.js:116:1)
    at Object._jsonInterfaceMethodToString (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-utils/src/index.js:99:1)
    at /home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:117:1
    at Array.map (<anonymous>)
    at Object.set [as jsonInterface] (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:107:1)
    at Contract (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:218:1)
    at new Contract (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-eth/src/index.js:149:1)
    at Function.deploy (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/lib/execute.js:213:1)
    at constructor.detectNetwork.then.network (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/lib/contract/constructorMethods.js:56:1)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
Error: components found but type is not tuple; report on GitHub
    at /home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-utils/src/index.js:119:1
    at Array.forEach (<anonymous>)
    at _flattenTypes (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-utils/src/index.js:116:1)
    at Object._jsonInterfaceMethodToString (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-utils/src/index.js:99:1)
    at /home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:117:1
    at Array.map (<anonymous>)
    at Object.set [as jsonInterface] (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:107:1)
    at Contract (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:218:1)
    at new Contract (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/~/web3-eth/src/index.js:149:1)
    at Function.deploy (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/lib/execute.js:213:1)
    at constructor.detectNetwork.then.network (/home/amxx/.nvm/versions/node/v11.12.0/lib/node_modules/truffle/build/webpack:/packages/truffle-contract/lib/contract/constructorMethods.js:56:1)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

/home/amxx/.config/truffle/compilers/node_modules/soljson-v0.5.8+commit.23d335f2.js:30
(Module.asmGlobalArg,Module.asmLibraryArg,buffer);var __GLOBAL__I_000101=Module["__GLOBAL__I_000101"]=asm["__GLOBAL__I_000101"];var __GLOBAL__sub_I_ABIFunctions_cpp=Module["__GLOBAL__sub_I_ABIFunctions_cpp"]=asm["__GLOBAL__sub_I_ABIFunctions_cpp"];var __GLOBAL__sub_I_ABI_cpp=Module["__GLOBAL__sub_I_ABI_cpp"]=asm["__GLOBAL__sub_I_ABI_cpp"];var __GLOBAL__sub_I_ASTJsonConverter_cpp=Module["__GLOBAL__sub_I_ASTJsonConverter_cpp"]=asm["__GLOBAL__sub_I_ASTJsonConverter_cpp"];var __GLOBAL__sub_I_AST_cpp=Module["__GLOBAL__sub_I_AST_cpp"]=asm["__GLOBAL__sub_I_AST_cpp"];var __GLOBAL__sub_I_ArrayUtils_cpp=Module["__GLOBAL__sub_I_ArrayUtils_cpp"]=asm["__GLOBAL__sub_I_ArrayUtils_cpp"];var __GLOBAL__sub_I_AsmAnalysis_cpp=Module["__GLOBAL__sub_I_AsmAnalysis_cpp"]=asm["__GLOBAL__sub_I_AsmAnalysis_cpp"];var __GLOBAL__sub_I_CompilerContext_cpp=Module["__GLOBAL__sub_I_CompilerContext_cpp"]=asm["__GLOBAL__sub_I_CompilerContext_cpp"];var __GLO
abort({}). Build with -s ASSERTIONS=1 for more info.
```

**Comment by CruzMolina** [comment]
Hey @Amxx, thanks for reporting this.
Can you provide reproducible steps or a reproduction repo?

**Comment by Amxx** [comment]
I cannot reproduce it consistently. Deleting the `build` folder and recompiling solves the issue. I don't know how to reproduce it 

it happens regularly when trying to migrate/test after having modified some contracts

**Comment by CruzMolina** [comment]
Ah, I think you might have run into this issue #2048 which (hopefully 🤞) was resolved in 5.0.20, can you give that version a shot?
