### ISSUE TITLE
Truffle fails due to presence of swap files in build folder

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#2134]
## Issue

If you have an artifact file open in a text editor that creates swap files or backup files, various truffle commands will attempt to read this as JSON and then fail when it's improperly formatted.  (I've noticed this issue specifically with Vim; I don't know offhand how it would differ for other text editors.)  It comes up with both `truffle migrate` and `truffle console`, for instance.

Note: This seems to have been raised as an issue before regarding `.DS_Store` files on Macintosh.  So I guess it's not just swapfiles, but other hidden files that may pop up without deliberate user action.

## Expected Behavior

Truffle should have some way of recognizing naming conventions for such files and skipping them.  Actually, it might just suffice to skip all files with names not ending in `.json`.  Then we don't have to worry about the precise naming conventions.  (We could also skip all hidden files or dotfiles as well, perhaps.)

## Actual Results

An example, with `truffle migrate`:

```
sniffnoy@hyperpotato ~/truffle/test-cases/malformed-test $ truffle-next migrate

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Error: Could not find built Migrations contract: Unexpected token b in JSON at position 0
    at Object.lastCompletedMigration (/home/sniffnoy/truffle/truffle/packages/truffle-migrate/index.js:190:13)
    at Promise (/home/sniffnoy/truffle/truffle/packages/truffle-migrate/index.js:227:19)
    at new Promise (<anonymous>)
    at Object.needsMigrating (/home/sniffnoy/truffle/truffle/packages/truffle-migrate/index.js:224:12)
    at runMigrations (/home/sniffnoy/truffle/truffle/packages/truffle-core/lib/commands/migrate.js:238:46)
    at Contracts.compile.then (/home/sniffnoy/truffle/truffle/packages/truffle-core/lib/commands/migrate.js:204:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle (unbundled) (core: 5.0.24)
Node v10.15.3
```

(Here I have `MalformedTest.json` open in Vim.)

Here's a different error caused by this, in `truffle console`:

```
sniffnoy@hyperpotato ~/truffle/test-cases/malformed-test $ truffle-next console
Unexpected error: Cannot provision contracts while instantiating the console.
Error: Cannot parse .MalformedTest.json.swp: Unexpected token b in JSON at position 0
    at /home/sniffnoy/truffle/truffle/packages/truffle-core/lib/console.js:109:19
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
truffle(development)> 
```

Of course, if I close the file, the swapfile goes away and everything is fine.

**Comment by CruzMolina** [comment]
Good find @haltman-at !
