### ISSUE TITLE
`Returned values aren't valid, did it run Out of Gas?`  when  queying eth balance

### ISSUE THREAD

**Issue by wangjunbao2018** [trufflesuite/truffle#2136]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I have created a project following the doc Truffle Quick Start, After I run truffle develop, I depolyed a contract, then I tried to test it. But it has a error like this:

```
truffle(develop)> let instance = await MetaCoin.deployed()
undefined
truffle(develop)> let accounts = await web3.eth.getAccounts()
undefined
truffle(develop)> let balance = await instance.getBalance(accounts[0])
Error: Returned values aren't valid, did it run Out of Gas?
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/~/web3-providers-http/src/index.js:96:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-requestmanager/src/index.js:147:1
    at sendTxCallback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-method/src/index.js:473:1)
    at Method.formatOutput (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/~/web3-core-method/src/index.js:163:1)
    at Method.outputFormatter (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:818:1)
    at Contract._decodeMethodReturn (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-contract/src/index.js:465:1)
    at ABICoder.decodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/src/index.js:226:1)

```

For this is a query operation, why does this happen?  

## Environment

* Operating System:  MacOS Mojave 10.14
* Ethereum client:
* Truffle version (`truffle version`):  Truffle v5.0.18 (core: 5.0.18)
* node version (`node --version`):  Node v10.15.3
* npm version (`npm --version`):   6.4.1
* web3js version (`npm --version`):  Web3.js v1.0.0-beta.37

**Comment by rotcivegaf** [comment]
Give us the steps to reproduce the Error

**Comment by eggplantzzz** [comment]
Hey @wangjunbao2018! I'm guessing that you forgot to run your migrations. If you don't run the migrations first and deploy the contract then you won't be able to interact with it. When I run them and then run the commands above, everything goes smoothly. If I neglect to run the migrations I get the error that you received above. Try running the migrations first and let me know how it goes!

**Comment by CruzMolina** [comment]
@wangjunbao2018 Can you try upgrading to the latest `truffle`?

**Comment by fainashalts** [comment]
@wangjunbao2018 is this still an issue? Did you run your migrations and are you on the latest truffle? Thanks, please let us know!

**Comment by wangjunbao2018** [comment]
> @wangjunbao2018 is this still an issue? Did you run your migrations and are you on the latest truffle? Thanks, please let us know!

I didn't remember how I fixed this problem, but it's my code that has some problems.  thanks a lot.

**Comment by amitk41727** [comment]
> > @wangjunbao2018 is this still an issue? Did you run your migrations and are you on the latest truffle? Thanks, please let us know!
> 
> I didn't remember how I fixed this problem, but it's my code that has some problems. thanks a lot.

hii i am facing the same issues can u just remember and tell the solution . i am not able to complete a single deployment of blockchain its frustrating

**Comment by amitk41727** [comment]
> @wangjunbao2018 is this still an issue? Did you run your migrations and are you on the latest truffle? Thanks, please let us know!

on migrating it shows the same error and atlast its showing the version of truffle and node. as shown below:

Error: Returned values aren't valid, did it run Out of Gas?
    at ABICoder.decodeParameters (C:\Users\amitk\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3-eth-abi\src\index.js:226:1)
    at Contract._decodeMethodReturn (C:\Users\amitk\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3-eth-contract\src\index.js:465:1)
    at Method.outputFormatter (C:\Users\amitk\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3-eth-contract\src\index.js:818:1)
    at Method.formatOutput (C:\Users\amitk\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3-eth-contract\~\web3-core-method\src\index.js:163:1)
    at sendTxCallback (C:\Users\amitk\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3-eth-contract\~\web3-core-method\src\index.js:473:1)
    at C:\Users\amitk\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3-core-requestmanager\src\index.js:147:1
    at C:\Users\amitk\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-provider\wrapper.js:112:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\amitk\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3-providers-http\src\index.js:96:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\amitk\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request-event-target.js:34:1)
    at XMLHttpRequest._setReadyState (C:\Users\amitk\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request.js:208:1)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\amitk\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request.js:318:1)
    at IncomingMessage.<anonymous> (C:\Users\amitk\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2-cookies\dist\xml-http-request.js:289:47)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Truffle v5.0.2 (core: 5.0.2)
Node v16.13.2
