### ISSUE TITLE
Unable to migrate smart contract (Token ERC20) when using parameters in constructor

### ISSUE THREAD

**Issue by alexandreValente** [trufflesuite/truffle#2141]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
Issue not found on Gitter but still searching.
---------------------------

## Issue

Hi to all,

don't know if this is a truffle init issue but I get this...
When I try to migrate my Token smart contract (using Openzeppelin ERC20) I want to migrate using a custom script for initializing constructor parameter but I get stuck somewhere:

This is the constructor of myToken...

constructor (uint _quantity, uint _price, uint _ethconv, uint _fees, address payable _codex, address payable _to) public {

    owner =  msg.sender;
    codex = _codex;
    quantity = _quantity;
    price = _price;
    ethconv = _ethconv;
    seller = _to;
    fees = _fees;
    
    initialSupply = _quantity;
    ethPrice = _price * _ethconv;
    
    transfer(msg.sender, initialSupply);
}

## Steps to Reproduce
truffle migrate or truffle migrate --reset

using following migration script:

And this is the migration script:

var myToken = artifacts.require("myToken");

let quantity = 100;
let price = 50;
let ethconv = 1;
let fees = 45;

owner = "0xbFe32eD630d3dBEFFa7Fa1dc38aA3108B8df840c";
codex = "0x36373E9d3A70c971D4D04b09697DA7d337204CDa";
seller = "0x3F3dEeA4877D97c98f610b5BE580DdA83dBC5C36";

module.exports = function(deployer) {
deployer.deploy(myToken, quantity, price, ethconv, fees, codex, seller, {from: owner});
};

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior
To get my Token deployed on local RPC (ganache GUI local blockchain).

What you expected to happen.
to get my constructor initialize the variables at migration.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

Error: Error: Error:  *** Deployment Failed ***

"myToken" hit a require or revert statement somewhere in its constructor. Try:
   * Verifying that your constructor params satisfy all require conditions.
   * Adding reason strings to your require statements.

    at Object.run (/usr/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)

## Environment

* Operating System: 4.18.0-21-generic #22-Ubuntu SMP (running inside Virtual Box 6.0)
* Ethereum client: Ganache GUI v2.0.2 beta 0
* Truffle version (`truffle version`): previously V.5.0.19 and now Truffle v5.0.25 (core: 5.0.25)  .
* node version (`node --version`): Node v10.15.3
* npm version (`npm --version`): 6.9.2 (just upgraded).

**Comment by alexandreValente** [comment]
OK I found my error...I made a mistake when calling the transfer function...transfer(msg.sender, initialSupply); This is the function causing the revert. And the parameters the error message talks about is about the function not the constructor parameters.
I have set this function in comment and the migration works as expected.
