### ISSUE TITLE
trouble with Migrations : sender account doesn't exist

### ISSUE THREAD

**Issue by vincentvanhassel** [trufflesuite/truffle#2160]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I can't migrate my contract on rsk testnet

## Steps to Reproduce

mkdir test && cd test && truffle init

npm install truffle-hdwallet-provider

define rsk in networks of the truffle configuration

``` javascript
rsk: {
      provider: () =>
        new HDWalletProvider(mnemonic, publicNode),
        network_id: '*',
        websockets: true,
        gas: 2500000,
        gasPrice: 183000
    }
```

add these lines before module.exports
``` javascript
const HDWalletProvider = require('truffle-hdwallet-provider');
const mnemonic = *your mnemonic*;
const publicNode = 'https://public-node.testnet.rsk.co:443';
```

truffle console --network rsk

## Expected Behavior

``` javascript
1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0xedb3fe0fcb025c24fbf7e10167874c9aa75c043d5e490ceef2d92ef6cd95f384
   > contract address:    0x2A9153ADb72Db565fcA8fcEf7AEC67772098Ec36
   > block number:        1
   > block timestamp:     1562600252
   > account:             0x8676cC4A318c3519093113668A750589F8d4D9c1
   > balance:             99.99430184
   > gas used:            284908
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00569816 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00569816 ETH


Summary
=======
> Total deployments:   1
> Final cost:          0.00569816 ETH
```

## Actual Results

``` javascript
1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
Error: Error: Error:  *** Deployment Failed ***

"Migrations" -- the sender account doesn't exist.

    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:84:1)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

## Environment

* Operating System: OS X 10.14.5
* Ethereum client:
* Truffle version: v5.0.18 (core: 5.0.18)
* node version: v11.7.0
* npm version: 6.9.0

**Comment by vincentvanhassel** [comment]
The problem comes from the fact that I had no rbtc on my wallet, obviously a wallet exists only when it is active (when it has rbtc). But the error message is not very explicit.

to solve this problem you just have to get rbtc: 

first get the address of your wallet
``` javascript
web3.currentProvider.wallets
```
then obtain rbtc via the faucet testnet

https://faucet.testnet.rsk.co/

and finally check that you have received them
```javascript
 web3.eth.getBalance (account, (err, res) => console.log (res))
 ```

 to finally restart the command
 ```javascript
 migrate --reset
 ```
