### ISSUE TITLE
permission denied, open '/root/.config/truffle/config.json'

### ISSUE THREAD

**Issue by thecircleoflifefree** [trufflesuite/truffle#2217]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

Didn't ask in gitter, all I see is a huge amount of questions unanswered and just broad disorder IMHO. 

## Issue

Unable to get truffel working due to the permission denied, already I have tried already using nvm rather than sudo npm as per other issue, and also chmoding things.

## Steps to Reproduce
[delta@alpha ~]$ sudo npm install -g truffle
/usr/local/lib/nodejs/node-v10.16.0-linux-x64/bin/truffle -> /usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/cli.bundled.js

> truffle@5.0.27 postinstall /usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle
> node ./scripts/postinstall.js

Error: EACCES: permission denied, open '/root/.config/truffle/config.json'
You don't have access to this file.

    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Configstore.get all [as all] (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/~/configstore/index.js:31:1)
    at new Configstore (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/~/configstore/index.js:25:31)
    at Function.Config.getUserConfig (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:395:1)
    at Object.<anonymous> (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/mnemonics/mnemonic.js:11:1)
    at __webpack_require__ (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/webpack/bootstrap fa1fcd3fc6c4fef3eaf9:19:1)
    at Object.command.command (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/develop.js:2:22)
    at __webpack_require__ (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/webpack/bootstrap fa1fcd3fc6c4fef3eaf9:19:1)
    at Object.module.exports.$schema (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/index.js:9:12)
    at __webpack_require__ (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/webpack/bootstrap fa1fcd3fc6c4fef3eaf9:19:1)
    at Object.<anonymous> (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/packages/truffle-core/cli.js:33:29)
    at __webpack_require__ (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/webpack/bootstrap fa1fcd3fc6c4fef3eaf9:19:1)
    at /usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/webpack/bootstrap fa1fcd3fc6c4fef3eaf9:65:1
    at Object.<anonymous> (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/cli.bundled.js:71:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
Error: Error while attempting to download and cache solc 0.5.8: Command failed: node ./build/cli.bundled.js obtain --solc=0.5.8
Error: EACCES: permission denied, open '/root/.config/truffle/config.json'
You don't have access to this file.

    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Configstore.get all [as all] (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/~/configstore/index.js:31:1)
    at new Configstore (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/~/configstore/index.js:25:31)
    at Function.Config.getUserConfig (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/packages/truffle-config/index.js:395:1)
    at Object.<anonymous> (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/mnemonics/mnemonic.js:11:1)
    at __webpack_require__ (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/webpack/bootstrap fa1fcd3fc6c4fef3eaf9:19:1)
    at Object.command.command (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/develop.js:2:22)
    at __webpack_require__ (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/webpack/bootstrap fa1fcd3fc6c4fef3eaf9:19:1)
    at Object.module.exports.$schema (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/packages/truffle-core/lib/commands/index.js:9:12)
    at __webpack_require__ (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/webpack/bootstrap fa1fcd3fc6c4fef3eaf9:19:1)
    at Object.<anonymous> (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/packages/truffle-core/cli.js:33:29)
    at __webpack_require__ (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/webpack/bootstrap fa1fcd3fc6c4fef3eaf9:19:1)
    at /usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/webpack:/webpack/bootstrap fa1fcd3fc6c4fef3eaf9:65:1
    at Object.<anonymous> (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/build/cli.bundled.js:71:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)

    at postinstallObtain (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/scripts/postinstall.js:13:11)
    at Object.<anonymous> (/usr/local/lib/nodejs/node-v10.16.0-linux-x64/lib/node_modules/truffle/scripts/postinstall.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
+ truffle@5.0.27

## Expected Behavior

Come out clean and ready so I can start writting code.

## Actual Results

Shared above.

## Environment

* Operating System: Centos ...Linux User 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* Ethereum client: na 
* Truffle version (`truffle version`):
* node version (`node --version`): v10.16.0
* npm version (`npm --version`): 6.9.0

nvm --version
0.34.0

**Comment by thecircleoflifefree** [comment]
Looks like someone has similar issue, but instead of CentOS it is Ubuntu:

https://ethereum.stackexchange.com/questions/72894/i-am-getting-error-while-installing-truffle-in-ubuntu-16-04-lts-how-to-resolve

**Comment by thecircleoflifefree** [comment]
v12.6 solved issue

**Comment by gnidan** [comment]
Re-opening because Truffle supports v8.9.4 and higher!

**Comment by eggplantzzz** [comment]
Actually I don't think v12 does solve this issue. It currently looks like if you use `sudo npm install -g truffle` you will get the error above due to permissions issues. For reference, the ConfigStore package is trying to access a file that is used to hold user configuration data. Perhaps there is some information about this in the ConfigStore repo?

**Comment by thecircleoflifefree** [comment]
Plain honest the upgrade was the last thing I did, but there is certainly no track on my end of what else was done as many things were done. I would say take it with a grain of salt and just close it, if you wish I will hide/delete the fix post.

**Comment by jamatulli** [comment]
This solution at this [URL](https://stackoverflow.com/questions/38323880/error-eacces-permission-denied
) worked for me. 

1. Back up your computer
2. On the command line, in your home directory, create a directory for global installations:
`mkdir ~/.npm-global`
3. Configure npm to use the new directory path:
`npm config set prefix '~/.npm-global'`
4. In your preferred text editor, open or create a ~/.profile file and add this line:
 `export PATH=~/.npm-global/bin:$PATH`
5. On the command line, update your system variables:
`source ~/.profile`
6. To test your new configuration, install a package globally without using sudo:
`npm install -g jshint`

Alternatively, Instead of steps 2-4, you can use the corresponding ENV variable (e.g. if you don’t want to modify ~/.profile):

`NPM_CONFIG_PREFIX=~/.npm-global`

**Comment by diogoab** [comment]
Very good @jamatulli for me it worked very well! thanks!

**Comment by gnidan** [comment]
Does anyone know how to fix this via a code change to Truffle? I've had it on my to-do list to look into this for a couple weeks, but haven't had the chance yet. It's definitely preferable not to have to do the above.

**Comment by tserg** [comment]
I'm having the same issue. I've tried the above suggestion but it does not work.

**Comment by eggplantzzz** [comment]
I think these kinds of errors are usually successfully resolved by installing npm with nvm. npm has these recommendations for issues involving these types of problems. Hopefully someone might find it helpful. https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by thecircleoflifefree** [comment]
Looking back into this issue i'd like to add two things:

- My initial statement on Gitter was just wrong. Tyler helps and has helped alot, props to him.
- Somewhere down the road I had read that instead of using ```sudo``` with npm commands was to use ```--unsafe-perm``` . Again I don't recall much about it, but mixing up nvm and npm alone on the fly can cause issues.

**Comment by eggplantzzz** [comment]
Ok thanks @thecircleoflifefree. We want to get to investigate and get to the bottom of this. Do you have any specific steps that might help us recreate this problem? If you do, it would be super helpful!

**Comment by earizon** [comment]
I could fix it cheating about the $HOME directory.

    set HOME_BACKUP=$HOME
    export HOME=/tmp/truffle_install
    mkdir -p $HOME/.config/truffle
    chmod a+rwx $HOME/.config               
    chmod a+rwx $HOME/.config/truffle     # <- install fails with EACCESS (dir doesn't exists)
    npm install -g truffle@${TRUFFLE_VERSION} # <- $HOME is ignored. Install in correct path
                                                                          # /opt/nvm/versions/node/v10.16.3/bin/truffle in my setup
    rm -rf $HOME                                    # <- I can remove it once installed. Weird!!!???
    set HOME=$HOME_BACKUP

**Comment by eggplantzzz** [comment]
Closing this issue for maintenance. Please let us know if you want it re-opened to troubleshoot further, thanks!

**Comment by ktecho** [comment]
I cannot install truffle in Ubuntu 19.10 even with @earizon's method. I guess this should not be closed...

**Comment by ktecho** [comment]
It works if I do `npm install truffle`, but fails if I do `npm install -g truffle`

**Comment by codepandy** [comment]
Here's my solution：
```
npm install npm@latest -g
sudo npm install truffle -g --unsafe-perm
```

**Comment by codepandy** [comment]
modify the permission of the file:
```
chmod 777 /Users/youname/.config/truffle/config.json
```

**Comment by enderphan94** [comment]
`chmod 777 /Users/XXX/.config/`

**Comment by akrolak** [comment]
jamatulli method worked for me as well, thank you!

**Comment by ZheBan-Jassic** [comment]
> Does anyone know how to fix this via a code change to Truffle? I've had it on my to-do list to look into this for a couple weeks, but haven't had the chance yet. It's definitely preferable not to have to do the above.

Have you solved the problem?

**Comment by TheDApact** [comment]
jamatulli 's method worked for me too

**Comment by heimi-block** [comment]
sudo chown -R [user name] ~/.config

**Comment by rahul1471** [comment]
This worked for me:

sudo npm install --unsafe-perm -g truffle

**Comment by xxCoDeBoX** [comment]
This worked for me .

sudo npm install -g truffle --unsafe-perm=true --allow-root

**Comment by manwelbugeja** [comment]
> I could fix it cheating about the $HOME directory.
> 
> ```
> set HOME_BACKUP=$HOME
> export HOME=/tmp/truffle_install
> mkdir -p $HOME/.config/truffle
> chmod a+rwx $HOME/.config               
> chmod a+rwx $HOME/.config/truffle     # <- install fails with EACCESS (dir doesn't exists)
> npm install -g truffle@${TRUFFLE_VERSION} # <- $HOME is ignored. Install in correct path
>                                          # /opt/nvm/versions/node/v10.16.3/bin/truffle in my setup
> rm -rf $HOME   # <- I can remove it once installed. Weird!!!???
> set HOME=$HOME_BACKUP
> ```

Adding to this I also had to remove the old truffle config file located in ~/.config
And the it worked
