### ISSUE TITLE
Request error: Unable to get local issuer certificate

### ISSUE THREAD

**Issue by hv7214** [trufflesuite/truffle#2248]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
Unable to download any  boilerplate code
## Steps to Reproduce

truffle unbox pet-shop

## Expected Behavior

Biolerplate code should have been downloaded
## Actual Results

RequestError: Error: unable to get local issuer certificate
    at new RequestError (/usr/local/lib/node_modules/truffle/build/webpack:/~/request-promise-core/lib/errors.js:14:1)
    at Request.plumbing.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/request-promise-core/lib/plumbing.js:87:1)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/truffle/build/webpack:/~/request-promise-core/lib/plumbing.js:46:1)
    at self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:185:1)
    at Request.emit (events.js:189:13)
    at Request.onRequestError (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:881:1)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Truffle v5.0.28 (core: 5.0.28)
Node v10.15.2

## Environment

* Operating System:  Ubunty 19.04
* Ethereum client: 
* Truffle version (`truffle version`): 5.0.28
* node version (`node --version`): 10.x
* npm version (`npm --version`): 6.09

**Comment by eggplantzzz** [comment]
Hey @hv7214, this is probably not a Truffle error but rather some problem with your machine's configuration or npm. Try to google this to find out more information about what is going on. If I get any insight into this I'll try and report back here.

**Comment by fainashalts** [comment]
HI @hv7214 we're closing this for issue maintenance, but if you are still having an issue we can help with, please open another issue with that information. Thank you!
