### ISSUE TITLE
ttruffle init doesn't work

### ISSUE THREAD

**Issue by talaikis** [trufflesuite/truffle#2311]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

ttruffle init doesn't work.

## Steps to Reproduce

```
npm i -g truffle
md test
cd test
truffle init
```

## Expected Behavior

Should create project files.

## Actual Results

```
PS \test> truffle init
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
Keccak bindings are not compiled. Pure JS implementation will be used.

× Preparing to download
Error: ENOENT: no such file or directory, mkdir '\test\tmp-9456aJOkMA10HAig'
    at Object.mkdirSync (fs.js:757:3)
    at Object.dirSync (\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\tmp\lib\tmp.js:357:1)
    at Object.setUpTempDirectory (\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-box\lib\utils\index.js:42:1)
    at Object.unbox (\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-box\box.js:38:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Truffle v5.0.32 (core: 5.0.32)
Node v10.16.0
```

## Environment

* Operating System: Windows 10
* Ethereum client: web3 1.2.1
* Truffle version (`truffle version`): 5.0.32
* node version (`node --version`): 10.16.0
* npm version (`npm --version`): 6.9.0

**Comment by talaikis** [comment]
Closing this, because it is Windows 10 related.
