### ISSUE TITLE
Truffle deployment, issues with gas?

### ISSUE THREAD

**Issue by NicolaGessa** [trufflesuite/truffle#2347]
## Issue
I have the same very simple Smart Contract:

```solidity
pragma solidity ^0.5.1;

contract HW {

  function print() public view returns (string memory) {
    return "HelloWorld";
  }
}
```

I'm using  a personal blockchain with Geth on localhost.

When I deploy this contract using Remix, I have no problem in call the function add(), and all works well from remix.

When I deploy this contract using truffle, I cannot call the function print():
If a call from Remix, I got

> Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
> gas required exceeds allowance or always failing transaction

and the call doesn't work. So I guess the deployment didn't work well...)

If a call from truffle console, like this:

let i = await HW.deployed()
i.print()

I got 
```
Thrown:
Error: Returned values aren't valid, did it run Out of Gas?
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/~/web3-providers-http/src/index.js:96:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-requestmanager/src/index.js:147:1
    at sendTxCallback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-method/src/index.js:473:1)
    at Method.formatOutput (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-method/src/index.js:163:1)
    at Method.outputFormatter (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-eth-contract/src/index.js:818:1)
    at Contract._decodeMethodReturn (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-eth-contract/src/index.js:465:1)
    at ABICoder.decodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3-eth-abi/src/index.js:226:1)
```

may someone help me on this?
thank you
## Environment

I use
Truffle v5.0.29 (core: 5.0.29)
Solidity v0.5.0 (solc-js)
Node v10.16.0
Web3.js v^1.2.0

**Comment by fainashalts** [comment]
Hi @NicolaGessa, this may not be an issue with gas per se. This appears to be an error coming from web3. What version of Geth are you using and what command are you using to run it?

**Comment by gnidan** [comment]
Possibly related: #2136

**Comment by fainashalts** [comment]
Hi @NicolaGessa just wanted to check - did you run your migrations for this?

**Comment by NicolaGessa** [comment]
Dear all, 

I solved the problem just recreating the blockchain, adding in the genesis file the two rows in config:

"config": {
.....
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
...
}

... honestly I did not understand well why this solution works, if someone could explain me better why it works it would be very appreciated ...

thanks to all.

**Comment by haltman-at** [comment]
Glad to hear this was resolved; we're going to close this for now, as we don't really have enough information to go on.  If this becomes an issue again or if you can provide more detailed information, we can re-open it.
