### ISSUE TITLE
Migrations fail with `geth --dev`

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#2353]
## Issue

As reported by @axic, migrations are failing again `geth --dev` networks

## Steps to Reproduce

1. `truffle init`
2. Uncomment the `"development"` network in truffle-config.js
3. (In another terminal) `geth --dev --rpc`
4. `truffle migrate`

## Expected Behavior

Migration to succeed.

## Actual Results

```


Starting migrations...
======================
> Network name:    'development'
> Network id:      1337
> Block gas limit: 0x5fdfb1


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
Error: Error: Error:  *** Deployment Failed ***

"Migrations" exceeded the block limit (with a gas value you set).
   * Block limit:  0x201ae63
   * Gas sent:     6721975
   * Try:
      + Sending less gas.
      + Setting a higher network block limit if you are on a
        private network or test client (like ganache).

    at Object.run (/.../truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

## Environment

* Operating System: Mac
* Ethereum client: Geth
* Truffle version (`truffle version`): 5.0.33

**Comment by cgewecke** [comment]
@gnidan @axic 

Geth dev's [starting block gas limit](https://github.com/ethereum/go-ethereum/blob/cc9eb91d30a5d4806154b832b9665aecc617b6d8/core/genesis.go#L389) is lower than truffle's default "gas sent" for transactions...
```
geth: 6,283,185
truffle: 6,721,975
```
A quick work-around is to set the `gas` param in the truffle config for the relevant network lower, (eg 6000000)

The block limit gas value in the error output is incorrect. It's getting mangled somewhere.  
```
* Block limit:  0x201ae63
```

The block limit reported in the top layer is correct but should probably be in decimal:
```
> Block gas limit: 0x5fdfb1
```
