### ISSUE TITLE
Improve debug messages to include the full path of an error

### ISSUE THREAD

**Issue by pyskell** [trufflesuite/truffle#2368]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------
Technically I [complained on Twitter](https://twitter.com/pyskell/status/1169323268555325440?s=20) and didn't ask in Gitter but it still counts right?
## Issue
The only debug information from Mocha comes in the form of JavaScript errors. If an error exists within the tested code there will be limited (if any) debugging information about the error.

## Steps to Reproduce
Have a test throw an error that occurs in the EVM.

For example, this code will error at the call to `ct.deleteSchedule()`.
```
        it("should delete a VestingSchedule", async () => {
            let vestingSchedule = await VestingSchedule.new(accounts[0], accounts[0], "test_deploy", 1000, 1, 5)
            await ct.addSchedule(vestingSchedule.address, {from: accounts[0]})

            await ct.deleteSchedule(accounts[0], {from: accounts[0]})
            let deletedSchedule = await ct.vestingSchedules.call(accounts[0])

            await assert.equal(deletedSchedule, 0x0)
        })
```

`ct.deleteSchedule()` will then error when it calls a function in another contract `oldSchedule.disable()`
```
  function deleteSchedule(address grantee) public {
    VestingSchedule oldSchedule = vestingSchedules[address(grantee)];
    oldSchedule.disable(true);
    delete vestingSchedules[address(grantee)];
  }
```

## Expected Behavior

I expected to see some errors from the EVM so I can know what function, code, and line resulted in the error. This is potentially fixable with #2253 (as per @gnidan)

## Actual Results

But the output is simply the error propagation after execution in the EVM halts and we get back to JavaScript. There's no actual info about what happened when `oldSchedule.disable()` was called.
```
  1) Contract: CapTable
       basic tests
         should delete a VestingSchedule:
     Error: Returned error: VM Exception while processing transaction: revert
      at Object.ErrorResponse (/usr/lib/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-helpers/src/errors.js:29:1)
      at /usr/lib/node_modules/truffle/build/webpack:/~/web3-eth/~/web3-core-requestmanager/src/index.js:140:1
      at /usr/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
      at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/webpack:/~/web3/~/web3-providers-http/src/index.js:96:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
      at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:289:47)
      at endReadableNT (_stream_readable.js:1139:12)
      at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

## Environment

* Operating System: Linux
* Ethereum client: ganache
* Truffle version (`truffle version`): Truffle v5.0.12 (core: 5.0.12)
* node version (`node --version`): Node v11.15.0
* npm version (`npm --version`): 6.10.3
Solidity - 0.5.1 (solc-js)
Web3.js v1.0.0-beta.37

**Comment by gnidan** [comment]
This might be resolved by #2170, currently needing love. Will investigate.
