### ISSUE TITLE
Transient `Expected n, got n'!` error

### ISSUE THREAD

**Issue by pyskell** [trufflesuite/truffle#2372]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Occasionally some tests run with `truffle test` will fail with the error `Error: Invalid number of parameters for "functionName". Got 0 expected 1!`

## Steps to Reproduce

I really don't know what causes this. The test is correct. But what fixes it is clearing my `build/contracts` directory.

## Expected Behavior

Test succeeds.

## Actual Results

Test fails. This is for a function that takes 0 arguments.
```
  3) Contract: VestingSchedule
       basic tests
         should vest 20% per day over a period of 5 days:
     Error: Invalid number of parameters for "vested". Got 0 expected 1!
      at Object.InvalidNumberOfParams (C:\Users\me\AppData\Roaming\nvm\v8.11.1\node_modules\truffle\build\webpack:\~\web3-eth-contract\~\web3-core-helpers\src\errors.js:32:1)
      at Object._createTxObject (C:\Users\me\AppData\Roaming\nvm\v8.11.1\node_modules\truffle\build\webpack:\~\web3-eth-contract\src\index.js:699:1)
      at Promise (C:\Users\me\AppData\Roaming\nvm\v8.11.1\node_modules\truffle\build\webpack:\packages\truffle-contract\lib\execute.js:128:1)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Environment

* Operating System: Windows
* Ethereum client: ganache
* Truffle version (`truffle version`): Truffle v5.0.14 (core: 5.0.14)
* node version (`node --version`): Node v8.11.1
* npm version (`npm --version`): 5.6.0
Solidity - 0.5.1 (solc-js)
Web3.js v1.0.0-beta.37

**Comment by CruzMolina** [comment]
Hey @pyskell ! Does the bug resurface when using the latest version of Truffle?

**Comment by eggplantzzz** [comment]
Closing for issue maintenance, please let us know if you'd like it re-opened! Thank you!
