### ISSUE TITLE
`selfdestruct` in constructor gives "The contract code couldn't be stored, please check your gas limit"

### ISSUE THREAD

**Issue by xavierlepretre** [trufflesuite/truffle#2398]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When your contract `selfdestruct`s in its constructor, and you deploy it, the transaction receipt has `status: true`, but Truffle is unable to understand this as a successful transaction.

## Steps to Reproduce

Create this contract:

```solidity
pragma solidity 0.5.8;

contract BackDoor {
    constructor() public payable {
        selfdestruct(msg.sender);
    }
}
```
Then, run `ganache-cli`, and in a Truffle test, do:

```javascript
it("should deploy a BackDoor", async function() {
    const backDoor = await BackDoor.new({ from: accounts[0], value: 30, gas: 3000000});
});
```
What you get is:

```
  1) Contract: BackDoor
       should deploy a BackDoor:
     Error: The contract code couldn't be stored, please check your gas limit.
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:6:1)
      at /home/vagrant/DAPPS/b9internal/capture_flag/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:211:1
      at Function.new (node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:33:1)
      at Context.<anonymous> (test/backDoor.js:14:27)
      at web3.eth.getBlockNumber.then.result (node_modules/truffle/build/webpack:/packages/core/lib/testing/testrunner.js:153:1)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
Now, in `ganache-cli`, you see:

```
eth_sendTransaction

  Transaction: 0x59d9dd797cd1b31a4cb0d7615cb9ee394effffc177a4651407632d307be8005b
  Contract created: 0xd833c6d1b86aa11b0f07c3d89f9f3ee387f23ceb
  Gas usage: 36066
  Block Number: 100
  Block Time: Thu Sep 19 2019 13:34:02 GMT+0000 (Coordinated Universal Time)

eth_getTransactionReceipt
eth_getCode
```
And if, in `truffle console`, you do 

```javascript
web3.eth.getTransactionReceipt("0x59d9dd797cd1b31a4cb0d7615cb9ee394effffc177a4651407632d307be8005b")
```
You get:

```
{
    ...
    gasUsed: 36066,
    contractAddress: '0xd833C6D1B86aA11b0F07C3D89f9f3ee387F23CEb',
    status: true,
    ...
}
```

## Expected Behavior

The `await BackDoor.new({ from: accounts[0], value: 30, gas: 3000000});` line should return a `truffle-contract` instance of `BackDoor`. **Even though it has no code at the address**.

Note that Truffle v4.1.13 has the expected behaviour.

## Actual Results

Actually, Truffle is fooled by the absence of code at the address as seen in the "Steps to Reproduce".

## Environment

* Operating System: Ubuntu 16.04.6 LTS
* Ethereum client: `ganache-cli`
* Truffle version (`truffle version`): v5.0.36 (core: 5.0.36)
* Solidity version: v0.5.8 (solc-js)
* node version (`node --version`): v10.16.3
* npm version (`npm --version`): 6.9.0

**Comment by xavierlepretre** [comment]
Here is my workaround:

```javascript
let txHash;
await BackDoor.new(accounts[1], { from: accounts[0], value: 30, gas: 3000000})
    .on("transactionHash", hash => txHash = hash)
    .catch(e => {});
```

**Comment by haltman-at** [comment]
I'm not sure this is an issue with Truffle per se; I think this is an issue with web3 (I've noticed the same thing happening when I have a selfdestruct during deployment while using web3 directly).  Fixing this may have to wait until we're less reliant on web3.

**Comment by eggplantzzz** [comment]
We can consider checking for this specific error and handling it for a nice user experience. Note that this exception occurs when a transaction reverts as well so we could check for multiple conditions.
