### ISSUE TITLE
truffle-db unable to resolve npm installed contracts

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/truffle#2411]
Given a project that installs solidity contracts via npm, like openzeppelin-solidity, 

The following mutation query fails
```
mutation foo  {
  loaders {
    artifactsLoad {
      success
    }
  }
}
```

with error output

```
{
  "errors": [
    {
      "message": "Error: Could not find openzeppelin-solidity/contracts/token/ERC20/ERC20.sol from any sources; imported from /Users/amal/dev/scratch/test-drizzle-box/contracts/TutorialToken.sol",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "loaders",
        "artifactsLoad"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "errors": [
            {
              "message": "Error: Could not find openzeppelin-solidity/contracts/token/ERC20/ERC20.sol from any sources; imported from /Users/amal/dev/scratch/test-drizzle-box/contracts/TutorialToken.sol",
              "locations": [],
              "path": [
                "artifactsLoad"
              ]
            }
          ],
          "stacktrace": [
            "Error: Error: Could not find openzeppelin-solidity/contracts/token/ERC20/ERC20.sol from any sources; imported from /Users/amal/dev/scratch/test-drizzle-box/contracts/TutorialToken.sol",
            "    at new CombinedError (/Users/amal/work/truffle/node_modules/@gnd/graphql-tools/src/stitching/errors.ts:90:5)",
            "    at Object.checkResultAndHandleErrors (/Users/amal/work/truffle/node_modules/@gnd/graphql-tools/src/stitching/errors.ts:111:11)",
            "    at CheckResultAndHandleErrors.transformResult (/Users/amal/work/truffle/node_modules/@gnd/graphql-tools/src/transforms/CheckResultAndHandleErrors.ts:15:12)",
            "    at /Users/amal/work/truffle/node_modules/@gnd/graphql-tools/src/transforms/transforms.ts:37:45",
            "    at Array.reduce (<anonymous>)",
            "    at applyResultTransforms (/Users/amal/work/truffle/node_modules/@gnd/graphql-tools/src/transforms/transforms.ts:35:21)",
            "    at /Users/amal/work/truffle/node_modules/@gnd/graphql-tools/src/stitching/delegateToSchema.ts:104:12",
            "    at step (/Users/amal/work/truffle/node_modules/@gnd/graphql-tools/dist/stitching/delegateToSchema.js:31:23)",
            "    at Object.next (/Users/amal/work/truffle/node_modules/@gnd/graphql-tools/dist/stitching/delegateToSchema.js:12:53)",
            "    at fulfilled (/Users/amal/work/truffle/node_modules/@gnd/graphql-tools/dist/stitching/delegateToSchema.js:3:58)"
          ]
        }
      }
    }
  ],
  "data": {
    "loaders": {
      "artifactsLoad": null
    }
  },
  "extensions": {}
}
```

**Comment by haltman-at** [comment]
Closing this since this was apparently resolved.
