### ISSUE TITLE
"truffle test" failing while "../" within "contracts_build_directory" in "truffle-config.js"

### ISSUE THREAD

**Issue by PyrateAkananto** [trufflesuite/truffle#2453]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

The command `truffle test` fails and creates error messages if the the value `contracts_build_directory` inside `truffle-config.js` uses a directory "outside" the current directory, for example `contracts_build_directory: "./../somewhere/build"` (note the `/../` part).

Failing or working, I cannot see `truffle test` generating `.json` files and using the specified directory in any way.

All other Truffle commands do not have this issue.

## Steps to Reproduce

Call `truffle test` with `truffle-config.js` containing `/../` within the value for `contracts_build_directory`.

## Expected Behavior

`truffle test` working without error messages.

## Actual Results

`truffle test` fails with this error message:

```
Compiling your contracts...
===========================
SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at filesData.map.data (E:\myProjectsJavaScript\InnovationEconomyCryptoGame2019\smartcontracts\node_modules\truffle\build\webpack:\packages\core\lib\testing\testsource.js:62:1)
    at Array.map (<anonymous>)
    at Promise.all.then.filesData (E:\myProjectsJavaScript\InnovationEconomyCryptoGame2019\smartcontracts\node_modules\truffle\build\webpack:\packages\core\lib\testing\testsource.js:62:1)
Truffle v5.0.39 (core: 5.0.39)
Node v10.16.3
```

## Environment

* Windows 10 64 Bit German
* Truffle v5.0.39 (core: 5.0.39)
* Solidity - ^0.5.10 (solc-js)
* Node v10.16.3
* npm v6.9.0
* [nvm](https://github.com/coreybutler/nvm-windows) v1.1.7
* Web3.js v1.2.1

## Workaround

My current workaround is the following code within `truffle-config.js`:
```javascript
  get contracts_build_directory() {
    if (process.argv.length >= 3 && process.argv[2] === "test") {
      return "./whatever-because-it-is-ignored-anyway";
    } else {
      return "./../somewhere/build";
    }
  },
```

**Comment by eggplantzzz** [comment]
Thanks for the writeup @PyrateAkananto! I'll look into this soon!

**Comment by eggplantzzz** [comment]
@PyrateAkananto I can't seem to duplicate your issue. I set the `contracts_build_directory` to `../build` but it doesn't fail like you describe above. If you have a toy project that I could try and clone to investigate it would be appreciated!

However, when you run `truffle test` it creates it's own version of the artifacts and copies them to a temporary directory. It then deletes them afterwards. That is why you are not seeing the results of those compilations saved anywhere after running the tests.

**Comment by eggplantzzz** [comment]
Actually, try deleting your `build` folder. The error that you mentioned seems to indicate that your artifacts are messed up somehow. See if that solves your problem.

**Comment by PyrateAkananto** [comment]
First of all, thank you for your help!

It seems the `contracts_build_directory` folder has to be empty or at least contain no other files than the generated `.json` files. I had a `.keep` file in that directory, for version control to keep this directory. `truffle test` seems to try to parse all files within that folder as if they are JSON files. If I delete my `.keep` file, it works fine. But still only `truffle test` is having this issue. I'm still not sure why it needs that directory or why it parses all the files in it, not just `.json` files.

By the way the error message gets a little bit more helpful if the file, for example `dummy.txt` actually contains valid JSON, for example `{ }`.
