### ISSUE TITLE
download what ?

### ISSUE THREAD

**Issue by loveship00** [trufflesuite/truffle#2563]
This directory is non-empty...
? Proceed anyway? Yes
√ Preparing to download
× Downloading
RequestError: Error: connect ETIMEDOUT 69.171.225.13:443
    at new RequestError (C:\Users\HONGJE3\AppData\Roaming\nvm\v12.6.0\node_modules\truffle\build\webpack:\~\request-promise-core\lib\errors.js:14:1)
    at Request.plumbing.callback (C:\Users\HONGJE3\AppData\Roaming\nvm\v12.6.0\node_modules\truffle\build\webpack:\~\request-promise-core\lib\plumbing.js:87:1)
    at Request.RP$callback [as _callback] (C:\Users\HONGJE3\AppData\Roaming\nvm\v12.6.0\node_modules\truffle\build\webpack:\~\request-promise-core\lib\plumbing.js:46:1)
    at self.callback (C:\Users\HONGJE3\AppData\Roaming\nvm\v12.6.0\node_modules\truffle\build\webpack:\~\request\request.js:185:1)
    at Request.emit (events.js:203:13)
    at Request.onRequestError (C:\Users\HONGJE3\AppData\Roaming\nvm\v12.6.0\node_modules\truffle\build\webpack:\~\request\request.js:881:1)
    at ClientRequest.emit (events.js:203:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Truffle v5.0.43 (core: 5.0.43)
Node v12.6.0

--------

really need download?

**Comment by gnidan** [comment]
Yes, `truffle unbox` downloads a Truffle Box from the internet and sets it up for you!
