### ISSUE TITLE
@truffle/hdwallet-provider is not supported events subscribing

### ISSUE THREAD

**Issue by MrRefactoring** [trufflesuite/truffle#2567]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Add HDWalletProvider to drizzle store

## Expected Behavior

Drizzle successful subscribed to events

## Actual Results

![subscriptions problem](https://user-images.githubusercontent.com/10329528/68387283-0bd92800-016f-11ea-801c-0f5de2b44267.PNG)

## Environment

* Operating System: Win 10
* Ethereum client: N/A
* Truffle version (`truffle version`): v5.0.43
* node version (`node --version`): 10.17.0
* npm version (`npm --version`): 6.11.3

**Comment by gnidan** [comment]
Hm, sounds like this is a Drizzle issue, for https://github.com/trufflesuite/drizzle/issues

**Comment by MrRefactoring** [comment]
I am afraid that if I inherit from ProviderEngine this problem will be solved

**Comment by fainashalts** [comment]
Hi @MrRefactoring! I don't totally understand what you mean about ProviderEngine, can you clarify? Do you mean instead of accessing HDWalletProvider directly?

**Comment by MrRefactoring** [comment]
I think that HDWalletProvider should inherit ProviderEngine, and not write an adapter for it

**Comment by gnidan** [comment]
I'm generally opposed to inheritance in favor of composition, but that seems like an implementation detail. Is there more information about what is causing this not to work? Thanks!

**Comment by gnidan** [comment]
Hey @MrRefactoring or maybe @adrianmcli, could either of you lend any clarity to this issue? Thanks in advance!

**Comment by MrRefactoring** [comment]
@gnidan I'm busy at work so far, I can’t see this issue, sorry :(

**Comment by mikec** [comment]
The issue is that HDWalletProvider does not have an `on()` function, so web3 assumes no subscription support and throws an error. `Web3.providers.WebsocketProvider` implements `.on()` and supports subscription callbacks. HDWalletProvider uses WebsocketProvider when rpcUrl has `ws:` or `wss:`, but it's added via `web3-provider-engine`, which also doesn't support subscriptions by implementing `on()`. web3 looks for the `on()` function on the top level provider (HDWalletProvider) and can't find it.

Here's the monkey patched workaround I'm using:

```js
const Web3 = require('web3')
const HDWalletProvider = require('@truffle/hdwallet-provider')

const rpcUrl = 'http://localhost:8545'
const mnemonic = 'monkey patch bad ...'

const wsProvider = new Web3.providers.WebsocketProvider(rpcUrl)
HDWalletProvider.prototype.on = wsProvider.on.bind(wsProvider)
const provider = new HDWalletProvider(mnemonic, wsProvider)

const web3 = new Web3(provider)

// subscribe callbacks should work now
web3.eth.subscribe('newBlockHeaders', (error, block) => console.log(error || block))
```

**Comment by MohamedLEGH** [comment]
Hello, any news on this ? Do we still need to do the "hack" mentioned above to make HDWalletProvider works with WebSockets ?

**Comment by Idiono-mfon** [comment]
Monkey patch is great but an official solution will be really appreciated. Thanks

**Comment by KLM-GIT** [comment]
Thanks @mikec - monkey patch worked, but agree with @Idiono-mfon that official solution would be better - thanks.

**Comment by anibaljasin** [comment]
> The issue is that HDWalletProvider does not have an `on()` function, so web3 assumes no subscription support and throws an error. `Web3.providers.WebsocketProvider` implements `.on()` and supports subscription callbacks. HDWalletProvider uses WebsocketProvider when rpcUrl has `ws:` or `wss:`, but it's added via `web3-provider-engine`, which also doesn't support subscriptions by implementing `on()`. web3 looks for the `on()` function on the top level provider (HDWalletProvider) and can't find it.
> 
> Here's the monkey patched workaround I'm using:
> 
> ```js
> const Web3 = require('web3')
> const HDWalletProvider = require('@truffle/hdwallet-provider')
> 
> const rpcUrl = 'http://localhost:8545'
> const mnemonic = 'monkey patch bad ...'
> 
> const wsProvider = new Web3.providers.WebsocketProvider(rpcUrl)
> HDWalletProvider.prototype.on = wsProvider.on.bind(wsProvider)
> const provider = new HDWalletProvider(mnemonic, wsProvider)
> 
> const web3 = new Web3(provider)
> 
> // subscribe callbacks should work now
> web3.eth.subscribe('newBlockHeaders', (error, block) => console.log(error || block))
> ```

This workaround doesn't work for when trying to use an rpc from velas network like these `https://mainnet.velas.com/rpc`, `wss://api.velas.com`. I get this error:
```
Error: connection not open on send()
```

Do you know if this is related to my rpc provider? or if it is related to `HDWalletProvider`?

**Comment by HassanAmed** [comment]
It would be nice to have this feature. Is someone working on this?

**Comment by Jntmkk** [comment]
> The issue is that HDWalletProvider does not have an `on()` function, so web3 assumes no subscription support and throws an error. `Web3.providers.WebsocketProvider` implements `.on()` and supports subscription callbacks. HDWalletProvider uses WebsocketProvider when rpcUrl has `ws:` or `wss:`, but it's added via `web3-provider-engine`, which also doesn't support subscriptions by implementing `on()`. web3 looks for the `on()` function on the top level provider (HDWalletProvider) and can't find it.
> 
> Here's the monkey patched workaround I'm using:
> 
> ```js
> const Web3 = require('web3')
> const HDWalletProvider = require('@truffle/hdwallet-provider')
> 
> const rpcUrl = 'http://localhost:8545'
> const mnemonic = 'monkey patch bad ...'
> 
> const wsProvider = new Web3.providers.WebsocketProvider(rpcUrl)
> HDWalletProvider.prototype.on = wsProvider.on.bind(wsProvider)
> const provider = new HDWalletProvider(mnemonic, wsProvider)
> 
> const web3 = new Web3(provider)
> 
> // subscribe callbacks should work now
> web3.eth.subscribe('newBlockHeaders', (error, block) => console.log(error || block))
> ```

When using the above method to solve the websocket problem, it will cause the command "truffle migration" to fail and keep waiting for the block to complete, remove the above settings and revert to the previous method can be solved, change back when testing

**Comment by Thankgod20** [comment]
``

> The issue is that HDWalletProvider does not have an `on()` function, so web3 assumes no subscription support and throws an error. `Web3.providers.WebsocketProvider` implements `.on()` and supports subscription callbacks. HDWalletProvider uses WebsocketProvider when rpcUrl has `ws:` or `wss:`, but it's added via `web3-provider-engine`, which also doesn't support subscriptions by implementing `on()`. web3 looks for the `on()` function on the top level provider (HDWalletProvider) and can't find it.
> 
> Here's the monkey patched workaround I'm using:
> 
> ```js
> const Web3 = require('web3')
> const HDWalletProvider = require('@truffle/hdwallet-provider')
> 
> const rpcUrl = 'http://localhost:8545'
> const mnemonic = 'monkey patch bad ...'
> 
> const wsProvider = new Web3.providers.WebsocketProvider(rpcUrl)
> HDWalletProvider.prototype.on = wsProvider.on.bind(wsProvider)
> const provider = new HDWalletProvider(mnemonic, wsProvider)
> 
> const web3 = new Web3(provider)
> 
> // subscribe callbacks should work now
> web3.eth.subscribe('newBlockHeaders', (error, block) => console.log(error || block))
> ```

got this error when trying to connect `Error: ProviderSubprovider - specified provider does not have a sendAsync method
    at new ProviderSubprovider (/home/vwegba/Documents/Listener2.0/node_modules/web3-provider-engine/subproviders/provider.js:12:34)
    at new HDWalletProvider (/home/vwegba/Documents/Listener2.0/node_modules/@truffle/hdwallet-provider/dist/index.js:239:37)
    at Object.<anonymous> (/home/vwegba/Documents/Listener2.0/client/NewPendingTransaction.js:58:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47`
