### ISSUE TITLE
Using deployed contracts packaged as npm

### ISSUE THREAD

**Issue by tuler** [trufflesuite/truffle#2612]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When importing contracts packaged as npm the deployment information for those contracts is not being used. The contract is being recompiled, and not resolving to the original dependency already compiled code.

## Steps to Reproduce

The following test project has instructions on how to reproduce this:
https://github.com/tuler/truffle-npm-test

## Expected Behavior

Use the files from `node_modules/<package>/build` if they exist, instead of recompiling all contracts.

## Actual Results

Dependent solidity code is recompiled, generating a new set of `.json` files at `truffle-test-b/build`. Those files do not have deployment information (networks), so the migration of `truffle-test-b` fails.

```
2_deploy_app.js
===============

Error: Error: SimpleStorage has no network configuration for its current network id (1574099427158).
    at Object.run (/workspace/truffle-npm-test/truffle-test-b/node_modules/truffle/build/webpack:/packages/migrate/index.js:92:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## Environment

* Operating System: macOS Catalina 10.15.1

* Truffle version (`truffle version`):
Truffle v5.1.0 (core: 5.1.0)
Solidity v0.5.12 (solc-js)
Node v12.13.0
Web3.js v1.2.2

* node version (`node --version`): v12.13.0
* npm version (`npm --version`): 6.12.0

**Comment by fainashalts** [comment]
Hi @tuler, thank you for bringing this up!
There may be no way to avoid re-compilation, but the issue here is that the artifacts from the previous compilation in the npm dependency are not being merged with the new compilation as they should, making you lose the networks info. We'll take a closer look at this issue once #2599 is resolved, which will lay some groundwork for fixing this.

**Comment by haltman-at** [comment]
Related to #1250.

**Comment by eggplantzzz** [comment]
do npm packages still distribute with built Truffle artifact files?

**Comment by eggplantzzz** [comment]
One thing to note is that normally when Truffle compiles and saves artifacts from a user's project (Solidity files that are by default in the `contracts` folder), we merge in the new one with the old. That way network information gets persisted across multiple compiles. Seems like we should probably do that here.

However, the problem is a little bit bigger than that. If you import a Solidity file in your own Solidity files, compilation needs to happen and there is currently no way to feed that info to the compiler. Normally you would have to compile and then record the address of the deployed contract in the constructor of your new contract during deployment or use some other kind of setter. I'm not sure what there is to do about that part of the problem.
