### ISSUE TITLE
Error while unboxing the pet-shop box

### ISSUE THREAD

**Issue by unstopablewoman** [trufflesuite/truffle#2692]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
 truffle unbox pet-shop                                                                  
√ Preparing to download
× Downloading
RequestError: Error: read ECONNRESET
    at new RequestError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\errors.js:14:1)
    at Request.plumbing.callback (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\plumbing.js:87:1)
    at Request.RP$callback [as _callback] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\plumbing.js:46:1)
    at self.callback (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:185:1)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:881:1)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Truffle v5.1.4 (core: 5.1.4)
Node v12.13.1
* npm version (`npm --version`): 6.12.1

I update the node version but it doesn't work.
but the command truffle unbox pet-shop i use yesterday work well.
i try to look for the file  C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:881:1
and i can not find such a file.there is only a build  folder.webpack: i can't find it.

**Comment by adrianmcli** [comment]
I've tried to replicate this on both Node v10 and Node v12 w/ MacOS, but was unsuccessful. Let me see if I can find another team member with more Windows knowledge to look into this.

**Comment by unstopablewoman** [comment]
> I've tried to replicate this on both Node v10 and Node v12 w/ MacOS, but was unsuccessful. Let me see if I can find another team member with more Windows knowledge to look into this.

**Comment by caoyifeng007** [comment]
I have some question 
╰─ truffle unbox pet-shop                                                              1 ↵  3349  14:15:44  
✔ Preparing to download box
✖ Downloading
✖ Downloading
RequestError: Error: connect ECONNREFUSED 151.101.228.133:443
    at new RequestError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/errors.js:14:1)
    at Request.plumbing.callback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:87:1)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:46:1)
    at self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:185:1)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:881:1)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Truffle v5.1.6 (core: 5.1.6)
Node v12.14.0

**Comment by gnidan** [comment]
Do either of you reporting this problem have a proxy or other specific network configuration that could give us clues as to what's happening?

Thanks!

**Comment by zjuguyunzhe** [comment]
I also got this issue
when running:
truffle unbox webpack
-------------------------
√ Preparing to download box
× Downloading
RequestError: Error: read ECONNRESET
    at new RequestError (C:\Users\admin\nvm\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\errors.js:14:1)
    at Request.plumbing.callback (C:\Users\admin\nvm\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\plumbing.js:87:1)
    at Request.RP$callback [as _callback] (C:\Users\admin\nvm\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\plumbing.js:46:1)
    at self.callback (C:\Users\admin\nvm\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:185:1)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (C:\Users\admin\nvm\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:881:1)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Truffle v5.1.5 (core: 5.1.5)
Node v10.17.0

However, when I run
truffle unbox pet-shop
--------------
√ Preparing to download box
√ Downloading
npm WARN pet-shop@1.0.0 No description
npm WARN pet-shop@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

√ cleaning up temporary files
√ Setting up box

It seems Ok.
I can't find the reason.

**Comment by wei193** [comment]
If you are in China, You can use a hosts to solve this problem.
https://github.com/googlehosts/hosts

**Comment by adrianmcli** [comment]
To everyone in this thread, can we confirm that this is a problem with China's great firewall?

**Comment by zjuguyunzhe** [comment]
I added the #GoogleHosts# part to my hosts file, and then I ran truffle unbox webpack.
It seems to work now.

√ Preparing to download box
√ Downloading
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

√ cleaning up temporary files
√ Setting up box

I'm not sure if it is because of the China's firewall against google.
But anyway thanks, I'll try a couple of times later to confirm if it really works.

**Comment by gnidan** [comment]
If possible, I'd love to investigate workarounds to make this easier.

**Comment by 489356037** [comment]
i also have this problem

**Comment by Komari-Koshigaya** [comment]
Three days ago t is successfully when running "truffle unbox pet-shop", but today it doesn't work.

Starting unbox...
=================

✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
**RequestError: Error: connect ECONNREFUSED 0.0.0.0:443**
    at new RequestError (/home/niejun/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/errors.js:14:1)
    at Request.plumbing.callback (/home/niejun/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:87:1)
    at Request.RP$callback [as _callback] (/home/niejun/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:46:1)
    at self.callback (/home/niejun/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:185:1)
    at Request.emit (events.js:310:20)
    at Request.onRequestError (/home/niejun/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:881:1)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Truffle v5.1.22 (core: 5.1.22)
Node v12.16.2

**Comment by youwenbusi** [comment]
> Three days ago it is successfully when running "truffle unbox pet-shop", but today it doesn't work.
> Starting unbox...
> ✔ Preparing to download box
> ✖ Downloading
> Unbox failed!
> ✖ Downloading
> Unbox failed!
> RequestError: Error: connect ECONNREFUSED 0.0.0.0:443
> at new RequestError (/home/niejun/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/errors.js:14:1)
> at Request.plumbing.callback (/home/niejun/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:87:1)
> at Request.RP$callback [as _callback] (/home/niejun/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:46:1)
> at self.callback (/home/niejun/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:185:1)
> at Request.emit (events.js:310:20)
> at Request.onRequestError (/home/niejun/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:881:1)
> at ClientRequest.emit (events.js:310:20)
> at TLSSocket.socketErrorListener (_http_client.js:426:9)
> at TLSSocket.emit (events.js:310:20)
> at emitErrorNT (internal/streams/destroy.js:92:8)
> at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
> at processTicksAndRejections (internal/process/task_queues.js:84:21)
> Truffle v5.1.22 (core: 5.1.22)
> Node v12.16.2

I had the same problem, have you solved it, please help me, thx

**Comment by Komari-Koshigaya** [comment]
@youwenbusi   
I'm sorry that i have no idea. But you can find a set of boilerplates in [https://github.com/truffle-box](https://github.com/truffle-box). 
So you can using "git clone https://github.com/truffle-box/pet-shop-box" instead of "truffle unbox pet-shop"

**Comment by PingPongSet** [comment]
I have a similar issue like below:

> $ truffle unbox pet-shop
> 
> Starting unbox...
> =================
> 
> - Preparing to download box
> ΓêÜ Preparing to download box
> - Downloading
> ├ù Downloading
> Unbox failed!
> ├ù Downloading
> Unbox failed!
> RequestError: Error: getaddrinfo ENOENT raw.githubusercontent.com
>     at new RequestError (C:\Users\songxun.lin\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\errors.js:14:1)
>     at Request.plumbing.callback (C:\Users\songxun.lin\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\plumbing.js:87:1)
>     at Request.RP$callback [as _callback] (C:\Users\songxun.lin\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\plumbing.js:46:1)
>     at self.callback (C:\Users\songxun.lin\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:185:1)
>     at Request.emit (events.js:315:20)
>     at Request.onRequestError (C:\Users\songxun.lin\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:881:1)
>     at ClientRequest.emit (events.js:315:20)
>     at TLSSocket.socketErrorListener (_http_client.js:426:9)
>     at TLSSocket.emit (events.js:315:20)
>     at emitErrorNT (internal/streams/destroy.js:92:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> Truffle v5.1.41 (core: 5.1.41)
> Node v12.18.3
> 
> 

I added below, am still getting error:
1. add GoogleHost from https://github.com/googlehosts/hosts/blob/master/hosts-files/hosts to C:\Windows\System32\drivers\etc\hosts
2. even try to use VPN.

I don't have problem download the project from web browser without above.

Any idea?

**Comment by muhammadYunas** [comment]
> Do either of you reporting this problem to have a proxy or other specific network configuration that could give us clues as to what's happening?
> 
> Thanks!

I have tried with both proxy and without proxy still not working.

**Comment by Funkunlun** [comment]
the question：
Starting unbox...
=================

✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
Truffle v5.4.0 (core: 5.4.0)
Node v12.22.2

**Comment by gkilmain** [comment]
I ran into this but was using a wifi extender. Once I connect directly to my network truffle init worked.
node@14.17.4
truffle@5.0.2

**Comment by Cristliu** [comment]
> @youwenbusi 对不起，我不知道。但是您可以在[https://github.com/truffle-box 中](https://github.com/truffle-box)找到一组样板。 所以你可以使用“git clone https://github.com/truffle-box/pet-shop-box ”而不是“truffle unbox pet-shop”



> @youwenbusi I'm sorry that i have no idea. But you can find a set of boilerplates in https://github.com/truffle-box. So you can using "git clone https://github.com/truffle-box/pet-shop-box" instead of "truffle unbox pet-shop"

It works!
But it still needs to be run with a proxy. For me, using a proxy node in Japan works. Under this proxy node, `git clone https://github.com/truffle-box/webpack-box` and `truffle init `
are working, but `truffle unbox webpack` still `Unbox failed`

**Comment by Cristliu** [comment]
> @youwenbusi I'm sorry that i have no idea. But you can find a set of boilerplates in https://github.com/truffle-box. So you can using "git clone https://github.com/truffle-box/pet-shop-box" instead of "truffle unbox pet-shop"

It works!
But it still needs to be run with a proxy. For me, using a proxy node in Japan works. Under this proxy node, `git clone https://github.com/truffle-box/webpack-box` and `truffle init`
are working, but `truffle unbox webpack` still `Unbox failed`

**Comment by caoyifeng007** [comment]
> If you are in China, You can use a hosts to solve this problem. https://github.com/googlehosts/hosts

how should I use this hosts ?

**Comment by inso-** [comment]
same issue happen often to me during contract deployment/upgrade.
I am not under any special network condition (not in china/no proxy/etc...), changing the wallet use to deploy or disconnect/reconnect my computer from network solve the issue.

 I suspect an issue on Truffle (socket not correctly closed or something like this)

**Comment by cds-amal** [comment]
@inso- can you run and share the result of running the unbox command with debug env set?

`DEBUG=* truffle unbox <some box>`

**Comment by inso-** [comment]
Debug from my contract deployment:

Attempt 1:
```
...
 compile ] +41s
> Everything is up to date, there is nothing to compile.
  db:meta:graph:schema Creating DefinitonSchema for sources... +0ms
  db:meta:graph:schema Created ImmutableDefinitionSchema for sources. +1ms
  db:meta:graph:schema Creating DefinitonSchema for bytecodes... +0ms
  db:meta:graph:schema Created ImmutableDefinitionSchema for bytecodes. +0ms
  db:meta:graph:schema Creating DefinitonSchema for compilations... +0ms
  db:meta:graph:schema Created ImmutableDefinitionSchema for compilations. +0ms
  db:meta:graph:schema Creating DefinitonSchema for contracts... +0ms
  db:meta:graph:schema Created ImmutableDefinitionSchema for contracts. +0ms
  db:meta:graph:schema Creating DefinitonSchema for contractInstances... +0ms
  db:meta:graph:schema Created ImmutableDefinitionSchema for contractInstances. +0ms
  db:meta:graph:schema Creating DefinitonSchema for networks... +1ms
  db:meta:graph:schema Created ImmutableDefinitionSchema for networks. +0ms
  db:meta:graph:schema Creating DefinitonSchema for nameRecords... +0ms
  db:meta:graph:schema Created ImmutableDefinitionSchema for nameRecords. +0ms
  db:meta:graph:schema Creating DefinitonSchema for projects... +0ms
  db:meta:graph:schema Created ImmutableDefinitionSchema for projects. +0ms
  db:meta:graph:schema Creating DefinitonSchema for projectNames... +0ms
  db:meta:graph:schema Created MutableDefinitonSchema for projectNames. +0ms
  db:meta:graph:schema Creating DefinitonSchema for networkGenealogies... +0ms
  db:meta:graph:schema Created ImmutableDefinitionSchema for networkGenealogies. +0ms
  db:meta:graph:schema:typeDefs Generating... +0ms
  db:meta:graph:schema:sources:typeDefs Generating... +0ms
  db:meta:graph:schema:sources:typeDefs Generated. +1ms
  db:meta:graph:schema:bytecodes:typeDefs Generating... +0ms
  db:meta:graph:schema:bytecodes:typeDefs Generated. +1ms
  db:meta:graph:schema:compilations:typeDefs Generating... +0ms
  db:meta:graph:schema:compilations:typeDefs Generated. +2ms
  db:meta:graph:schema:contracts:typeDefs Generating... +0ms
  db:meta:graph:schema:contracts:typeDefs Generated. +5ms
  db:meta:graph:schema:contractInstances:typeDefs Generating... +0ms
  db:meta:graph:schema:contractInstances:typeDefs Generated. +18ms
  db:meta:graph:schema:networks:typeDefs Generating... +0ms
  db:meta:graph:schema:networks:typeDefs Generated. +1ms
  db:meta:graph:schema:nameRecords:typeDefs Generating... +0ms
  db:meta:graph:schema:nameRecords:typeDefs Generated. +0ms
  db:meta:graph:schema:projects:typeDefs Generating... +0ms
  db:meta:graph:schema:projects:typeDefs Generated. +1ms
  db:meta:graph:schema:projectNames:typeDefs Generating... +0ms
  db:meta:graph:schema:projectNames:typeDefs Generated. +0ms
  db:meta:graph:schema:networkGenealogies:typeDefs Generating... +0ms
  db:meta:graph:schema:networkGenealogies:typeDefs Generated. +1ms
  db:meta:graph:schema:typeDefs Generated. +34ms
  db:meta:graph:schema:resolvers Generating... +0ms
  db:meta:graph:schema:sources:resolvers Generating... +0ms
  db:meta:graph:schema:sources:resolvers Generating... +0ms
  db:meta:graph:schema:sources:resolvers Generated. +1ms
  db:meta:graph:schema:sources:resolvers Generated. +1ms
  db:meta:graph:schema:bytecodes:resolvers Generating... +0ms
  db:meta:graph:schema:bytecodes:resolvers Generating... +0ms
  db:meta:graph:schema:bytecodes:resolvers Generated. +0ms
  db:meta:graph:schema:bytecodes:resolvers Generated. +0ms
  db:meta:graph:schema:compilations:resolvers Generating... +0ms
  db:meta:graph:schema:compilations:resolvers Generating... +0ms
  db:meta:graph:schema:compilations:resolvers Generated. +0ms
  db:meta:graph:schema:compilations:resolvers Generated. +0ms
  db:meta:graph:schema:contracts:resolvers Generating... +0ms
  db:meta:graph:schema:contracts:resolvers Generating... +0ms
  db:meta:graph:schema:contracts:resolvers Generated. +0ms
  db:meta:graph:schema:contracts:resolvers Generated. +0ms
  db:meta:graph:schema:contractInstances:resolvers Generating... +0ms
  db:meta:graph:schema:contractInstances:resolvers Generating... +0ms
  db:meta:graph:schema:contractInstances:resolvers Generated. +0ms
  db:meta:graph:schema:contractInstances:resolvers Generated. +0ms
  db:meta:graph:schema:networks:resolvers Generating... +0ms
  db:meta:graph:schema:networks:resolvers Generating... +0ms
  db:meta:graph:schema:networks:resolvers Generated. +0ms
  db:meta:graph:schema:networks:resolvers Generated. +1ms
  db:meta:graph:schema:nameRecords:resolvers Generating... +0ms
  db:meta:graph:schema:nameRecords:resolvers Generating... +0ms
  db:meta:graph:schema:nameRecords:resolvers Generated. +0ms
  db:meta:graph:schema:nameRecords:resolvers Generated. +0ms
  db:meta:graph:schema:projects:resolvers Generating... +0ms
  db:meta:graph:schema:projects:resolvers Generating... +0ms
  db:meta:graph:schema:projects:resolvers Generated. +1ms
  db:meta:graph:schema:projects:resolvers Generated. +1ms
  db:meta:graph:schema:projectNames:resolvers Generating... +0ms
  db:meta:graph:schema:projectNames:resolvers Generating... +0ms
  db:meta:graph:schema:projectNames:resolvers Generated. +0ms
  db:meta:graph:schema:projectNames:resolvers Generated. +0ms
  db:meta:graph:schema:networkGenealogies:resolvers Generating... +0ms
  db:meta:graph:schema:networkGenealogies:resolvers Generating... +0ms
  db:meta:graph:schema:networkGenealogies:resolvers Generated. +0ms
  db:meta:graph:schema:networkGenealogies:resolvers Generated. +1ms
  db:meta:graph:schema:resolvers Generated. +5ms
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  code: -32603,
  message: 'read ECONNRESET',
  data: {
    originalError: { errno: -54, code: 'ECONNRESET', syscall: 'read' }
  },
  stack: 'Error: read ECONNRESET\n' +
    '    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)'
})
    at Web3ProviderEngine.emit (events.js:389:17)
    at Web3ProviderEngine.emit (domain.js:470:12)
    at /Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/@trufflesuite/web3-provider-engine/index.js:57:14
    at afterRequest (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/@trufflesuite/web3-provider-engine/index.js:151:21)
    at /Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/@trufflesuite/web3-provider-engine/index.js:176:21
    at /Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/@trufflesuite/web3-provider-engine/index.js:238:9
    at /Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/async/internal/once.js:12:16
    at replenish (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/async/internal/eachOfLimit.js:61:25)
    at /Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/async/eachLimit.js:43:36)
    at /Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/@trufflesuite/web3-provider-engine/index.js:217:5)
    at Request._callback (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:36:21)
    at self.callback (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.emit (domain.js:470:12)
    at Request.onRequestError (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.emit (domain.js:470:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:470:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
error Command failed with exit code 1.

```

Attempt 2:
```
...
  compile ] +53s
> Everything is up to date, there is nothing to compile.
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  code: -32603,
  message: 'ESOCKETTIMEDOUT',
  data: { originalError: { code: 'ESOCKETTIMEDOUT', connect: false } },
  stack: 'Error: ESOCKETTIMEDOUT\n' +
    '    at ClientRequest.<anonymous> (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/request/request.js:816:19)\n' +
    '    at Object.onceWrapper (events.js:519:28)\n' +
    '    at ClientRequest.emit (events.js:400:28)\n' +
    '    at ClientRequest.emit (domain.js:470:12)\n' +
    '    at TLSSocket.emitRequestTimeout (_http_client.js:790:9)\n' +
    '    at Object.onceWrapper (events.js:519:28)\n' +
    '    at TLSSocket.emit (events.js:412:35)\n' +
    '    at TLSSocket.emit (domain.js:470:12)\n' +
    '    at TLSSocket.Socket._onTimeout (net.js:484:8)\n' +
    '    at listOnTimeout (internal/timers.js:557:17)\n' +
    '    at processTimers (internal/timers.js:500:7)'
})
    at Web3ProviderEngine.emit (events.js:389:17)
    at Web3ProviderEngine.emit (domain.js:470:12)
    at /Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/@trufflesuite/web3-provider-engine/index.js:57:14
    at afterRequest (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/@trufflesuite/web3-provider-engine/index.js:151:21)
    at /Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/@trufflesuite/web3-provider-engine/index.js:176:21
    at /Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/@trufflesuite/web3-provider-engine/index.js:238:9
    at /Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/async/internal/once.js:12:16
    at replenish (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/async/internal/eachOfLimit.js:61:25)
    at /Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/async/eachLimit.js:43:36)
    at /Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/@trufflesuite/web3-provider-engine/index.js:217:5)
    at Request._callback (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:36:21)
    at self.callback (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.emit (domain.js:470:12)
    at ClientRequest.<anonymous> (/Users/inso/WebstormProjects/rosart/lib.rosart.io/packages/rosart-marketplace/node_modules/request/request.js:819:16)
    at Object.onceWrapper (events.js:519:28)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:470:12)
    at TLSSocket.emitRequestTimeout (_http_client.js:790:9)
    at Object.onceWrapper (events.js:519:28)
error Command failed with exit code 1.
```

**Comment by cds-amal** [comment]
Hi @inso- Apologies, I thought you had an issue with the `unbox` command. Please open a new issue, so it will be easier to track and resolve the original Issue as well as yours. It would be helpful to include the command, truffle-config and output. Thanks!

**Comment by inso-** [comment]
Look like the exact same issue happen on init, deploy and unbox. Will open a new one with details when I have time.

**Comment by Pavanee12** [comment]
Starting unbox...
=================

✓ Preparing to download box
✖ Downloading
Unbox failed!
Error: connect ETIMEDOUT 2405:200:1607:2820:41::36:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16)
Truffle v5.7.3 (core: 5.7.3)
Node v18.13.0

how to resolve??

**Comment by eggplantzzz** [comment]
Hey @Pavanee12, usually this means there is something up with your network connection. Do you get the same results when using a different network connection?

**Comment by cliffoo** [comment]
Closing for issue maintenance.
