### ISSUE TITLE
Disconnect from ganache-cli forked mainnet

### ISSUE THREAD

**Issue by k06a** [trufflesuite/truffle#2705]
##  Issue

I run project tests in ganache-cli fork of mainnet over infura. And when tests took too long I receive this:
```
Could not connect to your Ethereum client with the following parameters:
    - host       > localhost
    - port       > 9545
    - network_id > 1
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)
```

But I am pretty sure `ganache-cli` is still running. What's happening?

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): 5.1.4
* node version (`node --version`): 10.17.0
* npm version (`npm --version`): 6.11.3

**Comment by k06a** [comment]
Any thoughts?

**Comment by fainashalts** [comment]
Hi @k06a, thanks for bringing this up! Can you share some steps to reproduce this issue, so we can dig in?

**Comment by gnidan** [comment]
Could you log the JSON RPC (`truffle test --verbose-rpc`) and show us that? Might provide some insight.

**Comment by k06a** [comment]
@gnidan will check!

**Comment by k06a** [comment]
[log.txt](https://github.com/trufflesuite/truffle/files/4098781/log.txt)

**Comment by fainashalts** [comment]
Hi @k06a thank you for providing your logs, it does look like ganache is not responding as expected. Can you provide a link to your project so we can try to reproduce this? Thanks!

**Comment by k06a** [comment]
You can run `yarn && yarn run test` from this repo: [@CryptoManiacsZone/1split](https://github.com/CryptoManiacsZone/1split)
Truffle verbose: [truffle.txt](https://github.com/trufflesuite/truffle/files/4099540/truffle.txt)
Ganache-cli verbose: [ganache-cli.txt](https://github.com/trufflesuite/truffle/files/4099539/ganache-cli.txt)

**Comment by sobolev-igor** [comment]
Hi, everyone!

I'm facing the same issue when running tests and coverage locally. However, the issue does not appear when running tests using GitHub Actions.

Unfortunately, I work in a private repo, but I can provide any logs if needed.

**Comment by gnidan** [comment]
Thanks @k06a for that extra information!

Adding this to our backlog to dig into.

(@sobolev-igor will ping you if more data will be helpful!)

**Comment by eggplantzzz** [comment]
@k06a I was able to successfully run `yarn run test` in that repo. I hope that helps!

**Comment by k06a** [comment]
@eggplantzzz sometimes it works, but in 90% cases doesn’t. Check Travis-CI logs, for example.

**Comment by eggplantzzz** [comment]
Hmm, I was able to successfully run it thrice in a row. This might be tricky to track down...

**Comment by eggplantzzz** [comment]
Hmm, I wonder if this suggests it might be some sort of performance issue...

**Comment by k06a** [comment]
@eggplantzzz maybe you also really close to Infura HQ 😁

**Comment by k06a** [comment]
@eggplantzzz checkout CI logs or the repo

**Comment by k06a** [comment]
I see truffle performes second call and something strange happens:
```
eth_call
   > {
   >   "jsonrpc": "2.0",
   >   "id": 33,
   >   "method": "eth_call",
   >   "params": [
   >     {
   >       "from": "0xdf08f82de32b8d460adbe8d72043e3a7e25a3b39",
   >       "gas": "0x7a1200",
   >       "gasPrice": "0x3b9aca00",
   >       "to": "0x7cc4b1851c35959d34e635a470f6b5c43ba3c9c9",
   >       "data": "0x085e2c5b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000089d24a6b4ccb1b6faa2625fe562bdd9a23260359000000000000000000000000000000000000000000000001158e460913d00000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000004"
   >     },
   >     "latest"
   >   ]
   > }
eth_getBlockByNumber
   > {
   >   "jsonrpc": "2.0",
   >   "id": 34,
   >   "method": "eth_getBlockByNumber",
   >   "params": [
   >     null,
   >     false
   >   ]
   > }
 <   {
 <     "id": 33,
 <     "jsonrpc": "2.0",
 <     "result": "0x0000000000000000000000000000000000000000000000c6bdea648fc0e9f39000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
 <   }
 <   {
 <     "id": 34,
 <     "jsonrpc": "2.0",
 <     "error": {
 <       "message": "Returned error: invalid argument 0: empty hex string",
 <       "code": -32000,
 <       "data": {
 <         "stack": "Error: Returned error: invalid argument 0: empty hex string\n    at Object.ErrorResponse (/Users/k06a/Projects/1split/node_modules/ganache-cli/build/ganache-core.node.cli.js:53:1421880)\n    at /Users/k06a/Projects/1split/node_modules/ganache-cli/build/ganache-core.node.cli.js:53:1420752\n    at t.n.onreadystatechange (/Users/k06a/Projects/1split/node_modules/ganache-cli/build/ganache-core.node.cli.js:89:10247)\n    at t.e.dispatchEvent (/Users/k06a/Projects/1split/node_modules/ganache-cli/build/ganache-core.node.cli.js:17:47987)\n    at t._setReadyState (/Users/k06a/Projects/1split/node_modules/ganache-cli/build/ganache-core.node.cli.js:89:15283)\n    at t._onHttpResponseEnd (/Users/k06a/Projects/1split/node_modules/ganache-cli/build/ganache-core.node.cli.js:89:18380)\n    at IncomingMessage.<anonymous> (/Users/k06a/Projects/1split/node_modules/ganache-cli/build/ganache-core.node.cli.js:89:17635)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)",
 <         "name": "Error"
 <       }
 <     }
 <   }
```

**Comment by johnnyshankman** [comment]
I have a very similar on a very very long test suite. Was anyone able to figure out what their issue was? The verbose logs are useless.

**Comment by lsqproduction** [comment]
Hi @johnnyshankman. Would you please help to open a new issue with the reproduction repo and steps and the version info?

**Comment by lsqproduction** [comment]
Does anything think this is still an issue with Ganache 7? (It's `ganache` now, instead of `ganache-cli`) If you do, can you please help to provide the reproduction steps and repo?

**Comment by cds-amal** [comment]
Closing for issue maintenance. cc: @davidmurdoch
