### ISSUE TITLE
Truffle fails to resolve solc remapping

### ISSUE THREAD

**Issue by pik694** [trufflesuite/truffle#2768]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue. []()

---------------------------

## Issue

I tried to use `solc` `remapping` by adding the proper option to `truffle-config.js`, but `Resolver` fires an exception before the flow even reaches solc.

`solc remapping` has been enabled (the option is passed from config to `solc`) as a fix to #2355, and it passes unit tests, but there is no integration test that checks whether it is actually possible to compile contracts using `remappings` option.

## Steps to Reproduce

Follow README in [https://github.com/pik694/truffle-remapping-issue.git](https://github.com/pik694/truffle-remapping-issue.git). 

The exception seems to be thrown in this line [https://github.com/trufflesuite/truffle/blob/7c19713c22a512b6a7f936a6927ddb553836d56e/packages/resolver/index.js#L75](https://github.com/trufflesuite/truffle/blob/7c19713c22a512b6a7f936a6927ddb553836d56e/packages/resolver/index.js#L75).

## Expected Behavior

Contracts should compile without errors.

## Actual Results

```
Compiling your contracts...
===========================
Error: Could not find remapped/C.sol from any sources; imported from /***/truffle-remapping-issue/contracts/A.sol
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/index.js:82:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/async/internal/onlyOnce.js:12:1
    at next (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/async/whilst.js:68:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/index.js:69:1
    at FS.resolve (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/fs.js:69:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/index.js:60:1
    at next (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/async/whilst.js:66:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/index.js:69:1
    at GlobalNPM.resolve (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/globalnpm.js:50:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/index.js:60:1
    at next (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/async/whilst.js:66:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/index.js:69:1
    at NPM.resolve (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/npm.js:54:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/index.js:60:1
    at next (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/async/whilst.js:66:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/index.js:69:1
    at EPM.resolve (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/epm.js:109:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/index.js:60:1
    at whilst (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/async/whilst.js:70:1)
    at Resolver.resolve (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/index.js:52:1)
    at Promise (/usr/local/lib/node_modules/truffle/build/webpack:/packages/compile-solidity/profiler/index.js:199:1)
    at new Promise (<anonymous>)
Truffle v5.1.7 (core: 5.1.7)
Node v10.16.3
make: *** [truffle] Error 1
```

## Environment

* Operating System: `macOS 10.15`
* Truffle: `v5.1.7 (core: 5.1.7)`
* Solidity: `v0.5.12 (solc-js)`
* Node: `v10.16.3`
* Web3.js: `v1.2.1`
* npm: `6.13.4`

**Comment by eggplantzzz** [comment]
@pik694 Thanks for reporting this and providing the repro steps! I'll see if I can get to the bottom of this.

**Comment by eggplantzzz** [comment]
Oh it looks like this problem will be a bit more involved than I thought. The problem is that the resolver doesn't know how to deal with (resolve) the remappings. I don't think we'll have time for it in the immediate future but if anyone is interested in tackling this then let me know!

**Comment by cameel** [comment]
For anyone interested in tackling this: compiler's behavior is now fully documented in [Import remapping](https://docs.soliditylang.org/en/develop/path-resolution.html#import-remapping).

Also, the compiler is actually supposed to be able to do that translation for you automatically. The problem is that the resolved path is only computed after parsing and has been missing from the output: https://github.com/ethereum/solidity/issues/11756. This will be fixed in one of the upcoming releases.
