### ISSUE TITLE
Truffle test throws error when specify web3 options on overloaded function

### ISSUE THREAD

**Issue by r0qs** [trufflesuite/truffle#2868]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.
---------------------------

## Issue

I don't know if this is a bug of Truffle or web3, or if I'm doing something wrong. But when I try to specify some options parameter (e.g. {from: some_address}) on an overloaded function the truffle test throws the following error:
```
Error: invalid number value (arg="number", coderType="uint256", valu e="One")
  at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:9:1)
  at TruffleContract.write (node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:169:1)
  at Context.it (test/TestC.js:10:15)
  at processTicksAndRejections (internal/process/task_queues.js:86:5)
```
If I remove the option parameter (e.g. {from: some_address}) the test works. So it seems that truffle or web3 are getting the wrong function signature. Or I'm declaring it in the wrong way.

```javascript
const c = await C.deployed();
await c.write("One", { from: account }); // this doesn't work
await c.write("One"); // this work
```
The code is:
```solidity
pragma solidity >=0.5.13 <0.7.0;

interface I {
    function write(string calldata str) external;
    function read() external view returns (string memory);
}

abstract contract A is I {

    string _str;
    
    constructor() public {}

    function write(string memory str)
        public
        override
    {
        _str = str;
    }

    function read() public view override returns (string memory){
        return _str;
    }
}

abstract contract B is A {

    uint256 _number;

    constructor() public A() {}

    function write(uint256 number, string memory str)
        public
    {
        _number = number;
        _str = str;
    }
}

contract C is B {
    constructor() public B() {}
}
```

## Steps to Reproduce

I created a repository to test this code and reproduce the problem. Just clone [this repo](https://github.com/r0qs/test-func-overload.git) and run "npm install" to install the dependencies, and run the ethereum client in one terminal:
```
$ npm run ganache-cli
```

Then, to see the test passing without the options parameter, run in another terminal:
```
$ npm run test
```

To see the error when the options parameter is informed, run:
```
$ npm run test:bug
```

## Expected Behavior

The test should succeed passing the web3 options parameter.

## Actual Results

Truffle test throws the error: "invalid number value (arg="number", coderType="uint256", valu e="One")"

## Environment

* Operating System: Arch Linux x86_64 Linux 5.5.7-arch1-1
* Ethereum client: ganache-cli verison 6.9.1
* Solc version: solc: 0.6.3+commit.8dda9521
* Truffle version (`truffle version`): 5.1.15
* node version (`node --version`): v11.15.0
* npm version (`npm --version`): 6.14.1

Am I missing something? Even though if I make the "write" function virtual on the A contract and override it on the B contract, like the following:
```solidity
abstract contract A is I {
...
function write(string memory str)
        public
        override
        virtual
    {
        _str = str;
    }
...
}
abstract contract B is A {
....
function write(string memory str)
        public
        override
    {
        super.write(str);
    }
...
}
```
I still get the same error.

**Comment by gnidan** [comment]
Ah, thanks for reporting this! Congrats, you've successfully confused Truffle! :)

Sounds like your hunch is correct: because you define more than one `write()` method (`write(string memory)` and `write(uint256, string memory)`), and because your C contract inherits B, which has both of those methods, Truffle sees the second argument in `c.write("...", { from: "..." })` and assumes you mean to use `write(uint256, string memory)`. Thus, it tries to interpret `"One"` as a `uint256`.

(You had me for a second there with that error message... I thought you were making a joke, saying `"One`" is supposed to be a `uint` ;)

Anyway, Truffle provides a way for you to get around this incorrect method discernment... and it's that `c.methods` object you found! Unfortunately this isn't in our docs, but see the [original release notes for this feature](https://github.com/trufflesuite/truffle/releases/tag/v5.0.0#user-content-what-s-new-in-truffle-v5-interacting-with-your-contracts-overloaded-solidity-functions). Roughly, you should just do this:

```javascript
await c.methods["write(uint256,string)"]("One", { from: account });
```

Hope this helps!

**Comment by haltman-at** [comment]
Btw, I want to pop in here that better overload resolution is planned for the future to make resorting to `methods` less necessary!

**Comment by r0qs** [comment]
Hahaha, thanks @gnidan! It works indeed, but the correct method is:
```solidity
await c.methods["write(string)"]("One", { from: account });
```
Since the method with signature "write(string)" looks to be hidden for truffle, but can be accessed explicitly as you recommended.

**Comment by gnidan** [comment]
> It works indeed, but the correct method is:

Oh of course; I wrote the wrong one, oops :)

Anyway, glad I could help! Besides the docs change, anything else actionable here? Is this a case where Truffle can error better? Can we feasibly detect the ambiguity here / is it worth it to add this before @haltman-at's teased changes?

Feel free to close if you're satisfied, or I'll follow-up after some team discussion in our weekly ticket processing on Wednesday. Thanks again!

**Comment by gnidan** [comment]
@haltman-at brings up a good point that we should be able to detect when the last argument is an options and thus not conformant to one of the overloads. Calling this a bug, then!

**Comment by Epict33tus** [comment]
Can an object ever be a useable parameter? The solidity ABI can only accept strings and number types?

**Comment by haltman-at** [comment]
@Epict33tus No, the Solidity ABI is considerably broader than that; it includes both structs and arrays, for instance.  You can read more about it [here](https://docs.soliditylang.org/en/v0.8.21/abi-spec.html).
