### ISSUE TITLE
Events package uses ora but does not declare this dependency in package.json

### ISSUE THREAD

**Issue by dstarke** [trufflesuite/truffle#2923]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

`@truffle/events` uses `ora` but does not declare this dependency in `package.json`

## Steps to Reproduce

Create a project that requires `@truffle/events`. (In my case, I was depending on `@truffle/config`, which in turn depends on`@truffle/events` ). Try to run it.

## Expected Behavior

Things should run normally.

## Actual Results

Running the project fails with the error:

```
Error: Cannot find module 'ora'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/app/current/node_modules/@truffle/events/defaultSubscribers/obtain.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/var/app/current/node_modules/@truffle/events/defaultSubscribers/index.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

## Environment

* Operating System: various
* Ethereum client: various
* Truffle version (`truffle version`): Truffle v5.1.18 (core: 5.1.18)
* node version (`node --version`): Node v10.16.3
* npm version (`npm --version`): 6.9.0

**Comment by haltman-at** [comment]
Thanks for noticing this!  I've put up #2924 to address this.
