### ISSUE TITLE
truffle init error，unbox Downloading

### ISSUE THREAD

**Issue by cx2929** [trufflesuite/truffle#2925]
when I use command truffle init ,

✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
RequestError: Error: connect ETIMEDOUT 151.101.108.133:443
    at new RequestError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/errors.js:14:1)
    at Request.plumbing.callback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:87:1)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:46:1)
    at self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:185:1)
    at Request.emit (events.js:311:20)
    at Request.onRequestError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:881:1)
    at ClientRequest.emit (events.js:311:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Truffle v5.1.19 (core: 5.1.19)
Node v12.16.1

Then I try to modify the "hosts" file (with my address added)
The whole contents of the document are as follows：

##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
#github
151.101.xxxxxxxxxxx(my address) github.com
::1             localhost

But it still failed
please help me!!!!!!!! T-T

**Comment by haltman-at** [comment]
Is this a consistent error?

**Comment by cx2929** [comment]
Yes, I found that some developers also have the first error. His solution is to add their own address in the "hosts" file, but I can't solve the problem after doing this. I don't know how to proceed Specific operations.
















At 2020-04-09 01:35:43, "Harry Altman" <notifications@github.com> wrote:

Is this a consistent error?

**Comment by cx2929** [comment]
> 这是一个一致的错误吗？

Yes, I found that some developers also have the first error. His solution is to add their own address in the "hosts" file, but I can't solve the problem after doing this. I don't know how to proceed Specific operations.

**Comment by adrianmcli** [comment]
This might be an error caused by the Chinese Firewall. I think I've seen something similar before, but it's really hard for us to replicate because we're not in China and I'm unaware of any tools that allow us to do so easily.

I am open to any ideas though.

**Comment by adrianmcli** [comment]
This issue seems relevant: https://github.com/trufflesuite/truffle/issues/2692

**Comment by cx2929** [comment]
> This issue seems relevant: #2692
> 
> The proposed solution is this: https://github.com/googlehosts/hosts
Thank you very much! ! ! I have solved this problem! !

**Comment by cx2929** [comment]
Thank you very much! ! I have solved this problem! ! !
















在 2020-04-09 10:14:39，"Adrian Li" <notifications@github.com> 写道：

This issue seems relevant: #2692

**Comment by cx2929** [comment]
> This issue seems relevant: #2692
> 
> The proposed solution is this: https://github.com/googlehosts/hosts

thank you very much! ! I have solved this problem! ! !

**Comment by cx2929** [comment]
> Is this a consistent error?

I have solved this problem, thank you anyway!
