### ISSUE TITLE
Error when using "truffle init"

### ISSUE THREAD

**Issue by hanting001** [trufflesuite/truffle#2995]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When i use "truffle init", show downloading error

## Steps to Reproduce

truffle init

## Expected Behavior

init a project

## Actual Results
download connect to localhost "0.0.0.0:443"
Starting unbox...
=================

? Proceed anyway? Yes
✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
RequestError: Error: connect ECONNREFUSED 0.0.0.0:443
    at new RequestError (/Users/hanting/.tnvm/versions/node/v13.1.0/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/errors.js:14:1)
    at Request.plumbing.callback (/Users/hanting/.tnvm/versions/node/v13.1.0/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:87:1)
    at Request.RP$callback [as _callback] (/Users/hanting/.tnvm/versions/node/v13.1.0/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:46:1)
    at self.callback (/Users/hanting/.tnvm/versions/node/v13.1.0/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:185:1)
    at Request.emit (events.js:210:5)
    at Request.onRequestError (/Users/hanting/.tnvm/versions/node/v13.1.0/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:881:1)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:407:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

## Environment

* Operating System: macOS Catalina
* Ethereum client: Ganache
* Truffle version (`truffle version`):
Truffle v5.1.22 (core: 5.1.22)
Solidity v0.5.16 (solc-js)
Node v13.1.0
Web3.js v1.2.1
* node version (`node --version`):
v13.1.0
* npm version (`npm --version`): 
6.14.2

**Comment by gnidan** [comment]
We're aware of this problem and are currently looking into a fix. Stay tuned! Thanks for reporting this!

**Comment by hanting001** [comment]
It's all GFW's fault, when i crossed GFW, everything work.

**Comment by eggplantzzz** [comment]
Hey @hanting001, what is GFW?

**Comment by flyq** [comment]
> Hey @hanting001, what is GFW?

Great Firewall

**Comment by flyq** [comment]
> It's all GFW's fault, when i crossed GFW, everything work.

me too:


```shell
$ truffle init

This directory is non-empty...
? Proceed anyway? Yes
✔ Preparing to download
✖ Downloading
RequestError: Error: getaddrinfo ENOTFOUND raw.githubusercontent.com raw.githubusercontent.com:443
    at new RequestError (/home/flyq/.nvm/versions/node/v10.13.0/lib/node_modules/truffle/build/webpack:/~/request-promise-core/lib/errors.js:14:1)
    at Request.plumbing.callback (/home/flyq/.nvm/versions/node/v10.13.0/lib/node_modules/truffle/build/webpack:/~/request-promise-core/lib/plumbing.js:87:1)
    at Request.RP$callback [as _callback] (/home/flyq/.nvm/versions/node/v10.13.0/lib/node_modules/truffle/build/webpack:/~/request-promise-core/lib/plumbing.js:46:1)
    at self.callback (/home/flyq/.nvm/versions/node/v10.13.0/lib/node_modules/truffle/build/webpack:/~/request/request.js:185:1)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (/home/flyq/.nvm/versions/node/v10.13.0/lib/node_modules/truffle/build/webpack:/~/request/request.js:881:1)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Truffle v5.0.37 (core: 5.0.37)
Node v10.13.0
flyq@ubuntu:~/workspaces/gitlab/upgradeable-token-01$ truffle init

This directory is non-empty...
? Proceed anyway? Yes
✔ Preparing to download
✖ Downloading
RequestError: Error: connect ECONNREFUSED 0.0.0.0:443
    at new RequestError (/home/flyq/.nvm/versions/node/v10.13.0/lib/node_modules/truffle/build/webpack:/~/request-promise-core/lib/errors.js:14:1)
    at Request.plumbing.callback (/home/flyq/.nvm/versions/node/v10.13.0/lib/node_modules/truffle/build/webpack:/~/request-promise-core/lib/plumbing.js:87:1)
    at Request.RP$callback [as _callback] (/home/flyq/.nvm/versions/node/v10.13.0/lib/node_modules/truffle/build/webpack:/~/request-promise-core/lib/plumbing.js:46:1)
    at self.callback (/home/flyq/.nvm/versions/node/v10.13.0/lib/node_modules/truffle/build/webpack:/~/request/request.js:185:1)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (/home/flyq/.nvm/versions/node/v10.13.0/lib/node_modules/truffle/build/webpack:/~/request/request.js:881:1)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Truffle v5.0.37 (core: 5.0.37)
Node v10.13.0
flyq@ubuntu:~/workspaces/gitlab/upgradeable-token-01$ truffle init

This directory is non-empty...
? Proceed anyway? Yes
✔ Preparing to download
✔ Downloading
✔ Cleaning up temporary files
✔ Setting up box

Unbox successful. Sweet!

Commands:

  Compile:        truffle compile
  Migrate:        truffle migrate
  Test contracts: truffle test

flyq@ubuntu:~/workspaces/gitlab/upgradeable-token-01$ 
```
The first one is that I don't use network proxy, and it failed because it can't connect to raw.githubusercontent.com. The second one is alse failed because I use the proxy. The last one is that I use another WiFi, and it succeed.

so could truffle package **do not**  put on raw.githubusercontent.com? or put it in a images

**Comment by zhaoxy2850** [comment]
If anyone encounter the same problem, just add the following line in the /etc/host:
`151.101.56.133  raw.githubusercontent.com`
It will work.

**Comment by ken-wong** [comment]
> 

works for me. Thank you very much.

**Comment by ken-wong** [comment]
> If anyone encounter the same problem, just add the following line in the /etc/host: `151.101.56.133 raw.githubusercontent.com` It will work.

works for me. Thank you very much.
