### ISSUE TITLE
Truffle quorum extension error while submitting command with privateFor

### ISSUE THREAD

**Issue by mrarjunbgupta** [trufflesuite/truffle#3045]
## Issue

I was testing quorum smart contract deployment and transaction invocation using Truffle Suit. It was working fine until I ran "npm audit fix" to cater to error had come for npm install in my truffle project folder. Below is error listing.

## Steps to Reproduce

1. Download truffle pet shop example.
2. Change truffle config file to map to Quorum network.
3. Deploy the smart contract using truffle compile, truffle migrate.
4. Run "npm install" to get dependency installed in pet shop directory.
5. Run "npm audit fix" to fix the audit errors.
6. Run truffle console to execute the transactions.

## Expected Behavior

Transaction were executing successfully but post "npm audit fix" it has stopped working.

## Actual Results

```
truffle(development)> Meme.deployed().then(function(instance) { return instance.set('QmaayjaXmVHcow5LrGpWsrbeGA1Wi62eiNtdhY3nHNf9SK', {privateFor: ["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]}); })
Uncaught:
Error: Transaction: 0x9f42cf453ab5c27f50fd4a61e126a1eb7ea9bb84007b4219b597ca93b4631976 exited with an error (status 0). 
    at evalmachine.<anonymous>:0:59
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  message: 'Transaction: 0x9f42cf453ab5c27f50fd4a61e126a1eb7ea9bb84007b4219b597ca93b4631976 exited with an error (status 0). \n' +
    '     Please check that the transaction:\n' +
    '     - satisfies all conditions set by Solidity `require` statements.\n' +
    '     - does not trigger a Solidity `revert` statement.\n',
  stack: 'Error: Transaction: 0x9f42cf453ab5c27f50fd4a61e126a1eb7ea9bb84007b4219b597ca93b4631976 exited with an error (status 0). \n' +
    '    at evalmachine.<anonymous>:0:59\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
  name: 'StatusError',
  tx: '0x9f42cf453ab5c27f50fd4a61e126a1eb7ea9bb84007b4219b597ca93b4631976',
  receipt: {
    blockHash: '0x2a49e6cfff8116f281f86971ea978271aef19ca8a1fbcf0fc20d99d9a420f8b7',
    blockNumber: 5,
    contractAddress: null,
    cumulativeGasUsed: 0,
    from: '0xed9d02e382b34818e88b88a309c7fe71e65f419d',
    gasUsed: 0,
    logs: [],
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    status: false,
    to: '0x9d13c6d3afe1721beef56b55d303b09e021e27ab',
    transactionHash: '0x9f42cf453ab5c27f50fd4a61e126a1eb7ea9bb84007b4219b597ca93b4631976',
    transactionIndex: 0,
    rawLogs: []
  },
  reason: undefined,
  hijackedStack: 'Error: Transaction: 0x9f42cf453ab5c27f50fd4a61e126a1eb7ea9bb84007b4219b597ca93b4631976 exited with an error (status 0). \n' +
    '     Please check that the transaction:\n' +
    '     - satisfies all conditions set by Solidity `require` statements.\n' +
    '     - does not trigger a Solidity `revert` statement.\n' +
    '\n' +
    '    at StatusError.ExtendableError (/Users/arjungupta/.nvm/versions/node/v12.16.1/lib/node_modules/truffle/build/webpack:/packages/error/index.js:10:1)\n' +
    '    at new StatusError (/Users/arjungupta/.nvm/versions/node/v12.16.1/lib/node_modules/truffle/build/webpack:/packages/contract/lib/statuserror.js:33:1)\n' +
    '    at Object.receipt (/Users/arjungupta/.nvm/versions/node/v12.16.1/lib/node_modules/truffle/build/webpack:/packages/contract/lib/handlers.js:124:1)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n' +
    '    at Function.start (/Users/arjungupta/.nvm/versions/node/v12.16.1/lib/node_modules/truffle/build/webpack:/packages/contract/lib/override.js:49:1)'
}
```

## Environment

* Operating System: OSx
* Ethereum client: 
Geth
```
Version: 1.8.18-stable
Git Commit: 685f59fb5e08bf9d26fa2b8a1effbb03355b7c4f
Quorum Version: 2.5.0
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.11.13
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.11.13.linux.amd64
```

* Truffle version (`truffle version`): 
```
Truffle v5.1.25 (core: 5.1.25)
Solidity v0.5.16 (solc-js)
Node v12.16.1
Web3.js v1.2.1
```

* node version (`node --version`): v12.16.1
* npm version (`npm --version`): 6.13.4

**Comment by haltman-at** [comment]
Could you tell us anything about how specific this error is?  Like, does this only occur with Quorum or is it a more general problem?  Thank you!

**Comment by haltman-at** [comment]
OK, I think we're going to have to close this for issue maintenance.  But if there's still a problem, please do let us know and we can reopen this.
