### ISSUE TITLE
truffle test dosen't run

### ISSUE THREAD

**Issue by yasemincirt** [trufflesuite/truffle#3054]
Hi,

when I used truffle latest(v5.1.26) version on Node  v.12.16.3, truffle test command didn't run.
the truffle give me this error:

`TypeError [ERR_INVALID_REPL_INPUT]: Listeners for `uncaughtException` cannot be used in the REPL
    at process.<anonymous> (repl.js:253:15)
    at process.emit (events.js:322:22)
    at process.emit (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/source-map-support/source-map-support.js:495:1)
    at processEmit (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/signal-exit/index.js:155:1)
    at process.emit (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/reselect-tree/node_modules/source-map-support/source-map-support.js:485:1)
    at _addListener (events.js:353:14)
    at process.addListener (events.js:401:10)
    at Runner.run (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/runner.js:868:11)
    at Mocha.run (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:612:17)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/test.js:159:1
    at new Promise (<anonymous>)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/test.js:158:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

how should I solve this error?

## Environment

* Operating System: macOS
* Ethereum client:
* Truffle version (`truffle version`): v5.1.26
* node version (`node --version`): v12.16.3
* npm version (`npm --version`): 6.14.4

**Comment by yasemincirt** [comment]
the solution : 

#https://github.com/trufflesuite/truffle/issues/2070#issuecomment-573198692
