### ISSUE TITLE
RequestError: Error: certificate has expired

### ISSUE THREAD

**Issue by ChenJiaman11** [trufflesuite/truffle#3062]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.
I installed truffle successful , but when i used command truffle init to initialize a file,  there was a problem:
"RequestError: Error: certificate has expired
    at new RequestError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/errors.js:14:1)
    at Request.plumbing.callback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:87:1)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:46:1)
    at self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:185:1)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:881:1)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:463:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
"
## Steps to Reproduce
execute command "truffle init"

Please provide the shortest amount of steps to reproduce your issue.
install  Truffle version (`truffle version`):v5.1.26，node version (`node --version`):v14.2.0，npm version (`npm --version`): 6.14.4 at ubuntu16.04
then run command "truffle init"
## Expected Behavior
init successful
What you expected to happen.
init successful
## Actual Results
RequestError: Error: certificate has expired
    at new RequestError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/errors.js:14:1)
    at Request.plumbing.callback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:87:1)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:46:1)
    at self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:185:1)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:881:1)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:463:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21
What actually happened. Please give examples and support it with screenshots, copied output or error messages
## Environment

* Operating System: ubuntu16.04
* Ethereum client:geth
* Truffle version (`truffle version`):v5.1.26
* node version (`node --version`):v14.2.0
* npm version (`npm --version`): 6.14.4

**Comment by eggplantzzz** [comment]
Oh weird, do you have any unorthodox network settings? Sounds like there might be some problem with your configuration.

**Comment by eggplantzzz** [comment]
Note for the future: perhaps we should make `truffle init` work without an internet connection. :)

**Comment by haltman-at** [comment]
Closing this for issue maintenance.  Let us know if there's still a problem!
