### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Roelman** [trufflesuite/truffle#3121]
After " truffle compile " in terminal;

```
SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at Object.require (internal/modules/cjs/helpers.js:14:16)
    at Function.load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:145:1)
    at Function.detect (/usr/local/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:134:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/compile.js:53:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/cli.js:52:1)
    at __webpack_require__ (/usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 15740a559193d50cf75b:19:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/webpack/bootstrap 15740a559193d50cf75b:62:1
    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:68:10)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
Truffle v5.1.2 (core: 5.1.2)
Node v11.15.0
```

## Environment

* Operating System: 
* Ethereum client:
* Truffle version Truffle v5.1.2 (core: 5.1.2)
* node version Node v11.15.0
* npm version 6.7.0

**Comment by CruzMolina** [comment]
Hey @Roelman !

It looks like there could be an issue with your `truffle-config` file, can you share what that file looks like?

**Comment by gnidan** [comment]
Closing this for issue maintenance. Hopefully you've gotten around this problem by now!

(For what it's worth, another hypothesis is that on v5.1.2, `truffle compile` doesn't work inside `truffle develop`, and you had to write only `compile`. That's now been addressed in the latest release, if you can upgrade!)

**Comment by PDOG099** [comment]
Did I figure it out? I'm also stuck :(

**Comment by Nim1com** [comment]
same here

**Comment by Nim1com** [comment]
this is my compile part :
compilers: {
    solc: {
      version: "0.6.12"
    }
  }
