### ISSUE TITLE
Issue deploying to Rinkeby network

### ISSUE THREAD

**Issue by lrnzdevza** [trufflesuite/truffle#3155]
## Issue

I am having an issue when migrating to the Rinkeby network. 

## Steps to Reproduce

In the console run the following:
truffle dev
truffle migrate --network rinkeby

## Expected Behavior

Compiles and deploys to Rinkeby network. 

## Actual Results

Network up to date.
truffle(develop)> truffle migrate --network rinkeby

Compiling your contracts...
===========================
> Compiling .\contracts\Campaign.sol
> Compiling .\contracts\ContractFactory.sol
> Compiling .\contracts\Group.sol
> Compiling .\contracts\Migrations.sol
> Artifacts written to C:\DeRisk\app\src\contracts
> Compiled successfully using:
   - solc: 0.6.8+commit.0bbfe453.Emscripten.clang

truffle(develop)> > Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
> Something went wrong while attempting to connect to the network. Check your network configuration.
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (C:\DeRisk\node_modules\web3-core-helpers\src\errors.js:42:16)
    at XMLHttpRequest.request.onreadystatechange (C:\DeRisk\node_modules\web3-providers-http\src\index.js:92:32)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\DeRisk\node_modules\xhr2-cookies\xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (C:\DeRisk\node_modules\xhr2-cookies\xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpRequestError (C:\DeRisk\node_modules\xhr2-cookies\xml-http-request.ts:379:8)
    at ClientRequest.<anonymous> (C:\DeRisk\node_modules\xhr2-cookies\xml-http-request.ts:266:37)
    at ClientRequest.emit (events.js:311:20)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
truffle(develop)>

## Environment

* Operating System: Microsoft Windows 10
* Ethereum client: Ganache  ^6.9.1
* Truffle version (`truffle version`):  v5.1.33 (core: 5.1.33)
* node version (`node --version`):  v12.16.1
* npm version (`npm --version`): 6.13.4 

Extra Information
Solidity - 0.6.8 (solc-js)
"@openzeppelin/contracts": "^3.0.1",
"@truffle/hdwallet-provider": "^1.0.37",
"dotenv": "^8.2.0",
"ganache-cli": "^6.9.1"

**Comment by lrnzdevza** [comment]
Okay turns out it was my network, I created a hotspot and then it worked.  This can be closed
