### ISSUE TITLE
truffle init => Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by jeffmentor** [trufflesuite/truffle#3163]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------
Update: This only happens in my office laptop. My personal Mac this works as charm. Something to do with the certs or org security. Any idea how to bypass this? I tried the npm ways by providing a self signed cert and ssl false, but in vain.

## Issue

truffle init or truffle unbox metacoin results in 
Error: self signed certificate in certificate chain

## Steps to Reproduce

>> truffle unbox webpack

## Actual Results

Download and unbox the project

Starting unbox...
=================

✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
RequestError: Error: self signed certificate in certificate chain
    at new RequestError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/errors.js:14:1)
    at Request.plumbing.callback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:87:1)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:46:1)
    at self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:185:1)
    at Request.emit (events.js:314:20)
    at Request.onRequestError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:881:1)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Truffle v5.1.34 (core: 5.1.34)
Node v14.5.0

## Environment

* Operating System: MacOS
* Ethereum client: GETH
* Truffle version (`truffle version`): v5.1.34
* node version (`node --version`): v14.5.0
* npm version (`npm --version`): v6.14.5

**Comment by CruzMolina** [comment]
Hey @jeffmentor ! This looks like either a permissions or firewall issue.

I see you've tried a few ways to get this working (`npm config set strict-ssl false`, etc). You might try making sure `truffle` and `npm` are not installed using `sudo` and possibly re-installing `npm` w/o `sudo`.

**Comment by fainashalts** [comment]
Hi @jeffmentor this is fixed in Truffle v5.1.36, so we're closing this issue. Please let us know if you are still experiencing this problem!
