### ISSUE TITLE
Error Deploying a basic project via VSC following MS doc

### ISSUE THREAD

**Issue by PingPongSet** [trufflesuite/truffle#3286]
I have an error below when deploying a Sodality basic project via VSC following the steps below:
https://docs.microsoft.com/en-gb/azure/blockchain/service/send-transaction#deploy-a-smart-contract

```
Get version for required apps: truffle
[Execute command] 
Working dir: c:\_MyLab\AzureCode\Blockchain\HelloBlockchain
Running command
npx truffle migrate --reset --network abs_consortiumhello1_membername_membername
[Execute command] 
Compiling your contracts...
[Execute command] ===========================
[Execute command] > Everything is up to date, there is nothing to compile.
[Execute command] 
[Execute command] 
[Execute command] 
Starting migrations...
======================
> Network name:    'abs_consortiumhello1_membername_membername'
> Network id:      204
> Block gas limit: 2328199759 (0x8ac5824f)

[Execute command] 
1_initial_migration.js
======================
[Execute command] 
   Deploying 'Migrations'
   ----------------------
[Execute command]    > transaction hash:    0x59aabcf635ffecf410bc49cb70f720a77b8d7631af29bc4fe52e56696426c237
[Execute command] - Blocks: 0            Seconds: 0
[Execute command]    > Blocks: 1            Seconds: 9
[Execute command]    > contract address:    0x57aD50C452B5916947725c17eee15e66bc7D20B2
   > block number:        1968
   > block timestamp:     1597926758
   > account:             0xeD95E6eb7a1536D0c23d79D538c93d1EeD8cf8de
   > balance:             0
   > gas used:            225237 (0x36fd5)
   > gas price:           0 gwei
   > value sent:          0 ETH
   > total cost:          0 ETH

[Execute command] 
[Execute command] - Saving migration to chain.
[Execute command]    > Saving migration to chain.
[Execute command]    > Saving artifacts
   -------------------------------------
   > Total cost:                   0 ETH

[Execute command] 
2_deploy_contracts.js
=====================
[Execute command] 
   Deploying 'HelloBlockchain'
   ---------------------------
[Execute command] 
[Execute command] Error:  *** Deployment Failed ***

"HelloBlockchain" -- Invalid JSON RPC response: "".

    at C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\deployer\src\deployment.js:364:1
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration._deploy (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:68:1)
    at Migration._load (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:55:1)
    at Migration.run (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:171:1)
    at Object.runMigrations (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:150:1)
    at Object.runFrom (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:110:1)
    at Object.runAll (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:114:1)
    at Object.run (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:79:1)
    at runMigrations (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:269:1)
    at C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:231:1
[Execute command] Truffle v5.1.41 (core: 5.1.41)
[Execute command] Node v12.18.3
[Execute command] Finished running command
[Azure Blockchain] Deploy failed

```

- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

## Environment

* Operating System: Win 10
* Ethereum client:
* Truffle version (`truffle version`): Truffle v5.1.41 (core: 5.1.41)
* node version (`node --version`): Node v12.18.3
* npm version (`npm --version`): 6.14.6

**Comment by PingPongSet** [comment]
Is it possible to deploy it via other way, without using truffle command? For example, using VS IDE?

**Comment by gnidan** [comment]
Thanks for opening this @PingPongSet. Not sure what's going wrong, we'll have to try to reproduce on our side.

**Comment by haltman-at** [comment]
We suspect this is probably an issue with the VSCode extension.  We notice you opened an [issue](https://github.com/microsoft/vscode-azure-blockchain-ethereum/issues/61) there; could you repoen it perhaps?  Thank you!

**Comment by PingPongSet** [comment]
@haltman-at thanks!
