### ISSUE TITLE
truffle test hangs forever (develop:ipc:client error:  Error: connect ECONNREFUSED /tmp/truffle.test)

### ISSUE THREAD

**Issue by kevholder** [trufflesuite/truffle#3290]
- [ x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

truffle test hangs indefinitely with the default truffle-config.js and node v14+

## Steps to Reproduce

truffle init and truffle test

## Expected Behavior

Run tests.

## Actual Results

```
$ DEBUG=* truffle test

Secp256k1 bindings are not compiled. Pure JS implementation will be used.
Keccak bindings are not compiled. Pure JS implementation will be used.
Keccak bindings are not compiled. Pure JS implementation will be used.
Keccak bindings are not compiled. Pure JS implementation will be used.
Keccak bindings are not compiled. Pure JS implementation will be used.
Keccak bindings are not compiled. Pure JS implementation will be used.
Keccak bindings are not compiled. Pure JS implementation will be used.
Keccak bindings are not compiled. Pure JS implementation will be used.
Keccak bindings are not compiled. Pure JS implementation will be used.
  develop:ipc:client requested connection to  test /tmp/truffle.test +0ms
  develop:ipc:client Connecting client on Unix Socket : /tmp/truffle.test +0ms
  develop:ipc:client
  develop:ipc:client
  develop:ipc:client ######
  develop:ipc:client error:  Error: connect ECONNREFUSED /tmp/truffle.test
  develop:ipc:client     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  develop:ipc:client   errno: -61,
  develop:ipc:client   code: 'ECONNREFUSED',
  develop:ipc:client   syscall: 'connect',
  develop:ipc:client   address: '/tmp/truffle.test'
  develop:ipc:client } +4ms
  develop:ipc:client connection closed test /tmp/truffle.test 0 tries remaining of 0 +0ms
  develop:ipc:client mbp exceeded connection rety amount of  or stopRetrying flag set. +0ms
  develop:ipc:client requested connection to  test /tmp/truffle.test +0ms
  develop:ipc:client Connecting client on Unix Socket : /tmp/truffle.test +0ms
  develop:ipc:client
  develop:ipc:client
  develop:ipc:client ######
  develop:ipc:client error:  Error: connect ECONNREFUSED /tmp/truffle.test
  develop:ipc:client     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  develop:ipc:client   errno: -61,
  develop:ipc:client   code: 'ECONNREFUSED',
  develop:ipc:client   syscall: 'connect',
  develop:ipc:client   address: '/tmp/truffle.test'
  develop:ipc:client } +1ms
  develop:ipc:client connection closed test /tmp/truffle.test Infinity tries remaining of Infinity +0ms
  develop:ipc:client requested connection to  test /tmp/truffle.test +501ms
  develop:ipc:client Connecting client on Unix Socket : /tmp/truffle.test +0ms
  develop:ipc:client
  develop:ipc:client
```

## Environment

* Operating System:  macox 

```
truffle version; node --version; npm --version;
Truffle v5.1.41 (core: 5.1.41)
Solidity v0.5.16 (solc-js)
Node v14.5.0
Web3.js v1.2.1
v14.5.0
6.14.5
```

**Comment by gnidan** [comment]
Does `truffle develop` work for you?

**Comment by gnidan** [comment]
FYI Truffle doesn't support Node v14 yet

**Comment by codebam** [comment]
Thanks @gnidan. Switched to LTS and worked like a charm.

**Comment by fainashalts** [comment]
Glad it worked out @codebam! We're closing this for issue maintenance but feel free to open another issue if something comes up!
