### ISSUE TITLE
Permission Issues while Installing Truffle

### ISSUE THREAD

**Issue by abdullahbm09** [trufflesuite/truffle#3342]
**I am not able to install truffle even after upgrading node js and npm to v12 and v6 respectively. Can you kindly help**

abdullah@abdullah:~$ sudo npm install -g truffle
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
/home/abdullah/.npm-global/bin/truffle -> /home/abdullah/.npm-global/lib/node_modules/truffle/build/cli.bundled.js

> truffle@5.1.43 postinstall /home/abdullah/.npm-global/lib/node_modules/truffle
> node ./scripts/postinstall.js

Error: EACCES: permission denied, open '/home/abdullah/.config/truffle/config.json'
You don't have access to this file.

    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Configstore.get all [as all] (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/configstore/index.js:31:1)
    at new Configstore (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/configstore/index.js:25:31)
    at Function.getUserConfig (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:171:1)
    at Object.<anonymous> (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/packages/core/lib/mnemonics/mnemonic.js:11:1)
    at __webpack_require__ (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/develop.js:2:22)
    at __webpack_require__ (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/index.js:9:12)
    at __webpack_require__ (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/packages/core/cli.js:33:29)
    at __webpack_require__ (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at /home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/home/abdullah/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:89:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Error: Error while attempting to download and cache solc 0.5.16: Command failed: node ./build/cli.bundled.js obtain --solc=0.5.16
Error: EACCES: permission denied, open '/home/abdullah/.config/truffle/config.json'
You don't have access to this file.

    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Configstore.get all [as all] (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/configstore/index.js:31:1)
    at new Configstore (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/node_modules/configstore/index.js:25:31)
    at Function.getUserConfig (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:171:1)
    at Object.<anonymous> (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/packages/core/lib/mnemonics/mnemonic.js:11:1)
    at __webpack_require__ (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/develop.js:2:22)
    at __webpack_require__ (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/index.js:9:12)
    at __webpack_require__ (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at Object.<anonymous> (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/packages/core/cli.js:33:29)
    at __webpack_require__ (/home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at /home/abdullah/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/home/abdullah/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:89:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

    at postinstallObtain (/home/abdullah/.npm-global/lib/node_modules/truffle/scripts/postinstall.js:13:11)
    at Object.<anonymous> (/home/abdullah/.npm-global/lib/node_modules/truffle/scripts/postinstall.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/truffle/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ truffle@5.1.43
updated 1 package in 10.319s

**Comment by eggplantzzz** [comment]
Hey @abdullahbm09! You shouldn't install Truffle using `sudo`. The best solution I have found is to use/install npm with a version manager like nvm, and this is what npm itself recommends. Check out [this article from npm](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally).

Try re-installing npm with nvm and try again. It should resolve these types of issues.

**Comment by fainashalts** [comment]
This issue is a duplicate of #2127, we are closing this issue in favor of that one. Thanks for bringing this up @abdullahbm09, we will be working on a fix!
