### ISSUE TITLE
Unable to install truffle with npm on WSL

### ISSUE THREAD

**Issue by GitHubCloud** [trufflesuite/truffle#3347]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Unable to install truffle with npm on WSL

## Steps to Reproduce
```
root@Surface-Book-2:~# sudo npm install truffle -g
npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
/root/.nvm/versions/node/v12.18.2/bin/truffle -> /root/.nvm/versions/node/v12.18.2/lib/node_modules/truffle/build/cli.bundled.js

> truffle@5.1.43 postinstall /root/.nvm/versions/node/v12.18.2/lib/node_modules/truffle
> node ./scripts/postinstall.js

sh: 1: node: Permission denied
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/truffle/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! truffle@5.1.43 postinstall: `node ./scripts/postinstall.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the truffle@5.1.43 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-08T05_50_22_436Z-debug.log
```

here is full log
```
3891 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/truffle/node_modules/chokidar/node_modules/fsevents):
3892 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
3893 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
3893 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
3893 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
3893 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
3894 verbose stack Error: truffle@5.1.43 postinstall: `node ./scripts/postinstall.js`
3894 verbose stack spawn ENOENT
3894 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v12.18.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
3894 verbose stack     at ChildProcess.emit (events.js:315:20)
3894 verbose stack     at maybeClose (internal/child_process.js:1021:16)
3894 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
3895 verbose pkgid truffle@5.1.43
3896 verbose cwd /root
3897 verbose Linux 4.4.0-19041-Microsoft
3898 verbose argv "/root/.nvm/versions/node/v12.18.2/bin/node" "/usr/bin/npm" "install" "truffle" "-g"
3899 verbose node v12.18.2
3900 verbose npm  v6.14.5
3901 error code ELIFECYCLE
3902 error syscall spawn
3903 error file sh
3904 error errno ENOENT
3905 error truffle@5.1.43 postinstall: `node ./scripts/postinstall.js`
3905 error spawn ENOENT
3906 error Failed at the truffle@5.1.43 postinstall script.
3906 error This is probably not a problem with npm. There is likely additional logging output above.
3907 verbose exit [ 1, true ]
```

## Environment

* Operating System: Ubuntu 20.04 LTS **WSL** on Windows 10.0.19041
* Ethereum client: -
* Truffle version (`truffle version`): -
* node version (`node --version`): v12.18.2
* npm version (`npm --version`): 6.14.5

**Comment by eggplantzzz** [comment]
Just for completeness, from Gitter...
```
@GitHubCloud You should not use sudo to install Truffle. I recommend using nvm and using it with npm as npm recommends this. https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
Doing so should eliminate your permissions errors.
@swkim109 You could just remove it from your migrations. Usually the first migration file created is the one that migrates that file. I'm not sure what impact that will have on the rest of your project though as Truffle sometimes uses that contract for some things.
```

**Comment by GitHubCloud** [comment]
> Just for completeness, from Gitter...
> 
> ```
> @GitHubCloud You should not use sudo to install Truffle. I recommend using nvm and using it with npm as npm recommends this. https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
> Doing so should eliminate your permissions errors.
> ```

I'm originally used `npm install truffle -g`, but it didn't work, and the error above shows that is some permission denied error, so i'm adding `sudo` to try it out.

I've tried change npm's global directory, but it didn't work either.
Using yarn can install properly, so never mind with npm, thanks anyway.
