### ISSUE TITLE
Error: Could not create addresses from your mnemonic or private key(s)

### ISSUE THREAD

**Issue by tunkash** [trufflesuite/truffle#3424]
## Issue

Error: Could not create addresses from your mnemonic or private key(s). Please check that your inputs are correct.
    at new HDWalletProvider (D:\blockchain\tests\truffle\hd_wallet\node_modules\@truffle\hdwallet-provider\src\index.ts:121:13)
    at Object.provider (D:\blockchain\tests\truffle\hd_wallet\truffle-config.js:73:22)

got this error when running  truffle migrate --reset --network ropsten 
or just test  
```
new HDWalletProvider("mountains supernatural bird coffee monkey bulky build spark dog baseball fee exceed" ,"http://localhost:8545") 
```

from truffle console

## Steps to Reproduce

from truffle console:

```
const HDWalletProvider = require("@truffle/hdwallet-provider");

 new HDWalletProvider("mountains supernatural bird coffee monkey bulky build spark dog baseball fee exceed" ,"http://localhost:8545")
```

## Expected Behavior

No error to run:
`truffle migrate --reset --network ropsten`

or on truffle console to run this command:
```
 new HDWalletProvider("mountains supernatural bird coffee monkey bulky build spark dog baseball fee exceed" ,"http://localhost:8545")
```

## Actual Results

```
D:\blockchain\tests\truffle\hd_wallet\node_modules\@truffle\hdwallet-provider\dist\index.js:118
            throw new Error(`Could not create addresses from your mnemonic or private key(s). ` +
            ^

Uncaught:
Error: Could not create addresses from your mnemonic or private key(s). Please check that your inputs are correct.
    at new HDWalletProvider (D:\blockchain\tests\truffle\hd_wallet\node_modules\@truffle\hdwallet-provider\src\index.ts:121:13)
    at evalmachine.<anonymous>:0:1
    at sigintHandlersWrap (vm.js:272:15)
    at Script.runInContext (vm.js:127:14)
    at runScript (C:\Users\eric11\AppData\Local\Yarn\Data\global\node_modules\truffle\build\webpack:\packages\core\lib\console.js:227:1)
    at Console.interpret (C:\Users\eric11\AppData\Local\Yarn\Data\global\node_modules\truffle\build\webpack:\packages\core\lib\console.js:242:1)
    at ReplManager.interpret (C:\Users\eric11\AppData\Local\Yarn\Data\global\node_modules\truffle\build\webpack:\packages\core\lib\repl.js:129:1)
    at bound (domain.js:427:14)
    at REPLServer.runBound [as eval] (domain.js:440:12)
    at REPLServer.onLine (repl.js:760:10)
    at REPLServer.emit (events.js:315:20)
    at REPLServer.EventEmitter.emit (domain.js:483:12)
    at REPLServer.Interface._onLine (readline.js:329:10)
    at REPLServer.Interface._line (readline.js:658:8)
    at REPLServer.Interface._ttyWrite (readline.js:1003:14)
    at REPLServer.self._ttyWrite (repl.js:850:9)
    at ReadStream.onkeypress (readline.js:205:10)
    at ReadStream.emit (events.js:315:20)
    at ReadStream.EventEmitter.emit (domain.js:483:12)
    at emitKeys (internal/readline/utils.js:335:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (readline.js:1137:36)
```

## Environment

* Operating System: windows 10
* Ethereum client: local
* Truffle version (`5.1.43`):
* node version (`12.18.3`):
* npm version (`6.14.6`):

**Comment by eggplantzzz** [comment]
Hi @tunkash, I think your mnemonic is invalid. When I try to use it I receive a "Mnemonic invalid or undefined" error. Note that you cannot just use any 12 random words but rather they must have a certain format. Check that you have your mnemonic in the proper format. Also don't post your mnemonic here if it is something that you use for real as anyone will have access to your stuff! :)

**Comment by lukeshim** [comment]
I am getting the same error message. How is it that the mnemonic is "invalid"? What can we do to resolve this?

**Comment by eggplantzzz** [comment]
So here is the official spec for mnemonics https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

You can also find a nifty mnemonic code converter [here](https://iancoleman.io/bip39/)

**Comment by haltman-at** [comment]
Closing this for issue maintenance.
