### ISSUE TITLE
debugger v command throws an error inspecting solidity test transaction

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/truffle#3440]
Type error thrown when using v-command in debugger
```
// full snippet below
TypeError: Cannot read property 'kind' of undefined
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at DebugPrinter.printVariables (/home/amal/.nvm/versions/node/v10.22.1/lib/node_modules/truffle/build/webpack:/packages/core/lib/debug/printer.js:504:1)
```
## Versions
  Truffle (unbundled) (core: 5.1.48)
  Solidity - 0.7.3 (solc-js)
  Node v10.22.1
  Web3.js v1.2.1

## How to reproduce

  - clone [this repo](https://github.com/trufflesuite/webinar-episode-01) and switch to **repro/type-error** branch
  - You will need two terminals for this
  - Term1: `$ truffle develop`
  - Term2: `$ truffle develop --log`
    - Needed to grab the last transaction
  - Term1: `truffle(develop)> test`
  - Copy the last transaction from Term1 and then...
  - Term1: `truffle(develop)> debug <copied txn>`
  - Term1: `debug(develop:0xdec48beb...)> v`
  
###  Result
  
``` sh
truffle(develop)> debug 0xdec48beb5d34a540d7de7cec2db641e4ef05acd93246f4ca18562b66655086e3
Starting Truffle Debugger...

Addresses affected:
 0xE4C87EF3c3CEC158FA15243769B5c3a5E5cf88c8 - SimpleStorage
 0x193A098F6F537021b8CE948964c59Bcb9EF302e8(UNKNOWN)
 0x58774542423D3507429b09dC175E917f1E29ccd8(UNKNOWN)

Warning: The source code for one or more contracts could not be found.

Commands:
(enter) last command entered (step next)
(o) step over, (i) step into, (u) step out, (n) step next
(c) continue until breakpoint
(;) step instruction (include number to step multiple)
(p) print instruction & state (`p [mem|cal|sto]*`; see docs for more)
(l) print additional source context, (s) print stacktrace, (h) print this help
(q) quit, (r) reset, (t) load new transaction, (T) unload transaction
(b) add breakpoint (`b [[<source-file>:]<line-number>]`; see docs for more)
(B) remove breakpoint (similar to adding, or `B all` to remove all)
(+) add watch expression (`+:<expr>`), (-) remove watch expression (-:<expr>)
(?) list existing watch expressions and breakpoints
(v) print variables and values, (:) evaluate expression - see `v`


?:

1: // No source code found.

debug(develop:0xdec48beb...)> v

Solidity built-ins:
    msg: { data: hex'c1161cd6',
           sig: 0xc1161cd6,
           sender:
            0x41567405Ed4F3f408a7388a28B6e510BF70383eD,
           value: 0 }
     tx: { origin:
            0x41567405Ed4F3f408a7388a28B6e510BF70383eD,
           gasprice: 20000000000 }
  block: { coinbase:
            0x0000000000000000000000000000000000000000,
           difficulty: 0,
           gaslimit: 6721975,
           number: 135,
           timestamp: 1602803053 }
Thrown:
TypeError: Cannot read property 'kind' of undefined
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at DebugPrinter.printVariables (/home/amal/.nvm/versions/node/v10.22.1/lib/node_modules/truffle/build/webpack:/packages/core/lib/debug/printer.js:504:1)
    at Object.formatValue (/home/amal/.nvm/versions/node/v10.22.1/lib/node_modules/truffle/build/webpack:/packages/debug-utils/index.js:549:1)
    at Object.inspect (internal/util/inspect.js:189:10)
    at formatValue (internal/util/inspect.js:491:31)
    at ResultInspector.[nodejs.util.inspect.custom] (/home/amal/.nvm/versions/node/v10.22.1/lib/node_modules/truffle/build/webpack:/packages/codec/dist/lib/format/utils/inspect.js:68:1)
debug(develop:0xdec48beb...)>

```

**Comment by haltman-at** [comment]
OK, confirming I can reproduce the error.  Will need to see what's going on here.  Thanks!
