### ISSUE TITLE
Error: EPERM: operation not permitted, rename 'C:\Users\Kombo\.config\truffle\config.json.2536073666' -> 'C:\Users\Kombo\.config\truffle\config.json'

### ISSUE THREAD

**Issue by kombos** [trufflesuite/truffle#3443]
the following error comes up when i run 'npx truffle migrate --network ropsten' : 

```
Error: EPERM: operation not permitted, rename 'C:\Users\Kombo\.config\truffle\config.json.2536073666' -> 'C:\Users\Kombo\.config\truffle\config.json'
    at Object.renameSync (fs.js:734:3)
    at Function.writeFileSync [as sync] (C:\Users\Kombo\Code\EthFellas\codebase\node_modules\truffle\build\webpack:\node_modules\write-file-atomic\index.js:224:1)
    at Configstore.set all [as all] (C:\Users\Kombo\Code\EthFellas\codebase\node_modules\truffle\build\webpack:\node_modules\configstore\index.js:58:1)
    at new Configstore (C:\Users\Kombo\Code\EthFellas\codebase\node_modules\truffle\build\webpack:\node_modules\configstore\index.js:25:1)
    at Function.getUserConfig (C:\Users\Kombo\Code\EthFellas\codebase\node_modules\truffle\build\webpack:\packages\config\dist\index.js:171:1)
    at Function.getTruffleDataDirectory (C:\Users\Kombo\Code\EthFellas\codebase\node_modules\truffle\build\webpack:\packages\config\dist\index.js:174:1)
    at new LoadingStrategy (C:\Users\Kombo\Code\EthFellas\codebase\node_modules\truffle\build\webpack:\packages\compile-solidity\compilerSupplier\loadingStrategies\LoadingStrategy.js:18:1)
    at new VersionRange (C:\Users\Kombo\Code\EthFellas\codebase\node_modules\truffle\build\webpack:\packages\compile-solidity\compilerSupplier\loadingStrategies\VersionRange.js:10:1)
    at CompilerSupplier.load (C:\Users\Kombo\Code\EthFellas\codebase\node_modules\truffle\build\webpack:\packages\compile-solidity\compilerSupplier\index.js:65:1)
    at invokeCompiler (C:\Users\Kombo\Code\EthFellas\codebase\node_modules\truffle\build\webpack:\packages\compile-solidity\run.js:252:17)
    at run (C:\Users\Kombo\Code\EthFellas\codebase\node_modules\truffle\build\webpack:\packages\compile-solidity\run.js:29:40)
    at compile (C:\Users\Kombo\Code\EthFellas\codebase\node_modules\truffle\build\webpack:\packages\compile-solidity\legacy\index.js:31:1)
    at C:\Users\Kombo\Code\EthFellas\codebase\node_modules\truffle\build\webpack:\packages\compile-solidity\legacy\index.js:101:1
    at C:\Users\Kombo\Code\EthFellas\codebase\node_modules\truffle\build\webpack:\packages\compile-solidity\profiler\index.js:118:1
```

Truffle v5.1.33 (core: 5.1.33)
Node v12.18.1

**Comment by haltman-at** [comment]
This may be due to Windows Defender; it's known to cause sporadic errors for this.  Could you perhaps try this a second time and see if the results are any different?  Thanks!

**Comment by gnidan** [comment]
Closing this for issue maintenance, but do let us know if configuring Windows Defender differently doesn't help you. Thanks!

**Comment by thomasender** [comment]
Any advice on how to configure WindowsDefender so this error goes away? I am facing this error quite regularly during unit testing with truffle, 8 out of 10 times it will pass without a problem but this remaining 20 %, would just be very neat to get rid of it.

**Comment by psj900918** [comment]
I'm rushing into this, with few attempts, and think i found one of small clue,
that using shared drive (in my case Dropbox) could be an issue.
After using vanilla local storage, it now working again,
but i'll keep updated if this issue brings up again
