### ISSUE TITLE
truffle test on v5.1.50 does not work when using a Websocket provider

### ISSUE THREAD

**Issue by dstarke** [trufflesuite/truffle#3464]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

After upgrading to 5.1.50, Truffle does not work when configured to use a Websocket provider. 

## Steps to Reproduce

I have a project that was working correctly in 5.1.49. It is configured to use a Websocket provider. After upgrading to 5.1.50, it does not work. After changing the configuration to not use a Websocket provider, it works.

The failure occurs immediately when running `truffle test`.

## Expected Behavior

I expected the tests to run normally.

## Actual Results
(I've redacted my local path information with `...`)
```> Something went wrong while attempting to connect to the network. Check your network configuration.
ProviderError: 
    at .../node_modules/truffle/build/webpack:/packages/provider/wrapper.js:75:1
    at  .../node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
    at Object.callback ( .../node_modules/truffle/build/webpack:/packages/provider/wrapper.js:112:1)
    at  .../node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-ws/src/index.js:133:1
    at Array.forEach (<anonymous>)
    at WebsocketProvider._onMessage  (.../node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-ws/src/index.js:118:1)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] ( .../node_modules/truffle/build/webpack:/node_modules/yaeti/lib/EventTarget.js:115:1)
    at W3CWebSocket.onMessage ( .../node_modules/truffle/build/webpack:/node_modules/websocket/lib/W3CWebSocket.js:234:1)
    at WebSocketConnection.<anonymous> ( .../node_modules/truffle/build/webpack:/node_modules/websocket/lib/W3CWebSocket.js:205:1)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.processFrame ( .../node_modules/truffle/build/webpack:/node_modules/websocket/lib/WebSocketConnection.js:554:1)
    at  .../node_modules/truffle/build/webpack:/node_modules/websocket/lib/WebSocketConnection.js:323:34
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
Truffle v5.1.50 (core: 5.1.50)
Node v12.18.4
```

## Environment

* Operating System: MacOS 10.15.7
* Ethereum client: Truffle / Ganache
* Truffle version (`truffle version`): Truffle v5.1.50 (core: 5.1.50)
* node version (`node --version`): Node v12.18.4
* npm version (`npm --version`): 6.14.6

**Comment by dstarke** [comment]
After further investigation, this seems to be the result of a change in behavior in web3. In version 1.2.1 of Web3, the Websocket provider calls its callbacks with an `error` parameter of `null`. In 1.2.9, this parameter is passed as `false`. Truffle's provider wrapper tests against `null`: https://github.com/trufflesuite/truffle/blob/47686d9dedc3174e3133b89b3da9f4cd1d2eae82/packages/provider/wrapper.js#L73
Since `false` != `null`, the wrapper will now always throw a ProviderError.

**Comment by FortisFortuna** [comment]
Having the same issue

**Comment by eggplantzzz** [comment]
@dstarke Thanks for reporting this! I'll take a look and try and see if I can cook up a fix for this week's release!
