### ISSUE TITLE
Nonsensical "ProviderError: CONNECTION ERROR: Couldn't connect to node"

### ISSUE THREAD

**Issue by vporton** [trufflesuite/truffle#3645]
https://github.com/vporton/truffle-cannot-connect

Demonstrations of a Truffle bug:

```
npx ganache-cli -d  # in another terminal
npx truffle deploy --network local --reset
...
ProviderError: CONNECTION ERROR: Couldn't connect to node http://localhost:8545.
    at module.exports (/home/porton/Projects/bugs/truffle-cannot-connect/migrations/03_deploy_science.js:5:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration._deploy (/home/porton/Projects/bugs/truffle-cannot-connect/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:73:1)
    at Migration._load (/home/porton/Projects/bugs/truffle-cannot-connect/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:55:1)
    at Migration.run (/home/porton/Projects/bugs/truffle-cannot-connect/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:171:1)
    at Object.runMigrations (/home/porton/Projects/bugs/truffle-cannot-connect/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/home/porton/Projects/bugs/truffle-cannot-connect/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/home/porton/Projects/bugs/truffle-cannot-connect/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/home/porton/Projects/bugs/truffle-cannot-connect/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at runMigrations (/home/porton/Projects/bugs/truffle-cannot-connect/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:269:1)
    at /home/porton/Projects/bugs/truffle-cannot-connect/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:231:1
Truffle v5.1.59 (core: 5.1.59)
Node v12.16.2
```

**Comment by eggplantzzz** [comment]
Hey @vporton, looks like that error is coming from web3. Can you ensure that ganache-cli is running at that port? There may be something else running there and this error would occur if Truffle received some kind of a weird response from something else. 

Also, is there anything else to the error? If not can you post the message in its entirety?

**Comment by eggplantzzz** [comment]
Ok actually I located the error. In your second migrations file you use `deployer` in the place where an address should be for the `createOracle` function. You can't do this because `from` is expected to be an address while `deployer` is an object used for deploying. If you remove the argument from that function (or specify an address for `from` I presume) the error does not occur. Let me know if you are able to resolve this!

**Comment by gnidan** [comment]
Closing this for issue maintenance. Let us know if @eggplantzzz's solution doesn't work for you, and we can dig further. Thanks!
