### ISSUE TITLE
truffle debug: Compile your contracts...Error: ENOENT

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/truffle#3651]
Reproduction steps
  1. clone this [project](https://github.com/cds-amal/psychic-octo-parakeet)
  2. start `ganache-cli` in a separate terminal
  3. run the tests: `truffle test`
  4. grab a transaction from ganache's output
  5. run the debugger with the compile-tests flag: `truffle debug --compile-tests <txn>`

I was able to reproduce this on both WSL and Arch. See arch session below

```

$ use-truffle-core
$ lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

$ truffle version
Truffle (unbundled) (core: 5.1.60)
Solidity v0.5.16 (solc-js)
Node v10.22.1
Web3.js v1.2.9


$ truffle test

Compiling your contracts...
===========================
> Compiling ./contracts/Dummy.sol
> Compiling ./contracts/Migrations.sol
> Compiling ./test/TestDummy.sol
> Artifacts written to /tmp/test--7948-6Pksjlvts5pY
> Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang



  TestDummy
    ✓ testTargetIsInitialized (54ms)

  Contract: Dummy
    ✓ should assert true


  2 passing (4s)

$ truffle debug --compile-tests 0x38e676885fb0e18f2191d4bb3ae256ecd77d6cf827d7617369d94d59db03384f
Starting Truffle Debugger...
⠹ Compiling your contracts...Error: ENOENT: no such file or directory, scandir '/home/amal/dev/txlog/truffle-test-template/build/contracts'
    at Object.readdirSync (fs.js:790:3)
    at Truffle.<anonymous> (/home/amal/work/truffle/packages/resolver/lib/sources/truffle/index.ts:20:53)
    at Generator.next (<anonymous>)
    at fulfilled (/home/amal/work/truffle/packages/resolver/dist/lib/sources/truffle/index.js:5:58)
Truffle (unbundled) (core: 5.1.60)
Node v10.22.1

```

**Comment by haltman-at** [comment]
Thanks, I can now reproduce the problem!
