### ISSUE TITLE
Truffle init webpack does not work

### ISSUE THREAD

**Issue by Djuliuss** [trufflesuite/truffle#366]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

`truffle init webpack` does not work 

## Steps to Reproduce

```
mkdir foo
cd foo
truffle init webpack

```

## Expected Behavior

Initialization should suceed.

## Actual Results

I get the following error:

```
vagrant@vagrant-ubuntu-trusty-64:~/DAPPS$ mkdir foo
vagrant@vagrant-ubuntu-trusty-64:~/DAPPS$ cd foo
vagrant@vagrant-ubuntu-trusty-64:~/DAPPS/foo$ truffle init webpack
Downloading project...
Installing dependencies...
Error: Command failed: npm install babel-cli@^6.22.2 babel-core@^6.22.1 babel-eslint@^6.1.2 babel-loader@^6.2.10 babel-plugin-tra
nsform-runtime@^6.22.0 babel-preset-env@^1.1.8 babel-preset-es2015@^6.22.0 babel-register@^6.22.0 copy-webpack-plugin@^4.0.1 css-
loader@^0.26.1 eslint@^3.14.0 eslint-config-standard@^6.0.0 eslint-plugin-babel@^4.0.0 eslint-plugin-mocha@^4.8.0 eslint-plugin-p
romise@^3.0.0 eslint-plugin-standard@^2.0.0 html-webpack-plugin@^2.28.0 json-loader@^0.5.4 style-loader@^0.13.1 truffle-contract@
^1.1.6 web3@^0.18.2 webpack@^2.2.1 webpack-dev-server@^2.3.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (curre
nt: {"os":"linux","arch":"x64"})
npm WARN truffle-init-webpack@0.0.1 No repository field.
npm ERR! Linux 3.13.0-107-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "babel-cli@^6.22.2" "babel-core@^6.22.1" "babel-eslint@^6.1.2" "babel-lo
ader@^6.2.10" "babel-plugin-transform-runtime@^6.22.0" "babel-preset-env@^1.1.8" "babel-preset-es2015@^6.22.0" "babel-register@^6
.22.0" "copy-webpack-plugin@^4.0.1" "css-loader@^0.26.1" "eslint@^3.14.0" "eslint-config-standard@^6.0.0" "eslint-plugin-babel@^4
.0.0" "eslint-plugin-mocha@^4.8.0" "eslint-plugin-promise@^3.0.0" "eslint-plugin-standard@^2.0.0" "html-webpack-plugin@^2.28.0" "
json-loader@^0.5.4" "style-loader@^0.13.1" "truffle-contract@^1.1.6" "web3@^0.18.2" "webpack@^2.2.1" "webpack-dev-server@^2.3.0"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! path ../acorn/bin/acorn
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../acorn/bin/acorn' -> '/home/vagrant/DAPPS/foo/node_modules/.bin/acorn'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/DAPPS/foo/npm-debug.log

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

After doing some research I found this: npm/npm#12733 , which seems to be connected
Indeed, if I run the following : 

`sudo npm install --no-bin-links babel-cli@^6.22.2 babel-core@^6.22.1 babel-eslint@^6.1.2 babel-loader@^6.2.10 babel-plugin-transform-runtime@^6.22.0 babel-preset-env@^1.1.8 babel-preset-es2015@^6.22.0 babel-register@^6.22.0 copy-webpack-plugin@^4.0.1  css-loader@^0.26.1 eslint@^3.14.0 eslint-config-standard@^6.0.0 eslint-plugin-babel@^4.0.0 eslint-plugin-mocha@^4.8.0 eslint-plugin-promise@^3.0.0 eslint-plugin-standard@^2.0.0 html-webpack-plugin@^2.28.0 json-loader@^0.5.4 style-loader@^0.13.1 truffle-contract@^1.1.6 web3@^0.18.2 webpack@^2.2.1 webpack-dev-server@^2.3.0 `

it ends successfully. However, if try to run `truffle init webpack `after that, I get the same error again.

 

## Environment

* Operating System:  vagrant running on windows host
* Truffle version: 3.1.2.
* Ethereum client: -
* node version: 6.9.5
* npm version: 3.10.10

**Comment by Djuliuss** [comment]
OK, I have managed to make it work by moving the folder out of the shared folder within the Vagrant VM.

**Comment by tcoulter** [comment]
:+1: Interesting issue. Thanks for reporting.
