### ISSUE TITLE
global install of truffle results in Error: Cannot find module 'truffle-hdwallet-provider'

### ISSUE THREAD

**Issue by SvenMeyer** [trufflesuite/truffle#3708]
node --version v12.19.0

```
$ npm uninstall -g truffle
$ npm install -g truffle
/home/sum/.nvm/versions/node/v12.19.0/bin/truffle -> /home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/cli.bundled.js

> truffle@5.1.61 postinstall /home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle
> node ./scripts/postinstall.js

- Fetching solc version list from solc-bin. Attempt #1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/truffle/node_modules/chokidar/node_modules/fsevents):

...

+ truffle@5.1.62
added 143 packages from 62 contributors in 24.839s
```

```
$ truffle version
Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.
Error: Cannot find module 'truffle-hdwallet-provider'
Require stack:
- /home/sum/DEV/ETH/truffle-config.js
- /home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/node_modules/original-require/index.js
- /home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/cli.bundled.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sum/DEV/ETH/truffle-config.js:21:26)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at Object.require (internal/modules/cjs/helpers.js:74:18)
    at Function.load (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:161:1)
    at Function.detect (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:150:1)
    at Object.run (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/version.js:16:1)
    at Command.run (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
    at Object.<anonymous> (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/packages/core/cli.js:56:1)
    at __webpack_require__ (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at /home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/cli.bundled.js:89:10)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
Truffle v5.1.62 (core: 5.1.62)
Node v12.19.0

```

**Comment by fainashalts** [comment]
Hi @SvenMeyer it looks like you're requiring a module that isn't properly installed. The way we name the package now is `@truffle/hdwallet-provider`. You may need to change both the import and the reference in your `package.json`. It seems you have two truffle configuration files, so it is worth checking that they are both referring to the same package. But really you should prefer the `truffle-config` file, and it may be worth deleting the other file so there isn't any confusion. 

The important part is you should be installing the most current package and you should be consistent on the naming throughout your project. Can you try to make the change and see if it resolves your issue?

**Comment by gnidan** [comment]
Closing this for issue maintenance. Thanks for opening this! Let us know if there's anything else we can do to help; always happy to re-open this.

**Comment by 1anre** [comment]
Hi @SvenMeyer, did this work for you, were you able to proceed with your 'truffle develop' command successfully afterward?

How did you eventually resolve it?

**Comment by ExpandedMancho** [comment]
Hi @fainashalts I'm also unable to install `@truffle/hdwallet-provider` , in my case I'm getting the following error from console:
`npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent`

I have tried to check for all dependencies and installed one by one, however it still wouldn't install correctly.

I'm trying also to use `ethereumjs-wallet` instead of hdwallet-provider, but i'm unsure how to configurate the signing. Are you able to deploy to Ropsten networking using truffle?

Thanks!

**Comment by sivehost** [comment]
how does your package.json contents look like?
Try adding this inside the dependencies:   "@truffle/hdwallet-provider": "^1.0.17"
Then go to your command line and try installing it with this command: sudo npm install @truffle/hdwallet-provider
