### ISSUE TITLE
Debugger - TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/truffle#3713]
Couldn't step into some of the test transactions generated by a truffle project.

1. clone https://github.com/fodisi/hackapay
1. yarn
1. mv credentials-sample.js credentials.js
1. `truffle test test/factory/ContestTeamFactory.test.js`

One of those transactions fails when trying to step through.

## versions

my pc
```
$ truffle version
Truffle (unbundled) (core: 5.1.61)
Solidity v0.5.16 (solc-js)
Node v10.23.1
Web3.js v1.2.9
```

remote machine
```

$ truffle version
Truffle (unbundled) (core: 5.1.60)
Solidity v0.5.16 (solc-js)
Node v10.20.1
Web3.js v1.2.9
```

## session
```
$ truffle debug 0x46595a61841284e8c924a4cbcf9e2e87d5ac08a69859f75157ae51ae16838210
Starting Truffle Debugger...
✔ Compiling your contracts...
✔ Gathering information about your project and the transaction...

Addresses affected:
 0x359E769F88aC76D3fCd2a31ab7a2a05Db4058aC9 - ContestTeamFactory
 0xB495aE1b2e4590E0B05222eE9155571AD0155d29 - ContestTeam

Commands:
(enter) last command entered (step next)
(o) step over, (i) step into, (u) step out, (n) step next
(c) continue until breakpoint
(;) step instruction (include number to step multiple)
(g) turn on generated sources, (G) turn off generated sources except via `;`
(p) print instruction & state (`p [mem|cal|sto]*`; see docs for more)
(l) print additional source context, (s) print stacktrace, (h) print this help
(q) quit, (r) reset, (t) load new transaction, (T) unload transaction
(b) add breakpoint (`b [[<source-file>:]<line-number>]`; see docs for more)
(B) remove breakpoint (similar to adding, or `B all` to remove all)
(+) add watch expression (`+:<expr>`), (-) remove watch expression (-:<expr>)
(?) list existing watch expressions and breakpoints
(v) print variables and values, (:) evaluate expression - see `v`


ContestTeamFactory.sol:

 9:     @dev TODO: use struct to keep record of hackathon names, and allow implementing upgradability.
10:  */
11: contract ContestTeamFactory {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

debug(development:0x46595a61...)> c
⠋ Stepping...TypeError: Cannot read property 'start' of undefined
    at m.current.isSourceRangeFinalRaw (/home/amal/work/truffle/packages/debugger/lib/solidity/selectors/index.js:283:19)
    at /home/amal/work/truffle/node_modules/reselect/lib/index.js:76:25
    at /home/amal/work/truffle/node_modules/reselect/lib/index.js:36:25
    at /home/amal/work/truffle/node_modules/reselect/lib/index.js:90:33
    at Function.<anonymous> (/home/amal/work/truffle/node_modules/reselect/lib/index.js:36:25)
    at args (/home/amal/work/truffle/node_modules/reselect-tree/lib/index.js:85:1)
    at /home/amal/work/truffle/node_modules/reselect/lib/index.js:86:37
    at /home/amal/work/truffle/node_modules/reselect/lib/index.js:36:25
    at /home/amal/work/truffle/node_modules/reselect/lib/index.js:86:37
    at /home/amal/work/truffle/node_modules/reselect/lib/index.js:36:25
    at runSelectEffect (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:734:26)
    at runEffect (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
    at proc (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1112:3)
    at /home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:589:17
    at immediately (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:60:12)
    at runForkEffect (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:588:3)
    at runEffect (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
    at currCb (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at takeCb (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:507:5)
    at put (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:343:9)
    at Object.chan.put (/home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:375:7)
    at /home/amal/work/truffle/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1416:17
    at dispatch (/home/amal/work/truffle/node_modules/redux/lib/applyMiddleware.js:45:18)
    at /home/amal/work/truffle/node_modules/@redux-saga/core/dist/io-1d6eccda.js:137:12
The above error occurred in task _
    created by takeEvery(TRACE_TICK, _)
    created by data.C
    created by session.S
Tasks cancelled due to error:
takeEvery(TRACE_TICK, _)
T
evm.g
solidity.y
stacktrace.y
txlog.g
trace.y
controller.v
web3._
⠸ Stepping...

```

**Comment by haltman-at** [comment]
That's a lot of transactions to try out, so I had to go through them one-by-one to see which one causes the crash.  Fortunately I found it: It's the second-to-last one.  Possibly other ones as well, but definitely that one.  Anyway, now that I found the crashing transaction, I can actually see what's up with this...

**Comment by haltman-at** [comment]
Hm -- the issue seems to be that Solidity (0.5.16) is producing too short a source map, for some reason.  We'll have to figure out what to do about this...

**Comment by haltman-at** [comment]
Hm, actually that might not be the problem after all.  I'm going to have to look at this more...

**Comment by fodisi** [comment]
@haltman-at 
There's another branch in this project (`upgrade-solc`) where i upgraded the solidity pragma to `pragma solidity >=0.7.0 <0.8.0;
`. In the truffle-config file, the compiler version is set to `0.7.6`.

Would this help further check if it's really related to that specific solidity version?

Let me know if I can further help.
