### ISSUE TITLE
truffle console CRASH on start - trying to connect to local development network

### ISSUE THREAD

**Issue by SvenMeyer** [trufflesuite/truffle#3736]
trying to connect to Ganache GUI

```
$ truffle version
Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.
Truffle v5.1.63 (core: 5.1.63)
Solidity - 0.6.6 (solc-js)
Node v12.19.0
Web3.js v1.2.9
```

```
    development: {
     host: "127.0.0.1",     // Localhost (default: none)
     port: 8545,            // Standard Ethereum port (default: none)
     network_id: "*",       // Any network (default: none)
    },
```

```
$ truffle console --network development
Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.
truffle(development)> 
/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/index.js:31
    instance.address = contract.options.address;
^
TypeError: Cannot read property 'address' of undefined
    at TruffleContract.Contract (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/index.js:31:1)
    at new TruffleContract (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:231:1)
    at XMLHttpRequest._onHttpResponseData (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:304:1)
    at IncomingMessage.<anonymous> (/home/sum/.nvm/versions/node/v12.19.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:288:52)
    at IncomingMessage.emit (events.js:314:20)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.Readable.read (_stream_readable.js:508:10)
    at flow (_stream_readable.js:1008:34)
    at resume_ (_stream_readable.js:989:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

```

**Comment by eggplantzzz** [comment]
@SvenMeyer thanks for submitting this. Can you provide us with a project so we can try and reproduce this? Thanks!

**Comment by SvenMeyer** [comment]
https://github.com/SvenMeyer/lotto-chainlink

**Comment by eggplantzzz** [comment]
Hey again @SvenMeyer, I cloned your repo. I installed the deps via `npm i`, started up Ganache, then successfully used `truffle console --network development` to connect to Ganache. I did not get your error.

Can you give me really specific steps for recreating your error? Make sure Ganache is running at `http://127.0.0.1:8545`

**Comment by gnidan** [comment]
Closing for issue maintenance, but @SvenMeyer if you can get us specific reproduction steps, we'll reopen and see what we can figure out. Thank you!

**Comment by SvenMeyer** [comment]
Thanks for following up, but the current version of my repo is quite different now, so I wont be able to provide additional info to what I have provided back then ...
