### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object at validateString (internal/validators.js:125:11)

### ISSUE THREAD

**Issue by ArjunRajJain** [trufflesuite/truffle#3745]
Need some help running `truffle test`. The following is the output that occurs when it runs. 

Artifacts written to /var/folders/z1/r280806j5w30vqffcf71bv7m0000gn/T/test--63519-8wq5SeXnm7jD
Compiled successfully using:

solc: 0.7.6+commit.7338295f.Emscripten.clang
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
at validateString (internal/validators.js:125:11)
at Object.isAbsolute (path.js:1136:5)
at Function.detect (/Users/arjunjain/n/lib/node_modules/truffle/build/webpack:/packages/config/dist/index.js:140:1)
at Object.assemble (/Users/arjunjain/n/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:30:1)
at Object.runFrom (/Users/arjunjain/n/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:98:1)
at Object.runAll (/Users/arjunjain/n/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
at Object.run (/Users/arjunjain/n/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
at Object.performInitialDeploy (/Users/arjunjain/n/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:247:1)
at Object.run (/Users/arjunjain/n/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:107:1)
Truffle v5.1.63 (core: 5.1.63)
Node v10.16.3

**Comment by davidmurdoch** [comment]
Hey @ArjunRajJain, thanks for opening this issue. Could you provide us with reproduction steps or a project we can clone?

**Comment by ArjunRajJain** [comment]
Sure -> https://github.com/blockcollider/Emblem_Ethereum_Anchor
