### ISSUE TITLE
truffle tests not running after init

### ISSUE THREAD

**Issue by gagarin55** [trufflesuite/truffle#377]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
After truffle and testrpc reinstall `truffle test` doesn't work.
Other users have same problem: http://ethereum.stackexchange.com/questions/13294/some-truffle-tests-not-running-after-truffle-init-mac-osx-uncaught-typeerror

## Steps to Reproduce
`testrpc -l 0x88E7C4`

`mkdir prj1`

`cd prj1`

`truffle init`

`truffle test`

## Expected Behavior

tests OK

## Actual Results

```
  1) TestMetacoin testInitialBalanceUsingDeployedContract:
     Uncaught TypeError: Cannot read property '1' of undefined
      at /usr/local/lib/node_modules/truffle/node_modules/ethjs-abi/lib/index.js:139:34
      at Array.map (native)
      at Object.decodeEvent (/usr/local/lib/node_modules/truffle/node_modules/ethjs-abi/lib/index.js:138:6)
      at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:73:38
      at Array.map (native)
      at Object.decodeLogs (/usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:44:19)
      at Object.callback (/usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:172:35)
      at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/method.js:142:25
      at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:89:9
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:119:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:509:12)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:469:24)

  2) TestMetacoin testInitialBalanceWithNewMetaCoin:
     Uncaught TypeError: Cannot read property '1' of undefined
      at /usr/local/lib/node_modules/truffle/node_modules/ethjs-abi/lib/index.js:139:34
      at Array.map (native)
      at Object.decodeEvent (/usr/local/lib/node_modules/truffle/node_modules/ethjs-abi/lib/index.js:138:6)
      at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:73:38
      at Array.map (native)
      at Object.decodeLogs (/usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:44:19)
      at Object.callback (/usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:172:35)
      at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/method.js:142:25
      at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:89:9
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:119:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:509:12)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:469:24)

  3) Contract: MetaCoin should send coin correctly:
     Uncaught TypeError: Cannot read property '1' of undefined
      at /usr/local/lib/node_modules/truffle/node_modules/ethjs-abi/lib/index.js:139:34
      at Array.map (native)
      at Object.decodeEvent (/usr/local/lib/node_modules/truffle/node_modules/ethjs-abi/lib/index.js:138:6)
      at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:73:38
      at Array.map (native)
      at Object.decodeLogs (/usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:44:19)
      at Object.callback (/usr/local/lib/node_modules/truffle/node_modules/truffle-contract/contract.js:172:35)
      at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/method.js:142:25
      at /usr/local/lib/node_modules/truffle/node_modules/truffle-contract/node_modules/web3/lib/web3/requestmanager.js:89:9
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:119:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:509:12)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:469:24)


```

## Environment

* Operating System: 
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

* Truffle version:
$ truffle version
Truffle v3.1.2

* Ethereum client:
EthereumJS TestRPC v3.0.3

* node version:
$ node -v
v6.9.4

* npm version: 
$ npm -v
3.10.10

**Comment by tcoulter** [comment]
Hi there,

Thanks for reporting this. It looks like one of our dependencies (ethjs-abi) released a breaking change in a minor version bump, causing Truffle to fail. We've locked that dependency to a working version, so all should be fixed.

To fix your installation specifically, first uninstall Truffle then reinstall it. This will ensure you have the correct version of the dependency.

Thanks again!
