### ISSUE TITLE
Error: at Deployer._preFlightCheck

### ISSUE THREAD

**Issue by BringMaster** [trufflesuite/truffle#3791]
## Issue

Issue during the test.

## Steps to Reproduce

Clone https://github.com/BringMaster/FestivalCoin
`truffle test`

## Expected Behavior

```
Using network 'test'.


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



0 passing (1ms)

```
## Actual Results

```
Error: 
    at Deployer._preFlightCheck (/usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:179:1)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:282:1
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:55:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:171:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:109:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/test/index.js:165:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
```

## Environment

* Operating System: macOS Big Sur 11.2
* Truffle version (`truffle version`): Truffle v5.1.65 (core: 5.1.65)
* node version (`node --version`): Node v15.4.0
* npm version (`npm --version`): 7.5.3

**Comment by garysdevil** [comment]
I met this problem too.  How to solve it?
