### ISSUE TITLE
Truffle compile error with multiline imports

### ISSUE THREAD

**Issue by JChanceHud** [trufflesuite/truffle#3815]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Compilation fails as a result of an invalid regular expression.

## Steps to Reproduce

Running [these shell commands](https://gist.github.com/JChanceHud/fe72c6f923096638e54228c0630dccbb) will reproduce the error.

Specifically the error is occurring when compiling [this solidity code.](https://gist.github.com/JChanceHud/c96ced80122f515c556fd7b3b7e3bf58)

[This](https://github.com/trufflesuite/truffle/blob/develop/packages/compile-solidity/parser.js#L61) is the section of truffle throwing the error. This is the message that is output by solc (and then used to construct the regex). All the import statements in the error from solc have strange unicode characters at the beginning.

```
Source "(�aries/Types.sol" not found: Callback not supported. ParsedContract.sol:9:1: ParserError: Source "(�aries/Types.sol" not found: Callback not supported.
import {
^ (Relevant source part starts here and spans across multiple lines).
```

This issue is new with 5.1.66.

## Expected Behavior

The code compiles without error.

## Actual Results

```
SyntaxError: Invalid regular expression: /("|')(.*(�aries/Types.sol)("|')/: Unterminated group
    at new RegExp (<anonymous>)
    at /zkopru/node_modules/truffle/build/webpack:/packages/compile-solidity/parser.js:63:1
    at Array.map (<anonymous>)
    at Object.parseImports (/zkopru/node_modules/truffle/build/webpack:/packages/compile-solidity/parser.js:53:1)
    at parseImports (/zkopru/node_modules/truffle/build/webpack:/packages/compile-solidity/profiler/loadParser.js:24:1)
    at Object.<anonymous> (/zkopru/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/getImports.js:23:1)
    at Generator.next (<anonymous>)
    at /zkopru/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/getImports.js:8:1
    at new Promise (<anonymous>)
    at __awaiter (/zkopru/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/getImports.js:4:1)
    at Object.getImports (/zkopru/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/getImports.js:19:1)
    at /zkopru/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/resolveAllSources.js:58:1
    at Generator.next (<anonymous>)
    at fulfilled (/zkopru/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/resolveAllSources.js:5:42)
Truffle v5.1.66 (core: 5.1.66)
Node v14.14.0
error Command failed with exit code 1.
```

## Environment

* Operating System: docker `node:14.14-buster-slim`
* Ethereum client:
* Truffle version (`truffle version`): 5.1.66
* node version (`node --version`): 14.14.0
* npm version (`npm --version`): yarn v1.22.5

**Comment by haltman-at** [comment]
I'm pretty sure this is the same issue as #3799.  There's already a PR merged to fix it which should go out in tomorrow's release.  Still, thanks for the report!

**Comment by JChanceHud** [comment]
Ah, thanks for the heads up! I'll reopen if the next release doesn't fix.
