### ISSUE TITLE
Truffle cant find hd-wallet module 

### ISSUE THREAD

**Issue by adeolu98** [trufflesuite/truffle#3865]
**## Issue**

hi, ive run into some issues with truffle on my windows pc, i am trying to use truffle/hdwallet-provider to deploy my contracts to kovan but truffle keeps returning the error code ''truffle/hdwallet-provider module not found''. I have installed truffle/hdwallet-provider globally and locally in the project folder but still doesnt work. Does anyone know what other ways i can use to solve this?
besides i have deployed to ropsten and the mainnet in the past with truffle/hdwallet working fine. dont know why its acting up now

## Steps to Reproduce

i did a 'truffle deploy --network kovan'

**## Expected Behavior**

My smart contracts are supposed to deploy but they dont.

**## Actual Results**

this was how i defined hdwallet in my truffle config file: var HDWalletProvider = require("@truffle/hdwallet-provider") ;
then it returns this error message 

Error: Cannot find module '@truffle/hdwallet-provider'
Require stack:
- C:\Users\HP\Desktop\fireTokenDapp\FireToken\truffle-config.js
- C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\node_modules\original-require\index.js
- C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\HP\Desktop\fireTokenDapp\FireToken\truffle-config.js:1:24)     
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Object.require (internal/modules/cjs/helpers.js:88:18)
    at Function.load (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\config\dist\index.js:161:1)
    at Function.detect (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\config\dist\index.js:150:1)
    at Object.run (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:199:1)
    at Command.run (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command.js:136:1)
    at Object.<anonymous> (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\cli.js:57:1)
    at __webpack_require__ (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap:19:1)
    at C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap:83:1  
    at Object.<anonymous> (C:\Users\HP\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:89:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
Truffle v5.1.66 (core: 5.1.66)
Node v14.15.0

**## Environment**

* Operating System: windows 10
* Ethereum client: infura/ kovan testnet
* Truffle version (`v5.1.66 (core: 5.1.66)`):
* node version ('v14.15.0'):
* npm version (`7.5.4`):

**Comment by haltman-at** [comment]
Hi, are you sure you correctly installed the package `@truffle/hdwallet-provider`?  I ask because you sometimes refer to it as `truffle/hdwallet-provider`, so I want to be sure that you installed the correct package (which includes the `@`).

Alternatively, is your project uploaded somewhere where we chould check it out?  Thank you!

**Comment by eggplantzzz** [comment]
I am closing this for issue maintenance. Feel free to open this again if you are still experiencing issues.
