### ISSUE TITLE
I got some err msg when I truffle migrate 

### ISSUE THREAD

**Issue by trybye** [trufflesuite/truffle#3921]
```
truffle migrate --network test --reset

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'test'
> Network id:      65
> Block gas limit: 4294967295 (0xffffffff)


1_upgrade1.js
=============

   Deploying 'Master'
   ------------------
   > transaction hash:    0xccc76cad0bbeb05265204d6728650d5aa957f04f0c4263b681ab512b24763793
   ⠦ Blocks: 1            Seconds: 8
/Volumes/Untitled/contract/node_modules/graceful-fs/polyfills.js:299
        if (cb) cb.apply(this, arguments)
                   ^
Error: Unable to update lock within the stale threshold
    at /Volumes/Untitled/contract/node_modules/proper-lockfile/lib/lockfile.js:136:25
    at callback (/Volumes/Untitled/contract/node_modules/graceful-fs/polyfills.js:299:20)
    at FSReqCallback.oncomplete (fs.js:184:5)

```
## Environment

Truffle v5.1.37 (core: 5.1.37)
Solidity - 0.6.12 (solc-js)
Node v14.16.0
Web3.js v1.2.1

**Comment by eggplantzzz** [comment]
Hey @trybye, I've never seen this error before. Are you able to provide some code and specific reproduction steps so that we can take a look?

**Comment by gnidan** [comment]
Closing for issue maintenance. If you still have this problem, please let us know so we can re-open and try to diagnose.
