### ISSUE TITLE
Truffle migrate failure

### ISSUE THREAD

**Issue by f117f117f117677** [trufflesuite/truffle#393]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Coming to truffle migrate on following Getting Started in docs, 

Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:414:24)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)

## Steps to Reproduce
Just follow the getting started

[done] install truffle and testrpc
[done] create a project
[done] compiling

## Environment

* Operating System:  mac os
* Truffle version:  install from node.js 6.10.2
* Ethereum client: Ethereumjs  testrpc
* node version: 6.10.2
* npm version: 3.10.10

**Comment by f117f117f117677** [comment]
Hi guys

I figure it out.  The reason is because no Ethereum client is running. we just need to run testrpc in another terminal.

`username@workstation$ testrpc -a`
