### ISSUE TITLE
@truffle/hdwallet-provider broken after v1.2.3 for truffle migrations

### ISSUE THREAD

**Issue by miguelmtzinf** [trufflesuite/truffle#3946]
## Issue

After @truffle/hdwallet-provider@1.2.3, truffle migration does not work perfectly.
 

## Steps to Reproduce

When migrating a simple box (I used [mine](https://www.github.com/miguelmartinezinf/hdw-metacoin-box/tree/main/)) does not work well... It seems making an `eth_call` instead an `eth_sendTransaction`.

```
$ truffle migrate --reset --verbose-rpc

Compiling your contracts...
===========================
✔ Fetching solc version list from solc-bin. Attempt #1
✔ Downloading compiler. Attempt #1.
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'development'
> Network id:      2018
> Block gas limit: 16234336 (0xf7b760)


2_deploy.js
===========

   Replacing 'Simple'
   ------------------
   > {
   >   "jsonrpc": "2.0",
   >   "method": "eth_call",
   >   "params": [
   >     {
   >       "from": "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73",
   >       "gas": "0x6691b7",
   >       "gasPrice": "0x4a817c800",
   >       "data": "0x60806040526040805190810160405280600c81526020017f68656c6c6f20776f726c642100000000000000000000000000000000000000008152506000908051906020019061004f929190610062565b5034801561005c57600080fd5b50610107565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106100a357805160ff19168380011785556100d1565b828001600101855582156100d1579182015b828111156100d05782518255916020019190600101906100b5565b5b5090506100de91906100e2565b5090565b61010491905b808211156101005760008160009055506001016100e8565b5090565b90565b610410806101166000396000f300608060405260043610610057576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806319ff1d211461005c5780634ed3885e146100ec5780636d4ce63c14610155575b600080fd5b34801561006857600080fd5b506100716101e5565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156100b1578082015181840152602081019050610096565b50505050905090810190601f1680156100de5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b3480156100f857600080fd5b50610153600480360381019080803590602001908201803590602001908080601f0160208091040260200160405190810160405280939291908181526020018383808284378201915050505050509192919290505050610283565b005b34801561016157600080fd5b5061016a61029d565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156101aa57808201518184015260208101905061018f565b50505050905090810190601f1680156101d75780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b60008054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561027b5780601f106102505761010080835404028352916020019161027b565b820191906000526020600020905b81548152906001019060200180831161025e57829003601f168201915b505050505081565b806000908051906020019061029992919061033f565b5050565b606060008054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156103355780601f1061030a57610100808354040283529160200191610335565b820191906000526020600020905b81548152906001019060200180831161031857829003601f168201915b5050505050905090565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061038057805160ff19168380011785556103ae565b828001600101855582156103ae579182015b828111156103ad578251825591602001919060010190610392565b5b5090506103bb91906103bf565b5090565b6103e191905b808211156103dd5760008160009055506001016103c5565b5090565b905600a165627a7a72305820b5793504f55edb9e4f3393e0779842ddae37937a1e128726e2e05587705cf6ba0029",
   >       "chainId": "0x7e2"
   >     },
   >     "latest"
   >   ],
   >   "id": 1616586757215
   > }

Error:  *** Deployment Failed ***

"Simple" -- Internal error.

    at /home/miki/.nvm/versions/node/v12.20.1/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration._deploy (/home/miki/.nvm/versions/node/v12.20.1/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:74:1)
    at Migration._load (/home/miki/.nvm/versions/node/v12.20.1/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:61:1)
    at Migration.run (/home/miki/.nvm/versions/node/v12.20.1/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:212:1)
    at Object.runMigrations (/home/miki/.nvm/versions/node/v12.20.1/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/home/miki/.nvm/versions/node/v12.20.1/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/home/miki/.nvm/versions/node/v12.20.1/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/home/miki/.nvm/versions/node/v12.20.1/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at runMigrations (/home/miki/.nvm/versions/node/v12.20.1/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:263:1)
    at Object.run (/home/miki/.nvm/versions/node/v12.20.1/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:228:1)
    at Command.run (/home/miki/.nvm/versions/node/v12.20.1/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
Truffle v5.2.5 (core: 5.2.5)
Node v12.20.1
```

**Comment by lolieatapple** [comment]
@truffle/hdwallet-provider v1.2.4 can not work. I got a error: { code: -32000, message: 'invalid sender' }, even I support chainId, but it not works.

@truffle/hdwallet-provider v1.2.2 is good to work.

I print the log of txParams and tx.
In 1.2.2 good is:
```
{ from: '0x4cf0a877e906dead748a41ae7da8c220e4247d9e',
  gas: '0x1e8480',
  gasPrice: '0x4a817c800',
  chainId: '0x61',
  nonce: '0x7' } Transaction {
  raw:
   [ <Buffer 07>,
     <Buffer 04 a8 17 c8 00>,
     <Buffer 1e 84 80>,
     <Buffer >,
     <Buffer >,
     <Buffer 60 80 60 40 52 34 80 15 61 00 10 57 60 00 80 fd 5b 50 61 18 5b 80 61 00 20 60 00 39 60 00 f3 fe 60 80 60 40 52 60 04 36 10 61 01 0f 57 60 00 35 7c 01 ... >,
     <Buffer e5>,
     <Buffer 1b 1f 39 40 b8 c3 23 77 3a 0e 0b 3a 1a 59 89 e8 dc 3b a5 de c1 67 05 25 02 79 4e 04 4f 27 57 a9>,
     <Buffer 52 d0 03 aa 8d 3e 17 d1 19 4f a0 db c1 06 b4 f4 18 b6 4b 40 18 cf 6a 19 65 18 b0 48 8e aa 03 63> ],
  _fields:
   [ 'nonce',
     'gasPrice',
     'gasLimit',
     'to',
     'value',
     'data',
     'v',
     'r',
     's' ],
  toJSON: [Function],
  serialize: [Function: serialize],
  nonce: [Getter/Setter],
  gasPrice: [Getter/Setter],
  gasLimit: [Getter/Setter],
  to: [Getter/Setter],
  value: [Getter/Setter],
  data: [Getter/Setter],
  v: [Getter/Setter],
  r: [Getter/Setter],
  s: [Getter/Setter],
  from: [Getter],
  _chainId: '0x61',
  _homestead: true }
```

In 1.2.4 bad is:
```
{ from: '0x4cf0a877e906dead748a41ae7da8c220e4247d9e',
  to: '0x4cf0a877e906dead748a41ae7da8c220e4247d9e',
  value: '0x1',
  gasPrice: '0x4a817c800',
  gas: '0x7530',
  data: '0x',
  chainId: '0x61',
  nonce: '0x6' } Transaction {
  nonce: <BN: 6>,
  gasPrice: <BN: 4a817c800>,
  gasLimit: <BN: 0>,
  to:
   Address {
     buf:
      <Buffer 4c f0 a8 77 e9 06 de ad 74 8a 41 ae 7d a8 c2 20 e4 24 7d 9e> },
  value: <BN: 1>,
  data: <Buffer >,
  v: undefined,
  r: undefined,
  s: undefined,
  common:
   Common {
     _events: [Object: null prototype] {},
     _eventsCount: 0,
     _maxListeners: undefined,
     _supportedHardforks: [],
     _eips: [],
     _customChains: [],
     _chainParams:
      { name: 'mainnet',
        chainId: 1,
        networkId: 1,
        defaultHardfork: 'istanbul',
        consensus: [Object],
        comment: 'The Ethereum main chain',
        url: 'https://ethstats.net/',
        genesis: [Object],
        hardforks: [Array],
        bootstrapNodes: [Array],
        dnsNetworks: [Array] },
     DEFAULT_HARDFORK: 'istanbul',
     _hardfork: 'istanbul' } }
```

It has a bad tx after const tx = new ethereumjs_tx_1.default(txParams);

If you have the same problem, I recommend you use version 1.2.2 first.

**Comment by gabmontes** [comment]
Starting with 1.2.4 all transactions fail with "Error: Invalid Signature". Reverting to 1.2.3 solves the problem.

**Comment by eggplantzzz** [comment]
We released [v5.3.0](https://github.com/trufflesuite/truffle/releases/tag/v5.3.0) which has some changes that I think may have fixed this issue. Can someone test it out and confirm/deny that this is fixed?

**Comment by miguelmtzinf** [comment]
Not working with `truffle@5.3.0` and `@truffle/hdwallet-provider@1.2.6`

`Error: Unknown arguments format passed to new HDWalletProvider. Please check your configuration and try again
    at Object.exports.getOptions (/Users/miki/miki/tmp/hdw-metacoin-box/node_modules/@truffle/hdwallet-provider/src/constructor/getOptions.ts:141:11)
    at new HDWalletProvider (/Users/miki/miki/tmp/hdw-metacoin-box/node_modules/@truffle/hdwallet-provider/src/index.ts:53:9)
    at Object.<anonymous> (/Users/miki/miki/tmp/hdw-metacoin-box/truffle.js:15:17)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at Object.require (node:internal/modules/cjs/helpers:92:18)`


Using this network settings:
`    simpleprivatenetwork: {
      provider: new HDWalletProvider(mnemonicPhrase, "http://localhost:8545"),
      network_id: "999",
      gas: "6721975",
      gasPrice: "0"
    },
    privatenetwork: {
      provider: () =>
        new HDWalletProvider({
          mnemonic: mnemonicPhrase,
          providerOrUrl: "http://localhost:8545",
          addressIndex: 0,
          numberOfAddresses: 1
        }),
      network_id: "999",
      gas: "6721975",
      gasPrice: "0"
    }
`

**Comment by nkuba** [comment]
Worked fine with `"@truffle/hdwallet-provider": "1.2.6"` and `"truffle": "5.3.0"`.
Provider config:
```js
      provider: function () {
        return new HDWalletProvider({
          privateKeys: [PRIVATE_KEY],
          providerOrUrl: ETH_HOSTNAME,
        })
      },
```

**Comment by eggplantzzz** [comment]
@miguelmtzinf Can you post your entire error message? That looks like an unrelated issue at first glance. Thanks @nkuba for the confirmation!

**Comment by cds-amal** [comment]
Hi everyone, please try `@truffle/hdwallet-provider` (v1.4.0). We think this should resolve the issue. Please let us know if this is not the case.

**Comment by cds-amal** [comment]
Closing this for issue maintenance. Please comment if you'd like us to revisit
