### ISSUE TITLE
migration shlowing error

### ISSUE THREAD

**Issue by coderbang1** [trufflesuite/truffle#3953]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

migration is not working

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

it should migrate to ganache

## Actual Results

Error parsing F:/nft/contracts/contracts/Migrations.sol: Cannot read property 'addFunction' of undefined
at runWithReadCallback (F:\node\node_modules\truffle\build\webpack:\~\solc\wrapper.js:37:1)
    at compileStandard (F:\node\node_modules\truffle\build\webpack:\~\solc\wrapper.js:78:1)
    at Object.compileStandardWrapper (F:\node\node_modules\truffle\build\webpack:\~\solc\wrapper.js:85:1)
    at Object.parseImports (F:\node\node_modules\truffle\build\webpack:\packages\truffle-compile\parser.js:47:1)
    at Object.getImports (F:\node\node_modules\truffle\build\webpack:\packages\truffle-compile\profiler.js:374:1)
    at F:\node\node_modules\truffle\build\webpack:\packages\truffle-compile\profiler.js:346:1

## Environment

* Operating System: windos 10
* Ethereum client: Ganache
* Truffle version (`truffle version`):Truffle v5.0.5 (core: 5.0.5)
* node version (`node --version`):Node v14.16.0
* npm version (`npm --version`): 6.14.11

**Comment by eggplantzzz** [comment]
Can you provide us with a project and specific steps to recreate this error? That would help us a lot to troubleshoot this!

**Comment by coderbang1** [comment]
i have solve the issue  by updating
