### ISSUE TITLE
Error Migrating private chain

### ISSUE THREAD

**Issue by Jacodelange** [trufflesuite/truffle#398]
---------------------------

## Issue

When I use truffle migrate on private chain, I receive the error: Error: Invalid sender. On the testrpc it works.

## Steps to Reproduce

Genesis file for chain:

`{
    "config": {
        "chainId": 0,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
          "alloc": {},
  "coinbase"   : "0x0000000000000000000000000000000000000000",
  "difficulty" : "0x20000",
  "extraData"  : "",
  "gasLimit"   : "0x2fefd8",
  "nonce"      : "0x0000000000000042",
  "mixhash"    : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp"  : "0x00"

}
`
Then used geth --datadir ChainData init genenis.json
Then started the chain with: geth --datadir ChainData --networkid 45600 --verbosity 3 -ipcdisable --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "*" --port 30301 --rpcport 8545 --nodiscover console

Created an account with personal.newAccount("1234")
Unlocked account personal.unlockAccount(eth.accounts[0],"1234")

In new folder, used truffle init, truffle compile and then truffle migrate.

## Expected Behavior

On the testrpc chain the contracts migrate successfully. 

## Actual Results

Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Invalid sender
    at Object.InvalidResponse (/usr/lib/node_modules/truffle/node_modules/web3/lib/web3/errors.js:35:16)
    at /usr/lib/node_modules/truffle/node_modules/web3/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)

## Environment

* Operating System: Ubuntu 16.04 LTS
* Truffle version: v3.2.2
* Ethereum client: 1.6.1 stable
* node version: v6.10.3
* npm version:  3.10.10

**Comment by mr8q9wp** [comment]
I am getting the same problem. @Jacodelange , were you able to fix it or find something else that worked for you? Thanks!

**Comment by Jacodelange** [comment]
@mr8q9wp No I wasn't able to fix this issue, I had to downgrade to previous version of Geth. I think truffle and the new Geth doesn't work together correctly.

**Comment by lorepieri8** [comment]
Same here:
`Running migration: 1_initial_migration.js
  Deploying Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: exceeds block gas limit
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:36916:16)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:217494:36
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:216273:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:218146:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:218436:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:218591:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:218551:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)`

**Comment by zhifeiji** [comment]
the same problem.

**Comment by phroiland** [comment]
So did downgrading to previous version of geth work? Or are we stuck using testrpc for now?

**Comment by aaqib90** [comment]
Any solution?

**Comment by dcnl1980** [comment]
I think it a problem of Truffle. Yesterday I compiled contracts without any problem. Today I tried to migrate and deploy and get the same errors on Testnet Ropsten. So I was thinking, okey Ropsten have a problem, so I also installed TestRPC, same result. So Truffle tell me why it's not working now!
