### ISSUE TITLE
truffle/HDWalletProvider v1.3.0 doesn't work for Binance Smart Chain Testnet. 

### ISSUE THREAD

**Issue by nicezic0** [trufflesuite/truffle#4010]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

truffle/HDWalletProvider v1.3.0 doesn't work for Binance Smart Chain Testnet. 

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.
. install HDWalletProvider@1.3.0 ( latest )
. deploy to Binance Smart Chain Testnet ( failed )
. install HDWalletProvider@1.2.6
. deploy to Binance Smart Chain Testnet ( worked )

## Expected Behavior

HDWalletProvider@1.3.0 should also work out.

## Actual Results

```
> yarn upgrade @truffle/hdwallet-provider@latest
...
[4/4] Rebuilding all packages...
success Saved lockfile.
warning No license field
success Saved 1 new dependency.
info Direct dependencies
└─ @truffle/hdwallet-provider@1.3.0
info All dependencies
└─ @truffle/hdwallet-provider@1.3.0

> truffle.cmd migrate --reset --network bsctest

Compiling your contracts...
===========================
√ Fetching solc version list from solc-bin. Attempt #1
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'bsctest'
> Network id:      97
> Block gas limit: 30000000 (0x1c9c380)


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- invalid sender.

    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Migration._deploy (C:\Users\yhpark\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:74:1)
    at Migration._load (C:\Users\yhpark\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:61:1)
    at Migration.run (C:\Users\yhpark\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:212:1)
    at Object.runMigrations (C:\Users\yhpark\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:150:1)
    at Object.runFrom (C:\Users\yhpark\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:110:1)
    at Object.runAll (C:\Users\yhpark\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:114:1)
    at Object.run (C:\Users\yhpark\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:79:1)
    at runMigrations (C:\Users\yhpark\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:263:1)
    at Object.run (C:\Users\yhpark\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:228:1)
    at Command.run (C:\Users\yhpark\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command.js:140:1)
Truffle v5.3.3 (core: 5.3.3)
Node v14.16.1
> yarn upgrade @truffle/hdwallet-provider@1.2.6
yarn upgrade v1.22.10
...
info Direct dependencies
└─ @truffle/hdwallet-provider@1.2.6
info All dependencies
└─ @truffle/hdwallet-provider@1.2.6
Done in 1.14s.
PS C:\work\first-bnb> truffle.cmd migrate --reset --network bsctest 

Compiling your contracts...
===========================
√ Fetching solc version list from solc-bin. Attempt #1
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'bsctest'
> Network id:      97
> Block gas limit: 30000000 (0x1c9c380)


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------
   > transaction hash:    0xf7eec17ca8b8f57a984f4906ffe10ef8b9a3ff6462953deef57f8116f90cc1c1
   > Blocks: 2            Seconds: 9
   > contract address:    0x7b70A309e88c9CfABf3ABff6214F9e955F773c9a
   > block number:        8365390
   > block timestamp:     1619586361
   > account:             0x85Cc4aA3c32Bde305CD9C5dd3d2a4d40A5C39efF
   > balance:             7.16218322
   > gas used:            246904 (0x3c478)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00493808 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00493808 ETH


2_deploy_contracts.js
=====================

   Replacing 'MyContract'
   ----------------------
   > transaction hash:    0xdd613f6614460fce0372020c1d3b9a6611cae1828f867ef9c9a5bdfa9bab83ac
   > Blocks: 2            Seconds: 5
   > contract address:    0xF2aae9fabb22aAf852595544E9B592C3cF4E9390
   > block number:        8365396
   > block timestamp:     1619586379
   > account:             0x85Cc4aA3c32Bde305CD9C5dd3d2a4d40A5C39efF
   > balance:             7.15530878
   > gas used:            301209 (0x49899)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00602418 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00602418 ETH


Summary
=======
> Total deployments:   2
> Final cost:          0.01096226 ETH
```

## Environment

* Operating System: Win 10
* Ethereum client: Binance Smart Chain Testnet ( https://data-seed-prebsc-2-s3.binance.org:8545/ )
* Truffle version (`truffle version`): Truffle v5.3.3 (core: 5.3.3)
* node version (`node --version`): v14.16.1
* npm version (`npm --version`): yarn v1.22.10

### truffle-config.js
```
const provider = new HDWalletProvider(
  [process.env.MY_PRIVATE_KEY],
  'https://data-seed-prebsc-2-s3.binance.org:8545/',
  0, 1
);

  networks: {
    bsctest: {
      provider: () => provider,
      network_id: "97",
      gas: 1000000
    }
```

**Comment by davidmurdoch** [comment]
Thanks for opening this issue, @nicezic0. Let's track this over in #4000.

**Comment by nicezic0** [comment]
> 
> 
> Thanks for opening this issue, @nicezic0. Let's track this over in #4000.

Thanks a lot!

**Comment by gianlucamazza** [comment]
do you have any temporary solution? I'm stuck on this error too: 

"Migrations" -- invalid sender.

bsc_testnet: {
      provider: () => new HDWalletProvider({
        mnemonic: mnemonic,
        providerOrUrl: "https://data-seed-prebsc-1-s1.binance.org:8545",
        chainId: 42
      }),
      network_id: 97,
      confirmations: 10,
      timeoutBlocks: 200,
      skipDryRun: true,
      websockets: true
    }
    
What chainId should we use?

**Comment by nicezic0** [comment]
> 
> 
> do you have any temporary solution? I'm stuck on this error too:
> 
> "Migrations" -- invalid sender.
> 
> bsc_testnet: {
> provider: () => new HDWalletProvider({
> mnemonic: mnemonic,
> providerOrUrl: "https://data-seed-prebsc-1-s1.binance.org:8545",
> chainId: 42
> }),
> network_id: 97,
> confirmations: 10,
> timeoutBlocks: 200,
> skipDryRun: true,
> websockets: true
> }
> 
> What chainId should we use?

just use @truffle/hdwallet-provider@1.2.6 instead of latest.
