### ISSUE TITLE
truffle migrate  Error: invalid sender.How to solve this problem? thanks.

### ISSUE THREAD

**Issue by ouxiaobai** [trufflesuite/truffle#4032]
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: invalid sender
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:225:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by cds-amal** [comment]
Hi @ouxiabai,

Can you update to the `@truffle/hdwallet-provider` (v1.4.0)? We think this should resolve the problem. Please let us know.

**Comment by ouxiaobai** [comment]
> Hi @ouxiabai,
> 
> Can you update to the `@truffle/hdwallet-provider` (v1.4.0)? We think this should resolve the problem. Please let us know.

sorry,I am using it on my private chain.

**Comment by fainashalts** [comment]
Hi @ouxiaobai you should still be able to upgrade `@truffle/hdwallet-provider` to v1.4.0. This version specifically addresses the known issue with private chains. Please let us know if that works out! Thanks!

**Comment by gnidan** [comment]
Closing for issue maintenance. @ouxiaobai let us know if you had trouble with that upgrade and we'll see what we can do about it. Thanks!
