### ISSUE TITLE
@truffle/hdwallet-provider ChainID limitation.  "Chain with ID  not supported" when connect to private geth networks

### ISSUE THREAD

**Issue by dorinburcea** [trufflesuite/truffle#4056]
- [x ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Hello I get **truffle migrate** command error:  "Chain with ID  not supported" when use module **@truffle/hdwallet-provider** connect to a **remote private geth network** that has a chainID . 
Following an example where network chainID was 1871
## Steps to Reproduce

- create a private geth network (my version is based on geth v1.10.3)
- configure truffle.js 

`const HDWalletProvider = require("@truffle/hdwallet-provider");

const gasPrice = 1000000000; //process.env.GASPRICE;
let privateKeys = ["ad94c2949c05b2368418d4dac4281e60808b865fffbfe0a5ed0d0c9d8230717d"];
const network = "http://myprivatenetwork:1234";
const chainId = 1871 ;

  networks: {

    development: { 

      provider: function () {
        return new HDWalletProvider(
            {
                privateKeys: privateKeys,
                providerOrUrl: network,
                chainId: chainId
            }
        )
    },
      network_id: "*",
      gas: 6000000,
      gasPrice: gasPrice
    }
  }`
## Expected Behavior
able to connect to the network and deploy the smart contract. 

## Actual Results

`Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Starting migrations...
======================
> Network name:    'development'
> Network id:      1871
> Block gas limit: 14888621 (0xe32ead)

1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
Error: Chain with ID 1871 not supported
    at Function.Common._getChainParams (/projects/crowdfund-sample-new/ethereum/node_modules/ethereumjs-common/src/index.ts:54:13)
    at Common.setChain (/projects/crowdfund-sample-new/ethereum/node_modules/ethereumjs-common/src/index.ts:91:34)
    at new Common (/projects/crowdfund-sample-new/ethereum/node_modules/ethereumjs-common/src/index.ts:75:30)
    at new Transaction (/projects/crowdfund-sample-new/ethereum/node_modules/ethereumjs-tx/src/transaction.ts:85:22)
    at HookedWalletSubprovider.signTransaction (/projects/crowdfund-sample-new/ethereum/node_modules/@truffle/hdwallet-provider/src/index.ts:161:22)
    at nextTask (/projects/crowdfund-sample-new/ethereum/node_modules/async/waterfall.js:16:14)
    at next (/projects/crowdfund-sample-new/ethereum/node_modules/async/waterfall.js:23:9)
    at /projects/crowdfund-sample-new/ethereum/node_modules/async/internal/onlyOnce.js:12:16
    at /projects/crowdfund-sample-new/ethereum/node_modules/@trufflesuite/web3-provider-engine/subproviders/hooked-wallet.js:653:5
    at /projects/crowdfund-sample-new/ethereum/node_modules/async/internal/parallel.js:39:9
    at /projects/crowdfund-sample-new/ethereum/node_modules/async/internal/once.js:12:16
    at iterateeCallback (/projects/crowdfund-sample-new/ethereum/node_modules/async/internal/eachOfLimit.js:48:24)
    at /projects/crowdfund-sample-new/ethereum/node_modules/async/internal/onlyOnce.js:12:16
    at /projects/crowdfund-sample-new/ethereum/node_modules/async/internal/parallel.js:36:13
    at /projects/crowdfund-sample-new/ethereum/node_modules/@trufflesuite/web3-provider-engine/index.js:240:9
    at /projects/crowdfund-sample-new/ethereum/node_modules/async/internal/once.js:12:16
    at replenish (/projects/crowdfund-sample-new/ethereum/node_modules/async/internal/eachOfLimit.js:61:25)
    at /projects/crowdfund-sample-new/ethereum/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/projects/crowdfund-sample-new/ethereum/node_modules/async/eachLimit.js:43:36)
    at /projects/crowdfund-sample-new/ethereum/node_modules/async/internal/doLimit.js:9:16
    at end (/projects/crowdfund-sample-new/ethereum/node_modules/@trufflesuite/web3-provider-engine/index.js:217:5)
    at Request._callback (/projects/crowdfund-sample-new/ethereum/node_modules/@trufflesuite/web3-provider-engine/subproviders/rpc.js:72:5)
    at Request.self.callback (/projects/crowdfund-sample-new/ethereum/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/projects/crowdfund-sample-new/ethereum/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/projects/crowdfund-sample-new/ethereum/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)`

## Environment
Ubuntu 18.04.5 LTS
Truffle v5.3.3 (core: 5.3.3)
Solidity - 0.5.8 (solc-js)
Node v12.20.1
Web3.js v1.3.5

**Comment by eggplantzzz** [comment]
Interesting, what happens if you omit the chain id in the configuration? Would you be willing to provide specific steps for all this (along with a sample project) so I can try and reproduce your error?

**Comment by dorinburcea** [comment]
@eggplantzzz thanks for comment. without chain Id can't connect to the network since the chainID method been implemented.
