### ISSUE TITLE
Truffle error when trying to mint 721 tokens

### ISSUE THREAD

**Issue by Islandersfan2016** [trufflesuite/truffle#4065]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue. 
- [ ] Every time I have run into issues trying to mint tokens after deploying to a testnet (rinkeby, ropsten, matic) I have received an error message. Now I'm getting an error message "Error: Cannot find module 'scrypt'" when I try to call the mint.js script.

---------------------------

## Issue

What the issue is, in broad strokes. Unable to mint tokens after deploying contract on Truffle. 

## Steps to Reproduce

I have a mint.js script that I am trying to call for an 1155 contract that' deployed.  I exported in the owner address, nft contract address, and then "node script/mint.js". After that, I get the error message.

## Expected Behavior

What you expected to happen.

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.
root@LAPTOP-B626KPV8:/mnt/c/Tay1155# node scripts/mint.js
internal/modules/cjs/loader.js:716
    throw err;
    ^

Error: Cannot find module 'scrypt'
Require stack:
- /mnt/c/Tay1155/node_modules/scrypt.js/node.js
- /mnt/c/Tay1155/node_modules/web3/node_modules/web3-eth-accounts/src/index.js
- /mnt/c/Tay1155/node_modules/web3/node_modules/web3-eth/src/index.js
- /mnt/c/Tay1155/node_modules/web3/src/index.js
- /mnt/c/Tay1155/scripts/mint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/mnt/c/Tay1155/node_modules/scrypt.js/node.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/mnt/c/Tay1155/node_modules/web3/node_modules/web3-eth-accounts/src/index.js:35:16)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/c/Tay1155/node_modules/scrypt.js/node.js',
    '/mnt/c/Tay1155/node_modules/web3/node_modules/web3-eth-accounts/src/index.js',
    '/mnt/c/Tay1155/node_modules/web3/node_modules/web3-eth/src/index.js',
    '/mnt/c/Tay1155/node_modules/web3/src/index.js',
    '/mnt/c/Tay1155/scripts/mint.js'
  ]
}
## Environment

* Operating System: 
* Ethereum client: rinkeby 
* Truffle version (`truffle version`): 5.3.7
* node version (`node --version`): 12.8.1
* npm version (`npm --version`): 6.10.2

**Comment by fainashalts** [comment]
@cds-amal is in contact with OP. Will update once certain it is resolved.

**Comment by Islandersfan2016** [comment]
Issue has been resolved.
