### ISSUE TITLE
Running "truffle test" gives the error "No module found fs-extra"

### ISSUE THREAD

**Issue by realdiganta** [trufflesuite/truffle#4113]
I checked the package.json file of the truffle directory. There is fs-extra in devDepedencies.

![Screenshot from 2021-06-15 11-16-25](https://user-images.githubusercontent.com/47485188/121999646-2f446a00-cdcb-11eb-92cb-c35cce3c223e.png)

Still when I run "truffle test" I get the following error

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.call (/usr/local/lib/node_modules/truffle/node_modules/@truffle/debugger/dist/external "fs-extra":1:18)
    at r (/usr/local/lib/node_modules/truffle/node_modules/@truffle/debugger/dist/webpack/bootstrap:19:22)
    at Object.call (/Users/gnidan/src/work/truffle/packages/compile-common/dist/src/profiler/updated.js:33:26)
    at r (/usr/local/lib/node_modules/truffle/node_modules/@truffle/debugger/dist/webpack/bootstrap:19:22)
    at Object.call (/Users/gnidan/src/work/truffle/packages/compile-common/dist/src/profiler/profiler.js:20:19)
    at r (/usr/local/lib/node_modules/truffle/node_modules/@truffle/debugger/dist/webpack/bootstrap:19:22)
    at Object.call (/Users/gnidan/src/work/truffle/packages/compile-common/dist/src/profiler/index.js:4:18)
    at r (/usr/local/lib/node_modules/truffle/node_modules/@truffle/debugger/dist/webpack/bootstrap:19:22)
    at Object.call (/Users/gnidan/src/work/truffle/packages/compile-common/dist/src/index.js:26:18)
    at r (/usr/local/lib/node_modules/truffle/node_modules/@truffle/debugger/dist/webpack/bootstrap:19:22)
    at Object.call (/Users/gnidan/src/work/truffle/packages/debugger/lib/session/index.js:31:1)
    at r (/usr/local/lib/node_modules/truffle/node_modules/@truffle/debugger/dist/webpack/bootstrap:19:22)
    at Object.call (/Users/gnidan/src/work/truffle/packages/debugger/lib/debugger.js:4:1)
    at r (/usr/local/lib/node_modules/truffle/node_modules/@truffle/debugger/dist/webpack/bootstrap:19:22)
    at Object.call (/Users/gnidan/src/work/truffle/packages/debugger/debugger.js:1:16)
    at __webpack_require__ (/usr/local/lib/node_modules/truffle/node_modules/@truffle/debugger/dist/webpack/bootstrap:19:22)
    at /usr/local/lib/node_modules/truffle/node_modules/@truffle/debugger/dist/webpack/bootstrap:83:10
    at /usr/local/lib/node_modules/truffle/node_modules/@truffle/debugger/dist/debugger.js:1:1152
Truffle v5.3.10 (core: 5.3.10)
Node v10.19.0

npm v7.14.0

**Comment by eggplantzzz** [comment]
Can you tell me exactly what you are doing when you get this error? Can you include your project as well?

**Comment by realdiganta** [comment]
@kevinbluer yes downgrading to npm 6 solved the issue. This issue occurs just for npm 7. Thank You.
