### ISSUE TITLE
"truffle unbox react" is failling

### ISSUE THREAD

**Issue by mearafGitHub** [trufflesuite/truffle#4115]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
Starting unbox...
=================

✔ Preparing to download box
✔ Downloading
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/scrypt-shim.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/meraf/.npm/_logs/2021-06-16T14_23_52_869Z-debug.log
✔ Cleaning up temporary files
✖ Setting up box
Unbox failed!
✖ Setting up box
Unbox failed!
Error: Command failed: cd client && npm ci
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/scrypt-shim.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/meraf/.npm/_logs/2021-06-16T14_23_52_869Z-debug.log

    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.installBoxDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:136:1)
    at Object.setUpBox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:66:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:116:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
Truffle v5.3.10 (core: 5.3.10)
Node v10.19.0

## Steps to Reproduce
command: truffle unbox react

## Expected Behavior

I expected to have a successfully generate full truffle sample project .

## Actual Results
Unbox failed!
Error: Command failed: cd client && npm ci
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/web3-js/scrypt-shim.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/meraf/.npm/_logs/2021-06-16T14_23_52_869Z-debug.log

    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at Object.installBoxDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:136:1)
    at Object.setUpBox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:66:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:116:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
Truffle v5.3.10 (core: 5.3.10)
Node v10.19.0

## Environment
Truffle v5.3.10 (core: 5.3.10)
Node v10.19.0

* Operating System:  Ubuntu 20.04
* Ethereum client:
* Truffle version (`truffle version`): 5.3.10 (core: 5.3.10)
* node version (`node --version`): v10.19.0
* npm version (`npm --version`):  6.14.4

**Comment by mearafGitHub** [comment]
Issue is fixed by installing git on my machine.
