### ISSUE TITLE
Debugger - TypeError: Cannot read property 'definition' of undefined

### ISSUE THREAD

**Issue by regata** [trufflesuite/truffle#4120]
## Issue

Debugger is crashing when trying to step through the code. Any help would be appreciated.

```
UniswapV2Pair.sol:

471:         address _token1 = token1;
472:         require(to != _token0 && to != _token1, 'UniswapV2: INVALID_TO');
473:         if (amount0Out > 0) _safeTransfer(_token0, to, amount0Out); // optimistically transfer tokens
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                   
debug(development:0xed24c113...)> o
⠋ Stepping...TypeError: Cannot read property 'definition' of undefined
    at /Users/gnidan/src/work/truffle/packages/debugger/lib/data/selectors/index.js:1045:53
    at /home/arbitrageur/arbitrage/node_modules/reselect/lib/index.js:76:25
    at /home/arbitrageur/arbitrage/node_modules/reselect/lib/index.js:36:25
    at /home/arbitrageur/arbitrage/node_modules/reselect/lib/index.js:90:33
    at Function.<anonymous> (/home/arbitrageur/arbitrage/node_modules/reselect/lib/index.js:36:25)
    at /home/arbitrageur/arbitrage/node_modules/reselect-tree/lib/index.js:85:1
    at /home/arbitrageur/arbitrage/node_modules/reselect/lib/index.js:86:37
    at /home/arbitrageur/arbitrage/node_modules/reselect/lib/index.js:36:25
    at runSelectEffect (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:734:26)
    at runEffect (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
    at currCb (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
    at currCb (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/home/arbitrageur/arbitrage/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
The above error occurred in task h
    created by takeEvery(TRACE_TICK, h)
    created by txlog.g
    created by SESSION_START_FULL_MODE
    created by A
    created by session.S
Tasks cancelled due to error:
takeEvery(TRACE_TICK, h)
data.C
evm.g
solidity.y
stacktrace.y
trace.y
controller.v
web3._
```

## Steps to Reproduce

1. Run forked mainnet
```sh
npx ganache-cli --fork=https://mainnet.infura.io/v3/$INFURA_PROJECT_ID
```

2. Debug a failed transaction
```sh
npx truffle debug 0xed24c113da8ea6d4e126d7fd4cb8078dd02100b974bdcd17c9eb4a0fe6b336ba --compile-tests --network development --fetch-external
```

## Environment

```sh
npx truffle version
Truffle v5.3.10 (core: 5.3.10)
Solidity - 0.8.5 (solc-js)
Node v14.17.0
Web3.js v1.3.6
```

**Comment by haltman-at** [comment]
Huh, thanks for the report!  I'll have to take a look.

**Comment by regata** [comment]
thank you. Please let me know how i can assist you

**Comment by haltman-at** [comment]
Hey, I can't locate that particular transaction on mainnet.  Do you have some other reproduction example?  Thank you!

**Comment by regata** [comment]
yea, it's my local environment with a forked mainnet. I need to find a way for you to reproduce.

According to the stack trace the exception happens on this line:
https://github.com/trufflesuite/truffle/blob/bd53ee4a4bdc107c12a2ddf50bab81036ccfccb7/packages/debugger/lib/data/selectors/index.js#L1045

For whatever reason `scopes[id]` is undefined.

Maybe it can be fixed similar to how it was done here?
https://github.com/trufflesuite/truffle/blob/bd53ee4a4bdc107c12a2ddf50bab81036ccfccb7/packages/debugger/lib/data/selectors/index.js#L922

**Comment by regata** [comment]
@haltman-at I made a demo project to reproduce the bug https://github.com/regata/druffle.

Please let me know how i can help

Thank you

**Comment by haltman-at** [comment]
> Maybe it can be fixed similar to how it was done here?
> 
> https://github.com/trufflesuite/truffle/blob/bd53ee4a4bdc107c12a2ddf50bab81036ccfccb7/packages/debugger/lib/data/selectors/index.js#L922

Well, that's the lazy fix if we can't find a good reason this is occurring. :)  I think I have an inkling what's going on here, so I suspect there's probably a better fix than that.  But I'll check out your repro example.  Thanks!

**Comment by haltman-at** [comment]
OK, we've merged a PR that should fix this, it'll go out in this week's release!

**Comment by regata** [comment]
thank you. Looking forward to test
