### ISSUE TITLE
Truffle Deploy to matic failed. only replay-protected (EIP-155) transactions allowed over RPC.

### ISSUE THREAD

**Issue by myyan** [trufflesuite/truffle#4147]
- The Problem 
```

➜  testing git:(master) ✗ truffle deploy --network matic

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'matic'
> Network id:      137
> Block gas limit: 20009743 (0x131530f)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- only replay-protected (EIP-155) transactions allowed over RPC.

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:75:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:61:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:218:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:258:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:223:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:167:1)
Truffle v5.3.12 (core: 5.3.12)
Node v14.5.0

```

- My Local Environment
```
➜  testing git:(master) ✗ truffle version 
Truffle v5.3.12 (core: 5.3.12)
Solidity - 0.6.12 (solc-js)
Node v14.5.0
Web3.js v1.3.6
```

- Truffle Config

```
    matic: {
      provider: () => new HDWalletProvider(privateKey, `https://rpc-mainnet.maticvigil.com`),
      network_id: 137,
      confirmations: 2,
      timeoutBlocks: 200,
      skipDryRun: true
    }
```

**Comment by gnidan** [comment]
Can you share your `package.json`?

**Comment by scald** [comment]
Also running into this issue when attempting to deploy to `polygon_infura_testnet` walking through the boilerplate repo `polygon-box` ... guide located here: https://github.com/truffle-box/polygon-box

Everything compiles correctly but test and deploy fails with the same error:

```
npm run test:polygon --network=polygon_infura_testnet

> polygon-box@1.0.0 test:polygon /Users/scald/code/mandolin/polygon
> truffle test --config=truffle-config.polygon.js --network=$npm_config_network


Compiling your contracts...
===========================
> Compiling ./contracts/polygon/SimpleStorage.sol
> Artifacts written to /var/folders/yn/d_wn_44s6w138tgbww8zr_k00000gn/T/test--62836-EHbHhEDQMESL
> Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang

Error: while migrating SimpleStorage: only replay-protected (EIP-155) transactions allowed over RPC
    at /Users/scald/.nvm/versions/node/v14.14.0/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Migration._deploy (/Users/scald/.nvm/versions/node/v14.14.0/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:75:1)
    at Migration._load (/Users/scald/.nvm/versions/node/v14.14.0/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:61:1)
    at Migration.run (/Users/scald/.nvm/versions/node/v14.14.0/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:218:1)
    at Object.runMigrations (/Users/scald/.nvm/versions/node/v14.14.0/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/Users/scald/.nvm/versions/node/v14.14.0/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/Users/scald/.nvm/versions/node/v14.14.0/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/Users/scald/.nvm/versions/node/v14.14.0/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at Object.run (/Users/scald/.nvm/versions/node/v14.14.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:109:1)
    at Object.run (/Users/scald/.nvm/versions/node/v14.14.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/test/index.js:160:1)
    at Command.run (/Users/scald/.nvm/versions/node/v14.14.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:167:1)
Truffle v5.3.13 (core: 5.3.13)
Node v14.14.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! polygon-box@1.0.0 test:polygon: `truffle test --config=truffle-config.polygon.js --network=$npm_config_network`
npm ERR! Exit status 1
```

- Environment

```
Truffle v5.3.13 (core: 5.3.13)
Solidity v0.5.16 (solc-js)
Node v14.14.0
Web3.js v1.3.6
```
- Truffle Config
```
polygon_infura_testnet: {
      provider: () => new HDWalletProvider({
        mnemonic: {
          phrase: mnemonic
        },
        providerOrUrl:
         "https://polygon-mumbai.infura.io/v3/" + infuraProjectId
      }),
      network_id: 80001,
      confirmations: 2,
      timeoutBlocks: 200,
      skipDryRun: true,
      chainId: 80001
    },
```

- package.json
```
{
  "name": "polygon-box",
  "version": "1.0.0",
  "description": "A sample Truffle project that allows developers to deploy to the Polygon Matic PoS chain",
  "main": "truffle-config.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "truffle test",
    "test:polygon": "truffle test --config=truffle-config.polygon.js --network=$npm_config_network",
    "compile:polygon": "truffle compile --config=truffle-config.polygon.js",
    "migrate:polygon": "truffle migrate --config=truffle-config.polygon.js --network=$npm_config_network"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/truffle-box/polygon-box.git"
  },
  "keywords": [
    "Matic",
    "Polygon",
    "Ethereum",
    "Truffle",
    "dapp"
  ],
  "author": "Faina Shalts",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/truffle-box/polygon-box/issues"
  },
  "homepage": "https://github.com/truffle-box/polygon-box#readme",
  "devDependencies": {
    "@maticnetwork/maticjs": "^2.0.40",
    "@truffle/hdwallet-provider": "^1.2.3",
    "dotenv": "^9.0.0"
  },
  "dependencies": {}
}
```

**Comment by scald** [comment]
ah - I missed this reply 

https://github.com/trufflesuite/truffle/issues/3913#issuecomment-842282897

hdwallet-provider to 1.4.0 resolves the issue for me, will file a PR in `polygon-box`

**Comment by cds-amal** [comment]
Thanks for the PR @scald!
