### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by Kaleb47** [trufflesuite/truffle#4159]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

To put it simply, all of smart contracts were compiled successfully, but I think there might be something wrong with my test.js file because it might be missing a certain property.

## Steps to Reproduce

```npx truffle compile``` the following smart contracts from the repo  ```gnosis/dx-price-oracle```:
```DutchXPriceOracle.sol```
```IDutchX.sol```
```Migrations.sol```
```MockContracts.sol```

Next run ```npx truffle test```.

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

```
npx truffle test
1071
1072Using gas limit: 6500 K
1073Using gas price: 10 Gwei
1074Optimizer enabled: true
1075Using default mnemonic: true
1076Using default mnemonic
1077- Fetching solc version list from solc-bin
1078- Downloading compiler
1079Compiling ./contracts/DutchXPriceOracle.sol...
1080Compiling ./contracts/IDutchX.sol...
1081Compiling ./contracts/Imports.sol...
1082Compiling ./contracts/Migrations.sol...
1083Compiling ./contracts/WhitelistPriceOracle.sol...
1084Compiling @gnosis.pm/dx-contracts/contracts/DutchExchange.sol...
1085Compiling @gnosis.pm/dx-contracts/contracts/DutchExchangeHelper.sol...
1086Compiling @gnosis.pm/dx-contracts/contracts/DutchExchangeProxy.sol...
1087Compiling @gnosis.pm/dx-contracts/contracts/DxDevDependencies.sol...
1088Compiling @gnosis.pm/dx-contracts/contracts/Oracle/DSAuth.sol...
1089Compiling @gnosis.pm/dx-contracts/contracts/Oracle/DSMath.sol...
1090Compiling @gnosis.pm/dx-contracts/contracts/Oracle/DSNote.sol...
1091Compiling @gnosis.pm/dx-contracts/contracts/Oracle/DSThing.sol...
1092Compiling @gnosis.pm/dx-contracts/contracts/Oracle/DSValue.sol...
1093Compiling @gnosis.pm/dx-contracts/contracts/Oracle/Medianizer.sol...
1094Compiling @gnosis.pm/dx-contracts/contracts/Oracle/PriceFeed.sol...
1095Compiling @gnosis.pm/dx-contracts/contracts/Oracle/PriceOracleInterface.sol...
1096Compiling @gnosis.pm/dx-contracts/contracts/TokenFRT.sol...
1097Compiling @gnosis.pm/dx-contracts/contracts/TokenFRTProxy.sol...
1098Compiling @gnosis.pm/dx-contracts/contracts/base/AuctioneerManaged.sol...
1099Compiling @gnosis.pm/dx-contracts/contracts/base/DxMath.sol...
1100Compiling @gnosis.pm/dx-contracts/contracts/base/DxUpgrade.sol...
1101Compiling @gnosis.pm/dx-contracts/contracts/base/EthOracle.sol...
1102Compiling @gnosis.pm/dx-contracts/contracts/base/SafeTransfer.sol...
1103Compiling @gnosis.pm/dx-contracts/contracts/base/TokenWhitelist.sol...
1104Compiling @gnosis.pm/gno-token/contracts/TokenGNO.sol...
1105Compiling @gnosis.pm/mock-contract/contracts/MockContract.sol...
1106Compiling @gnosis.pm/owl-token/contracts/OWLAirdrop.sol...
1107Compiling @gnosis.pm/owl-token/contracts/TokenOWL.sol...
1108Compiling @gnosis.pm/owl-token/contracts/TokenOWLProxy.sol...
1109Compiling @gnosis.pm/util-contracts/contracts/EtherToken.sol...
1110Compiling @gnosis.pm/util-contracts/contracts/GnosisStandardToken.sol...
1111Compiling @gnosis.pm/util-contracts/contracts/Math.sol...
1112Compiling @gnosis.pm/util-contracts/contracts/Proxy.sol...
1113Compiling @gnosis.pm/util-contracts/contracts/Token.sol...
1114Deploying DutchX MockContract
1115Deploy DutchXPriceOracle using the mock DutchX:
1116  - Mock DutchX address: 0x28a1252dA7C56953a579CdB4a486f64696BdEBfD
1117  - Mock WETH address: 0x0000000000000000000000000000000000000001
1118
1119Deploy WhitelistPriceOracle using the mock DutchX:
1120  - Mock DutchX address: 0x28a1252dA7C56953a579CdB4a486f64696BdEBfD
1121  - Mock WETH address: 0x0000000000000000000000000000000000000001
1122
1123
1124  Contract: DutchXPriceOracle
1125~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1126[ { auctionIndex: 0,
1127    num: 554194827840,
1128    den: 12358446813,
1129    clearingTime: 1552570934 },
1130  { auctionIndex: 1,
1131    num: 126270548826,
1132    den: 384320833039,
1133    clearingTime: 1552605877 },
1134  { auctionIndex: 2,
1135    num: 531621722047,
1136    den: 485222699792,
1137    clearingTime: 1552646252 },
1138  { auctionIndex: 3,
1139    num: 694476422673,
1140    den: 994097048096,
1141    clearingTime: 1552672647 },
1142  { auctionIndex: 4,
1143    num: 633489716929,
1144    den: 109901959035,
1145    clearingTime: 1552704387 },
1146  { auctionIndex: 5,
1147    num: 486169460458,
1148    den: 392151037123,
1149    clearingTime: 1552749696 },
1150  { auctionIndex: 6,
1151    num: 852316326969,
1152    den: 12925318719,
1153    clearingTime: 1552797546 },
1154  { auctionIndex: 7,
1155    num: 419814186045,
1156    den: 950224204100,
1157    clearingTime: 1552824430 },
1158  { auctionIndex: 8,
1159    num: 969939934433,
1160    den: 145790060406,
1161    clearingTime: 1552848580 },
1162  { auctionIndex: 9,
1163    num: 995510544674,
1164    den: 794003675439,
1165    clearingTime: 1552873047 },
1166  { auctionIndex: 10,
1167    num: 554921678996,
1168    den: 454000654762,
1169    clearingTime: 1552886142 },
1170  { auctionIndex: 11,
1171    num: 800743921022,
1172    den: 51215561556,
1173    clearingTime: 1552899552 },
1174  { auctionIndex: 12,
1175    num: 355496762229,
1176    den: 969308717759,
1177    clearingTime: 1552910336 },
1178  { auctionIndex: 13,
1179    num: 735939905745,
1180    den: 514571985417,
1181    clearingTime: 1552945601 },
1182  { auctionIndex: 14,
1183    num: 727428966115,
1184    den: 394998814054,
1185    clearingTime: 1552962944 },
1186  { auctionIndex: 15,
1187    num: 250468786299,
1188    den: 276750443041,
1189    clearingTime: 1552995814 },
1190  { auctionIndex: 16,
1191    num: 156201826830,
1192    den: 921318016628,
1193    clearingTime: 1553016097 },
1194  { auctionIndex: 17,
1195    num: 883145068037,
1196    den: 56833206366,
1197    clearingTime: 1553045990 },
1198  { auctionIndex: 18,
1199    num: 488656740230,
1200    den: 74391876942,
1201    clearingTime: 1553090819 },
1202  { auctionIndex: 19,
1203    num: 46376008215,
1204    den: 180708149733,
1205    clearingTime: 1553139642 },
1206  { auctionIndex: 20,
1207    num: 486814695241,
1208    den: 486105362195,
1209    clearingTime: 1553150606 },
1210  { auctionIndex: 21,
1211    num: 225262630278,
1212    den: 711152553528,
1213    clearingTime: 1553165830 },
1214  { auctionIndex: 22,
1215    num: 84521609265,
1216    den: 140081766517,
1217    clearingTime: 1553206614 },
1218  { auctionIndex: 23,
1219    num: 908739501085,
1220    den: 416888072691,
1221    clearingTime: 1553247453 },
1222  { auctionIndex: 24,
1223    num: 284866699308,
1224    den: 638815636096,
1225    clearingTime: 1553289671 },
1226  { auctionIndex: 25,
1227    num: 489890233117,
1228    den: 260685249621,
1229    clearingTime: 1553301435 },
1230  { auctionIndex: 26,
1231    num: 762914410952,
1232    den: 541649499901,
1233    clearingTime: 1553340872 },
1234  { auctionIndex: 27,
1235    num: 204685720912,
1236    den: 111826402848,
1237    clearingTime: 1553374725 },
1238  { auctionIndex: 28,
1239    num: 31684951624,
1240    den: 735575080277,
1241    clearingTime: 1553409232 },
1242  { auctionIndex: 29,
1243    num: 353668176049,
1244    den: 933934499192,
1245    clearingTime: 1553453459 },
1246  { auctionIndex: 30,
1247    num: 958829304947,
1248    den: 235240689246,
1249    clearingTime: 1553474175 },
1250  { auctionIndex: 31,
1251    num: 629862866868,
1252    den: 625342083076,
1253    clearingTime: 1553507613 },
1254  { auctionIndex: 32,
1255    num: 420554378555,
1256    den: 108752612255,
1257    clearingTime: 1553518682 },
1258  { auctionIndex: 33,
1259    num: 222859488388,
1260    den: 141120029080,
1261    clearingTime: 1553568769 },
1262  { auctionIndex: 34,
1263    num: 405547414770,
1264    den: 711418049891,
1265    clearingTime: 1553590337 },
1266  { auctionIndex: 35,
1267    num: 892624563047,
1268    den: 778185483763,
1269    clearingTime: 1553610664 },
1270  { auctionIndex: 36,
1271    num: 455118865986,
1272    den: 70398968650,
1273    clearingTime: 1553659340 },
1274  { auctionIndex: 37,
1275    num: 538166884016,
1276    den: 775489836117,
1277    clearingTime: 1553688390 },
1278  { auctionIndex: 38,
1279    num: 580185320543,
1280    den: 426861804732,
1281    clearingTime: 1553725887 },
1282  { auctionIndex: 39,
1283    num: 449998843423,
1284    den: 83701178457,
1285    clearingTime: 1553763424 },
1286  { auctionIndex: 40,
1287    num: 256363960983,
1288    den: 431974853527,
1289    clearingTime: 1553809437 },
1290  { auctionIndex: 41,
1291    num: 220390608314,
1292    den: 778962251110,
1293    clearingTime: 1553842010 },
1294  { auctionIndex: 42,
1295    num: 897267491405,
1296    den: 544497941418,
1297    clearingTime: 1553865116 },
1298  { auctionIndex: 43,
1299    num: 661775835387,
1300    den: 649441994298,
1301    clearingTime: 1553878150 },
1302  { auctionIndex: 44,
1303    num: 320730794680,
1304    den: 45506905727,
1305    clearingTime: 1553901344 },
1306  { auctionIndex: 45,
1307    num: 633503832629,
1308    den: 972539858935,
1309    clearingTime: 1553949126 },
1310  { auctionIndex: 46,
1311    num: 816070300128,
1312    den: 829855682455,
1313    clearingTime: 1553980139 },
1314  { auctionIndex: 47,
1315    num: 57775694823,
1316    den: 152147276915,
1317    clearingTime: 1553995936 },
1318  { auctionIndex: 48,
1319    num: 670141643328,
1320    den: 989932630838,
1321    clearingTime: 1554040914 },
1322  { auctionIndex: 49,
1323    num: 773513364094,
1324    den: 61847915087,
1325    clearingTime: 1554063138 } ]
1326~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1327    ✓ getPrice() correct (705ms)
1328    ✓ getPriceCustom() correct (9367ms)
1329    ✓ getPricesAndMedian() correct (16588ms)
1330    ✓ isWhitelisted() correct (205ms)
1331    ✓ isSmaller() correct (87ms)
1332    ✓ computeAuctionIndex() correct (6346ms)
1333
1334
1335  6 passing (40s)
1336
1337 The command "npm test" exited with 0.
```
## Actual Results

```
Using gas limit: 6500 K
Using gas price: 10 Gwei
Optimizer enabled: true
Using default mnemonic: true
Using default mnemonic
Using network 'development'.


Compiling your contracts...
===========================
> Compiling ./contracts/MockContracts.sol
TypeError: Cannot read property '0' of null
    at detectErrors (/Users/kalebamarante/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:293:61)
    at run (/Users/kalebamarante/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:37:29)
    at Object.sourcesWithDependencies (/Users/kalebamarante/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:78:49)
    at necessary (/Users/kalebamarante/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:40:1)
    at /Users/kalebamarante/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:38:1
    at async Promise.all (index 0)
    at compile (/Users/kalebamarante/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:28:1)
    at Object.compile (/Users/kalebamarante/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:67:38)
    at Object.compileAndSave (/Users/kalebamarante/node_modules/truffle/build/webpack:/packages/workflow-compile/index.js:92:38)
    at Object.compileContractsWithTestFilesIfNeeded (/Users/kalebamarante/node_modules/truffle/build/webpack:/packages/core/lib/test.js:247:38)
    at Object.run (/Users/kalebamarante/node_modules/truffle/build/webpack:/packages/core/lib/test.js:105:27)
Truffle v5.1.45 (core: 5.1.45)
Node v16.4.0
```

## Environment

* Operating System: Mac OS
* Ethereum client: Web3js
* Truffle version (`truffle version`): 7:18:1
* node version (`node --version`): 16:4:0
* npm version (`npm --version`):  7.18.1

**Comment by haltman-at** [comment]
Hm, that shouldn't happen.  Do you have a reproduction example we could inspect?  Thank you!

**Comment by haltman-at** [comment]
Closing this for issue maintenance, but please let us know if there's still a problem, thanks!
