### ISSUE TITLE
Broken symlinks in `contracts/` directory are silently ignored

### ISSUE THREAD

**Issue by cameel** [trufflesuite/truffle#4167]
## Issue
Truffle just skips broken symlinks in its `contracts/` directory. If any are present, they are likely to be a symptom of an actual problem (e.g. use moving the directory and forgetting to update the links) so I think at least a warning should be generated.

## Steps to Reproduce
```bash
mkdir truffle-test/
cd truffle-test/
npm install truffle
npx truffle init
echo 'module.exports.compilers.solc.version = "0.8.6";' >> truffle-config.js

echo 'contract C {}' > contracts/C.sol
ln -s contracts/E.sol D.sol
npx truffle compile
```

## Actual Results
```
> Artifacts written to /tmp/truffle-test/build/contracts
> Compiled successfully using:
   - solc: 0.8.6+commit.11564f7e.Emscripten.clang
```

The `sources` dict in the JSON input contains these entries:
```json
"project:/contracts/C.sol": { "content": "contract C {}\n" }
```

## Expected Behavior
Something along these lines:
```
> Broken symbolic link found: "contracts/E.sol". The relative target "D.sol" does not exist.

> Artifacts written to /tmp/truffle-test/build/contracts
> Compiled successfully using:
   - solc: 0.8.6+commit.11564f7e.Emscripten.clang
```

## Environment
* Operating System: Arch Linux
* Truffle version: both `5.3.14` and current `develop` (abfb3646eea9d57e0a6f9186c12bb51680c181d8)
* node version: `v16.4.2`
* npm version: `7.17.0`

**Comment by cds-amal** [comment]
Hi @cameel, the `ln` command created a link in the project root which would cause truffle compile to behave normally as observed. I tried your scenario and truffle wasn't silent, though it would be more helpful to point out a broken link is at play.

```
$ echo 'module.exports.compilers.solc.version = "0.8.6";' >> truffle-config.js
   echo 'contract C {}' > contracts/C.sol
   ln -s contracts/E.sol D.sol
$ tree .
.
├── contracts
│   ├── C.sol
│   └── Migrations.sol
├── D.sol -> contracts/E.sol
├── migrations
│   └── 1_initial_migration.js
├── test
└── truffle-config.js
```

## Setup
```

$ ln -s $(pwd)/broken.sol contracts/D.sol
$ rm -rf build
$ tree
.
├── contracts
│   ├── C.sol
│   ├── D.sol -> /home/amal/work/reproduce/2021/07/09/4167-symlinks/broken.sol
│   └── Migrations.sol
├── migrations
│   └── 1_initial_migration.js
├── test
└── truffle-config.js

3 directories, 5 files
```

## Compile
```

$ truffle compile

Compiling your contracts...
===========================
TypeError: Cannot read property 'imports' of undefined
    at Object.<anonymous> (/home/amal/.nvm/versions/node/v12.22.1/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:78:1)
    at Generator.next (<anonymous>)
    at fulfilled (/home/amal/.nvm/versions/node/v12.22.1/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:5:42)
Truffle v5.3.13 (core: 5.3.13)
Node v12.22.1
```

## Compile with debug flag
```
$ DEBUG=*:requiredSources truffle compile  
Secp256k1 bindings are not compiled. Pure JS implementation will be used.
Keccak bindings are not compiled. Pure JS implementation will be used.

Compiling your contracts...
===========================
  compile-common:profiler:requiredSources allPaths: [
  compile-common:profiler:requiredSources   '/home/amal/work/reproduce/2021/07/09/4167-symlinks/contracts/C.sol',
  compile-common:profiler:requiredSources   '/home/amal/work/reproduce/2021/07/09/4167-symlinks/contracts/D.sol',
  compile-common:profiler:requiredSources   '/home/amal/work/reproduce/2021/07/09/4167-symlinks/contracts/Migrations.sol'
  compile-common:profiler:requiredSources ] +0ms
  compile-common:profiler:requiredSources updatedPaths: [
  compile-common:profiler:requiredSources   '/home/amal/work/reproduce/2021/07/09/4167-symlinks/contracts/C.sol',
  compile-common:profiler:requiredSources   '/home/amal/work/reproduce/2021/07/09/4167-symlinks/contracts/Migrations.sol'
  compile-common:profiler:requiredSources ] +1ms
  compile-common:profiler:requiredSources entering main loop +57ms
  compile-common:profiler:requiredSources currentFile: /home/amal/work/reproduce/2021/07/09/4167-symlinks/contracts/D.sol +0ms
TypeError: Cannot read property 'imports' of undefined
    at Object.<anonymous> (/home/amal/.nvm/versions/node/v12.22.1/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:78:1)
    at Generator.next (<anonymous>)
    at fulfilled (/home/amal/.nvm/versions/node/v12.22.1/lib/node_modules/truffle/build/webpack:/packages/compile-common/dist/src/profiler/requiredSources.js:5:42)
Truffle v5.3.13 (core: 5.3.13)
Node v12.22.1
```

**Comment by cameel** [comment]
True! My bad. I meant `ln -s E.sol contracts/D.sol` but that indeed causes the error you posted.

Truffle only reports this error when the file name ends with `.sol` though. The situation where I ran into it orignally was a broken symlink to a directory and looks like in this situation the broken link is still ignored:

```bash
cd /tmp/
mkdir truffle-test/
cd truffle-test/
npm install truffle
npx truffle init
echo 'module.exports.compilers.solc.version = "0.8.6";' >> truffle-config.js

mkdir -p ../my-project/src/
echo 'contract C {}' > ../my-project/src/C.sol
ln -s ../../My-project/src/ contracts/My-project
npx truffle compile
```

Truffle obviously can't know that it's a link to a directory that was meant to contain Solidity files but I think that the presence of any broken link should be reported.
