### ISSUE TITLE
Insufficient funds error when running migration script on mainnet

### ISSUE THREAD

**Issue by teikjun** [trufflesuite/truffle#4207]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When executing a truffle migration script on mainnet, I received Insufficient funds error. There are no errors during the dry run. This issue does not occur on ropsten testnet. 

## Steps to Reproduce

1. Use the following network configuration in truffle-config.js
```
    infura_mainnet: {
      networkCheckTimeout: 10000, 
      provider: function() {
        return new HD_WALLET_PROVIDER(DEPLOYER_MNEMONIC, INFURA_TOKEN, 0, 10);
      },
      network_id: 1
    },
```

2. Deploy the migration script in this gist (after running the default initial migration script)
https://gist.github.com/teikjun/07e9377e8ade1466abbefd1c4dcaeeeb

## Expected Behavior

Should execute migration script without error.

## Actual Results

Received an error.

```
Error: insufficient funds for gas * price + value
    at module.exports (/Users/tj/MyProject/migrations/6_deploy_multisig_pauser.js:8:29)
    at Migration._load (/Users/tj/.nvm/versions/node/v10.24.1/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:60:1)
```

## Remarks 

- I believe that my [deployer account](https://etherscan.io/address/0x276e800BD0EBff3BacaE5c6be7Ff86DFea0518b5) actually has sufficient ether. This is because I am still able to run the initial migration script. Furthermore, just a day ago, I was able to run a larger migration script (which tries to deploy several multisignature contracts instead of one) with less ether.

- I am suspecting that there could be issues with my environment, but I am not sure because I've only started using truffle very recently. I have included the dependencies of the project below. I have also tried using a deprecated version of hd-wallet (truffle-hdwallet-provider). Using the deprecated version gives a timeout error instead. Using @truffle/hdwallet-provider gives the error described in this issue.

<img width=300  src=https://user-images.githubusercontent.com/46853051/127384657-bb45a7be-df40-4de9-be5a-2b1ee6b18f25.png />

- running `truffle networks` gives the expected output for the migrations contract address.

## Environment

* Operating System: MacOS
* Ethereum client: Infura (I am using wss instead of https due to the issue described in https://github.com/trufflesuite/truffle/issues/3356#issuecomment-826310780)
* Truffle version (`truffle version`): 5.4.1
* node version (`node --version`): 10.24.1
* npm version (`npm --version`): 6.14.12

**Comment by teikjun** [comment]
The problem has been resolved by setting gas to an appropriate amount, so I will close this issue
