### ISSUE TITLE
Unclear error message when testrpc isn't running

### ISSUE THREAD

**Issue by ripper234** [trufflesuite/truffle#421]
## Issue

The error message when running `truffle test` without running `testrpc` is confusing.

## Steps to Reproduce

Run `truffle test` without running `testrpc`.

## Expected Behavior

A beginner-friendly error message that explains you should run `testrpc` before running `truffle test`

## Actual Results

```
truffle test
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/mnt/c/Users/User/AppData/Roaming/nvm/v7.5.0/node_modules/truffle/node_modules/xhr2/lib/xhr2.js:414:24)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
```

## Environment

* Operating System: Windows
* Truffle version: 3.2.1

**Comment by tcoulter** [comment]
Thanks! We'll be making this error message better. See #489.
