### ISSUE TITLE
truffle fails with `TypeError: path must be a string`

### ISSUE THREAD

**Issue by elenadimitrova** [trufflesuite/truffle#422]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue
Any `truffle` command breaks with
```
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.stat (fs.js:830:11)
    at Object.files (/opt/circleci/nodejs/v4.8.3/lib/node_modules/truffle/node_modules/node-dir/lib/paths.js:164:8)
```
Issue source is the _minor_ upgrade ()0.1.16->0.1.17) of `node-dir` package which is causing a wider disruption than just `truffle`
https://github.com/fshost/node-dir/issues/50

## Steps to Reproduce

run `truffle compile`

## Expected Behavior

Command completes

## Actual Results

```
Truffle commands fail with
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.stat (fs.js:830:11)
    at Object.files (/opt/circleci/nodejs/v4.8.3/lib/node_modules/truffle/node_modules/node-dir/lib/paths.js:164:8)
    at Object.module.exports.contractFiles (/opt/circleci/nodejs/v4.8.3/lib/node_modules/truffle/node_modules/ether-pudding/index.js:270:9)
    at Object.module.exports.requireAll (/opt/circleci/nodejs/v4.8.3/lib/node_modules/truffle/node_modules/ether-pudding/index.js:253:10)
    at Object.Contracts.provision (/opt/circleci/nodejs/v4.8.3/lib/node_modules/truffle/lib/contracts.js:39:13)
    at TruffleInterpreter.provision (/opt/circleci/nodejs/v4.8.3/lib/node_modules/truffle/lib/repl.js:56:13)
    at TruffleInterpreter.start (/opt/circleci/nodejs/v4.8.3/lib/node_modules/truffle/lib/repl.js:24:8)
    at Object.Repl.run (/opt/circleci/nodejs/v4.8.3/lib/node_modules/truffle/lib/repl.js:130:17)
    at /opt/circleci/nodejs/v4.8.3/lib/node_modules/truffle/lib/tasks.js:229:19
    at Tasks.(anonymous function) (/opt/circleci/nodejs/v4.8.3/lib/node_modules/truffle/lib/tasks.js:21:5)
    at Command.run (/opt/circleci/nodejs/v4.8.3/lib/node_modules/truffle/lib/command.js:50:5)
    at Object.<anonymous> (/opt/circleci/nodejs/v4.8.3/lib/node_modules/truffle/cli.js:11:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32
```

## Environment
Tested with multiple environments and versions.
* Operating System: OSX, Ubuntu
* Truffle version: 2.1.2, 3.2.4
* Ethereum client: parity v1.5.12
* node version: 4.8.3, 4.6.1
* npm version: 3.10.8

**Comment by elenadimitrova** [comment]
Confirming as fixed in 3.2.5. Thanks @tcoulter !

**Comment by externMing** [comment]
how to fix...

**Comment by Fabreeze23** [comment]
I'm still getting that error

**Comment by externMing** [comment]
@elenadimitrova  hello! how you fixed this problem "TypeError: path must be a string" ？

**Comment by elenadimitrova** [comment]
For me that was fixed when Tim pinned the `node-dir` version to one that didn't contain the bug. I see this is no longer a dependency of truffle though so it must be a different cause for you guys than what we saw.
