### ISSUE TITLE
Can not deploy to Binance Smart Chain

### ISSUE THREAD

**Issue by aliveli186** [trufflesuite/truffle#4288]
`truffle migrate --network bsctestnet`
fails with the following error message:
```
> Compiled successfully using:
   - solc: 0.8.7+commit.e28d00a7.Emscripten.clang


C:\Projects\node_modules\request\request.js:848
          var e = new Error('ETIMEDOUT')
                  ^
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
Error: ETIMEDOUT
    at Timeout.<anonymous> (C:\Projects\node_modules\request\request.js:848:19)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
    at PollingBlockTracker._performSync (C:\Projects\node_modules\eth-block-tracker\src\polling.js:51:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)
UnhandledRejections detected
Promise {
  <rejected> {
    code: -32603,
    message: 'ETIMEDOUT',
    data: { originalError: [Object] },
    stack: 'Error: ETIMEDOUT\n' +
      '    at Timeout.<anonymous> (F:\\Projects\\Blockchain\\node_modules\\request\\request.js:848:19)\n' +
      '    at listOnTimeout (internal/timers.js:557:17)\n' +
      '    at processTimers (internal/timers.js:500:7)'
  }
}
```

`truffle migrate --network ropsten` works.

The only difference is the one which fails is a HTTPS the other is a WebSocket address.

Tool Versions:
```
Truffle v5.4.5 (core: 5.4.5)
Solidity - 0.8.7 (solc-js)
Node v14.17.5
Web3.js v1.5.1
npm v6.14.14
```

truffle-config.js:
```
    ropsten: {
      provider: () => new HDWalletProvider(mnemonic, `wss://ropsten.infura.io/ws/v3/${infuraKey}`),
      websockets: true,
      network_id: 3,       // Ropsten's id
      gas: 5500000,        // Ropsten has a lower block limit than mainnet
      confirmations: 0,    // # of confs to wait between deployments. (default: 0)
      timeoutBlocks: 200,  // # of blocks before a deployment times out  (minimum/default: 50)
      skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
    },

    bsctestnet: {
      provider: () => new HDWalletProvider(mnemonic, `https://data-seed-prebsc-2-s3.binance.org:8545/`),
      network_id: 97,
      confirmations: 0,
      timeoutBlocks: 200,
      skipDryRun: true
    }
```

**Comment by mertcmutlu** [comment]
I am having the same issue. Any help is appreciated.

**Comment by JohnTendik** [comment]
Im having a ton of issues with BSC, weird issues like account not being recognized for one call but a second call it works fine. Im wondering if this is an issue with the testnet?

**Comment by leeftk** [comment]
Hey @aliveli186 , thanks for raising this issue with us. I attempted to reproduce the issue with the same configuration that you had in your truffle-config.js and it seems to have worked on my machine. Is your BSC wallet funded with the proper amount of BNB to deploy the contracts? If not you can find a faucet [here](https://testnet.binance.org/faucet-smart). I would also recommend trying a different RPC endpoint from the Binance site which you can find [here](https://docs.binance.org/smart-chain/developer/rpc.html) just to try and eliminate all possibilities. Let me know if this helps at all and keep me updated with what you find. Thanks!

**Comment by aliveli186** [comment]
@leeftk The error message above is about request timeout not about balance.
Yes there was enough balance.

**Comment by leeftk** [comment]
Okay @aliveli186 thanks for reaching out about this.

**Comment by miladnikad** [comment]
When I used other endpoints, The issue was fixed. You can try the below endpoints.

**BSC RPC Endpoints:**
```

https://data-seed-prebsc-1-s1.binance.org:8545/
https://data-seed-prebsc-2-s1.binance.org:8545/
https://data-seed-prebsc-1-s2.binance.org:8545/
https://data-seed-prebsc-2-s2.binance.org:8545/
https://data-seed-prebsc-1-s3.binance.org:8545/
https://data-seed-prebsc-2-s3.binance.org:8545/
```
