### ISSUE TITLE
truffle throws an error during the 'Saving migration to chain' process.

### ISSUE THREAD

**Issue by cic-developer** [trufflesuite/truffle#4293]
**1. Reproduce the problem**
```
Truffle v5.3.4 (core: 5.3.4)
Solidity - 0.5.0 (solc-js)
Node v14.15.5
Web3.js v1.3.5
```
Occurs in the same environment as above in MAC OS environment,
Although openzeppelin is used, it is not described as irrelevant to errors.

**2. Expected behavior & error**
```
pragma solidity ^0.5.0;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/ERC20Detailed.sol";
import "@openzeppelin/contracts/ownership/Ownable.sol";


contract Migrations is ERC20Detailed,ERC20, Ownable{
    constructor() ERC20Detailed('testcoin','tc',18) public {
        _mint(msg.sender, 10000*10**18);
    }
}
```
Attempts to test the contract with the corresponding contents.
Enter the 'truffle deploy --network testnet' command.
Error Occurred.

 ```
Saving migration to chain.
TypeError: migrations.setCompleted is not a function
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:103:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:61:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:212:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:263:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:228:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:140:1)
```

I think the object called 'migrations' is not being created properly.
Any solution?

**Comment by Socranote** [comment]
I have the same problems.Have you solve it?

**Comment by MicaiahReid** [comment]
Hi @cic-developer, this is a bug on our end; it looks like the name "Migrations" for a contract is reserved for Truffle's migration system. We will get a fix for this eventually, but in the meantime a workaround is to rename your Migrations contract.
