### ISSUE TITLE
Help with (Error: Could not find artifacts for BustaRhymes from any sources     at Resolver.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:61:1)

### ISSUE THREAD

**Issue by TechJonesAi** [trufflesuite/truffle#4315]
I have run the truffle test command from the terminal command line and i am getting the below error. The error i am getting is Error: Could not find artifacts for Rhymes from any sources
    at Resolver.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:61:1)
    at Object.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:275:1)
    at Object.<anonymous> (/Users/darrenjay/Desktop/BLOCKCHAIN COURSE DEV/rinkbey/test/Rhymes.test.js:1:31)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at /usr/local/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:390:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:387:14)
    at Mocha.run (/usr/local/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:961:10)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:151:1
    at new Promise (<anonymous>)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/Test.js:150:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/test/index.js:204:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:183:1)
Truffle v5.4.11 (core: 5.4.11)
Node v16.9.1

## Environment

* Operating System: Mac OS BigSur
* Ethereum client: 
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by fainashalts** [comment]
Hello @TechJonesAi, thanks for bringing this up. Without more information I can't confirm whether this is an issue with Truffle or your code. Do you have some example code to reproduce this? Thanks!
