### ISSUE TITLE
Unable to add HDWalletProvider to Web3 Engine providers

### ISSUE THREAD

**Issue by cycorax12** [trufflesuite/truffle#4373]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

Code
```
const Web3 = require("web3");
const Web3ProviderEngine = require("web3-provider-engine");
const HDWalletProvider = require("@truffle/hdwallet-provider");
const opensea = require("opensea-js");

const Network = opensea.Network;

const OrderSide = require("opensea-js/lib/types");


const OpenSeaPort = opensea.OpenSeaPort;



const ASSET_CONTRACT_ADDRESS = ''
const ASSET_TOKEN_ID = ''
const BUYER_WALLET_ADDRESS = ''
const MNEMONIC = ''


const BASE_DERIVATION_PATH = `44'/60'/0'/0`;

const provider = new HDWalletProvider({
  mnemonic: {
    phrase: MNEMONIC
  },
  providerOrUrl: "https://rinkeby.infura.io/v3/<my-project-id>"
});



const providerEngine = new Web3ProviderEngine();
providerEngine.addProvider(provider); // <------------------- ERROR occurs here
providerEngine.start();

//const web3 = new Web3(provider);


const seaport = new OpenSeaPort(
  providerEngine,
  {
    networkName: Network.Rinkeby
  },
  (arg) => console.log(arg)
);
```

Getting below error for above code
```
TypeError: source.setEngine is not a function
    at Web3ProviderEngine.addProvider (D:\Work\projects\nft\bloodhound-opensea-api-wrapper\node_modules\web3-provider-engine\index.js:68:10)
    at Object.<anonymous> (D:\Work\projects\nft\bloodhound-opensea-api-wrapper\server.js:36:16)
```

Package.json
```
"dependencies": {
    "@truffle/hdwallet-provider": "^1.5.1",
    "opensea-js": "^1.2.1",
    "web3": "^1.6.0"
  }
```

## Steps to Reproduce

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

Initialize Web3 provider engine

## Actual Results
ERROR

```
TypeError: source.setEngine is not a function
    at Web3ProviderEngine.addProvider (D:\Work\projects\nft\bloodhound-opensea-api-wrapper\node_modules\web3-provider-engine\index.js:68:10)
    at Object.<anonymous> (D:\Work\projects\nft\bloodhound-opensea-api-wrapper\server.js:36:16)
```

## Environment

* Operating System: Windows 10
* Ethereum client: infura
* Truffle version (`truffle version`):
* node version (`node --version`):v14.15.4
* npm version (`npm --version`):  n6.14.10

**Comment by eggplantzzz** [comment]
@cycorax12 hdwallet-provider should be used as a provider, not as a subprovider for web3-provider-engine. So you could provide it to web3 during instantiation like you have commented out in your code example.

**Comment by haltman-at** [comment]
Since it seems like a solution has been provided here, I'm going to close this for issue maintenance.  Let us know if there's still a problem and we can reopen this.  Thanks!
