### ISSUE TITLE
Cannot find module 'json-stable-stringify'

### ISSUE THREAD

**Issue by PpRarssa** [trufflesuite/truffle#4387]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

Cannot find module 'json-stable-stringify'

## Steps to Reproduce

I was trying to make a project (petshop ) which is on truffle website step by step and when I tried truffle test following error popped up

## Expected Behavior

test smart contracts

## Actual Results

`Error: Cannot find module 'json-stable-stringify'
Require stack:
- C:\Users\parss\AppData\Roaming\npm\node_modules\truffle\node_modules\@truffle\debugger\dist\debugger.js
- C:\Users\parss\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.exports (C:\Users\parss\AppData\Roaming\npm\node_modules\truffle\node_modules\@truffle\debugger\dist\external "@truffle\abi-utils":1:8)
    at n (C:\Users\parss\AppData\Roaming\npm\node_modules\truffle\node_modules\@truffle\debugger\dist\webpack\bootstrap:9:5)
    at Object.<anonymous> (C:\Users\parss\AppData\Roaming\npm\node_modules\truffle\node_modules\@truffle\debugger\dist\debugger.js:1:2639)
    at n (C:\Users\parss\AppData\Roaming\npm\node_modules\truffle\node_modules\@truffle\debugger\dist\webpack\bootstrap:9:5)
    at Object.<anonymous> (C:\Users\parss\AppData\Roaming\npm\node_modules\truffle\node_modules\@truffle\debugger\dist\debugger.js:1:98991)
    at n (C:\Users\parss\AppData\Roaming\npm\node_modules\truffle\node_modules\@truffle\debugger\dist\webpack\bootstrap:9:5)
    at Object.<anonymous> (C:\Users\parss\AppData\Roaming\npm\node_modules\truffle\node_modules\@truffle\debugger\dist\debugger.js:1:97854)
    at n (C:\Users\parss\AppData\Roaming\npm\node_modules\truffle\node_modules\@truffle\debugger\dist\webpack\bootstrap:9:5)
    at Object.get (C:\Users\tyler\projects\truffle\node_modules\colors\lib\colors.js:178:7)
    at n (C:\Users\parss\AppData\Roaming\npm\node_modules\truffle\node_modules\@truffle\debugger\dist\webpack\bootstrap:9:5)
    at object (C:\Users\parss\AppData\Roaming\npm\node_modules\truffle\node_modules\@truffle\debugger\dist\webpack\bootstrap:76:36)
    at C:\Users\parss\AppData\Roaming\npm\node_modules\truffle\node_modules\@truffle\debugger\dist\webpack\bootstrap:76:56
Truffle v5.4.14 (core: 5.4.14)
Node v14.18.0`

## Environment

* Operating System: Windows 10
* Ethereum client:
* Truffle version (`5.4.14`):
* node version (`14.18.0`):
* npm version (`6.14.15`):

**Comment by PpRarssa** [comment]
may i know what does the tag (needs reproduced )mean?

**Comment by cds-amal** [comment]
**needs reproduced** generally means we need steps to reproduce the error/issue. I plan to try reproducing this on Windows 11 and report what, if anything was learned. If I'm unsuccessful I will comment and ask for more specific steps.

**Comment by haltman-at** [comment]
@PpRarssa Do you have a reproduction project we could check out, with steps for causing the error within the project?  Thanks!

**Comment by eggplantzzz** [comment]
Closing for issue maintenance.
