### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by yieniggu** [trufflesuite/truffle#4421]
- [ X] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I'm trying to test a contract multiple times on truffle using javascript. The first test runs just fine, but the second gives me error no matter what's inside of it.

Here is my full testing code:

```
const LandContract = artifacts.require("LandNFT");
const IlandContract = artifacts.require("ILandNFT");
const LockedNFT = artifacts.require("LockedNFT");

const { assert } = require("chai");
const chai = require("chai");
const BN = web3.utils.BN;

const chaiBN = require("chai-bn")(BN);
chai.use(chaiBN);

const chaiAsPromised = require("chai-as-promised");
const { contracts_build_directory } = require("../truffle-config");
chai.use(chaiAsPromised);

const expect = chai.expect;

contract("NFT test", async (accounts) => {
  // Lets use 3 accounts to test functionalitites
  const [contractOwner, landOwner, buyer] = accounts;

  it("should mint a new nft and send it to the landOwner", async () => {
    // await for nft contract deployment
    let landContract = await LandContract.deployed();

    let newNft = {
      price: new BN(web3.utils.toWei(new BN(1000), "ether")),
      name: "Test",
    };

    // Lets mint a new nft to 2nd account
    let result = await landContract.safeMint(
      landOwner,
      newNft.price,
      newNft.name
    );

    // Lets test first the total supply of nfts
    expect(landContract.totalSupply()).to.eventually.be.a.bignumber.equal(
      new BN(1)
    );

    // Now lets test that the landOwner has the minted nft
    expect(
      landContract.balanceOf(landOwner)
    ).to.eventually.be.a.bignumber.equal(new BN(1));

    // Now lets test that the tokenId of the owner is 1
    expect(
      landContract.tokenOfOwnerByIndex(landOwner, new BN(1))
    ).to.eventually.be.a.bignumber.equal(new BN(1));
  });

  it("should set the proper attributes to a minted nft", async () => {
    // await for nft contract deployment
    let landContract = await LandContract.deployed();

    let newNft = {
      price: new BN(web3.utils.toWei(new BN(1000), "ether")),
      name: "Test",
    };

    // Lets mint a new nft to 2nd account
    let result = await landContract.safeMint(
      landOwner,
      newNft.price,
      newNft.name
    );

    // Now lets test that the minted nft has the right attributes
    /*let mintedNftInfo = await landContract.getNftInfo(new BN(1));
    mintedNftInfo.state = mintedNftInfo.state.toString();

    let expectedResult = {
      price: newNft.price,
      name: newNft.name,
      state: "Active",
      landOwner: landOwner,
    };

    expect(mintedNftInfo.name).to.be.equal(newNft.name);
    //expect(mintedNftInfo).to.deep.equal(expectedResult);*/
  });
});
```

And this is the output log:

```
 Contract: NFT test
    ✓ should mint a new nft and send it to the landOwner (128ms)
    1) should set the proper attributes to a minted nft
    > No events were emitted


  1 passing (1s)
  1 failing

  1) Contract: NFT test
       should set the proper attributes to a minted nft:
     Uncaught Error: Returned error: VM Exception while processing transaction: revert ERC721Enumerable: owner index out of bounds
      at Context.<anonymous> (test/alltests.js:50:20)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)



UnhandledRejections detected
Promise {
  <rejected> Error: Returned error: VM Exception while processing transaction: revert ERC721Enumerable: owner index out of bounds
      at Context.<anonymous> (test/alltests.js:50:20)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    data: {
      '0x9248d0f13806249989287b3a1b2037446dae2fce44243b6fad24fbca4e45abcc': [Object],
      stack: 'RuntimeError: VM Exception while processing transaction: revert ERC721Enumerable: owner index out of bounds\n' +
        '    at Function.RuntimeError.fromResults (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/ganache-core/lib/utils/runtimeerror.js:94:1)\n' +
        '    at /home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/ganache-core/lib/blockchain_double.js:568:1',
      name: 'RuntimeError'
    },
    hijackedStack: 'Error: Returned error: VM Exception while processing transaction: revert ERC721Enumerable: owner index out of bounds\n' +
      '    at Object.ErrorResponse (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/lib/errors.js:28:1)\n' +
      '    at /home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-core-requestmanager/lib/index.js:303:1\n' +
      '    at /home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1\n' +
      '    at XMLHttpRequest.request.onreadystatechange (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/lib/index.js:98:1)\n' +
      '    at XMLHttpRequestEventTarget.dispatchEvent (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)\n' +
      '    at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)\n' +
      '    at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpResponseEnd (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)\n' +
      '    at IncomingMessage.<anonymous> (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)\n' +
      '    at IncomingMessage.emit (node:events:377:35)\n' +
      '    at endReadableNT (node:internal/streams/readable:1312:12)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
    uncaught: true
  }
} Error: Returned error: VM Exception while processing transaction: revert ERC721Enumerable: owner index out of bounds
    at Context.<anonymous> (test/alltests.js:50:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  data: {
    '0x9248d0f13806249989287b3a1b2037446dae2fce44243b6fad24fbca4e45abcc': {
      error: 'revert',
      program_counter: 2894,
      return: '0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002b455243373231456e756d657261626c653a206f776e657220696e646578206f7574206f6620626f756e6473000000000000000000000000000000000000000000',
      reason: 'ERC721Enumerable: owner index out of bounds'
    },
    stack: 'RuntimeError: VM Exception while processing transaction: revert ERC721Enumerable: owner index out of bounds\n' +
      '    at Function.RuntimeError.fromResults (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/ganache-core/lib/utils/runtimeerror.js:94:1)\n' +
      '    at /home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/ganache-core/lib/blockchain_double.js:568:1',
    name: 'RuntimeError'
  },
  hijackedStack: 'Error: Returned error: VM Exception while processing transaction: revert ERC721Enumerable: owner index out of bounds\n' +
    '    at Object.ErrorResponse (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/lib/errors.js:28:1)\n' +
    '    at /home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-core-requestmanager/lib/index.js:303:1\n' +
    '    at /home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1\n' +
    '    at XMLHttpRequest.request.onreadystatechange (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/lib/index.js:98:1)\n' +
    '    at XMLHttpRequestEventTarget.dispatchEvent (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)\n' +
    '    at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)\n' +
    '    at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpResponseEnd (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)\n' +
    '    at IncomingMessage.<anonymous> (/home/basti/.nvm/versions/node/v16.2.0/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)\n' +
    '    at IncomingMessage.emit (node:events:377:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1312:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
  uncaught: true
}
```

Honestly I have no clue of what's going on. If anyone could help me solve this would be much appreciated. Thanks in advance!

**Comment by MicaiahReid** [comment]
Hi @yieniggu, this runtime error `VM Exception while processing transaction: revert ERC721Enumerable: owner index out of bounds` points to this being an issue with your code or tests rather than an issue with Truffle. You can use [Truffle's debugger](https://www.trufflesuite.com/docs/truffle/getting-started/debugging-your-contracts) to step through the failing transaction.

If you think this is in fact a Truffle issue, please provide details on how to reproduce and we'll look into it.

**Comment by shahafn** [comment]
This in fact happens to me when upgrading Truffle from 5.1.26 to 5.4.18/19.

**Comment by haltman-at** [comment]
OK, we're going to close this for issue maintenance.  @yienniggu, feel free to let us know if there's still a problem here.  Thanks!

**Comment by haltman-at** [comment]
@shahafn That sounds like an unrelated issue.  Would you mind opening a new issue for that?  Thank you!
