### ISSUE TITLE
"Migrations" -- only replay-protected (EIP-155) transactions allowed over RPC.

### ISSUE THREAD

**Issue by 1b1og-com** [trufflesuite/truffle#4474]
truffle migrate --network polygon

Compiling your contracts...
===========================
✔ Fetching solc version list from solc-bin. Attempt #1
✔ Fetching solc version list from solc-bin. Attempt #1
> Everything is up to date, there is nothing to compile.

Starting migrations...
======================
> Network name:    'polygon'
> Network id:      137
> Block gas limit: 20137109 (0x1334495)

1_initial_migrations.js
=======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- only replay-protected (EIP-155) transactions allowed over RPC.

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:70:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:56:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:258:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:223:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:183:1)
Truffle v5.4.22 (core: 5.4.22)
Node v14.17.6

**Comment by fainashalts** [comment]
This may be a Truffle issue, thanks for bringing it up @1b1og-com! We'll look into it. Truffle should be sending EIP-155 compliant signatures. 

While we look into this, please make sure you have the latest `@truffle/hdwallet-provider` package installed if you are using it, as we believe recent versions have addressed EIP-155.

**Comment by kevinweaver** [comment]
@1b1og-com I wasn't able to reproduce this issue, migrating on both mumbai testnet and polygon mainnet worked for me.  Are you able to share a repo link?

**Comment by MicaiahReid** [comment]
@1b1og-com Closing for issue maintenance. Please reopen a new issue if this is still a problem for you.
