### ISSUE TITLE
debugger throws error while stepping w/ `;` 

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/truffle#4478]
The following error occurred while [stepping through instructions](https://asciinema.org/a/DqmrxMnzSca8yiVPEn4ZgExPu) for a metacoin transaction.

```
Uncaught TypeError: Cannot read property 'name' of undefined                                                                                                                                                          
    at processTicksAndRejections (internal/process/task_queues.js:95:5)                                                                                                                                               
    at DebugInterpreter.interpreter (/home/amal/work/truffle/packages/core/lib/debug/interpreter.js:636:24)                                                                                                           
    at DebugPrinter.printInstruction (/home/amal/work/truffle/packages/core/lib/debug/printer.js:239:41)                                                                                                              
    at Object.formatInstruction (/home/amal/work/truffle/packages/debug-utils/index.js:543:38) 
```

## reproduction steps
You'll need two terminals.

- `$ truffle unbox metacoin`
- edit `truffle-config.json` to have the following network entry
  ```
      test: {
      host: "127.0.0.1",
      port: 9545,
      network_id: "*"
    }
- in terminal 1
  ```
  $ truffle develop
  truffle(develop)> migrate
  ```
- grab the last transaction hash from terminal 1 output
- in terminal 2, start the debugger
  ```
  $ truffle debug --network test <txn hash>
  ```
- press enter a few times, then step with `;` until the error occurs

## versions
Truffle v5.4.22 (core: 5.4.22)
Solidity v0.5.16 (solc-js)
Node v14.18.1
Web3.js v1.5.3

**Comment by haltman-at** [comment]
Oh, looks like this never got closed when the fix for it was released.  Closing this.
