### ISSUE TITLE
ubuntu truffle serve error！！！

### ISSUE THREAD

**Issue by acodercat** [trufflesuite/truffle#449]
Serving static assets in ./build on port 8080...
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: watch /root/truffle/app EPERM
    at exports._errnoException (util.js:1050:11)
    at FSWatcher.start (fs.js:1398:19)
    at Object.fs.watch (fs.js:1424:11)
    at createFsWatchInstance (/usr/lib/node_modules/truffle/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/usr/lib/node_modules/truffle/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/usr/lib/node_modules/truffle/node_modules/chokidar/lib/nodefs

**Comment by DiscRiskandBisque** [comment]
Try increasing the maximum number of watches:
`echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

Closing this for now, but if the above fails please re-open!

**Comment by blackbutler756** [comment]
facing error with :

```
>truffle serve 

Serving static assets in ./build on port 8080...
/usr/lib/node_modules/truffle/build/cli.bundled.js:124978
  return (new fsevents(path)).on('fsevent', callback).start();
          ^

TypeError: fsevents is not a constructor
    at createFSEventsInstance (/usr/lib/node_modules/truffle/build/cli.bundled.js:124978:11)
    at setFSEventsListener (/usr/lib/node_modules/truffle/build/cli.bundled.js:125032:16)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (/usr/lib/node_modules/truffle/build/cli.bundled.js:125196:16)
    at FSWatcher.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:125330:25)
    at LOOP (fs.js:1773:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I used webpack
