### ISSUE TITLE
`Error: spawnSync /bin/sh ENOBUFS` when compiling Colony with native compiler

### ISSUE THREAD

**Issue by cameel** [trufflesuite/truffle#4499]
## Issue

I'm trying to compile the [Colony](https://github.com/JoinColony/colonyNetwork) contracts using the native compiler and I'm running into an error:
```
Error: spawnSync /bin/sh ENOBUFS
```
The same contracts compile just fine when using an emscripten binary.

This seems to have already happened before (#3140) and the buffer size was increased to 10 MB in #3002. Something must have changed since then because this size seems insufficient now.

## Steps to Reproduce
```bash
git clone https://github.com/JoinColony/colonyNetwork.git
cd colonyNetwork/
git submodule update --init

curl -OL https://binaries.soliditylang.org/linux-amd64/solc-linux-amd64-v0.7.3+commit.9bfce1f6
chmod +x solc-linux-amd64-v0.7.3+commit.9bfce1f6

# NOTE: With https://github.com/trufflesuite/truffle/issues/4490 we could avoid the shell magic here
function solc { "$__SOLC_NATIVE_BINARY" "$@"; }
export -f solc
export __SOLC_NATIVE_BINARY=$(realpath solc-linux-amd64-v0.7.3+commit.9bfce1f6)

cat <<EOF >> truffle.js
module.exports['compilers']['solc']['version'] = "native";
module.exports['compilers']['solc']['docker'] = false;
module.exports['compilers']['solc']['parser'] = null;
EOF

npm install --legacy-peer-deps
npm update truffle
npx truffle compile
```

For the record, the top the main branch in the Colony repo while I'm testing it is at [`e06f7815902801c6b9cc66da8dbfa2aee2b9f874`](https://github.com/JoinColony/colonyNetwork/commit/e06f7815902801c6b9cc66da8dbfa2aee2b9f874).

## Expected Behavior

Compilation finishes without errors.

## Actual Results
```
Error: spawnSync /bin/sh ENOBUFS
    at Object.spawnSync (node:internal/child_process:1081:20)
    at spawnSync (node:child_process:812:24)
    at execSync (node:child_process:895:15)
    at Object.compile (/tmp/colonyNetwork/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/compilerSupplier/loadingStrategies/Native.js:14:1)
    at /tmp/colonyNetwork/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/run.js:200:1
    at Generator.next (<anonymous>)
    at /tmp/colonyNetwork/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/run.js:7:1
    at new Promise (<anonymous>)
    at exports.modules.571193.__awaiter (/tmp/colonyNetwork/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/run.js:3:1)
    at invokeCompiler (/tmp/colonyNetwork/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/run.js:187:1)
    at /tmp/colonyNetwork/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/run.js:41:46
    at Generator.next (<anonymous>)
    at /tmp/colonyNetwork/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/run.js:7:1
    at new Promise (<anonymous>)
    at exports.modules.571193.__awaiter (/tmp/colonyNetwork/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/run.js:3:1)
    at run (/tmp/colonyNetwork/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/run.js:19:1)
    at Object.<anonymous> (/tmp/colonyNetwork/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/index.js:148:1)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/colonyNetwork/node_modules/truffle/build/webpack:/packages/compile-solidity/dist/index.js:4:42)
Truffle v5.4.23 (core: 5.4.23)
Node v17.1.0
```

## Environment

* Operating System: Arch Linux
* Truffle version: v5.4.23 (reproducible on v5.1.48 as well)
* node version: v17.1.0 (reproducible on v12.22.7 as well)
* npm version 8.1.3

**Comment by fainashalts** [comment]
Hi @cameel you may want to try using a shell script instead of a bash function -- spawnSync in Truffle is set up to handle a shell script or a binary executable. Please let us know if that helps!

**Comment by cameel** [comment]
Unfortunately it did not help. I get the same error replacing the part that exports the function with either of these:

wrapper script:
```bash
echo '#!/usr/bin/bash' >> solc
echo "$(realpath solc-linux-amd64-v0.7.3+commit.9bfce1f6) \"\$@\"" >> solc
chmod +x solc
export PATH="$PWD:$PATH"
```

binary:
```bash
mv solc-linux-amd64-v0.7.3+commit.9bfce1f6 solc
export PATH="$PWD:$PATH"
```

**Comment by kevinweaver** [comment]
Thanks @cameel for bringing this to our attention!  We've added this to our backlog to investigate further.
