### ISSUE TITLE
Optimism-box testnet migrate fails

### ISSUE THREAD

**Issue by kevinweaver** [trufflesuite/truffle#4564]
## Issue

Using the optimism box fails while running a migration.  I only tested on testnet, not sure about local or mainnet.

## Steps to Reproduce

```shell
truffle unbox optimism-box
truffle compile --config=truffle-config.ovm.js --network=optimistic_kovan 
truffle migrate --config=truffle-config.ovm.js --network=optimistic_kovan --skip-dry-run
```

## Expected Behavior

It should migrate on testnet.

## Actual Results

```shell
/optimism-box/node_modules/@trufflesuite/web3-provider-engine/index.js:163
        cb(null, null)
        ^
Error: Could not find block
```

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):  v5.4.16
* node version (`node --version`): v14.18.0
* npm version (`npm --version`): 6.14.15

**Comment by fainashalts** [comment]
Using Node 12.17.0, I also fail to migrate but get a different error. Stacktrace here: 

```
TypeError: Cannot read property 'replace' of undefined
    at HDWalletProvider.ethUtilValidation (/Users/fainashalts/smokeOptimism/node_modules/@truffle/hdwallet-provider/src/index.ts:330:53)
    at new HDWalletProvider (/Users/fainashalts/smokeOptimism/node_modules/@truffle/hdwallet-provider/src/index.ts:111:12)
    at Object.provider (/Users/fainashalts/smokeOptimism/truffle-config.ovm.js:64:16)
    at Object.getProvider (/usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/index.js:20:1)
    at Object.create (/usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/index.js:13:1)
    at TruffleConfig.get [as provider] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/config/dist/configDefaults.js:235:1)
    at Object.detect (/usr/local/lib/node_modules/truffle/build/webpack:/packages/environment/environment.js:19:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:201:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:183:1)
```

**Comment by cds-amal** [comment]
@fainashalts says this is no longer the case.
