### ISSUE TITLE
Incompatibility with Node JS 8

### ISSUE THREAD

**Issue by drhouse7** [trufflesuite/truffle#457]
## Issue

I tried to install globally  **Truffle** without success

## Steps to Reproduce

npm install -g truffle

## Expected Behavior

Install Truffle

## Actual Results

Unable to install Truffle with this log file:

```
55721 verbose lifecycle wrtc@0.0.61~install: PATH: C:\Users\simon\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\simon\AppData\Roaming\npm\node_modules\truffle\node_modules\wrtc\node_modules\.bin;C:\Users\simon\AppData\Roaming\npm\node_modules\truffle\node_modules\.bin;C:\Users\simon\AppData\Roaming\npm\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Calibre2\;C:\Program Files\Git\cmd;C:\Windows\System32\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Geth;C:\Users\simon\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\simon\AppData\Local\Programs\Python\Python36\;C:\Users\simon\AppData\Local\atom\bin;C:\Users\simon\AppData\Roaming\npm;C:\Program Files (x86)\Microsoft VS Code\bin
55722 verbose lifecycle wrtc@0.0.61~install: CWD: C:\Users\simon\AppData\Roaming\npm\node_modules\truffle\node_modules\wrtc
55723 silly lifecycle wrtc@0.0.61~install: Args: [ '/d /s /c', 'node-pre-gyp install --fallback-to-build' ]
55724 silly lifecycle wrtc@0.0.61~install: Returned: code: 1  signal: null
55725 info lifecycle wrtc@0.0.61~install: Failed to exec install script
55726 verbose unlock done using C:\Users\simon\AppData\Roaming\npm-cache\_locks\staging-c80dd6836462856c.lock for C:\Users\simon\AppData\Roaming\npm\node_modules\.staging
55727 verbose stack Error: wrtc@0.0.61 install: `node-pre-gyp install --fallback-to-build`
55727 verbose stack Exit status 1
55727 verbose stack     at EventEmitter.<anonymous> (C:\Users\simon\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:283:16)
55727 verbose stack     at emitTwo (events.js:125:13)
55727 verbose stack     at EventEmitter.emit (events.js:213:7)
55727 verbose stack     at ChildProcess.<anonymous> (C:\Users\simon\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
55727 verbose stack     at emitTwo (events.js:125:13)
55727 verbose stack     at ChildProcess.emit (events.js:213:7)
55727 verbose stack     at maybeClose (internal/child_process.js:887:16)
55727 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
55728 verbose pkgid wrtc@0.0.61
55729 verbose cwd C:\Windows\system32
55730 verbose Windows_NT 6.3.9600
55731 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\simon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "truffle"
55732 verbose node v8.0.0
55733 verbose npm  v5.0.3
55734 error code ELIFECYCLE
55735 error errno 1
55736 error wrtc@0.0.61 install: `node-pre-gyp install --fallback-to-build`
55736 error Exit status 1
55737 error Failed at the wrtc@0.0.61 install script.
```

## Environment

* Operating System: Win 8.1
* node version: 8.0.0
* npm version: 5.0.3

**Comment by tcoulter** [comment]
Hi there. Thanks for the issue. Can you check out [our latest blog post](http://truffleframework.com/blog/how-were-making-installation-issues-a-thing-of-the-past) and try out the beta version of Truffle? My guess is that'll fix your issue. Cheers!
