### ISSUE TITLE
error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by ludekvodicka** [trufflesuite/truffle#4570]
Hello,

I just started with Solidity learning and trying Truffle. Unfortunately, I'm not able to solve the error 0308010C

`Error: error:0308010C:digital envelope routines::unsupported`

I found that this issue is caused by the latest nodejs and that can be solved with `--openssl-legacy-provider` switch. Unfortunately I'm not able to find out how/where to set it. 

I tried windows environment but without success and I can't find `package.json` where I should set it. 

Can I ask for help with that? I'm c++ dev and nodeJs environment is completely new for me so maybe I'm overlooking something. Thanks

```
PS Q:\Solidity\test01> truffle develop
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at hash160 (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\ethereum-cryptography\vendor\hdkey-without-crypto.js:249:1)
    at HDKey.set (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\ethereum-cryptography\vendor\hdkey-without-crypto.js:50:1)
    at Function.HDKey.fromMasterSeed (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\ethereum-cryptography\vendor\hdkey-without-crypto.js:194:1)
    at Function.EthereumHDKey.fromMasterSeed (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\ethereumjs-wallet\dist\hdkey.js:16:1)
    at Object.getAccountsInfo (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\mnemonics\mnemonic.js:45:1)
    at Object.module.exports [as run] (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\develop\run.js:30:44)
    at Command.run (C:\Users\user\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command.js:189:1)
Truffle v5.4.25 (core: 5.4.25)
Node v17.3.0
```

Versions:

```
Npm 8.3.0
Truffle v5.4.25 (core: 5.4.25)
Solidity - 0.8.4 (solc-js)
Node v17.3.0
Web3.js v1.5.3
```

Windows 10
VSCode

**Comment by kevinweaver** [comment]
Hi @ludekvodicka, unfortunately, Truffle does not support Node 17. Odd node versions are not stable, as they are meant for library maintainers to use to find bugs for the next even (stable) version. You can try downgrading to node 16, though we do not yet officially support it, so it may be necessary or safest to use node 14. Please let us know if you have any issues with this. Thanks!

**Comment by MicaiahReid** [comment]
Closing for issue maintenance. Please reopen or create a new issue if this is still happening.

**Comment by LeonardoAmerio** [comment]
> Hola @ludekvodicka , desafortunadamente, Truffle no es compatible con el nodo 17. Las versiones de nodos impares no son estables, ya que están destinadas a los mantenedores de bibliotecas para encontrar errores para la siguiente versión par (estable). Puede intentar bajar al nodo 16, aunque todavía no lo admitimos oficialmente, por lo que puede ser necesario o más seguro usar el nodo 14. Infórmenos si tiene algún problema con esto. ¡Gracias!

Me ayudo mucho esta respuesta. Instale Node.js 16.14.2 y se me soluciono el problema!

**Comment by moonman369** [comment]
Note:
- Truffle unboxing might take some time based on device specs.
- Most importantly give it some f****** time, to download all the dependencies.
- DO NOT INTERRUPT till you see `Unbox successful, sweet!`
- Follow the necessary steps i.e `truffle develop` -> `migrate` -> `open new terminal` -> `cd client`
- First run `npm test` to test if everything is working properly

ATTENTION:
- Make sure the folder containing the truffle box doesn't have any other node_modules in it (learnt it the hard way). This might cause the dependencies to clash.
