### ISSUE TITLE
Pet-shop Tutorial Tests failing

### ISSUE THREAD

**Issue by garyns** [trufflesuite/truffle#4576]
- [X] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

Following tutorial, `truffle test` fails.

## Steps to Reproduce

* Follow tutorial
* At section https://trufflesuite.com/tutorial/index.html#running-the-tests
* `truffle test` results in failures (full output in below).

## Expected Behavior

I'd expect it to work, given it's the tutorial.

## Actual Results

```
g@mbp:etherium/truffle_tutorial $ truffle compile

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

g@mbp:etherium/truffle_tutorial $ truffle migrate

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'development'
> Network id:      5777
> Block gas limit: 6721975 (0x6691b7)


1_initial_migration.js
======================

   Replacing 'Migrations'
   ----------------------
   > transaction hash:    0xa81ff322e2e3cb0451c6dd1158f0df0428665d7f9ab618c0cbaebdbe6f5f8afa
   > Blocks: 0            Seconds: 0
   > contract address:    0xcb40CD93c1367590E79bE3E4c80529d06D2F3269
   > block number:        3
   > block timestamp:     1640904107
   > account:             0x384685cFb741BDBae420720Ec8729668a84a51C8
   > balance:             99.99147552
   > gas used:            191943 (0x2edc7)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00383886 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00383886 ETH


Summary
=======
> Total deployments:   1
> Final cost:          0.00383886 ETH


g@mbp:etherium/truffle_tutorial $ truffle test
Using network 'development'.


Compiling your contracts...
===========================
> Compiling ./test/TestAdoption.sol
> Artifacts written to /var/folders/90/k7c519815_355mtmsrls64b40000gn/T/test--67223-VC67hr2zPWI5
> Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang



  TestAdoption
    1) "before all" hook: prepare suite for "testUserCanAdoptPet"

  Contract: Adoption
    2) "before all" hook in "Contract: Adoption"


  0 passing (7s)
  2 failing

  1) TestAdoption
       "before all" hook: prepare suite for "testUserCanAdoptPet":
     Error: while migrating TestAdoption: Returned error: VM Exception while processing transaction: revert
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:93:5)
      at Context.deployTestDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/SolidityTest.js:203:1)
      at Context.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/testing/SolidityTest.js:22:1)

  2) Contract: Adoption
       "before all" hook in "Contract: Adoption":
     Error: Adoption has not been deployed to detected network (network/artifact mismatch)
      at Object.checkNetworkArtifactMatch (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/utils/index.js:249:1)
      at Function.deployed (/usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/contract/constructorMethods.js:83:1)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:93:5)
      at Context.<anonymous> (test/testAdoption.test.js:8:18)
```

## Environment

* Operating System:  Mac 12.0.1
Truffle v5.4.26 (core: 5.4.26)
Solidity v0.5.16 (solc-js)
Node v15.3.0
Web3.js v1.5.3

**Comment by kevinweaver** [comment]
It looks like this was resolved by support in ticket 660112 and turned out to be a file naming issue.  Closing this out!
