### ISSUE TITLE
Socket Hang Up

### ISSUE THREAD

**Issue by billtlee** [trufflesuite/truffle#4598]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I am trying to deploy https://github.com/billtlee/tribute-contracts to polygon mainnet using alchemy and am getting 

Compiling your contracts...
===========================
Error: socket hang up
    at createHangUpError (_http_client.js:332:15)
    at TLSSocket.socketOnEnd (_http_client.js:435:23)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

## Steps to Reproduce

clone repo
create .env file with the following settings
TRUFFLE_MNEMONIC="your mnemonic"
COUPON_CREATOR_ADDR=0x61...
ETHERSCAN_API_KEY=AHV5CYTTC5ESGP55ABZVFCK7WPD5V53GUP
ETH_NODE_URL=wss://polygon-mainnet.g.alchemy.com/v2/your-api-key
DEBUG_CONTRACT_VERIFICATION=true
DAO_NAME=Some DAO
DAO_OWNER_ADDR=0x61...
ERC20_TOKEN_SYMBOL=ABC
ERC20_TOKEN_NAME=Some Name
ERC20_TOKEN_DECIMALS=0
VOTING_PERIOD_SECONDS=3600
GRACE_PERIOD_SECONDS=900
REMOTE_GRAPH_NODE=true

## Expected Behavior

What you expected to happen.
Deployed contracts

## Actual Results

What actually happened. Please give examples and support it with screenshots, copied output or error messages.

Compiling your contracts...
===========================
Error: socket hang up
    at createHangUpError (_http_client.js:332:15)
    at TLSSocket.socketOnEnd (_http_client.js:435:23)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

## Environment

* Operating System: Ubuntu 20.04
* Ethereum client: alchemy
* Truffle version (`truffle version`): 5.3.2
* node version (`node --version`): 10.19.0
* npm version (`npm --version`): 6.14.4

**Comment by billtlee** [comment]
The first time I ran the migration, it stopped because I missed a setting
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'polygon'
> Network id:      137
> Block gas limit: 17700840 (0x10e17e8)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0x56f45ffd6157fde436e7cd0334b7b182e3466edabf3edf3d5845413ef8876f70
- Blocks: 0            Seconds: 0
   > Blocks: 4            Seconds: 12
   > contract address:    0xB70Bf3D8B6f2022bE33ddbce8762A816571a1806
   > block number:        23404738
   > block timestamp:     1641476885
   > account:             0x61A3d01D4F7Ab602E44F24E7D139395c67069a05
   > balance:             27.2881531
   > gas used:            139358 (0x2205e)
   > gas price:           550 gwei
   > value sent:          0 ETH
   > total cost:          0.0766469 ETH


- Saving migration to chain.
   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:           0.0766469 ETH


2_deploy_contracts.js
=====================
### Deployment start at: 2022-01-06T13:48:29.726Z

Error: Missing env var: MAX_MEMBERS
    at getEnvVar (/home/docker/tribute-contracts/migrations/2_deploy_contracts.js:388:33)
    at deployPolygonDao (/home/docker/tribute-contracts/migrations/2_deploy_contracts.js:319:17)
    at module.exports (/home/docker/tribute-contracts/migrations/2_deploy_contracts.js:46:19)
    at Migration._load (/home/docker/tribute-contracts/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:60:1)
Truffle v5.3.2 (core: 5.3.2)
Node v10.19.0

Then I tried it again and it won't work any longer and kept getting that error
