### ISSUE TITLE
Project migrating fine with Mumbai testnet but not working with Matic mainnet.

### ISSUE THREAD

**Issue by mustafa-boorenie** [trufflesuite/truffle#4599]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

I have been trying to migrate my truffle ERC20 token to MATIC's main net. However I keep getting this error:

It seems that the running: $ truffle migrate --network matic (-- reset) OR $ truffle deploy --network matic (-- reset)
Does not connect with the MATIC chain. Regardless, it works fine when uploading to the Mumbai testnet. 

My truffle-config.js file:

```
`const HDWalletProvider = require('@truffle/hdwallet-provider');
require('dotenv').config();

const mnemonic = process.env.MNEMONIC;
const eth_key = process.env.ETHERSCAN_API_KEY;
const poly_key = process.env.POLY_API_KEY;

module.exports = {  
  api_keys : {  

    etherscan : eth_key,    // Add Etherscan API Key here
    polygonscan :  poly_key // Add Polygonscan API Key here
  },

  networks: {
    mumbai: {
      provider: () => new HDWalletProvider(mnemonic, `https://polygon-mumbai.infura.io/v3/${process.env.INFURA_KEY}`),
      network_id: 80001,
      confirmations: 2,
      timeoutBlocks: 200,
      skipDryRun: true
    },

    matic: {
      provider: () => new HDWalletProvider(mnemonic, `https://polygon-mainnet.infura.io/v3/${process.env.INFURA_KEY}`),
      network_id: 137,    // # Polygon network ID (default: 137)
      confirmations: 0,   // # of blocks to confirm deployment (default : 0)
      timeoutBlocks: 200, // # of blocks before deployment time runs out (default : 200 )
      skipDryRun: true,   // Simulated dry-run (default: false)
      networkCheckTimeout: 1000000
    },
  },

  mocha: {
    // timeout: 100000
  },

  compilers: {
    solc: {
      version: "0.8.9",    // Fetch exact version from solc-bin (default: truffle's version)
      // docker: true,        // Use "0.5.1" you've installed locally with docker (default: false)
      // settings: {          // See the solidity docs for advice about optimization and evmVersion
       optimizer: {
         enabled: true,
         runs: 200
       },
    }
  },

  plugins : [
    // Plug-in added here to improve verification efficiency
    // !!!!REMEMBER TO ADD ETHERSCAN API KEY!!!!
    'truffle-plugin-verify'
  ]

};`
```

Using this, running truffle deploy --network matic should deploy the contract, instead it displays:

/Users/mustafaboorenie/desertcoin/node_modules/web3-provider-engine/index.js:160
        cb(null, null)
        ^
Error: Could not find block
    at /Users/mustafaboorenie/desertcoin/node_modules/web3-provider-engine/index.js:59:28
    at afterRequest (/Users/mustafaboorenie/desertcoin/node_modules/web3-provider-engine/index.js:160:9)
    at /Users/mustafaboorenie/desertcoin/node_modules/web3-provider-engine/index.js:175:12
    at /Users/mustafaboorenie/desertcoin/node_modules/web3-provider-engine/index.js:234:9
    at /Users/mustafaboorenie/desertcoin/node_modules/async/internal/once.js:12:16
    at replenish (/Users/mustafaboorenie/desertcoin/node_modules/async/internal/eachOfLimit.js:61:25)
    at /Users/mustafaboorenie/desertcoin/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/Users/mustafaboorenie/desertcoin/node_modules/async/eachLimit.js:43:36)
    at /Users/mustafaboorenie/desertcoin/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/mustafaboorenie/desertcoin/node_modules/web3-provider-engine/index.js:211:5)
    at Request._callback (/Users/mustafaboorenie/desertcoin/node_modules/web3-provider-engine/subproviders/rpc.js:72:5)
    at Request.self.callback (/Users/mustafaboorenie/desertcoin/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at Request.<anonymous> (/Users/mustafaboorenie/desertcoin/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (/Users/mustafaboorenie/desertcoin/node_modules/request/request.js:1076:12)

OR displays:

 message: 'ESOCKETTIMEDOUT',
  data: { originalError: { code: 'ESOCKETTIMEDOUT', connect: false } }
})
    at new NodeError (node:internal/errors:371:5)
    at Web3ProviderEngine.emit (node:events:379:17)
    at /Users/mustafaboorenie/desertcoin/node_modules/web3-provider-engine/index.js:54:14
    at afterRequest (/Users/mustafaboorenie/desertcoin/node_modules/web3-provider-engine/index.js:148:21)
    at /Users/mustafaboorenie/desertcoin/node_modules/web3-provider-engine/index.js:174:21
    at /Users/mustafaboorenie/desertcoin/node_modules/web3-provider-engine/index.js:232:9
    at /Users/mustafaboorenie/desertcoin/node_modules/async/internal/once.js:12:16
    at replenish (/Users/mustafaboorenie/desertcoin/node_modules/async/internal/eachOfLimit.js:61:25)
    at /Users/mustafaboorenie/desertcoin/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/Users/mustafaboorenie/desertcoin/node_modules/async/eachLimit.js:43:36)
    at /Users/mustafaboorenie/desertcoin/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/mustafaboorenie/desertcoin/node_modules/web3-provider-engine/index.js:211:5)
    at Request._callback (/Users/mustafaboorenie/desertcoin/node_modules/web3-provider-engine/subproviders/rpc.js:36:21)
    at self.callback (/Users/mustafaboorenie/desertcoin/node_modules/request/request.js:185:22)
    at Request.emit (node:events:390:28)
    at ClientRequest.<anonymous> (/Users/mustafaboorenie/desertcoin/node_modules/request/request.js:819:16)

OR displays this:

Error: Transaction has been reverted by the EVM:
    at Migration._deploy (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:99:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration._load (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:56:1)
    at Migration.run (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
    at Object.runMigrations (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.runAll (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:114:1)
    at Object.run (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:79:1)
    at runMigrations (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:258:1)
    at Object.run (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:223:1)
    at Command.run (/opt/homebrew/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:183:1)

Using, truffle migrate --network matic causes:

"Migrations" -- Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!.

Here is my system settings:

macOS Monterey 12.0.1
Truffle v5.4.18 (core: 5.4.18)
Solidity - 0.8.9 (solc-js)
Node v17.0.1
Web3.js v1.5.3

I've been losing quite a bit of cash trying to get this up so if someone could help me out I'd be really grateful. Thank you!!

**Comment by fainashalts** [comment]
Hi @mustafa-boorenie thanks for bringing this up! While I would set up the provider a tad differently (see the configuration [here](https://github.com/truffle-box/polygon-box/blob/main/truffle-config.polygon.js), what you have should work. 

There is a new game on the Polygon network that appears to be causing gas prices to spike and intermittent issues with connecting to the network. I suggest editing your config to match what I linked above, and trying again in a couple of days (or perhaps checking [here](https://polygonscan.com/gastracker) and trying when gas is low, which should hopefully . If I find out that the issue from the Polygon side is fixed, I will update here!

**Comment by mustafa-boorenie** [comment]
Thanks for your help. I was able to successfully deploy the contract during a time with low traffic. I hope that this issue gets resolved soon!

**Comment by fainashalts** [comment]
So glad it worked out @mustafa-boorenie! I'm closing this issue for maintenance but if you encounter any other problems please feel free to open a new one.
