### ISSUE TITLE
**HELP** Error("Could not find artifacts for " + import_path + " from any sources")

### ISSUE THREAD

**Issue by sashanclrp** [trufflesuite/truffle#4620]
So Basically I'm new in Web3 Development, this is supposed to be my first project, sorry if its silly.

So this is the Contract, saved in the contracts folder as **firstContract.sol**
```
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.4.22 <0.9.0;

contract HelloBlockchain {
    
    function sayHi() public pure returns (string memory) {
        return "!Hello, blockchain!";
    }

}
```
SO Yeah, pretty Basic...
The **firstContract.js** File in the migrations folder is

```
var helloBlockchain = artifacts.require("./contracts/firstContract.sol");

module.exports = function (deployer) {
	deployer.deploy(helloBlockchain)
}
```

And the outpur/error I'm having when using the command -> 
>truffle(development)> migrate

```
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'development'
> Network id:      1642129526530
> Block gas limit: 6721975 (0x6691b7)


2_firstContract.js
==================

/usr/local/lib/node_modules/truffle/build/459.bundled.js:27188
        throw new Error("Could not find artifacts for " + import_path + " from any sources");
        ^

Error: Could not find artifacts for contracts/firstContract from any sources
    at Resolver.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:60:1)
    at Object.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:172:1)
    at ResolverIntercept.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/ResolverIntercept.js:22:1)
    at /home/sashanclrp/Platzi/web3/preworkAppsBlockchain/firstSmartContract/migrations/2_firstContract.js:1:33
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
    at Object.file (/usr/local/lib/node_modules/truffle/build/webpack:/packages/require/require.js:94:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:44:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:76:1)
    at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:44:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1)

truffle(development)> migrate

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'development'
> Network id:      1642129526530
> Block gas limit: 6721975 (0x6691b7)


2_firstContract.js
==================

/home/sashanclrp/Platzi/web3/preworkAppsBlockchain/firstSmartContract/migrations/2_firstContract.js:3
export default function (deployer) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (node:vm:100:7)
    at Object.createScript (node:vm:257:10)
    at Object.file (/usr/local/lib/node_modules/truffle/build/webpack:/packages/require/require.js:93:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:44:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:76:1)
    at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:44:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1)

truffle(development)> migrate

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'development'
> Network id:      1642129526530
> Block gas limit: 6721975 (0x6691b7)


2_firstContract.js
==================

/usr/local/lib/node_modules/truffle/build/459.bundled.js:27188
        throw new Error("Could not find artifacts for " + import_path + " from any sources");
        ^

Error: Could not find artifacts for contracts/firstContract from any sources
    at Resolver.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:60:1)
    at Object.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:172:1)
    at ResolverIntercept.require (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/ResolverIntercept.js:22:1)
    at /home/sashanclrp/Platzi/web3/preworkAppsBlockchain/firstSmartContract/migrations/2_firstContract.js:1:33
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
    at Object.file (/usr/local/lib/node_modules/truffle/build/webpack:/packages/require/require.js:94:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:44:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:217:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:76:1)
    at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:44:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1)
```

Can Anyone guide me on how to solve this? Thanks!

**Comment by sashanclrp** [comment]
So basically I fix it my self -> 
The problem is that the file.sol and the file.js that calls the contract in the migration folder can't be named the same, it does'nt matter the extension itself.
This is weird, I really don't understand why, if anyone can explain me why would be wonderful. 

Anyways,
So, basically all I did was changing the migration file associated with the contract from firstContract.js to first_contract.js and that did the trick!

Hope this helps! 

I Still want an answer regarding why this happens, so thank you in advanced to anyone willing to explain me.

**Comment by haltman-at** [comment]
The actual problem is that you're supplying the wrong argument to `artifacts.require`; it takes the name of the contract, not the name of the file; i.e., you should do `artifacts.require("HelloBlockchain")`, not `artifacts.require("./contracts/firstContract.sol")`.  In order to provide some limited compatibility with older versions of Truffle, we've made it so that using the name of the file will also sometimes work, but, as you've seen, this is not fully reliable.  I'm not familiar enough with that part of the code to know why it's hitting an error in this particular case, but the right way to solve your problem is to pass the contract name, not the file name, to `artifacts.require`.

**Comment by sashanclrp** [comment]
@haltman-at Thankyou Very much for the explanation! :D

**Comment by ShuxunoO** [comment]
我也遇到了类似的情况，错误原因：
我所编写的智能合约的文件名称：IFBK_Storage.sol，但在合约内部，合约的名称却依旧用了模板名称：SimpleStorage
也就是说一份名字叫：IFBK_Storage.sol的智能合约合约的内容却是：
```
pragma solidity >=0.4.21 <8.10.0;
contract SimpleStorage {
    string storedData;

    function set(string memory cid) public {
        storedData = cid;
    }

    function get() public view returns (string memory cid) {
        return storedData;
    }
```

在`migrations`文件夹中的名叫`2_deploy_contracts.js`的部署文件中，我修改文件为
```
var IFBK_Storage = artifacts.require("./IFBK_Storage.sol");

module.exports = function(deployer) {
  deployer.deploy(IFBK_Storage);
};
```

用以期待能把我的`IFBK_Storage.sol`部署到truffle本地网络里，结果可显而知，遇到了和；楼主一样的错误；
解决办法：更改智能合约的名字（注意区分 **智能合约文件名称** 和 **智能合约名称** 的区别）更改后的智能合约为：
```
pragma solidity >=0.4.21 <8.10.0;

contract IFBK_Storage {
    string storedData;

    function set(string memory cid) public {
        storedData = cid;
    }

    function get() public view returns (string memory cid) {
        return storedData;
    }
}
```

之后重新编译之后再部署：

> truffle(develop)> compile --reset
> truffle(develop)> migrate --reset

然后解决问题，输出为：

```

2_deploy_contracts.js
=====================

   Deploying 'IFBK_Storage'
   ------------------------
   > transaction hash:    0x438b47d9c1c139fc4c305141797bd45cd46ec614432277795b428e6a40585630
   > Blocks: 0            Seconds: 0
   > contract address:    0x679e93b51D0Df6d3eBAD14Ac9966cFad82dF2b9D
   > block number:        5
   > block timestamp:     1651477872
   > account:             0xF7C9e3b71c34Faf4582610f42f565E1AB2FAFFA4
   > balance:             99.997441686390025184
   > gas used:            309633 (0x4b981)
   > gas price:           3.023833662 gwei
   > value sent:          0 ETH
   > total cost:          0.000936278688266046 ETH

   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:     0.000936278688266046 ETH

```

希望这个回答能报道遇到类似问题的朋友们！👨‍🚀🚀

> The actual problem is that you're supplying the wrong argument to `artifacts.require`; it takes the name of the contract, not the name of the file; i.e., you should do `artifacts.require("HelloBlockchain")`, not `artifacts.require("./contracts/firstContract.sol")`. In order to provide some limited compatibility with older versions of Truffle, we've made it so that using the name of the file will also sometimes work, but, as you've seen, this is not fully reliable. I'm not familiar enough with that part of the code to know why it's hitting an error in this particular case, but the right way to solve your problem is to pass the contract name, not the file name, to `artifacts.require`.

**Comment by Johnmub** [comment]
> The actual problem is that you're supplying the wrong argument to `artifacts.require`; it takes the name of the contract, not the name of the file; i.e., you should do `artifacts.require("HelloBlockchain")`, not `artifacts.require("./contracts/firstContract.sol")`. In order to provide some limited compatibility with older versions of Truffle, we've made it so that using the name of the file will also sometimes work, but, as you've seen, this is not fully reliable. I'm not familiar enough with that part of the code to know why it's hitting an error in this particular case, but the right way to solve your problem is to pass the contract name, not the file name, to `artifacts.require`.

That's resolved my problem. Thanks

**Comment by sirineDEV** [comment]
well .. it didn't work

**Comment by istiaque010** [comment]
Please make the contract name and file name same, it will be solve. If not knock me: [isti.ru.cse@gmail.com](mailto:isti.ru.cse@gmail.com)

**Comment by sashankthapa** [comment]
Ensure that the filename of your smart contract is consistent and in capital letters, for example

- **`HealthContract.sol`,** don't name it like `healtcontract.sol` or `health_contract.sol`. 
- Inside the smart contract, maintain the same naming convention, specifying it as `contract HealthContract`.

# Example

      solidity
      // SPDX-License-Identifier: MIT
      pragma solidity ^0.8.0;
      
      contract HealthContract {
          // Smart contract logic
      }

# Followed By 
      var HealthRecord = artifacts.require('HealthContract');

      module.exports = function (deployer) {
	      deployer.deploy(HealthRecord)
      }

**Comment by dmadindividual** [comment]
> Please make the contract name and file name same, it will be solve. If not knock me: [isti.ru.cse@gmail.com](mailto:isti.ru.cse@gmail.com)

Yes it did work. Thanks mate
