### ISSUE TITLE
File paths from whoever did the release are appearing in debugger stacktraces again

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#4662]
## Issue

E.g., this stacktrace I got on my machine:

```
TypeError: this._prepareRequest is not a function
    at HttpProvider.send (/home/sniffnoy/truffle/debug-lib-repro/node_modules/web3-providers-http/lib/index.js:86:24)
    at internal/util.js:340:30
    at new Promise (<anonymous>)
    at promisify (internal/util.js:339:12)
    at xn.getTrace (/Users/leefaria/code/truffle/packages/debugger/lib/web3/adapter.js:13:24)
    at runCallEffect (/home/sniffnoy/truffle/debug-lib-repro/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:528:21)
    at runEffect (/home/sniffnoy/truffle/debug-lib-repro/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/home/sniffnoy/truffle/debug-lib-repro/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/home/sniffnoy/truffle/debug-lib-repro/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
    at proc (/home/sniffnoy/truffle/debug-lib-repro/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1112:3)
    at /home/sniffnoy/truffle/debug-lib-repro/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:589:17
    at immediately (/home/sniffnoy/truffle/debug-lib-repro/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:60:12)
    at runForkEffect (/home/sniffnoy/truffle/debug-lib-repro/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:588:3)
    at runEffect (/home/sniffnoy/truffle/debug-lib-repro/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/home/sniffnoy/truffle/debug-lib-repro/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/home/sniffnoy/truffle/debug-lib-repro/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
```

Notice the `/Users/leefaria/...` in there.

I'm hoping there's some way to fix this by fiddling with the webpack settings?

## Environment

* Truffle version (`truffle version`): 5.4.30

**Comment by eggplantzzz** [comment]
Oh, I didn't know that this was ever resolved. I talked to @gnidan when @lsqproduction did the release (because her file paths were present in stacktraces) and he said that "it is a known issue".

**Comment by gnidan** [comment]
> Oh, I didn't know that this was ever resolved. I talked to @gnidan when @lsqproduction did the release (because her file paths were present in stacktraces) and he said that "it is a known issue".

Didn't @michaeljohnbennett have a solution for this? Thought it got merged and everything (unless I'm just mistaken)

**Comment by haltman-at** [comment]
Yes, the problem was solved, but now it appears to have been unsolved.  Presumably it's all related to @michaeljohnbennett's work on the debugger's webpack settings.

**Comment by haltman-at** [comment]
OK, looking into this a bit, it seems like this ought to be possible by *not* using `devtool`, and instead using the [`SourceMapDevToolPlugin`](https://webpack.js.org/plugins/source-map-dev-tool-plugin/); specifically the `fileContext` option.  Yet for some reason, it seems like *none* of the options I pass to this plugin are being respected!  No idea what's going wrong here...

**Comment by kevinbluer** [comment]
Note that this is related to the fact that we don't have a fully automated release process. Also a possible interim fix could be for whomever's doing the release do to it from a `/Users/truffle` path.
