### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by Lizard-King101** [trufflesuite/truffle#4701]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

Truffle bundle error for install / compile / test

```
C:\Users\~~\Roaming\npm\node_modules\truffle\build\625.bundled.js:95862
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.__webpack_require__.f.require (C:\Users\SiliconSwamp\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:613:28)
```

## Steps to Reproduce

```
npm i -g truffle
```

## Expected Behavior

to install and compile or test

## Actual Results

error as shown above

## Environment

* Operating System: Windows 10
* Ethereum client: N/A
* Truffle version: Unable to get version
* node version: v8.17.0
* npm version: 6.13.4

**Comment by lsqproduction** [comment]
hello  👋 @Lizard-King101 
Can you help to upgrade the node version to 14 and try the installation again?

**Comment by tahaimran** [comment]
step1 = nvm install 14
step 2 = nvm use 14

**Comment by eggplantzzz** [comment]
Hey @Lizard-King101, you will need to update your version of Node to use Truffle. You will need to  use a version >=12.

**Comment by vjandrea** [comment]
@eggplantzzz 
> You will need to use a version >=12.

Please update the [tutorial](https://trufflesuite.com/tutorial/index.html):

> Setting up the development environment[¶](https://trufflesuite.com/tutorial/index.html#setting-up-the-development-environment)
> 
> There are a few technical requirements before we start. Please install the following:
> 
>     [Node.js v8+ LTS and npm](https://nodejs.org/en/) (comes with Node)
>     [Git](https://git-scm.com/)

If you agree I may send a PR to trufflesuite/trufflesuite.com
