### ISSUE TITLE
What does "abort(5) at Error" mean?

### ISSUE THREAD

**Issue by JustinDrake** [trufflesuite/truffle#473]
I am new to Truffle. I have tried posting this question (and another) to Gitter but didn't get an answer. My contract is not compiling. I am trying to decipher the output:

```
Justins-MacBook-Pro:learnTruffle justin$ truffle compile -s ASSERTIONS=1
Compiling ./contracts/Escrow.sol...
5
5

/usr/local/lib/node_modules/truffle/node_modules/solc/wrapper.js:48
        throw e;
        ^
abort(5) at Error
    at jsStackTrace (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:1:19718)
    at stackTrace (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:1:19901)
    at abort (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:19:15285)
    at Array.dXb (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:11:585101)
    at Array.tX (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:8:557453)
    at Array.eea (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:6:495332)
    at Object.wOb [as dynCall_ii] (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:11:540050)
    at invoke_ii (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:1:1275129)
    at Array.ixa (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:7:494308)
    at Object.bVb [as dynCall_viii] (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:11:577232)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

I have done as suggested and used the `-s ASSERTIONS=1` option, but this does not seem to change anything. What does "abort(5) at Error" mean?

**Comment by vacavaca** [comment]
You probably forgot a semicolon somewhere, the error message is really confusing.

**Comment by tcoulter** [comment]
This means you have a solidity syntax error somewhere. 

Unfortunately, the confusing error message comes from the most recent version of solidity. I've filed an issue [here](https://github.com/ethereum/solc-js/issues/113). It should be fixed in the next release.

**Comment by macbem** [comment]
Are you guys sure that this comes from a Solidity syntax error? I have this error while compiling OpenZeppelin's ERC20 StandardToken contract, which is highly unlikely to contain any syntax errors.

**Comment by tiennm-ibl** [comment]
solc version error, I changed the solc version in truffle-config file which is corresponding to the smart contract version.. it works!
