### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by tahaimran** [trufflesuite/truffle#4790]
E:\blockchain-bootcamp>truffle test
Using network 'development'.

Compiling your contracts...
===========================
× Fetching solc version list from solc-bin. Attempt #1
× Fetching solc version list from solc-bin. Attempt #2
√ Fetching solc version list from solc-bin. Attempt #3
TypeError: Cannot read properties of null (reading 'includes')
    at VersionRange.getSolcVersionFileName (C:\Users\TAHA-PC\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-solidity\dist\compilerSupplier\loadingStrategies\VersionRange.js:206:1)
    at VersionRange.<anonymous> (C:\Users\TAHA-PC\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-solidity\dist\compilerSupplier\loadingStrategies\VersionRange.js:171:1)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\TAHA-PC\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\compile-solidity\dist\compilerSupplier\loadingStrategies\VersionRange.js:5:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Truffle v5.4.33 (core: 5.4.33)
Node v16.13.0

**Comment by tahaimran** [comment]
Got It Solved

**Comment by thunderwin** [comment]
how did your solve it?

**Comment by hiromaily** [comment]
I got a same error, but i don't know how to fix it.
