### ISSUE TITLE
Truffle 5.5.x or 5.4.x test against Rinkeby causes error saying "Error: json: cannot unmarshal number into Go struct field params.fromBlock of type string" 

### ISSUE THREAD

**Issue by 3rdstage** [trufflesuite/truffle#4884]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

Truffle test on Javascript based test against Rinkeby with Truffle 5.5.x or 5.4.x  makes an error in "after each" hook saying **"Error: json: cannot unmarshal number into Go struct field params.fromBlock of type string"**  right after the first testcase.

Truffle 5.5.x or 5.4.x with Node 14.x or 12.x shows the same problem when running against Rinkeby, although the test against local Ganache has no problem

Truffle 5.3.14 with the same test runs well without the problem  

## Expected Behavior

Truffle test against Rinkeby is expected to run without error in 'after each' hook, like when running against local Ganache or with Truffle 5.3.x

### Truffle configuration

```javascript
module.exports = {
  networks: {
     ...
  
     rinkeby: {
        provider: () =>
          new HDWalletProvider({
            chainId: "4",
            mnemonic: process.env.BIP39_MNEMONIC,
            providerOrUrl: new Web3HttpProvider(
              "https://rinkeby.infura.io/v3/" + process.env.INFURA_PROJECT_ID, httpOptions),
            pollingInterval: "5500"
          }),
        network_id: "4",
        // gas: 7E6,
        // gasPrice: 1E10,
        skipDryRun: true
      },
     ...
  }
...
}
```

### Commandline result

* The test (`TestERC721ExportableInRinkeby.js`) has 3 testcases.
* `web3-providers-http` package is v1.5.3

```bash
$ truffle test --compile-none --migrate-none --show-events --network rinkeby test/token/TestERC721ExportableInRinkeby.js 
Using network 'rinkeby'.


Compiling your contracts...
===========================
> Compilation skipped because --compile-none option was passed.
> Migration skipped because --migrate-none option was passed.

....

      ✓ A token in normal state(owned by someone) can set to be exporting by the approved. (43851ms)
      1) "after each" hook: after test for "A token in normal state(owned by someone) can set to be exporting by the approved."


  1 passing (49s)
  1 failing

  1) Contract: ERC721Exportable Contract Test Suite
       "after each" hook: after test for "A token in normal state(owned by someone) can set to be exporting by the approved.":
     Error: json: cannot unmarshal number into Go struct field params.fromBlock of type string
      at /Users/3rdstage/Git/Repos/3rdstage/smart-contracts/node_modules/@trufflesuite/web3-provider-engine/subproviders/provider.js:18:36
      at XMLHttpRequest.request.onreadystatechange (node_modules/web3-providers-http/lib/index.js:98:13)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
      at XMLHttpRequest._setReadyState (node_modules/xhr2-cookies/xml-http-request.ts:219:8)
      at XMLHttpRequest._onHttpResponseEnd (node_modules/xhr2-cookies/xml-http-request.ts:345:8)
      at IncomingMessage.<anonymous> (node_modules/xhr2-cookies/xml-http-request.ts:311:39)
      at endReadableNT (internal/streams/readable.js:1334:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)

```

## Environment

* Operating System:  macOS 10.14.5 (Mojave) 
* Ethereum client:  Infura
* Truffle version (`truffle version`):  v5.5.4
* node version (`node --version`): v14.19.0
* npm version (`npm --version`):  v6.14.16

**Comment by eggplantzzz** [comment]
Hey @3rdstage, I'm not familiar with this error message. Is your repo available on GitHub so we can use it to try and reproduce your error? That along with specific steps to do so would be super helpful in figuring out what is going on here. Thanks!

**Comment by cds-amal** [comment]
Closing for issue maintenance.

**Comment by Aouchinx** [comment]
@cds-amal @3rdstage May I ask if this issue has been fixed? I also encountered this error when running the test script on the Goerli test network.
```bash
$ truffle version                                                                                                                                                                                                                                                                   
Truffle v5.7.9 (core: 5.7.9)
Ganache v7.7.5
Solidity - 0.8.19 (solc-js)
Node v16.17.0
Web3.js v1.8.2
```
```javascript
goerli: {
  provider: () => new HDWalletProvider(MNEMONIC, `https://goerli.infura.io/v3/${INFURA_PROJECT_ID}`),
  network_id: 5,       // Goerli's id
  confirmations: 2,    // # of confirmations to wait between deployments. (default: 0)
  timeoutBlocks: 200,  // # of blocks before a deployment times out  (minimum/default: 50)
  skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
}
```

![image](https://user-images.githubusercontent.com/71441807/224225176-e2b73bd6-4be9-49c1-a1b1-c673e9fa0eed.png)
