### ISSUE TITLE
When setting a uint256 in truffle deploy() function it fails:  -- underflow (fault="underflow", operation="BigNumber.from", value=0.12, code=NUMERIC_FAULT, version=bignumber/5.0.8)

### ISSUE THREAD

**Issue by marcpre** [trufflesuite/truffle#4908]
- [x ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

I am using `Truffle v5.5.5 ` and `solidity 0.8.0`.

I have the following constructor in my contract:

```
contract rNFT is ERC721Enumerable, Ownable {
  using Strings for uint256;

  string baseURI;
  string public baseExtension = ".json";
  uint256 public cost; // = 0.0 ether;
  uint256 public maxSupply = 999999999999999999;
  uint256 public maxMintAmount = 1;
  bool public paused = false;
  bool public revealed = true;
  string public notRevealedUri;

  constructor(
    string memory _name,
    string memory _symbol,
    string memory _initBaseURI,
    string memory _initNotRevealedUri,
    uint256 _cost
  ) ERC721(_name, _symbol) {
    setBaseURI(_initBaseURI);
    setNotRevealedURI(_initNotRevealedUri);
    setCost(_cost);
  }
```

So basically the costs can also be set for the contract.

When deploying with truffle I use the following:

```
var rNFT = artifacts.require("../contracts/rNFT.sol");

module.exports = function(deployer) {
  deployer.deploy(rNFT, "rNFT", "rNFT", "[www._initBaseURI.com](http://www._initbaseuri.com/)", "[www._initNotRevealedUri.com](http://www._initnotrevealeduri.com/)", 0.12);

};
```

However, I get the following error:

```

Error:  *** Deployment Failed ***

"rNFT" -- underflow (fault="underflow", operation="BigNumber.from", value=0.12, code=NUMERIC_FAULT, version=bignumber/5.0.8).

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:379:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:54:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:152:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:117:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:94:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:78:1)
    at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:44:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1)
UnhandledRejections detected
Promise {
  <rejected> Error: underflow (fault="underflow", operation="BigNumber.from", value=0.12, code=NUMERIC_FAULT, version=bignumber/5.0.8)
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:348:1
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
      at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:54:1)
      at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1)
      at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:152:1)
      at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:117:1)
      at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:94:1)
      at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:78:1)
      at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:44:1)
      at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1) {
    reason: 'underflow',
    code: 'NUMERIC_FAULT',
    fault: 'underflow',
    operation: 'BigNumber.from',
    value: 0.12,
    hijackedStack: 'Error: underflow (fault="underflow", operation="BigNumber.from", value=0.12, code=NUMERIC_FAULT, version=bignumber/5.0.8)\n' +
      '    at lib_esm_Logger.makeError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/node_modules/@ethersproject/logger/lib.esm/index.js:166:1)\n' +
      '    at lib_esm_Logger.throwError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/node_modules/@ethersproject/logger/lib.esm/index.js:175:1)\n' +
      '    at throwFault (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/node_modules/@ethersproject/bignumber/lib.esm/bignumber.js:273:18)\n' +
      '    at Function.from (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/node_modules/@ethersproject/bignumber/lib.esm/bignumber.js:175:1)\n' +
      '    at NumberCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/number.js:13:17)\n' +
      '    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/array.js:57:1\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at pack (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/array.js:43:1)\n' +
      '    at TupleCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/tuple.js:19:16)\n' +
      '    at AbiCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/abi-coder.js:82:1)\n' +
      '    at ABICoder.encodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth-abi/lib/index.js:120:1)\n' +
      '    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-eth-contract/lib/index.js:438:1\n' +
      '    at Array.map (<anonymous>)\n' +
      '    at Object._encodeMethodABI (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-eth-contract/lib/index.js:437:6)\n' +
      '    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:275:1\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'

```

## Steps to Reproduce

Set a numeric value in your constract f.ex. set individual costs for each NFT. Migrate the following with `truffle migrate`:

```
  deployer.deploy(rNFT, "rNFT", "rNFT", "[www._initBaseURI.com](http://www._initbaseuri.com/)", "[www._initNotRevealedUri.com](http://www._initnotrevealeduri.com/)", 0.12);

```

## Expected Behavior

Successful migration

## Actual Results

See above.

## Environment

* Operating System: Ubuntu 20.4
* Truffle version (`truffle version`): 5.5.5
* node version (`node --version`): v16.14.0
* npm version (`npm --version`): 8.3.1

**Comment by davidmurdoch** [comment]
Hey @marcpre, I suspect that the issue here is that you are passing the value `0.12` to your contract, but the contract expects to receive a `uint256` (per the constructor's signature). Unfortunately Solidity doesn't yet support any fixed point or decimal types, so you'll need to pass integer values only. I'll leave it up to you as to how many decimal places of precision your contract needs in its numeric types.

Let me know if this helps! Thanks!

**Comment by marcpre** [comment]
@davidmurdoch Thank you for your reply. I tried using a wei value such as `120000000000000000`

My `2_deploy_contracts.js` looks like that:

```
var rNFT = artifacts.require("../contracts/rNFT.sol");

/*
module.exports = function(deployer) {
  deployer.deploy(rNFT);
};
*/

module.exports = function(deployer) {
  deployer.deploy(rNFT, "rNFT", "rNFT", "www._initBaseURI.com", "www._initNotRevealedUri.com", 120000000000000000);

};
```

However, I still get the following error:

```
truffle(develop)> migrate

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.


Starting migrations...
======================
> Network name:    'develop'
> Network id:      5777
> Block gas limit: 6721975 (0x6691b7)


1_initial_migration.js
======================

   Replacing 'rNFT'
   ----------------
 *** Deployment Failed ***

"rNFT" -- overflow (fault="overflow", operation="BigNumber.from", value=120000000000000000, code=NUMERIC_FAULT, version=bignumber/5.0.8).


Exiting: Review successful transactions manually by checking the transaction hashes above on Etherscan.


Error:  *** Deployment Failed ***

"rNFT" -- overflow (fault="overflow", operation="BigNumber.from", value=120000000000000000, code=NUMERIC_FAULT, version=bignumber/5.0.8).

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:379:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:54:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:152:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:117:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:94:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:78:1)
    at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:44:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1)
UnhandledRejections detected
Promise {
  <rejected> Error: overflow (fault="overflow", operation="BigNumber.from", value=120000000000000000, code=NUMERIC_FAULT, version=bignumber/5.0.8)
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:348:1
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
      at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:54:1)
      at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1)
      at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:152:1)
      at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:117:1)
      at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:94:1)
      at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:78:1)
      at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:44:1)
      at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1) {
    reason: 'overflow',
    code: 'NUMERIC_FAULT',
    fault: 'overflow',
    operation: 'BigNumber.from',
    value: 120000000000000000,
    hijackedStack: 'Error: overflow (fault="overflow", operation="BigNumber.from", value=120000000000000000, code=NUMERIC_FAULT, version=bignumber/5.0.8)\n' +
      '    at lib_esm_Logger.makeError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/node_modules/@ethersproject/logger/lib.esm/index.js:166:1)\n' +
      '    at lib_esm_Logger.throwError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/node_modules/@ethersproject/logger/lib.esm/index.js:175:1)\n' +
      '    at throwFault (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/node_modules/@ethersproject/bignumber/lib.esm/bignumber.js:273:18)\n' +
      '    at Function.from (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/node_modules/@ethersproject/bignumber/lib.esm/bignumber.js:178:1)\n' +
      '    at NumberCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/number.js:13:17)\n' +
      '    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/array.js:57:1\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at pack (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/array.js:43:1)\n' +
      '    at TupleCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/tuple.js:19:16)\n' +
      '    at AbiCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/abi-coder.js:82:1)\n' +
      '    at ABICoder.encodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth-abi/lib/index.js:120:1)\n' +
      '    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-eth-contract/lib/index.js:438:1\n' +
      '    at Array.map (<anonymous>)\n' +
      '    at Object._encodeMethodABI (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-eth-contract/lib/index.js:437:6)\n' +
      '    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:275:1\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
  },
  _events: Events <[Object: null prototype] {}> {},
  emit: [Function: emit],
  on: [Function: on],
  once: [Function: once],
  off: [Function: removeListener],
  listeners: [Function: listeners],
  addListener: [Function: on],
  removeListener: [Function: removeListener],
  removeAllListeners: [Function: removeAllListeners],
  _eventsCount: 0
} Error: overflow (fault="overflow", operation="BigNumber.from", value=120000000000000000, code=NUMERIC_FAULT, version=bignumber/5.0.8)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:348:1
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:54:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:152:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:117:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:94:1)
    at runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:78:1)
    at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:44:1)
    at Command.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:189:1) {
  reason: 'overflow',
  code: 'NUMERIC_FAULT',
  fault: 'overflow',
  operation: 'BigNumber.from',
  value: 120000000000000000,
  hijackedStack: 'Error: overflow (fault="overflow", operation="BigNumber.from", value=120000000000000000, code=NUMERIC_FAULT, version=bignumber/5.0.8)\n' +
    '    at lib_esm_Logger.makeError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/node_modules/@ethersproject/logger/lib.esm/index.js:166:1)\n' +
    '    at lib_esm_Logger.throwError (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/node_modules/@ethersproject/logger/lib.esm/index.js:175:1)\n' +
    '    at throwFault (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/node_modules/@ethersproject/bignumber/lib.esm/bignumber.js:273:18)\n' +
    '    at Function.from (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/node_modules/@ethersproject/bignumber/lib.esm/bignumber.js:178:1)\n' +
    '    at NumberCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/number.js:13:17)\n' +
    '    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/array.js:57:1\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at pack (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/array.js:43:1)\n' +
    '    at TupleCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/coders/tuple.js:19:16)\n' +
    '    at AbiCoder.encode (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@ethersproject/abi/lib.esm/abi-coder.js:82:1)\n' +
    '    at ABICoder.encodeParameters (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth-abi/lib/index.js:120:1)\n' +
    '    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-eth-contract/lib/index.js:438:1\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at Object._encodeMethodABI (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-eth/node_modules/web3-eth-contract/lib/index.js:437:6)\n' +
    '    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:275:1\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

```

Any suggestions why I cannot set the initial price in the constructor?

**Comment by davidmurdoch** [comment]
Ah, I think you need to send it as a string:

`  deployer.deploy(rNFT, "rNFT", "rNFT", "www._initBaseURI.com", "www._initNotRevealedUri.com", "120000000000000000");`

**Comment by haltman-at** [comment]
@marcpre To give more detail -- the encoding library we use does not allow (and therefore we do not allow) passing in Javascript `number`s that are not [safe integers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger).  Since 120000000000000000 is outside of the safe range, you can't pass it in as a Javascript `number`.  But you can pass it in as a string, or a `BigInt`, or a `BN`, or a `BigNumber`.  Hope that's helpful!

**Comment by marcpre** [comment]
Does the same go for booleans? Like "true", "false" etc.

Thank you for your reply.

**Comment by haltman-at** [comment]
No, booleans can be passed directly.  (You definitely don't want to use strings for those; any nonempty string will be treated as `true`.)  Really most things work like you'd think, it's only large `number`s that pose a problem.  (Again, *small* numbers can be passed as `number`s; it's only ones outside the [safe range](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger), ones that are 2^53 or larger in absolute value, that require a format other than `number`s.

We're working on a system that will allow us to report better, more informative error messages for these cases (and also allow you to use strings for booleans if you really want, among many other things :P ), but I'm afraid it's going to be some time before it's ready...

**Comment by fainashalts** [comment]
@marcpre is there anything actionable left in this issue? From a quick read it looks like we are working on a better system for this, but for now you have a workaround. Please confirm. Thanks so much!
