### ISSUE TITLE
Debugger crashes with -x for contracts written for Solidity v0.4.4

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#5007]
## Issue
 
There's a TypeError for this transaction: 0xea524441c46fd574aac1d38fa83f3af3cbd6d27cb6e083cb4fa02edf1eee8604

## Steps to Reproduce

`truffle debug -x --network=mainnet 0xea524441c46fd574aac1d38fa83f3af3cbd6d27cb6e083cb4fa02edf1eee8604`

## Expected Behavior

I expect to be able to debug without source for this contract

## Actual Results

```
TypeError: Cannot read property 'language' of undefined
    at Function.normalize (/Users/fainashalts/truffle-dev/truffle/packages/debugger/lib/session/index.js:199:69)
    at fa.addExternalCompilations (/Users/fainashalts/truffle-dev/truffle/packages/debugger/lib/session/index.js:535:41)
    at DebugRecognizer.<anonymous> (/Users/gnidan/.nvm/versions/node/v14.19.0/lib/node_modules/truffle/build/webpack:/packages/fetch-and-compile/dist/debug.js:96:1)
    at Generator.next (<anonymous>)
    at /Users/gnidan/.nvm/versions/node/v14.19.0/lib/node_modules/truffle/build/webpack:/packages/fetch-and-compile/dist/debug.js:27:1
    at new Promise (<anonymous>)
    at exports.modules.687440.__awaiter (/Users/gnidan/.nvm/versions/node/v14.19.0/lib/node_modules/truffle/build/webpack:/packages/fetch-and-compile/dist/debug.js:23:1)
    at DebugRecognizer.addCompiledInfo (/Users/gnidan/.nvm/versions/node/v14.19.0/lib/node_modules/truffle/build/webpack:/packages/fetch-and-compile/dist/debug.js:92:1)
    at /Users/gnidan/.nvm/versions/node/v14.19.0/lib/node_modules/truffle/build/webpack:/packages/fetch-and-compile/dist/fetch.js:133:1
    at Generator.next (<anonymous>)
    at fulfilled (/Users/gnidan/.nvm/versions/node/v14.19.0/lib/node_modules/truffle/build/webpack:/packages/fetch-and-compile/dist/fetch.js:5:43)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`): v5.5.8
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by haltman-at** [comment]
Fix is now released!
