### ISSUE TITLE
Error: Cannot find module '@ethersproject/solidity'

### ISSUE THREAD

**Issue by OIU2020** [trufflesuite/truffle#5023]
I'm trying to use node run-arbitrage.js ,but it fails for module not found.

PS E:\Flashbots\Flahsloan2.0> node run-arbitrage.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '@ethersproject/solidity'
Require stack:
- E:\Flashbots\Flahsloan2.0\node_modules\@uniswap\sdk\dist\sdk.cjs.development.js
- E:\Flashbots\Flahsloan2.0\node_modules\@uniswap\sdk\dist\index.js
- E:\Flashbots\Flahsloan2.0\run-arbitrage.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\Flashbots\Flahsloan2.0\node_modules\@uniswap\sdk\dist\sdk.cjs.development.js:14:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (E:\Flashbots\Flahsloan2.0\node_modules\@uniswap\sdk\dist\index.js:7:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\Flashbots\\Flahsloan2.0\\node_modules\\@uniswap\\sdk\\dist\\sdk.cjs.development.js',
    'E:\\Flashbots\\Flahsloan2.0\\node_modules\\@uniswap\\sdk\\dist\\index.js',
    'E:\\Flashbots\\Flahsloan2.0\\run-arbitrage.js'
  ]
}

**Comment by haltman-at** [comment]
This doesn't sound like an error with Truffle; you're running `node` on some non-Truffle file and it's not working.  OK, but where is Truffle involved?  Does this script you're running invoke Truffle at some point?

If this is an error with Truffle, we're going to need more detailed reproduction steps.  You refer to a `run-arbitrage.js`, but what is that?  We have no idea what that is or what its contents are.

**Comment by MicaiahReid** [comment]
Closing for issue maintenance.
