### ISSUE TITLE
Unable to run the `debug 0x...` command from the Truffle REPL.

### ISSUE THREAD

**Issue by hickscorp** [trufflesuite/truffle#5075]
Installing the latest version of truffle (it's a new project) and trying to debug a transaction, I get the following:

```
truffle(development)> debug 0x547dc4e354a62e0afdc44d597a64853995e546fe05a37f167371abdc9b7ce682
Error: Cannot find module 'babel-runtime/core-js/object/entries'
Require stack:
- whatever/backend/node_modules/reselect-tree/index.js
- whatever/backend/node_modules/@truffle/debugger/dist/debugger.js
- whatever/backend/node_modules/truffle/build/consoleChild.bundled.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (whatever/backend/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (whatever/backend/node_modules/reselect-tree/external "babel-runtime/core-js/object/entries":1:1)
    at __webpack_require__ (whatever/backend/node_modules/reselect-tree/webpack/bootstrap e958f07978aa008e523d:19:1)
    at Object.<anonymous> (whatever/backend/node_modules/reselect-tree/index.js:87:16)
    at __webpack_require__ (whatever/backend/node_modules/reselect-tree/webpack/bootstrap e958f07978aa008e523d:19:1)
    at whatever/backend/node_modules/reselect-tree/webpack/bootstrap e958f07978aa008e523d:62:1
    at whatever/backend/node_modules/reselect-tree/index.js:76:10
    at webpackUniversalModuleDefinition (whatever/backend/node_modules/reselect-tree/webpack/universalModuleDefinition:3:1)
    at Object.<anonymous> (whatever/backend/node_modules/reselect-tree/webpack/universalModuleDefinition:10:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

It might be related to https://github.com/trufflesuite/truffle/issues/5074.

**Comment by athenayay** [comment]
This has got something to do with the new truffle release that was published 5 days ago - 

here mate - https://www.npmjs.com/package/truffle
if you've re-installed or upgraded truffle / npm, pls let me know so I can confirm my suspicion!

A

**Comment by hickscorp** [comment]
@athenayay given that tthis error popped on a fresh project created yesterday night, it's very likely yes.

**Comment by haltman-at** [comment]
OK, we think that #5082 will fix this... I guess we'll see once the next release is out!

**Comment by haltman-at** [comment]
OK, can people try this again with Truffle 5.5.13?  Thanks!

**Comment by hickscorp** [comment]
Thanks a lot @haltman-at - I've ended up switching to Hardhat on this project. But I'll make sure to try the proposed solution on projects that still use Truffle.
