### ISSUE TITLE
Truffle does not forward solidity compilation errors

### ISSUE THREAD

**Issue by Gustav-Simonsson** [trufflesuite/truffle#513]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Truffle does not forward solidity compilation errors to the user.

## Steps to Reproduce

Create a contract which assigns a value to a variable, then remove the '=' character in the assignment.

## Expected Behavior

```bash
truffle compile
contracts/mesh.sol:78:18: Error: Expected token Semicolon got 'Identifier'
    uint deposit nodeIdents[msg.sender].deposit;
```

## Actual Results

```bash
truffle compile
Compiling ./contracts/mesh.sol...
5
5

/usr/local/lib/node_modules/truffle/node_modules/solc/wrapper.js:48
        throw e;
        ^
abort(5) at Error
    at jsStackTrace (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:1:19718)
    at stackTrace (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:1:19901)
    at abort (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:19:15285)
    at Array.dXb (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:11:585101)
    at Array.tX (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:8:557453)
    at Array.eea (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:6:495332)
    at Object.wOb [as dynCall_ii] (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:11:540050)
    at invoke_ii (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:1:1275129)
    at Array.ixa (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:7:494308)
    at Object.bVb [as dynCall_viii] (/usr/local/lib/node_modules/truffle/node_modules/solc/soljson.js:11:577232)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

## Environment

* Ubuntu 16.04.2 LTS
* Truffle v3.4.6 (core: 3.4.6) Solidity v0.4.13 (solc-js)
* Ethereum client: N/A
* node version: v8.2.1
* npm version: 5.3.0

**Comment by tcoulter** [comment]
Hi there.

This issue has been fixed. It was a bug in Solidity! To get the update, upgrade Truffle to the latest version.

Thanks for writing!
