### ISSUE TITLE
Unknown server response 405 when downloading hash QmaCaDgbXgTJXdt8JRU46R59sH4UwnDHiAopdbndEDGqxV

### ISSUE THREAD

**Issue by kuznetsov-m** [trufflesuite/truffle#5159]
## Issue

Unable to install **zeppelin** package by **truffle**

```
> truffle install zeppelin
Error: Unknown server response 405 when downloading hash QmaCaDgbXgTJXdt8JRU46R59sH4UwnDHiAopdbndEDGqxV
    at Request._callback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/ethpm/lib/hosts/ipfshostwithlocalreader.js:27:1)
    at Request.self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:185:1)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:1154:1)
    at Request.emit (node:events:527:28)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:1076:1)
    at Object.onceWrapper (node:events:641:28)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Truffle v5.5.15 (core: 5.5.15)
Node v16.15.0
```

## Environment

* Operating System: macOS 11.6 BuildVersion: 20G165
* Truffle version (`truffle version`): v5.5.15 (core: 5.5.15)
* node version (`node --version`): v16.15.0
* npm version (`npm --version`): 8.5.5

**Comment by cds-amal** [comment]
Hi @kuznetsov-m, unfortunately, **EthPM** doesn't have the community support to be a reliable and robust ecosystem. As a result, we're considering dropping its support. You should install **Open Zeppelin Contracts** from **npm** instead (`npm install @openzeppelin/contracts`). AFAIK (please fact-check me), Open Zeppelin no longer maintains their **EthPM** distribution.
