### ISSUE TITLE
new Error("Could not find artifacts for " + import_path + " from any sources");

### ISSUE THREAD

**Issue by akashkatare5** [trufflesuite/truffle#5176]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
```
1_initial_migration.js
======================

C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\4889.bundled.js:21667
        throw new Error("Could not find artifacts for " + import_path + " from any sources");

**Here is a full code:**

**PS C:\Users\Sky\Desktop\Finilazing NFT\JSON\MintNFT-main> truffle console
truffle(development)> migrate

Compiling your contracts...
===========================
> Compiling @openzeppelin\contracts\access\Ownable.sol
> Compiling @openzeppelin\contracts\token\ERC721\ERC721.sol
> Compiling @openzeppelin\contracts\token\ERC721\IERC721.sol
> Compiling @openzeppelin\contracts\token\ERC721\IERC721Receiver.sol
> Compiling @openzeppelin\contracts\token\ERC721\extensions\ERC721URIStorage.sol
> Compiling @openzeppelin\contracts\token\ERC721\extensions\IERC721Metadata.sol 
> Compiling @openzeppelin\contracts\utils\Address.sol
> Compiling @openzeppelin\contracts\utils\Context.sol
> Compiling @openzeppelin\contracts\utils\Counters.sol
> Compiling @openzeppelin\contracts\utils\Strings.sol
> Compiling @openzeppelin\contracts\utils\introspection\ERC165.sol
> Compiling @openzeppelin\contracts\utils\introspection\IERC165.sol
> Compiling .\contracts\mintContract.sol
> Artifacts written to C:\Users\Sky\Desktop\Finilazing NFT\JSON\MintNFT-main\build\contracts
> Compiled successfully using:
   - solc: 0.8.14+commit.80d49f37.Emscripten.clang


Starting migrations...
======================
> Network name:    'development'
> Network id:      5777
> Block gas limit: 6721975 (0x6691b7)


1_initial_migration.js
======================

C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\4889.bundled.js:21667
        throw new Error("Could not find artifacts for " + import_path + " from any sources");
        ^

Error: Could not find artifacts for Migrations from any sources
    at Resolver.require (C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\resolver\dist\lib\resolver.js:60:1)
    at Object.require (C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:175:1)
    at ResolverIntercept.require (C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\ResolverIntercept.js:22:1)
    at C:\Users\Sky\Desktop\Finilazing NFT\JSON\MintNFT-main\migrations\1_initial_migration.js:1:30
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
    at Object.file (C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\require\require.js:94:1)
    at Migration._load (C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:42:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Migration.run (C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:202:1)
    at Object.runMigrations (C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:152:1)
    at Object.runFrom (C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:117:1)
    at Object.run (C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:94:1)
    at module.exports (C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate\runMigrations.js:10:1)
    at Object.module.exports [as run] (C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate\run.js:41:1)
    at runCommand (C:\Users\Sky\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command-utils.js:184:1)**
```

## Steps to Reproduce

...\truffle console

...]\Migrate

## Expected Behavior

should have deployed on Ganache personal blockchain

## Actual Results

(Trying to migrate the contract on ganache but I am stuck with this error)

## Environment

* Operating System: Windows 10
* Ethereum client: Ganache v7.1.0
* Truffle version (`5.5.16`):(core: 5.5.16)
* node version (`18.2.0`):
* npm version (`8.9.0`):

**Comment by eggplantzzz** [comment]
Hey @akashkatare5 can you show us your project so we can try and troubleshoot/see what is wrong? Is it on GitHub?

**Comment by akashkatare5** [comment]
> Hey @akashkatare5 can you show us your project so we can try and troubleshoot/see what is wrong? Is it on GitHub?


Hi I overcame with the problem it was related to my contract.sol file

during migration it was unable to capture its path, so I fixed it 

![BA5AC37E-4199-4939-B923-A3BBC57BB499](https://user-images.githubusercontent.com/62850215/172236883-117f63e9-9487-4b59-988b-b176f8c86653.jpeg)

Thank you for reverting on the error. 
I appreciated it.
