### ISSUE TITLE
Deploy Router Contract Failure on Harmony: not implemented

### ISSUE THREAD

**Issue by BiangSwapTeam** [trufflesuite/truffle#5200]
## Issue
Deploy Router Contract Failure on Harmony: not implemented

## Steps to Reproduce
- 1.Prepare the contract of Uniswap router v2 and good network connection
- 2.Config harmony  testnet network `https://api.s0.b.hmny.io` and networkId `1666700000`
- 3.Deploy `truffle deploy --network harmonyTestnet`
- 4.Error threw `"BiangSwapRouter" -- not implemented.`

## Expected Behavior
Deploy to Harmony testnet network normally

## Actual Results
Error threw as the following when deploying:
```
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Starting migrations...
======================
> Network name:    'harmonyTestnet'
> Network id:      1666700000
> Block gas limit: 80000000 (0x4c4b400)

3_deploy_harmony.js
===================
   Deploying 'BiangSwapRouter'
   ---------------------------
 *** Deployment Failed ***

"BiangSwapRouter" -- not implemented.

Exiting: Review successful transactions manually by checking the transaction hashes above on Etherscan.

Error:  *** Deployment Failed ***

"BiangSwapRouter" -- not implemented.

    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:379:1
    at Migration._deploy (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:68:1)
    at Migration._load (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:54:1)
    at Migration.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1)
    at Object.runMigrations (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:152:1)
    at Object.runFrom (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:117:1)
    at Object.runAll (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:121:1)
    at Object.run (/usr/local/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:86:1)
    at module.exports (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/runMigrations.js:10:1)
    at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:41:1)
    at runCommand (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command-utils.js:184:1)
Truffle v5.5.18 (core: 5.5.18)
Node v16.13.1
```

## Environment

* Operating System: macOS Monterey version 12.3.1
* Ethereum client: solc v0.6.6
* Truffle version (`truffle version`): v5.5.18
* node version (`node --version`): v16.13.1
* npm version (`npm --version`): v8.1.2

**Comment by dongmingh** [comment]
Closing for Issue Maintenance.
