### ISSUE TITLE
There is a debugger error!? Needs an update!

### ISSUE THREAD

**Issue by zrock23** [trufflesuite/truffle#5295]
there is a debugger error!?

```
zrock23@DESKTOP-950AS07:~/box$ truffle debug 0xad8561bbaab6a13c883ba2e5b2fc4d130a68fccf62836c0b4783ec2c9de68c86sage --network=ropsten --url=https://ropsten.infura.io/v3/879bd7f6cb4e4df0a8ed19a71b178e62 --fetch-external
Error: Url and Network options should not be specified together
    at Object.module.exports [as run] (/home/zrock23/.nvm/versions/node/v18.6.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/debug/run.js:11:1)
    at runCommand (/home/zrock23/.nvm/versions/node/v18.6.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/command-utils.js:184:1)
Truffle v5.5.21 (core: 5.5.21)
Node v18.6.0
```

-----------------------------------------------------------------------------

it's the right record and the validation works...!

```
zrock23@DESKTOP-950AS07:~/box$ truffle debug 0xad8561bbaab6a13c883ba2e5b2fc4d130a68fccf62836c0b4783ec2c9de68c86sage --url=https://ropsten.infura.io/v3/879bd7f6cb4e4df0a8ed19a71b178e62 --compile-all
Starting Truffle Debugger...
✓ Compiling your contracts...
✖ Gathering information about your project and the transaction...
Error: The method debug_traceTransaction does not exist/is not available
    at yn.getTrace (/Users/sukanyaparashar/Desktop/truffle/packages/debugger/lib/web3/adapter.js:36:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Commands:
(enter) last command entered (step next)
(o) step over, (i) step line / step into, (u) step out, (n) step next
(c) continue until breakpoint, (Y) reset & continue to previous error
(y) (if at end) reset & continue to final error
(;) step instruction (include number to step multiple)
(g) turn on generated sources, (G) turn off generated sources except via `;`
(p) print instruction & state (`p [mem|cal|sto]*`; see docs for more)
(l) print additional source context (`l [+<lines-ahead>] [-<lines-back>]`)
(s) print stacktrace, (h) print this help
(q) quit, (r) reset, (t) load new transaction, (T) unload transaction
(b) add breakpoint (`b [[<source-file>:]<line-number>]`; see docs for more)
(B) remove breakpoint (similar to adding, or `B all` to remove all)
(+) add watch expression (`+:<expr>`), (-) remove watch expression (-:<expr>)
(?) list existing watch expressions and breakpoints
(v) print variables and values (`v [bui|glo|con|loc]*`)
(:) evaluate expression - see `v`

debug(ropsten.infura.io)>
```

**Comment by cds-amal** [comment]
Hey @zrock23, 

> Error: Url and Network options should not be specified together at Object.module.exports

The `--url` and `--network` options are mutually exclusive here. Try using one option to see if it resolves the problem.

**Comment by cds-amal** [comment]
@zrock23, I notice the transaction hash is incorrect because it ends with non HEX digits (`sage`).  [There is a valid ropsten transaction hash without the suffix](https://asciinema.org/a/fdpUb5Ol11lxm1zV9XJDUBlcP).

**Comment by zrock23** [comment]
thanks for the ideas i didn't notice some of the things, i'll try again!😀

**Comment by gnidan** [comment]
let us know if you get this sorted out, please, @zrock23! thank you!

**Comment by gnidan** [comment]
oh wait there is likely more we could say here about getting `truffle debug` to work with ropsten... you'll have to run `ganache --fork=ropsten` and have truffle connect to that. I'll see if I can find somewhere where this process is documented.

**Comment by cds-amal** [comment]
Hi @zrock23, is this still an issue?

**Comment by fainashalts** [comment]
Hi @zrock23 thank you for bringing up this issue. As we haven't heard back from you in a while I am going to close it for maintenance. Please feel free to open a new issue if this is not resolved or you encounter a new error. Thanks!
