### ISSUE TITLE
 truffle exec problem: /truffle-require/index.js:121?

### ISSUE THREAD

**Issue by chengfenlu** [trufflesuite/truffle#530]
I typed "truffle exec generatorwithDB.js" , its result is:
-------------------------------------------------------------------------------------------------
jennifer@block-demo:~/ETHnursecall$ truffle exec generatorwithDB.js
Using network 'development'.

/usr/local/lib/node_modules/truffle/node_modules/truffle-require/index.js:121
      fn(done);
      ^

TypeError: fn is not a function
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-require/index.js:121:7
    at /usr/local/lib/node_modules/truffle/node_modules/truffle-require/index.js:94:7
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
---------------------------

I am new to this truffle exec, not clear about the problems.
Thanks.

## Environment

* Operating System: ubuntu 16.04 
* Truffle version: Truffle v3.2.1
* Ethereum client testrpc: 
* node version: v7.8.0
* npm version: ４.2.0

**Comment by chengfenlu** [comment]
And node is working as follows:
--------------
jennifer@block-demo:~/ETHnursecall$ node generatorwithDB.js
<p>Connected MongoDB CallCollection successfully!</p>
<p>Connected MongoDB: Call collection successfully!</p
