### ISSUE TITLE
Error: invalid address during migration process

### ISSUE THREAD

**Issue by LordotU** [trufflesuite/truffle#534]
- [+] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I can't deploy my contract to Rinkeby network through `truffle migrate --reset --network rinkeby`.

## Steps to Reproduce

You need to run geth in docker.

Init blockchain from rinkeby genesis file (https://www.rinkeby.io/rinkeby.json - put it to the host directory _$HOME/.ethereum/rinkeby_ (create it if needed) ):

```bash
docker run -it --name geth -p 8545:8545 -p 30303:30303 -p 30304:30304 -v $HOME/.ethereum:/root/.ethereum ethereum/client-go --datadir=/root/.ethereum/rinkeby init /root/.ethereum/rinkeby/rinkeby.json
```

Stop and remove container via `docker stop geth && docker rm geth`. Then start it again:

```bash
docker run -dit --name geth -p 8545:8545 -p 30303:30303 -p 30304:30304 -v $HOME/.ethereum:/root/.ethereum ethereum/client-go --rpc --rpcaddr 0.0.0.0 --rpccorsdomain="*" --rpcapi admin,debug,eth,miner,net,personal,shh,txpool,web3 --networkid=4 --datadir=/root/.ethereum/rinkeby --cache=32 --syncmode=light '--ethstats=LordotU-Test-Rinkeby:All hail ETH!@stats.rinkeby.io' --bootnodes=enode://a24ac7c5484ef4ed0c5eb2d36620ba4e4aa13b8c84684e1b4aab0cebea2ae45cb4d375b77eab56516d34bfbd3c1a833fc51296ff084b770b94fb9028c4d25ccf@52.169.42.101:30303?discport=30304
```

Your host should have an ability to accept connections to 8545 inside local loop.

Then you need to:

- create one or several accounts (you may exec shell commands inside container via `docker exec -ti geth sh`), unlock it and get some eth from [rinkeby faucet](https://faucet.rinkeby.io/);
- clone my repo from https://github.com/LordotU/secret-santa-smart-contract;
- switch to truffle branch;
- add rinkeby.js file to config/networks directory. File should contents:
```javascript
module.exports = {
	from       : 'your_unlocked_and_non_empty_wallet_addres',
	network_id : 4,
	gas        : 2700000,
	gasPrice   : 20000000000,
};
```
- run `truffle compile` and then - `truffle migrate --reset --network rinkeby`.

## Expected Behavior

I expect the same as in thecase of development/testrpc network - normal deployment of my contract. :-)

## Actual Results

Actually I have an error like:

```
Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x076235e944e70e561a0b9b6b14307157d07775d67a46689e44ffaf7675829b84
/home/admin/.nvm/versions/node/v8.2.1/lib/node_modules/truffle/build/cli.bundled.js:30534
    throw new Error('invalid address');
    ^

Error: invalid address
    at inputAddressFormatter (/home/admin/.nvm/versions/node/v8.2.1/lib/node_modules/truffle/build/cli.bundled.js:30534:11)
    at /home/admin/.nvm/versions/node/v8.2.1/lib/node_modules/truffle/build/cli.bundled.js:36660:28
    at Array.map (native)
    at Method.formatInput (/home/admin/.nvm/versions/node/v8.2.1/lib/node_modules/truffle/build/cli.bundled.js:36659:32)
    at Method.toPayload (/home/admin/.nvm/versions/node/v8.2.1/lib/node_modules/truffle/build/cli.bundled.js:36685:23)
    at Eth.send [as getCode] (/home/admin/.nvm/versions/node/v8.2.1/lib/node_modules/truffle/build/cli.bundled.js:36710:30)
    at Object.callback (/home/admin/.nvm/versions/node/v8.2.1/lib/node_modules/truffle/build/cli.bundled.js:241521:39)
    at /home/admin/.nvm/versions/node/v8.2.1/lib/node_modules/truffle/build/cli.bundled.js:36713:25
    at /home/admin/.nvm/versions/node/v8.2.1/lib/node_modules/truffle/build/cli.bundled.js:243485:9
    at /home/admin/.nvm/versions/node/v8.2.1/lib/node_modules/truffle/build/cli.bundled.js:78847:11
```

The most interesting thing is that I can find this transaction in blockchain explorer: https://rinkeby.etherscan.io/tx/0x076235e944e70e561a0b9b6b14307157d07775d67a46689e44ffaf7675829b84

## Environment

* Ubuntu 14.04: 
* Truffle v3.4.8:
* Geth 1.7.0-unstable running in Docker (official image):
* Node 8.2.1:
* NPM 5.3.0: 

All of it running inside one DigitalOcean droplet. _For example, yesterday I had a problem with connection to this Geth-node localy, but freely can connect from outside. The reason was in iptables rules._

**Comment by LordotU** [comment]
I've made a little debug of _cli.bundled.js_ file.

This is what I get whe try to deploy in testrpc network:

```
... 0x34865735e70707919805f2850b823e67adb25ff0fe059d5ece5836d9430a7208
[ [Function: inputAddressFormatter],
  [Function: inputDefaultBlockNumberFormatter] ] [ '0x97280c75faa2e7e1b2a182e34fffcb77c58b9b56' ]
  Migrations: 0x97280c75faa2e7e1b2a182e34fffcb77c58b9b56
```

And in Rinkeby network:

```
... 0xa2a4697161936052f320bbce9171600741cf155785d25ecf45d914f1445be648
[ [Function: inputAddressFormatter],
  [Function: inputDefaultBlockNumberFormatter] ] [ null ]
```

As we can see, in the case of Rinkeby we have _null_ instead of valid contract address. But... why has it happened?

**Comment by LordotU** [comment]
Ok, I went deeper.

So, when executes this line (https://github.com/ethereum/web3.js/blob/7560f273359071afae31d010b97fa1872dacd66c/lib/web3/contract.js#L119) of web3.js code (line 222802 in Truffel's _cli.bundled.js_) we are getting answer with _null_ in _contractAddress_ field.

For example:

```
{ 
  blockHash: '0xd08cee7ec0d9e50185099ca403b53798081f94ba73bbb9caa7a72fa2afb2591f',
  blockNumber: 696482,
  contractAddress: null,
  cumulativeGasUsed: 201492,
  from: '0xdc2e0c6e3d08bc53200ea0a90ec4f550d9d1f616',
  gasUsed: 0,
  logs: [],
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  root: '0x4ae760bf36bd646016db7018f16f6e5fadc2200aee17a89337b6d0a26534fb03',
  to: null,
  transactionHash: '0x6863a10cc9e42f62056f5defebd9f249ced92c024c1cb2ed94ae1a1efb1a5cc5',
  transactionIndex: 0 
}
```

And example for testrpc which works properly:

```
{ 
  transactionHash: '0x55bb0dc39488b897ced17831ff6308741045b463993d3b2d239748434b134b89',
  transactionIndex: 0,
  blockHash: '0xa04dc4a145b6884dfa78cfc4d55888b4e6c2ed41b8888cff72458728b474f6da',
  blockNumber: 15,
  gasUsed: 201262,
  cumulativeGasUsed: 201262,
  contractAddress: '0x0bfed93fdbcd00323918ad1d361cd999ba291ce4',
  logs: []
 }
```

**Comment by LordotU** [comment]
I've found the reason.
_contractAddress_ is _null_ because I'm using geth node in embedded/light mode - it hasn't enough information about blockchain.
Issue may be closed.
