### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by yahyeShorie** [trufflesuite/truffle#5354]
## I'm using truffle and ropsten  network to deploy smart contract with testnet. when i configure truffle-config.js and run truffle deploy --network ropsten i found this error.

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at hash160 (/home/yahye/node_modules/ethereumjs-wallet/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:249:21)
    at HDKey.set (/home/yahye/node_modules/ethereumjs-wallet/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:50:24)
    at Function.HDKey.fromMasterSeed (/home/yahye/node_modules/ethereumjs-wallet/node_modules/ethereum-cryptography/vendor/hdkey-without-crypto.js:194:20)
    at Function.fromMasterSeed (/home/yahye/node_modules/ethereumjs-wallet/src/hdkey.ts:13:36)
    at HDWalletProvider.checkBIP39Mnemonic (/home/yahye/node_modules/@truffle/hdwallet-provider/src/index.ts:327:35)
    at new HDWalletProvider (/home/yahye/node_modules/@truffle/hdwallet-provider/src/index.ts:108:12)
    at Object.provider (/home/yahye/myDev/web3/truffle_projects/truffle_tutorial_app/truffle-config.js:63:23)
    at Object.getProvider (/usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/index.js:20:1)
    at Object.create (/usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/index.js:13:1)
    at TruffleConfig.get [as provider] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/config/dist/configDefaults.js:271:1)
    at Object.detect (/usr/local/lib/node_modules/truffle/build/webpack:/packages/environment/environment.js:19:1)
    at Object.module.exports [as run] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:19:1)
    at runCommand (/usr/local/lib/node_modules/truffle/build/webpack:/packages/core/lib/command-utils.js:184:1)
Truffle v5.5.18 (core: 5.5.18)
Node v18.3.0

## Environment

* Operating System: Ubuntu 22.04 LTS
* Ethereum client:
* Truffle version (`v5.5.18`):
* node version (`v18.3.0`):
* npm version (`8.13.2`):

**Comment by cliffoo** [comment]
Hey @yahyeShorie, thanks for opening this. There is an [open issue](https://github.com/trufflesuite/truffle/issues/5305) on node 18 support (which Truffle is actively working towards but doesn't currently have). Could you try downgrading to node 16 and give it another try? Thanks.

**Comment by yahyeShorie** [comment]
Thanks. I will try it.

**Comment by cds-amal** [comment]
@yahyeShorie, did you have any luck downgrading Node?

**Comment by fainashalts** [comment]
Hi @yahyeShorie! It looks like we haven't had any activity on this issue since our suggestion to try downgrading Node. I'm going to close this issue for maintenance but please feel free to open a new issue if anything else comes up. Thanks!
