### ISSUE TITLE
Bug: `@truffle/require` not able to resolve locally-installed modules (e.g. `ts-node`, `typescript`) when running under the globally-installed truffle bundle

### ISSUE THREAD

**Issue by benjamincburns** [trufflesuite/truffle#5381]
## Issue

When testing TypeScript migrations under the latest Truffle release, we observe `@truffle/require` fails to resolve `ts-node`, `typescript`, or other locally-installed modules when attempting to run TypeScript modules.

## Steps to Reproduce

**Important Note:** This issue does not reproduce when running truffle from the local dev environment (either via `cli.js` or the webpack bundle). If you are using the truffle dotfiles scripts for truffle devs, be sure to run `use-truffle-stable` before doing any of this (runs the global NPM install when executing the `truffle` command).

1. `npm install -g truffle@5.5.24`
2. `truffle unbox pet-shop pet-shop`
3. `cd pet-shop`
4. `npm install`
5. `npm install -D typescript`
6. `npm install -D ts-node`
7. Modify `truffle-config.js` to remove the `develop` network and switch the port of the `development` network to `8545`.
8. `mv migrations/1_initial_migration.js migrations/1_initial_migration.ts`
9. Replace the contents of `migrations/1_initial_migration.ts` with the file below
10. In a separate terminal run `ganache`
11. run `truffle migrate --reset`

Contents of `migrations/1_initial_migration.ts`:

```typescript
const Migrations = artifacts.require("./Migrations");

export default function(deployer: any) {
  deployer.deploy(Migrations);
};
```

## Expected Behavior

The migration should succeed without error.

## Actual Results
The migration fails after compilation with an error similar to the following:

```
TsNodeDependencyError: Attempted to execute module at path /home/username/projects/petshop/migrations/1_initial_migration.ts, but the 'ts-node' module, or one of its required peers has not been installed.
    at _getOrCreateCompilationService (/home/username/.nvm/versions/node/v12.22.12/lib/node_modules/truffle/build/webpack:/packages/require/dist/typescript.js:61:1)
    at Object.compile (/home/username/.nvm/versions/node/v12.22.12/lib/node_modules/truffle/build/webpack:/packages/require/dist/typescript.js:41:1)
    at Object.file (/home/username/.nvm/versions/node/v12.22.12/lib/node_modules/truffle/build/webpack:/packages/require/dist/index.js:88:1)
    at Migration._load (/home/username/.nvm/versions/node/v12.22.12/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:42:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration.run (/home/username/.nvm/versions/node/v12.22.12/lib/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:202:1)
    at Object.runMigrations (/home/username/.nvm/versions/node/v12.22.12/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:142:1)
    at Object.runFrom (/home/username/.nvm/versions/node/v12.22.12/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:107:1)
    at Object.runAll (/home/username/.nvm/versions/node/v12.22.12/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:111:1)
    at Object.run (/home/username/.nvm/versions/node/v12.22.12/lib/node_modules/truffle/build/webpack:/packages/migrate/index.js:84:1)
    at module.exports (/home/username/.nvm/versions/node/v12.22.12/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/runMigrations.js:10:1)
    at Object.module.exports [as run] (/home/username/.nvm/versions/node/v12.22.12/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate/run.js:41:1)
    at runCommand (/home/username/.nvm/versions/node/v12.22.12/lib/node_modules/truffle/build/webpack:/packages/core/lib/command-utils.js:184:1)
```

## Environment

**Important Note:** This issue does not reproduce when running truffle from the local dev environment (either via `cli.js` or the webpack bundle)

* Truffle version (`truffle version`): v5.5.24
* node version (`node --version`): >= v12

**Comment by benjamincburns** [comment]
Note that when I attempt to work around the issue by installing `ts-node` and `typescript` globally, it will then fail on a missing `@truffle/resolver` package. It _should_ be resolving this from the bundle, but that doesn't seem to be happening. That said, if I go ahead and install that package (globally - yuck), it does work.

**Comment by benjamincburns** [comment]
Note: the simplest workaround that I've found so far is to install truffle locally and run it from `node_modules/.bin/truffle` or via the `npx` or `yarn exec` commands.
