### ISSUE TITLE
Javascript's console.log doesn't work in develop REPL

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/truffle#5409]
This seems to have happened sometime after v5.5.22. Note, if you try to install v5.5.22 it would not be the same because of caret/semver resolution. 

```console
truffle(develop)> console.log("hi")
evalmachine.<anonymous>:0
console.log("hi")
        ^

Uncaught TypeError: console.log is not a function
    at evalmachine.<anonymous>
    at sigintHandlersWrap (node:vm:268:12)
    at Script.runInContext (node:vm:137:14)
    at runScript (/home/amal/.nvm/versions/node/v16.16.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:381:1)
    at Console.interpret (/home/amal/.nvm/versions/node/v16.16.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:396:1)
    at bound (node:domain:421:15)
    at REPLServer.runBound [as eval] (node:domain:432:12)
    at REPLServer.onLine (node:repl:893:10)
    at REPLServer.emit (node:events:527:28)
    at REPLServer.emit (node:domain:475:12)
```

## Reproduction steps

- `truffle develop` 
- try to use console.log

**Comment by cds-amal** [comment]
doh! Turned out to be a contract name collision!
