### ISSUE TITLE
Nonce tracking error - web3.eth.sendTransaction incorrect nonce

### ISSUE THREAD

**Issue by alex-miller-0** [trufflesuite/truffle#549]
- [X] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When running a Truffle test, I need to send ether via `web3.eth.sendTransaction()`. I am using the global `web3` variable to do this. Making this call incorrectly tracks the nonce a forms a tx with nonce 1 higher than it should be. Note that in the same test, I am making a call to `myContract.myMethod()`, which tracks the nonce correctly.

## Steps to Reproduce

Here is my code:

```
it('Should register serial numbers for 4 test devices', function() {
    Promise.each(serials, function(s, j) {
        registry.register(infura_addrs[j+1], s, { from: deployer })
        .then((success) => {
          return new Promise((resolve, reject) => web3.eth.sendTransaction({ from: deployer, value: 0.1*Math.pow(10, 18), to: infura_addrs[j+1] }, (err, result) => err ? reject(err) : resolve(result)))
        .then(() => { assert.equal(1, 1) })
        .catch((err) => { assert.equal(err, null, err) })
    })
  })
```

## Expected Behavior

The test to pass.

## Actual Results

An error is thrown of form:

```
/Users/alexmiller/meta-gridplus/gridplus/gridx-hub/node_modules/truffle/build/cli.bundled.js:213982
        throw reason;
        ^
AssertionError: ProviderError: Error: the tx doesn't have the correct nonce. account has nonce of: 448 tx has nonce of: 449
    at runCall (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:88086:10)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11855:24
    at replenish (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8948:17)
    at iterateeCallback (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8933:17)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:8908:16
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:11860:13
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:74400:16
    at replenish (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:74347:25)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:74356:9
    at eachLimit (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:74280:36)
    at /usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:75460:16
    at VM.AsyncEventEmitter.emit (/usr/local/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:74051:3): expected { Object (message, stack, ...) } to equal null
    at registry.register.then.then.catch (/Users/alexmiller/meta-gridplus/gridplus/gridx-hub/truffle/test/registry.js:95:34)
    at <anonymous>
```

## Environment

* Operating System: Sierra 10.12.6 
* Truffle version: 3.4.4
* Ethereum client: INFURA (remote deployment)
* node version: 8.2.1
* npm version: 5.3.0

**Comment by taxic** [comment]
So have you solved it? I came across the same error.

**Comment by hayesgm** [comment]
I had a similar issue on deployments (incorrect nonce). I solved my issue by changing my deployment from:

```javascript
return deployer.deploy([
    ContractA,
    ContractB
  ]).then(function() {
    return deployer.deploy(ContractC);
  });
```

to

```javascript
return deployer.deploy(ContractA).then(function() {
  	return deployer.deploy(ContractB).then(function() {
  		return deployer.deploy(ContractC);
  	});
  });
```
