### ISSUE TITLE
During test, calling msg.sender.transfer produces `Error: VM Exception while processing transaction: invalid opcode`

### ISSUE THREAD

**Issue by jwietelmann** [trufflesuite/truffle#561]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

`Error: VM Exception while processing transaction: invalid opcode` when calling `msg.sender.transfer` that should not be happening. Contract code has been manually tested in Ethereum Wallet against Ropsten and found to work.

## Steps to Reproduce

In a fresh Truffle project, paste this into a file `tests/TestNonsense.sol`:

```
pragma solidity ^0.4.2;

import "truffle/Assert.sol";

contract Ledger {
  mapping(address => uint) balances;

  function Ledger() payable {
    balances[msg.sender] = msg.value;
  }

  function withdraw() {
    var balance = balances[msg.sender];
    balances[msg.sender] = 0;
    msg.sender.transfer(balance); // VM Exception here.
  }

  // This one won't fail because it doesn't attempt a transfer.
  function withdrawWithoutTransfer() {
    var balance = balances[msg.sender];
    balances[msg.sender] = 0;
  }

  function deposit() payable {
    balances[msg.sender] += msg.value;
  }
}

contract TestNonsense {
  uint public initialBalance = 5 ether;
  Ledger public ledger;

  // Does not have error.
  function testDeposit() {
    ledger = new Ledger();
    ledger.deposit.value(1 ether)();
  }

  // Also no error.
  function testWithdrawWithoutTransfer() {
    ledger = new Ledger();
    ledger.deposit.value(1 ether)();
    ledger.withdrawWithoutTransfer();
  }

  // Invalid opcode even though the contract function works in Ethereum Wallet.
  function testWithdraw() {
    ledger = new Ledger();
    ledger.deposit.value(1 ether)();
    ledger.withdraw();
  }
}
```

Then start up testrpc and run `truffle test test/TestNonsense.sol`.

## Expected Behavior

All tests pass without VM Exception.

## Actual Results

```
TestNonsense
    ✓ testDeposit (43ms)
    ✓ testWithdrawWithoutTransfer (39ms)
    1) testWithdraw
    > No events were emitted


  2 passing (1s)
  1 failing

  1) TestNonsense testWithdraw:
     Error: VM Exception while processing transaction: invalid opcode
      at Object.InvalidResponse (/Users/joel/.asdf/installs/nodejs/8.1.2/.npm/lib/node_modules/truffle/build/cli.bundled.js:37295:16)
      at /Users/joel/.asdf/installs/nodejs/8.1.2/.npm/lib/node_modules/truffle/build/cli.bundled.js:224765:36
      at /Users/joel/.asdf/installs/nodejs/8.1.2/.npm/lib/node_modules/truffle/build/cli.bundled.js:208348:9
      at XMLHttpRequest.request.onreadystatechange (/Users/joel/.asdf/installs/nodejs/8.1.2/.npm/lib/node_modules/truffle/build/cli.bundled.js:209773:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/Users/joel/.asdf/installs/nodejs/8.1.2/.npm/lib/node_modules/truffle/build/cli.bundled.js:67130:18)
      at XMLHttpRequest._setReadyState (/Users/joel/.asdf/installs/nodejs/8.1.2/.npm/lib/node_modules/truffle/build/cli.bundled.js:67420:12)
      at XMLHttpRequest._onHttpResponseEnd (/Users/joel/.asdf/installs/nodejs/8.1.2/.npm/lib/node_modules/truffle/build/cli.bundled.js:67575:12)
      at IncomingMessage.<anonymous> (/Users/joel/.asdf/installs/nodejs/8.1.2/.npm/lib/node_modules/truffle/build/cli.bundled.js:67535:24)
```

## Environment

* Operating System: OS X
* Truffle version: Truffle v3.4.9 (core: 3.4.8), Solidity v0.4.15 (solc-js)
* Ethereum client: EthereumJS TestRPC v4.1.1
* node version: v8.1.2
* npm version: 5.0.3

**Comment by idrabenia** [comment]
It's still actual!

**Comment by angilyu** [comment]
@jwietelmann did you find the answer?
