### ISSUE TITLE
Cannot initialize HDWalletProvider

### ISSUE THREAD

**Issue by dancespiele** [trufflesuite/truffle#5735]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue

When I try to initialize `HDWalletProvider` I get this error:
```bash
 `Expected input type is Uint8Array (got object)`
toBytes (node_modules/@noble/hashes/utils.js:89:15)
      at pbkdf2Init (node_modules/@noble/hashes/pbkdf2.js:17:45)
      at pbkdf2 (node_modules/@noble/hashes/pbkdf2.js:42:44)
      at mnemonicToSeedSync (node_modules/@scure/bip39/index.js:140:32)
      at HDWalletProvider.checkBIP39Mnemonic (node_modules/@truffle/hdwallet-provider/src/index.ts:329:25)
      at new HDWalletProvider (node_modules/@truffle/hdwallet-provider/src/index.ts:109:12)
      at Object.<anonymous> (integration-tests/dtp.spec.tsx:20:47)
```

## Steps to Reproduce

The code to reproduce:
```ts
if (process.env.SEED_WORDS) {
      const seedphrase = process.env.SEED_WORDS
      appConfig.web3Provider = new HDWalletProvider({
        mnemonic: {
          phrase: seedphrase
        },
        providerOrUrl: appConfig.web3ProviderUri,
        addressIndex: 0,
        numberOfAddresses: 10,
      })
    }
```
I checked that SEE_WORDS contain the 12 words

## Expected Behavior

HDWalletProvider should initialize

## Actual Results

```bash
 `Expected input type is Uint8Array (got object)`
toBytes (node_modules/@noble/hashes/utils.js:89:15)
      at pbkdf2Init (node_modules/@noble/hashes/pbkdf2.js:17:45)
      at pbkdf2 (node_modules/@noble/hashes/pbkdf2.js:42:44)
      at mnemonicToSeedSync (node_modules/@scure/bip39/index.js:140:32)
      at HDWalletProvider.checkBIP39Mnemonic (node_modules/@truffle/hdwallet-provider/src/index.ts:329:25)
      at new HDWalletProvider (node_modules/@truffle/hdwallet-provider/src/index.ts:109:12)
      at Object.<anonymous> (integration-tests/dtp.spec.tsx:20:47)
```

## Environment

* Operating System: Linux Manjaro
* Ethereum client: polygon infura
* @truffle/hdwallet-provider version (`truffle version`): 2.1.2
* node version (`node --version`): v16.14.0
* npm version (`npm --version`): 8.19.2

**Comment by eggplantzzz** [comment]
Hey @dancespiele, thanks for reporting this issue! Just checking to make sure, your seed phrase is a string with 12 words from the bip39 list. You can find the word list [here](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki). Also note that you cannot arbitrarily pick words in any order as there is some sort of checksum validation that happens. Let me know if you think that your seed phrase is in the proper format or not!

If it is the case that your seed phrase is not in the proper format, Truffle should probably produce a better error message for this case!

**Comment by lsqproduction** [comment]
Closing for issue maintenance.
