### ISSUE TITLE
Truffle doesn't decode custom revert error

### ISSUE THREAD

**Issue by cds-amal** [trufflesuite/truffle#5736]
## Issue

Can't decode a custom error with truffle develop or console.

## Steps to Reproduce

1. Create a new truffle project and add the following contract. 

  ```solidity
  // SPDX-License-Identifier: MIT
  pragma solidity >=0.4.22 <0.9.0;

  contract Clue {
    uint public counter = 0;

    error MysteryError(string enigma);

    function poke() public returns (uint) {
      counter += 1;
      if (counter == 1) {
        revert MysteryError({
          enigma: "mu mu mu"
        });
      }
      return counter;
    }
  }
```
1. start truffle develop
  `truffle develop`
1. Compile the contracts, instantiate and interact with contract
  - `compile`
  - `clue = await Clue.new()`
  - `await clue.poke({gas: 0xfffff})`
  
## Expected Behavior

The contract should revert and truffle should decode the custom error. 

## Actual Results

```console
truffle(develop)> await clue.poke({gas: 0xfffff})
Uncaught:
StatusError: Transaction: 0x52f3ed9ff72873fd41a7d1eb16cb151e96ebc99a4494b8dfa4d088ed2eb63bde exited with an error (status 0). Reason given: Custom error (could not decode).
    at evalmachine.<anonymous>:1:14
    at evalmachine.<anonymous>:2:49
    at sigintHandlersWrap (node:vm:276:12)
    at Script.runInContext (node:vm:139:14)
    at runScript (/home/amal/.nvm/versions/node/v18.12.1/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:454:1)
    at Console.interpret (/home/amal/.nvm/versions/node/v18.12.1/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:469:1)
    at bound (node:domain:433:15)
    at REPLServer.runBound [as eval] (node:domain:444:12)
    at REPLServer.onLine (node:repl:902:10)
    at REPLServer.emit (node:events:513:28)
    at REPLServer.emit (node:domain:489:12)
    at REPLServer.[_onLine] [as _onLine] (node:internal/readline/interface:425:12)
    at REPLServer.[_line] [as _line] (node:internal/readline/interface:886:18)
    at REPLServer.[_ttyWrite] [as _ttyWrite] (node:internal/readline/interface:1264:22)
    at REPLServer.self._ttyWrite (node:repl:997:9)
    at ReadStream.onkeypress (node:internal/readline/interface:273:20)
    at ReadStream.emit (node:events:513:28)
    at ReadStream.emit (node:domain:489:12)
    at emitKeys (node:internal/readline/utils:357:14)
    at emitKeys.next (<anonymous>) {
  tx: '0x52f3ed9ff72873fd41a7d1eb16cb151e96ebc99a4494b8dfa4d088ed2eb63bde',
  receipt: {
    transactionHash: '0x52f3ed9ff72873fd41a7d1eb16cb151e96ebc99a4494b8dfa4d088ed2eb63bde',
    transactionIndex: 0,
    blockNumber: 2,
    blockHash: '0x00eaf4821b87e216f8d954967c224124427b9f021f05434aa9bcb550a8cb7d32',
    from: '0xba6470d857d567b97355079650b7c2c1c55c0660',
    to: '0x5e2bf4b2bb75fa6e18bf455bb5958a33eaf3e2c8',
    cumulativeGasUsed: 43916,
    gasUsed: 43916,
    contractAddress: null,
    logs: [],
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    status: false,
    effectiveGasPrice: 3271325182,
    type: '0x2',
    rawLogs: []
  },
  reason: 'Custom error (could not decode)',
  hijackedStack: 'StatusError: Transaction: 0x52f3ed9ff72873fd41a7d1eb16cb151e96ebc99a4494b8dfa4d088ed2eb63bde exited with an error (status 0). Reason given: Custom error (could not decode).\n' +
    '     Please check that the transaction:\n' +
    '     - satisfies all conditions set by Solidity `require` statements.\n' +
    '     - does not trigger a Solidity `revert` statement.\n' +
    '\n' +
    '    at Object.receipt (/home/amal/.nvm/versions/node/v18.12.1/lib/node_modules/truffle/build/webpack:/packages/contract/lib/handlers.js:128:1)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
    '    at Function.start (/home/amal/.nvm/versions/node/v18.12.1/lib/node_modules/truffle/build/webpack:/packages/contract/lib/override.js:50:1)'
}

```

### Truffle debugger can decode the error

```console
truffle(develop)> debug 0x52f3ed9ff72873fd41a7d1eb16cb151e96ebc99a4494b8dfa4d088ed2eb63bde
Starting Truffle Debugger...

Addresses affected:
 0x5E2bF4b2bb75fA6e18BF455Bb5958a33eAf3e2c8 - Clue

Clue.sol:

2: pragma solidity >=0.4.22 <0.9.0;
3:
4: contract Clue {
   ^^^^^^^^^^^^^^^

debug(develop:0x52f3ed9f...)> c

Transaction halted with a RUNTIME ERROR.

The following error was thrown:
Clue.MysteryError(
  enigma: 'mu mu mu' (type: string)
)
Please inspect your transaction parameters and contract code to determine the meaning of this error.

Stacktrace:
Error: Revert (custom error)
  at Clue.poke (/home/amal/work/reproduce/2022/11/25/custom-error/contracts/Clue.sol:12:14)


Location of error:

Clue.sol:

10:     counter += 1;
11:     if (counter == 1) {
12:       revert MysteryError({
                 ^^^^^^^^^^^^^^

```

**Comment by haltman-at** [comment]
We already have #4123; can this be closed as a duplicate?
