### ISSUE TITLE
Codec docs no longer build

### ISSUE THREAD

**Issue by haltman-at** [trufflesuite/truffle#5793]
## Issue

Codec docs aren't building.  Attempting yields the following error message:
```
Error: The plugin typedoc-plugin-remove-references could not be loaded.
Error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/converter' is not defined by "exports" in /home/sniffnoy/truffle/truffle/node_modules/typedoc/package.json
    at new NodeError (internal/errors.js:322:7)
    at throwExportsNotFound (internal/modules/esm/resolve.js:332:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:565:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/sniffnoy/truffle/truffle/node_modules/typedoc-plugin-remove-references/dist/index.js:5:21)
error Command failed with exit code 1.
```

No idea what's going wrong.  I tried updating typedoc just in case that would help, it didn't.  Also apparently current typedoc versions don't require an explicit `plugin` line in their config...?  I actually tried removing the `plugin` line to see what would happen, and, indeed, the error was exactly the same!

## Environment

* Truffle version (`truffle version`): 5.7.0

**Comment by cliffoo** [comment]
Fixed in [v5.7.3](https://github.com/trufflesuite/truffle/releases/tag/v5.7.3). Closing.
