### ISSUE TITLE
Truffle unable to work over HTTPS

### ISSUE THREAD

**Issue by nosuchip** [trufflesuite/truffle#582]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

What the issue is, in broad strokes.

## Steps to Reproduce

1. Install Ethereum node using `geth` on the remote host and bind it to the local port, address 127.0.0.1
2. Install Nginx and setup SSL certificate using Let's Encrypt.
3. Setup Nginx's downstream pointing to the address 127.0.0.1, port - specified in pt.1
4. Check that you can connect to the node using `geth attach https://HOST:PORT`
5. Create basic contract (does not matter what content, only validity is important)
6. Update truffle config with `HOST` and `PORT` in network config
7. Run `truffle compile` and then `truffle deploy --network NETNAME`

## Expected Behavior

Contract deployed successfully

## Actual Results

Deployment failed with error below:

```
Using network 'rinkeby'.

Running migration: 1_initial_migration.js
Error: Invalid JSON RPC response: "<html>\r\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>The plain HTTP request was sent to HTTPS port</center>\r\n<hr><center>nginx/1.10.2</center>\r\n</body>\r\n</html>\r\n"
    at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/cli.bundled.js:37022:16)
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/cli.bundled.js:208872:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/cli.bundled.js:210748:18)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/cli.bundled.js:211038:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/cli.bundled.js:211193:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:211153:24)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
```

## Environment

* Operating System: Linux Mint 17
* Truffle version: 3.4.4
* Ethereum client: geth 1.6.7-stable-ab5646c5
* node version: 8.1.4
* npm version: 5.4.2

**Comment by shapeshed** [comment]
See https://ethereum.stackexchange.com/questions/26688/truffle-work-over-https
Successfully ran migrations over https using this method.

**Comment by nosuchip** [comment]
@shapeshed I know, it is my own solution.

**Comment by shapeshed** [comment]
Yeah, more for people finding this issue by Google.

**Comment by Levino** [comment]
Looks like the workaround only works with `web3@0.20.x` and not with the new `web3@1.0.0-beta.x`.
