### ISSUE TITLE
Debugger crashes on any action

### ISSUE THREAD

**Issue by nikita-fuchs** [trufflesuite/truffle#587]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Debugger crashes

## Steps to Reproduce
take any project,
truffle develop
migrate --reset
debug [txID of Migrations contract]
press enter, or enter "i" (step into) , "o" (step over), "u" (step out) or "n" (step next)

## Expected Behavior

See no errors.

## Actual Results

```
Error: Trace and instruction mismatch.

trace {
  "depth": 0,
  "error": "",
  "gas": 4628100,
  "gasCost": 200,
  "memory": [
    "0000000000000000000000000000000000000000000000000000000000000000",
    "0000000000000000000000000000000000000000000000000000000000000000",
    "0000000000000000000000000000000000000000000000000000000000000060"
  ],
  "op": "PUSH1",
  "pc": 21,
  "stack": [
    "0000000000000000000000000000000000000000000000000000000000000000",
    "0000000000000000000000000000000000000000000000000000000000000000"
  ],
  "storage": {}
}
instruction {
  "name": "PUSH2",
  "fee": 3,
  "in": 0,
  "out": 1,
  "dynamic": false,
  "pc": 52,
  "pushData": "0x005e",
  "index": 12,
  "jump": "-",
  "start": 25,
  "length": 507,
  "range": {
    "start": {
      "line": 2,
      "column": 0
    },
    "end": {
      "line": 23,
      "column": 0
    }
  }
}

This is likely due to a bug in the debugger. Please file an issue on the Truffle issue tracker and provide as much information about your code and transaction as possible.

Fatal Error: See above.
    at Debugger.advance (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:333137:13)
    at Debugger.step (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:333169:10)
    at Object.interpreter (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:327758:22)
    at ReplManager.interpret (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:200019:18)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:115:13)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:279:10)
```

## Environment

* Operating System: Ubuntu 16
* Truffle version: 4@Beta
* Ethereum client: Truffle develop
* node version: 8.5
* npm version: 5.3

**Comment by amosjyng** [comment]
I am getting this too on El Capitan, Truffle v4.0.6, Ethereum client Ganache,  node v9.6.1 and npm v5.6.0 . Have there been any updates on this?

**Comment by cgewecke** [comment]
@nikita-fuchs @amosjyng `truffle-debugger` on `4.1.5` contains some significant improvements - worth checking out! Closing this for house-keeping because it refers to a much earlier incarnation of the tool.
