### ISSUE TITLE
"Error: EACCES: permission denied, open '/Users/mac/Library/Preferences/truffle-nodejs/config.json.tmp-54458241332dcbd4'"

### ISSUE THREAD

**Issue by emeleonufavour** [trufflesuite/truffle#6059]
I am trying to run the command "truffle develop" on my laptop. This is what I keep getting.

```
mac@FAVOURs-MBP truffleLearning % truffle develop              
Error: EACCES: permission denied, open '/Users/mac/Library/Preferences/truffle-nodejs/config.json.tmp-54458241332dcbd4'
    at openSync (node:fs:601:3)
    at attempt (/Users/mac/.nvm/versions/node/v18.16.0/lib/node_modules/truffle/build/webpack:/node_modules/atomically/dist/utils/retryify.js:33:1)
    at Object.writeFileSync (/Users/mac/.nvm/versions/node/v18.16.0/lib/node_modules/truffle/build/webpack:/node_modules/atomically/dist/index.js:136:1)
    at Conf._write (/Users/mac/.nvm/versions/node/v18.16.0/lib/node_modules/truffle/build/webpack:/packages/config/node_modules/conf/dist/source/index.js:375:1)
    at Conf.set store [as store] (/Users/mac/.nvm/versions/node/v18.16.0/lib/node_modules/truffle/build/webpack:/packages/config/node_modules/conf/dist/source/index.js:296:1)
    at Conf.set (/Users/mac/.nvm/versions/node/v18.16.0/lib/node_modules/truffle/build/webpack:/packages/config/node_modules/conf/dist/source/index.js:189:1)
    at Object.getOrGenerateMnemonic (/Users/mac/.nvm/versions/node/v18.16.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/mnemonics/mnemonic.js:33:1)
    at Object.getAccountsInfo (/Users/mac/.nvm/versions/node/v18.16.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/mnemonics/mnemonic.js:47:1)
    at Object.module.exports [as run] (/Users/mac/.nvm/versions/node/v18.16.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/develop/run.js:31:1)
    at runCommand (/Users/mac/.nvm/versions/node/v18.16.0/lib/node_modules/truffle/build/webpack:/packages/core/lib/command-utils.js:297:1)
Truffle v5.9.2 (core: 5.9.2)
Node v18.16.0
mac@FAVOURs-MBP truffleLearning % 
```

**Comment by eggplantzzz** [comment]
Hey @emeleonufavour, these types of errors occur usually when a user doesn't have the proper permissions to access the config file. To solve these I would recommend re-installing node and npm using a node version manager like nvm (which is actually what npm recommends as well). You can check out [this article](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) from npm which goes into more detail about how to do this. Let me know how it goes!

**Comment by eggplantzzz** [comment]
Closing this for issue maintenance.
