### ISSUE TITLE
truffle init command does not work

### ISSUE THREAD

**Issue by Greg-Lumeo** [trufflesuite/truffle#6062]
- [x] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## Issue
Truffle init command does not work after install

## Steps to Reproduce
sudo npm install -g truffle
truffle init

## Expected Behavior

Initiates development suite

## Actual Results

/usr/local/lib/node_modules/truffle/build/3618.bundled.js:24504
            return _this.outputFormatter && res ? _this.outputFormatter(res, this?.hexFormat) : res;
                                                                                  ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.__webpack_require__.f.require (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:608:28)
    at Promise.all.Object.keys.reduce (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:538:40)
    at Array.reduce (<anonymous>)

## Environment

* Operating System: 
* Ethereum client:
* Truffle version (`truffle version`):
* node version (`node --version`):
* npm version (`npm --version`):

**Comment by Greg-Lumeo** [comment]
Fixed with node update
