### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by TomWang1** [trufflesuite/truffle#6158]
~/Desktop/2022/contract/RCATruffer main !1 ?6 ❯ truffle migrate --network bsctest                                                                          13s

Compiling your contracts...
===========================
> Compiling ./contracts/MetaCoin.sol
> Artifacts written to /Users/fly/Desktop/2022/contract/RCATruffer/build/contracts
> Compiled successfully using:
   - solc: 0.8.15+commit.e14f2714.Emscripten.clang

Starting migrations...
======================
> Network name:    'bsctest'
> Network id:      97
> Block gas limit: 50000000 (0x2faf080)

1_deploy_contracts.js
=====================

   Deploying 'MetaCoin'
   --------------------
Error: Unhandled error. ({
  code: -32603,
  message: 'Client network socket disconnected before secure TLS connection was established',
  data: {
    originalError: {
      code: 'ECONNRESET',
      path: undefined,
      host: undefined,
      port: 0,
      localAddress: undefined
    }
  }
})
    at new NodeError (node:internal/errors:399:5)
    at Web3ProviderEngine.emit (node:events:502:17)
    at /Users/fly/node_modules/web3-provider-engine/index.js:54:14
    at afterRequest (/Users/fly/node_modules/web3-provider-engine/index.js:148:21)
    at /Users/fly/node_modules/web3-provider-engine/index.js:174:21
    at /Users/fly/node_modules/web3-provider-engine/index.js:232:9
    at /Users/fly/node_modules/async/internal/once.js:12:16
    at replenish (/Users/fly/node_modules/async/internal/eachOfLimit.js:61:25)
    at /Users/fly/node_modules/async/internal/eachOfLimit.js:71:9
    at eachLimit (/Users/fly/node_modules/async/eachLimit.js:43:36)
    at /Users/fly/node_modules/async/internal/doLimit.js:9:16
    at end (/Users/fly/node_modules/web3-provider-engine/index.js:211:5)
    at Request._callback (/Users/fly/node_modules/web3-provider-engine/subproviders/rpc.js:36:21)
    at self.callback (/Users/fly/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/Users/fly/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

* Operating System: MAC OS
* Ethereum client:   BSC
*     bsctest: {
      provider: function() {
          return new HDWalletProvider("", "https://data-seed-prebsc-1-s1.binance.org:8545/") },
      network_id: 97,
      chain_id:97,
      gasPrice: 10000000000000, 
      gas:50000000,
      websockets: true,
     },
* Truffle version (`truffle version`):v5.5.23 (core: 5.5.23)
* node version (`node --version`):v18.15.0
* npm version (`npm --version`): 9.5.0

**Comment by haltman-at** [comment]
Hm, this doesn't really seem like a Truffle issue, but rather an issue with the connection... is there anything that makes you think this is a Truffle issue in particular?  Otherwise, I would suggest contacting Binance, since the issue would appear to be with the connection to their server.

Thanks!

**Comment by gnidan** [comment]
Closing this since you haven't gotten back to us. Please open a new issue if you run into this again!
