### ISSUE TITLE
unbox failed，Error connecting to https://raw.githubusercontent.com/xxx

### ISSUE THREAD

**Issue by yjshi2015** [trufflesuite/truffle#6161]
- [ ] I've [opened a support ticket](https://trufflesuite.zendesk.com/hc/en-us/requests/new) before filing this issue.

---------------------------

## `truffle unbox metacoin`failed

when i create new project by using `truffle unbox metacoin`, but it does not work, it looks like network problem. so i tried do something below:
1、config vscode's proxy. does not work
2、downgrade node version from v19 to v18. does not work
3、add `151.101.56.133 raw.githubusercontent.com` in host file (i am in china). does not work
4、run `curl https://raw.githubusercontent.com/xxx/truffle-box.json`, i got the response, network maybe is ok, so why unbox failed???

## Steps to Reproduce

run `truffle unbox metacoin` in vscode's terminal, then it show the following exception
```
PS D:\GitHub\TruffleProjectDemo> truffle unbox metacoin
This directory is non-empty...
? Proceed anyway? (Y/n) 
Starting unbox...
=================

? Proceed anyway? Yes
✓ Preparing to download box
✖ Downloading
Unbox failed!
Error: Error connecting to https://raw.githubusercontent.com/truffle-box/metacoin-box/master/truffle-box.json. Please check your internet connection and try again.

getaddrinfo ENOENT raw.githubusercontent.com
    at Function.AxiosError.from (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\axios\dist\node\axios.cjs:789:1)
    at RedirectableRequest.handleRequestError (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\axios\dist\node\axios.cjs:2744:1)
    at RedirectableRequest.emit (node:events:514:28)
    at ClientRequest.eventHandlers.<computed> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\follow-redirects\index.js:14:1)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

## Environment

* Operating System: win10
* Code editor: vscode 1.81.1
* Truffle version (`truffle version`): v5.11.2
* node version (`node --version`): v18.17.0
* npm version (`npm --version`):  v8.19.4

**Comment by eggplantzzz** [comment]
Hey @yjshi2015, what is the response you get from the request for the json file?

Are you running this is the VSCode terminal? Can you try in a a normal terminal window and see what happens?

I'm not sure what the issue is offhand (I have no problem unboxing on my computer), but it is likely that it has something to do with you being in China. Sometimes users have problems accessing GitHub stuff from there. You don't happen to have a VPN that you could try this with, do you?

**Comment by Kooooooma** [comment]
@yjshi2015 Hey，你解决了吗？我也遇到同样的问题
