### ISSUE TITLE
getting this error any solutions?

### ISSUE THREAD

**Issue by Kushvanshi-Shubham** [trufflesuite/truffle#6166]
PS C:\Users\shubh\Blockchain\eventtrigger> truffle unbox react

Starting unbox...
=================

√ Preparing to download box
× Downloading
Unbox failed!
Error: Error connecting to https://raw.githubusercontent.com/truffle-box/react-box/master/truffle-box.json. Please check your internet connection and try again.

connect ETIMEDOUT 2405:200:1607:2820:41::36:443
    at Function.AxiosError.from (C:\Users\shubh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\axios\dist\node\axios.cjs:789:1)
    at RedirectableRequest.handleRequestError (C:\Users\shubh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\axios\dist\node\axios.cjs:2744:1)
    at RedirectableRequest.emit (node:events:514:28)
    at ClientRequest.eventHandlers.<computed> (C:\Users\shubh\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\follow-redirects\index.js:14:1)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
Truffle v5.11.2 (core: 5.11.2)
Node v18.17.0

**Comment by gnidan** [comment]
Hi, thanks for raising this.

Do you get this same result if you try `truffle unbox` with other boxes (e.g. `truffle unbox metacoin`)? I would guess so, but would like to confirm.

Do you have any interesting network conditions? Corporate proxy or great firewall perhaps? Those might get in the way in ways we can't help, unfortunately.
