### ISSUE TITLE
debug command fails inconsistently

### ISSUE THREAD

**Issue by bmmpxf** [trufflesuite/truffle#623]

**Comment by bmmpxf** [comment]
When inside the `truffle develop` console, running debug with a valid transaction id will sometimes fail, and sometimes succeed. There doesn't appear to be any pattern. Quotes or no quotes around the transaction id doesn't seem to make a difference either.

For example, below I ran the exact same command twice; the first failed, the second succeeded:

```
truffle(develop)> debug 0x7f799ad56584199db36bd617b77cc1d825ff18714e80da9d2d5a0a9fff5b4d42
Gathering transaction data...

TypeError: Cannot read property 'indexOf' of undefined
    at Function.get (C:\Users\Mike\AppData\Roaming\nvm\v7.9.0\node_modules\truffle\build\cli.bundled.js:299655:17)
    at Function.getter (C:\Users\Mike\AppData\Roaming\nvm\v7.9.0\node_modules\truffle\build\cli.bundled.js:299463:25)
    at Function.deployedBinary (C:\Users\Mike\AppData\Roaming\nvm\v7.9.0\node_modules\truffle\build\cli.bundled.js:299631:37)
    at Function.getter (C:\Users\Mike\AppData\Roaming\nvm\v7.9.0\node_modules\truffle\build\cli.bundled.js:299466:49)
    at Debugger.findMatchingContract (C:\Users\Mike\AppData\Roaming\nvm\v7.9.0\node_modules\truffle\build\cli.bundled.js:309059:42)
    at Debugger.contextForBinary (C:\Users\Mike\AppData\Roaming\nvm\v7.9.0\node_modules\truffle\build\cli.bundled.js:309024:23)
    at C:\Users\Mike\AppData\Roaming\nvm\v7.9.0\node_modules\truffle\build\cli.bundled.js:309179:39
    at Array.forEach (native)
    at C:\Users\Mike\AppData\Roaming\nvm\v7.9.0\node_modules\truffle\build\cli.bundled.js:309178:28
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
truffle(develop)> debug 0x7f799ad56584199db36bd617b77cc1d825ff18714e80da9d2d5a0a9fff5b4d42
Gathering transaction data...

Addresses affected:
  0x377bbcae5327695b32a1784e0e13bedc8e078c9c - SimpleStorage

Commands:
(enter) last command entered (step next)
(o) step over, (i) step into, (u) step out, (n) step next
(;) step instruction, (p) print instruction, (h) print this help, (q) quit


Store.sol | 0x377bbcae5327695b32a1784e0e13bedc8e078c9c:

1: pragma solidity ^0.4.0;
2:
3: contract SimpleStorage {
   ^^^^^^^^^^^^^^^^^^^^^^^

debug(develop:0x7f799ad5...)>
```

**Comment by brianedelman** [comment]
Getting same error but consistently with node 8.4.0 and 4 beta 2

**Comment by tcoulter** [comment]
Hi @brianedelman. The `invalid opcode` error is a completely different issue. Please file that in a new ticket.
