### ISSUE TITLE
Immediate deployment failure Parity/Byzantium

### ISSUE THREAD

**Issue by mbrix** [trufflesuite/truffle#626]
## Issue

Deploying a contract with truffle 4.0.0-beta.2 or earlier does not work on mainnet on Byzantium using Parity 1.8.0-betag.

## Steps to Reproduce

npm-run truffle migrate --network production --reset

## Expected Behavior
Normal contract deployment. No problems on Ropsten revival.

## Actual Results
Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x02c3dc1f97f2872b441abde072299a6d5a50607f0ba3b243a392be372c871b8a
Error encountered, bailing. Network state unknown. Review successful transactions manually.

However, the migrations contract is mined and deployed onto the network, but detection fails. I suspect it may have to do with it getting mined too quickly.

## Environment

* Operating System: Ubuntu Linux
* Truffle version: 4.0.0-beta.2
* Ethereum client: Parity 
* node version: v1.8.0-beta, v1.7.7
* npm version: 5.3.0

**Comment by drgorb** [comment]
at least it works with the stable release

**Comment by drgorb** [comment]
I just tried `MyContract.new()`in the console with 

* Ropsten
* Truffle v4.0.1
* Parity 1.7.10 (latest stable release)

The behaviour is slightly different: the transaction waits until it's been mined and then fails with 

    Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/Users/mroon/.nvm/versions/node/v8.5.0/lib/node_modules/truffle/build/cli.bundled.js:329221:46)
    at /Users/mroon/.nvm/versions/node/v8.5.0/lib/node_modules/truffle/build/cli.bundled.js:39618:25
    at /Users/mroon/.nvm/versions/node/v8.5.0/lib/node_modules/truffle/build/cli.bundled.js:331159:9
    at /Users/mroon/.nvm/versions/node/v8.5.0/lib/node_modules/truffle/build/cli.bundled.js:314196:9
    at XMLHttpRequest.request.onreadystatechange (/Users/mroon/.nvm/versions/node/v8.5.0/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/mroon/.nvm/versions/node/v8.5.0/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
    at XMLHttpRequest._setReadyState (/Users/mroon/.nvm/versions/node/v8.5.0/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/mroon/.nvm/versions/node/v8.5.0/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
    at IncomingMessage.<anonymous> (/Users/mroon/.nvm/versions/node/v8.5.0/lib/node_modules/truffle/build/cli.bundled.js:70564:24)
    at emitNone (events.js:110:20)

but the transaction is successful and the contract has been created as displayed in etherscan.io

**Comment by gnidan** [comment]
This looks like it's been fixed, so closing for now. Please let us know if that's not the case and we'll re-open.
