### ISSUE TITLE
Public fallback functions cannot be deployed 

### ISSUE THREAD

**Issue by illuzen** [trufflesuite/truffle#637]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Labelling fallback function as public causes inability to deploy with truffle.

I have a fallback function

```
function () public{
      revert();
}
```

When deploying contract I get 

```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:218485:46)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:34886:25
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:220423:9
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:72910:11
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:204149:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:205574:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:73069:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:73359:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:73514:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:73474:24)

```
This is despite using 6e6 gas on a small contract. Removing the public modifier makes it deploy fine. 

## Environment

* Operating System: OSX 10.12.6
* Truffle version: Truffle v3.4.11 
* Ethereum client: geth 1.7.2
* node version: v7.7.4
* npm version: 5.5.1

**Comment by illuzen** [comment]
Actually it may have just been a coincidence, it seems this error is non-deterministic. I just have to change something about the contract, and it works again. I get the error, remove the fallback entirely, it deploys. Later I get the error again, same contract, I put the fallback back in, it deploys. 

Btw I've been running into this issue for months now.

**Comment by cgewecke** [comment]
Closing as duplicated of #638
