### ISSUE TITLE
Dry-run migrations fail on block gas limit inside `truffle develop`

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/truffle#648]
<img width="639" alt="screen shot 2017-10-31 at 2 53 06 pm" src="https://user-images.githubusercontent.com/151065/32243322-533242f4-be4b-11e7-91fa-909b12134859.png">

**Comment by roderik** [comment]
I have the same thing, for me, also `truffle migrate` without develop fails with this error.

**Comment by roderik** [comment]
Did some further testing.

1. via truffle console I ran web3.eth.getBlock('latest') 

```
{ number: 0,
  hash: '0x477afbf81c6206f0cdda8f618ee4f494c4d22df82c2f3747ed5eebc756942ba8',
  parentHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
  nonce: '0x0',
  sha3Uncles: '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  transactionsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  stateRoot: '0xf128b89f919eb9b9a39125d4b172674a2947f9ea34a0bcb6a72f7ec897d60ad3',
  receiptRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
  miner: '0x0000000000000000000000000000000000000000',
  difficulty: BigNumber { s: 1, e: 0, c: [ 0 ] },
  totalDifficulty: BigNumber { s: 1, e: 0, c: [ 0 ] },
  extraData: '0x0',
  size: 1000,
  gasLimit: 4712388,
  gasUsed: 0,
  timestamp: 1509545916,
  transactions: [],
  uncles: [] }
```
**Notice the gasLimit of 4.712.388**

2. Then I ran migrate using `--verbose-rpc` and this is the deploy "Migrations" part

```
  > {
   >   "jsonrpc": "2.0",
   >   "id": 5,
   >   "method": "eth_sendTransaction",
   >   "params": [
   >     {
   >       "from": "0x60480e2e94613ab3187b9debe80a7822024f7e57",
   >       "gas": "0x6691b7",
   >       "gasPrice": "0x174876e800",
   >       "data": "0x6060604052341561000f57600080fd5b336000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506102e58061005e6000396000f300606060405260043610610062576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680630900f01014610067578063445df0ac146100a05780638da5cb5b146100c9578063fdacd5761461011e575b600080fd5b341561007257600080fd5b61009e600480803573ffffffffffffffffffffffffffffffffffffffff16906020019091905050610141565b005b34156100ab57600080fd5b6100b3610229565b6040518082815260200191505060405180910390f35b34156100d457600080fd5b6100dc61022f565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b341561012957600080fd5b61013f6004808035906020019091905050610254565b005b60008060009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561019e57600080fd5b8190508073ffffffffffffffffffffffffffffffffffffffff1663fdacd5766001546040518263ffffffff167c010000000000000000000000000000000000000000000000000000000002815260040180828152602001915050600060405180830381600087803b151561021157600080fd5b6102c65a03f1151561022257600080fd5b5050505050565b60015481565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415156102af57600080fd5b80600181905550505600a165627a7a72305820986ce3f04c906030d655d6a32d3e032bbe6a760f86ddec6d1402d535a23183100029"
   >     }
   >   ]
   > }
 <   {
 <     "id": 5,
 <     "jsonrpc": "2.0",
 <     "error": {
 <       "message": "Error: Exceeds block gas limit\n    at StateManager.queueTransaction (/src/build/cli.node.js:83114:21)\n    at GethApiDouble.eth_sendTransaction (/src/build/cli.node.js:82631:14)\n    at GethApiDouble.handleRequest (/src/build/cli.node.js:82434:10)\n    at next (/src/build/cli.node.js:52153:18)\n    at VmSubprovider.handleRequest (/src/build/cli.node.js:59291:12)\n    at next (/src/build/cli.node.js:52153:18)\n    at GethDefaults.handleRequest (/src/build/cli.node.js:82339:12)\n    at next (/src/build/cli.node.js:52153:18)\n    at FilterSubprovider.handleRequest (/src/build/cli.node.js:58850:7)\n    at next (/src/build/cli.node.js:52153:18)",
 <       "code": -32000
 <     }
 <   }
```
** Notice the  `"gas": "0x6691b7"` where that hex number is 6.721.975, so we need about 2 million more gas than the gasLimit.

Some spelunking got me to https://github.com/trufflesuite/truffle/commit/463415e00124872798aed18012d52ef19e4d6181 where a test workaround was made, but I guess it did not deal with the source issue.

**Comment by roderik** [comment]
Ok, my issue was the same error but probably unrelated. v4 turned off the optimizer making the contracts bigger. If you use a standalone testrpc you need to set a higher gas limit like: `-l 0xfffffffffff`

**Comment by tomasienrbc** [comment]
I believe my error here: 

https://github.com/trufflesuite/truffle/issues/680

Is the same issue. I think dry-run is not using gasPrice settings properly or gasLimit or gas.

**Comment by gnidan** [comment]
Can anyone confirm if this is still an issue or not? Looking to close. Thanks!
