### ISSUE TITLE
[4beta2] Repeatedly have to restart development --log when using truffle test

### ISSUE THREAD

**Issue by brianedelman** [trufflesuite/truffle#659]
## Issue

Using `truffle develop --log` as my testrpc replacement, every 4 (or so) times of running `truffle test`, I have to exit out of the develop env and start it again. The error I receive is below.

```
Error: VM Exception while processing transaction: invalid opcode
    at Object.InvalidResponse (/Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:37872:16)
    at /Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:316805:36
    at /Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:164746:11
    at /Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:294942:9
    at XMLHttpRequest.request.onreadystatechange (/Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:296367:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:164934:18)
    at XMLHttpRequest._setReadyState (/Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:165224:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:165379:12)
    at IncomingMessage.<anonymous> (/Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:165339:24)
    at emitNone (events.js:110:20)
```

## Steps to Reproduce

Run truffle test multiple times without restarting truffle develop --log. I am running about 17 tests at the moment.

## Expected Behavior

The test should complete normally.

## Actual Results

The test does not get run. Files are compiled and solc runs and gives me warnings about public declarations, but the error above halts everything.

## Environment

* Operating System: 10.12.6
* Truffle version: 4.0.0-beta.2
Solidity v0.4.17
* node version: 8.4.0
* npm version: 5.5.1

**Comment by gnidan** [comment]
The `invalid opcode` error will likely be fixed once we get TestRPC upgraded in Truffle (release planned for next week). There might be an underlying issue however; leaving this open to follow-up after the release.

**Comment by brianedelman** [comment]
Moved on to other things for a while now. Can't speak to this specific bug. If I come back to it and it is an issue I can reopen. Thanks for checking in!

**Comment by gnidan** [comment]
Closing this for issue maintenance. Please let us know if it's still a problem! Thanks!
