### ISSUE TITLE
Truffle fails on testrpc v6 if there is an address for Migrations, but the chain does not have it anymore.

### ISSUE THREAD

**Issue by roderik** [trufflesuite/truffle#663]
Crosspost from: https://github.com/ethereumjs/testrpc/issues/414

in testrpc v5 if I ran "truffle migrate" on a new testrpc run, it was able to figure out that the Migrations contract was no longer there and do a full deploy.

since v6 it fails like this:

```
Error: Invalid JSON RPC response: {"id":3,"jsonrpc":"2.0"}
    at Object.InvalidResponse (/home/travis/.nvm/versions/node/v8.9.0/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
    at /home/travis/.nvm/versions/node/v8.9.0/lib/node_modules/truffle/build/cli.bundled.js:331156:36
    at /home/travis/.nvm/versions/node/v8.9.0/lib/node_modules/truffle/build/cli.bundled.js:314196:9
    at XMLHttpRequest.request.onreadystatechange (/home/travis/.nvm/versions/node/v8.9.0/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/travis/.nvm/versions/node/v8.9.0/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
    at XMLHttpRequest._setReadyState (/home/travis/.nvm/versions/node/v8.9.0/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
    at XMLHttpRequest._onHttpResponseEnd (/home/travis/.nvm/versions/node/v8.9.0/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
    at IncomingMessage.<anonymous> (/home/travis/.nvm/versions/node/v8.9.0/lib/node_modules/truffle/build/cli.bundled.js:70564:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
```

Running with --reset fixes this, but it is a change vs the previous version.

**Comment by gnidan** [comment]
Ooo @roderik thanks for reporting this! Pinging @benjamincburns so he's aware.

**Comment by benjamincburns** [comment]
@roderik just to save me a bit of time tracking that down - by any chance did you capture which RPC call produced erroneous response?

**Comment by tcoulter** [comment]
This has been fixed on the TestRPC side. We'll be updating the TestRPC used in `truffle develop` shortly.
