### ISSUE TITLE
Contract is not compilable if it's located in test/someFolder directory which contains Structs

### ISSUE THREAD

**Issue by rstormsf** [trufflesuite/truffle#695]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When mocked contract is located in tests folder with some Structs/Mappings in it, 
it can't be compiled

## Steps to Reproduce
1. Insert MainFile.sol into contracts folder (https://gist.github.com/rstormsf/19c48b76527aec15ae23546da24177ef)
2. Insert MainFileMock.sol into `test/mocks/MainFileMock.sol`

run some tests that use `MainFileMock.sol`

Please provide the shortest amount of steps to reproduce your issue.

## Expected Behavior

it should just work
## Actual Results
```bash

/Users/rstorm/repos/oracles-poa-network-contracts/node_modules/truffle/build/cli.bundled.js:304568
      throw e;
      ^
SyntaxError: Expected "!", "!=", "(", ")", "+", "++", "-", "--", "0", "<", "<=", "==", ">", ">=", "[", "^", "delete", "false", "hex", "mapping", "new", "this", "true", "v", "~", [1-9], comment, end of line, identifier, number, string, or whitespace but "{" found.
    at peg$buildStructuredError (/Users/rstorm/repos/oracles-poa-network-contracts/node_modules/truffle/build/cli.bundled.js:291924:12)
    at Object.peg$parse [as parse] (/Users/rstorm/repos/oracles-poa-network-contracts/node_modules/truffle/build/cli.bundled.js:304510:11)
    at Object.parse (/Users/rstorm/repos/oracles-poa-network-contracts/node_modules/truffle/build/cli.bundled.js:304563:23)
    at /Users/rstorm/repos/oracles-poa-network-contracts/node_modules/truffle/build/cli.bundled.js:202178:32
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)
make: *** [test] Error 1
```

## Environment

* Operating System: OSX
* Truffle version: 4.0.1
* Ethereum client: testrpc 6.0.3
* node version: 8.3.0
* npm version: 5.3.0

Possibly related to #309

**Comment by rstormsf** [comment]
when I move the same method into MainFile.sol (setBallotId) it complies just fine
