### ISSUE TITLE
Weird Compilation Issue when trying to run tests and log output

### ISSUE THREAD

**Issue by VoR0220** [trufflesuite/truffle#701]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

When running `truffle test` on a previously running contract, I added a log event to write a "we've reached this point" message. Getting a weird compilation error. Whenever it's removed it runs just fine.

## Steps to Reproduce

Start up a test contract. Add an event log `event Log(string)`. Try to use it in one of the Solidity unit tests. 

## Expected Behavior

Should just work. 

## Actual Results

```
  TestRoleManager
/Users/vor0220/.nvm/versions/node/v8.0.0/lib/node_modules/truffle/build/cli.bundled.js:317993
          if (val.constructor.isBN) {
                 ^

TypeError: Cannot read property 'constructor' of undefined
    at /Users/vor0220/.nvm/versions/node/v8.0.0/lib/node_modules/truffle/build/cli.bundled.js:317993:18
    at Array.forEach (native)
    at /Users/vor0220/.nvm/versions/node/v8.0.0/lib/node_modules/truffle/build/cli.bundled.js:317989:32
    at Array.map (native)
    at Object.decodeLogs (/Users/vor0220/.nvm/versions/node/v8.0.0/lib/node_modules/truffle/build/cli.bundled.js:317942:19)
    at Object.callback (/Users/vor0220/.nvm/versions/node/v8.0.0/lib/node_modules/truffle/build/cli.bundled.js:318070:35)
    at /Users/vor0220/.nvm/versions/node/v8.0.0/lib/node_modules/truffle/build/cli.bundled.js:39618:25
    at /Users/vor0220/.nvm/versions/node/v8.0.0/lib/node_modules/truffle/build/cli.bundled.js:331159:9
    at /Users/vor0220/.nvm/versions/node/v8.0.0/lib/node_modules/truffle/build/cli.bundled.js:314196:9
    at XMLHttpRequest.request.onreadystatechange (/Users/vor0220/.nvm/versions/node/v8.0.0/lib/node_modules/truffle/build/cli.bundled.js:329855:7)
```

## Environment

* Operating System: OSX High Sierra 10.13.1
* Truffle version: 4.0.1
* Ethereum client: Ganache?
* node version: 8.0.0
* npm version: 5.5.1

**Comment by VoR0220** [comment]
Weirdly enough I was able to get around this by changing the event log to `event Log(string s);`. This shouldn't really be a factor though.
