### ISSUE TITLE
Can't compile solidity assembly using truffle

### ISSUE THREAD

**Issue by facuspagnuolo** [trufflesuite/truffle#707]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Contracts with solidity assembly won't compile.

## Steps to Reproduce

1. clone this repo https://github.com/facuspagnuolo/ethereum-in-depth
2. install dependencies
3. run `npx truffle test`

## Expected Behavior

Contracts should compile.

## Actual Results
```
Compiling ./contracts/Migrations.sol...
Compiling ./test/assembly/conditional/Conditional.sol...
Compiling ./test/assembly/loop/Loop.sol...
Compiling ./test/edge_scenarios/non_payable/NonPayable.sol...

Compilation warnings encountered:

xxx/ethereum-in-depth/test/assembly/conditional/Conditional.sol:10:32: Warning: Variable is shadowed in inline assembly by an instruction of the same name
  function assemblyConditional(int256 number) public returns(uint256 result) {
                               ^-----------^
xxx/ethereum-in-depth/test/assembly/loop/Loop.sol:17:7: Warning: Jump instructions are low-level EVM features that can lead to incorrect stack access. Because of that they are discouraged. Please consider using "switch" or "for" statements instead.
      jumpi(loop, lt(i, times))
      ^---^
xxx/ethereum-in-depth/test/assembly/conditional/Conditional.sol:10:32: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
  function assemblyConditional(int256 number) public returns(uint256 result) {
                               ^-----------^
xxx/ethereum-in-depth/test/assembly/conditional/Conditional.sol:10:3: Warning: Function state mutability can be restricted to view
  function assemblyConditional(int256 number) public returns(uint256 result) {
  ^
Spanning multiple lines.


xxx/ethereum-in-depth/node_modules/truffle/build/cli.bundled.js:304568
      throw e;
      ^
SyntaxError: Expected comment, end of line, identifier, or whitespace but "1" found.
    at peg$buildStructuredError (xxx/ethereum-in-depth/node_modules/truffle/build/cli.bundled.js:291924:12)
    at Object.peg$parse [as parse] (xxx/ethereum-in-depth/node_modules/truffle/build/cli.bundled.js:304510:11)
    at Object.parse (xxx/ethereum-in-depth/node_modules/truffle/build/cli.bundled.js:304563:23)
    at xxx/ethereum-in-depth/node_modules/truffle/build/cli.bundled.js:202178:32
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)
```

## Environment

* Operating System: Mac OS Sierra
* Truffle version: 4.0.1
* Ethereum client: testrpc
* node version: 8.4.0
* npm version: 5.5.1

**Comment by mikegg89** [comment]
by any chance did you find a solution to this?

**Comment by facuspagnuolo** [comment]
Sadly  not @mikegg89

**Comment by cgewecke** [comment]
@facuspagnuolo Thanks for opening this and apologies for the delay in resolving - Truffle was using a deprecated JS parser to manage the way solidity tests are sequenced. That's been replaced with solc in the lastest release `0.4.6`. You should be able to write anything that's legal in your tests now :) 

Thanks again.
