### ISSUE TITLE
Error in truffle unbox webpack

### ISSUE THREAD

**Issue by mshadab-adeptia** [trufflesuite/truffle#716]
While running **truffle unbox webpack**, get this error,

C:\Users\Shadab\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:2253
});
^
SyntaxError: Unexpected token }
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

**Comment by aberger91** [comment]
I have a similar bug, trying to unbox pet-shop on Linux Mint

/usr/local/lib/node_modules/truffle/build/cli.bundled.js:126223
function VM (opts = {}) {
                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by elliotthill** [comment]
Same here, clean install of truffle:

`npm install truffle -g`

then 

> `truffle console --network rinkeby
/usr/local/lib/node_modules/truffle/build/cli.bundled.js:126223
function VM (opts = {}) {
                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
`

**Comment by reneras** [comment]
Investigating this.
@mshadab-adeptia What node version are you running? Does upgrading to version 6 resolve the issue for you as well?

**Comment by elliotthill** [comment]
Theres nothing to investigate? ES6 default function parameters are introduced in node 6 and above - so you either need to rework the code to not use default function params or not support node 6 and below.

**Comment by reneras** [comment]
@elliotthill Thanks for the info. If something needs fixing, always investigate by collecting the facts.

**Comment by mshadab-adeptia** [comment]
@reneras @elliotthill these are the versions installed,

$ node -v
v9.3.0

$ npm -v
Node.js version v9.3.0 is not supported. Agent disabled.
Node.js version v9.3.0 is not supported. Agent disabled.
Agent already injected - exiting
5.6.0

Could you please share commands to upgrade, if still needed?

**Comment by cgewecke** [comment]
@aberger91, @elliotthill is correct - Truffle requires Node 6.9.1 or higher. 
 
@mshadab-adeptia It looks like this problem has been resolved recently [over at NodeJS](https://github.com/nodejs/node/issues/16649). Their issue closed 16 days ago (just a few days before you're last comment). 

Hopefully you'll be able to get around this by re-installing Node. 

Closing because it looks like the underlying problem is upstream from Truffle. Please re-open if you find this is not the case and thanks for reporting.

**Comment by thomas-profitt** [comment]
This error message isn't printed by truffle, or webpack, or npm, or even node.
It's printed by the agent daemon for a service called DynaTrace, which hooks into node's execution, and misbehaves by printing warnings, breaking things like parsing JSON output from tools written in node.

We could've been spared the confusion of debugging this, had DynaTrace wrote a warning message that made it clear it was coming from the agent daemon, not from the software you thought you were running.

Update the DynaTrace agent, or remove it.
