### ISSUE TITLE
Truffle error for all commands (init, unbox, etc)

### ISSUE THREAD

**Issue by hendrikkoetsier** [trufflesuite/truffle#723]
hendrik@hendrik-SG3-345NL-m:~$ mkdir MetaCoin
hendrik@hendrik-SG3-345NL-m:~$ cd MetaCoin
hendrik@hendrik-SG3-345NL-m:~/MetaCoin$ truffle unbox metacoin
/usr/local/lib/node_modules/truffle/build/cli.bundled.js:126215
function VM (opts = {}) {
                             ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

* Operating System: Ubutu 16.04 LTS
* Truffle version: 4.0.3
* Ethereum client: Ganache
* node version: 4.2.6
* npm version: 3.5.2

**Comment by bwheeler96** [comment]
Your node version is way out of date for Truffle. Get node 8 or 9

**Comment by hendrikkoetsier** [comment]
Problem solved!.  Thanks for  your assistance!
