### ISSUE TITLE
Erorr on generating solidity event that has 'string indexed' argument

### ISSUE THREAD

**Issue by v-lukanin** [trufflesuite/truffle#728]
- [ v ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

The error 'Error: Number can only safely store up to 53 bits'
is shown when I  call contact method that has 'string indexed hello' parameter in event. If I remove the 'indexed' word then it works fine. Method is called from truffle console

## Steps to Reproduce
```
contract test { 
                uint _multiplier;
                event MultipliedLog(uint indexed a, uint indexed result, string indexed hello, address sender );

                function test(uint multiplier){
                    _multiplier = multiplier;
                }

                function multiply(uint a) returns(uint d) {
                    d = a * _multiplier;
                    MultipliedLog(a, d, "Hello world", msg.sender);
                    return d;
                }
            }
```

truffle(development)> migrate
truffle(development)> var c = test.at(test.address)
truffle(development)> c.address
'0x345ca3e014aaf5dca488057592ee47305d9b3e10'
truffle(development)> c.multiply(18)

## Expected Behavior

Method call should not fail. It works OK when is called from nethereum (.net c#)

## Actual Results

Error: Number can only safely store up to 53 bits
    at assert (C:\Users\vlukanin\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:228025:21)
    at BN.toNumber (C:\Users\vlukanin\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:228525:7)
    at C:\Users\vlukanin\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:182430:59
    at Array.forEach (<anonymous>)
    at decodeParams (C:\Users\vlukanin\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:182426:9)
    at Object.decodeEvent (C:\Users\vlukanin\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:182471:10)
    at C:\Users\vlukanin\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:317971:38
    at Array.map (<anonymous>)
    at Object.decodeLogs (C:\Users\vlukanin\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:317942:19)
    at Object.callback (C:\Users\vlukanin\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:318070:35)
truffle(development)> test.deployed().then(function(instance){instance.exit
SyntaxError: Unexpected end of input
    at createScript (vm.js:80:10)
    at Object.runInContext (vm.js:119:10)
    at Console.interpret (C:\Users\vlukanin\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:200887:17)
    at ReplManager.interpret (C:\Users\vlukanin\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:201603:18)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
    at emitOne (events.js:116:13)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10)

## Environment

* Operating System: Windows 10
* Truffle version: 4.0.1
* Ethereum client: truffle develop. Same issue when using Ganache
* node version: 8.9.1
* npm version: 5.5.1

**Comment by selfresonator** [comment]
I've seen people have this issue before, where either web3 or Solidity doesn't like that you are trying to mark your strings as `indexed`. There is discussion of this(https://ethereum.stackexchange.com/a/7170), but my problem is that my strings are _not_ indexed, and I am still receiving this error.

**Comment by cgewecke** [comment]
@selfresonator Could you share the event definition that's triggering this error so we can try to reproduce this?

**Comment by selfresonator** [comment]
Hopefully I'm not missing something painfully obvious here, especially since this is my first time open source GitHub issuing!

Anyway:

Contract
```
contract Elections is Ownable {
  event SendElection(string name, string description);

  function getElection() public {
    SendElection(electionList[0].name, electionList[0].description);
  }
}
```
In development console:
```
> compile
> migrate
> Elections.at("0x2a50...").createElection(<name>, <description>);
> Elections.at("0x2a50...").getElection(function(result){return result})
```
Error that runs both through the client and the development console:
```
BigNumber Error: new BigNumber() not a number: function (result){return result}
    at raise (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:45276:25)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:45264:33
    at new BigNumber (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:44292:67)
    at new BigNumber (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:44302:25)
    at toBigNumber (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:8991:12)
    at Object.toTwosComplement (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:9002:21)
    at SolidityTypeAddress.formatInputInt [as _inputFormatter] (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:28380:38)
    at SolidityTypeAddress.SolidityType.encode (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:32746:17)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:69251:29
    at Array.map (native)
```

**Comment by cgewecke** [comment]
Congratulations on your first issue!!! That's fantastic. Your report is lucid and concise, so high marks all round. 

To me it looks like the problem is that you're passing a function as a parameter to `.getElection`. But in the develop console you should be able to do this:
```
> Elections.at("0x2a50...").getElection()
.... transaction object should appear here .... another approach is:
> var result
> Elections.at("0x2a50...").getElection().then( val => result = val )
> result
.... another transaction object ...
> result.logs[0].args
{ name: 'self', description: 'resonator' }
```

Does that work?

**Comment by cgewecke** [comment]
@v-lukanin I think @selfresonator is correct that this behavior for dynamically sized solidity datatypes is expected. Just reproducing the (excellent) StackExchange discussion of this issue here for anyone else finding this issue:
>The combination of string and indexed does not work. To understand why, see how event arguments are stored in the blockchain.

>All transactions that are executed generate a transaction receipt, which contains a property called logs. You can look up the receipt using eth.getTransactionReceipt("0x...").

>In the transaction receipt, all event arguments that are not indexed are included in the data property. This property can hold values of arbitrary length. However, event arguments that are indexed are not stored in the data property, but end up in topics. This allows filters to work.

>For fixed size arguments types this is ok. The size of the entries in topics is long enough to hold all fixed types supported by Solidity. However, string can have an arbitrary length. To still be able to store those values in a topic, Solidity creates a hash of the value, which ends up in the topic.

>The upside is that filters can still work, since you can just create the hash of the value you're filtering for. The downside is that web3 is unable to decode the value, since that would require performing the hash function in reverse direction.

>To solve this problem, you have two options. You can remove indexed from the argument, so it is stored in the data field and no longer hashed to become part of a topic. Or, you change the type of the argument, e.g. into bytes32 or another. Which is appropriate depends on your case.

Closing for housekeeping.

**Comment by v-lukanin** [comment]
Sorry, I'm still do not understand two moments:
1. Why it works with no problem in NEthereum? The same blockchain is used.
2. Why this behavior for dynamically sized solidity datatypes is expected according to text above? As far as I understood, solidity creates a hash for string arguments. Hash always has the same length so there should be no problem to have it indexed also. This explains why NEthereum works fine with same contract. For me it seems that discussed error is an inner truffle issue.

**Comment by cgewecke** [comment]
@v-lukanin Just saw this, reopening.

**Comment by cgewecke** [comment]
@v-lukanin It looks like it's at the `web3` level - there's a recent comment on this subject by `web3`'s maintainer [here](https://github.com/ethereum/web3.js/issues/434#issuecomment-321526814) and they are working on a solution for `web3 1.0`. 

The underlying issue seems to be about decoding.

**Comment by cgewecke** [comment]
@v-lukanin Apologies but I'm going to close this again for house-keeping. The error comes from one of our dependencies and is a long-standing issue there. Hopefully there will be a resolution in the future.
