### ISSUE TITLE
Whenever i try to run migration it gives an error of invalid object response

### ISSUE THREAD

**Issue by dagogodboss** [trufflesuite/truffle#759]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

##  Migration Not Working

Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: revert
    at Object.InvalidResponse (C:\Program Files\nodejs\node_modules\truffle\build\cli.bundled.js:41483:16)
    at C:\Program Files\nodejs\node_modules\truffle\build\cli.bundled.js:330353:36
    at C:\Program Files\nodejs\node_modules\truffle\build\cli.bundled.js:176198:11
    at C:\Program Files\nodejs\node_modules\truffle\build\cli.bundled.js:326008:9
    at XMLHttpRequest.request.onreadystatechange (C:\Program Files\nodejs\node_modules\truffle\build\cli.bundled.js:329052:7)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Program Files\nodejs\node_modules\truffle\build\cli.bundled.js:176427:18)
    at XMLHttpRequest._setReadyState (C:\Program Files\nodejs\node_modules\truffle\build\cli.bundled.js:176717:12)
    at XMLHttpRequest._onHttpResponseEnd (C:\Program Files\nodejs\node_modules\truffle\build\cli.bundled.js:176872:12)
    at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\truffle\build\cli.bundled.js:176832:24)
    at emitNone (events.js:91:20)

**Comment by okwme** [comment]
i'm getting this error while running a test with some simple math. when i increase one of the variables (an addition) i get the error. when i decrease the variable it works correctly.

**Comment by cgewecke** [comment]
@dagogodboss @okwme Could you share the code causing this error so we can try to reproduce the problem? Thanks!

**Comment by cgewecke** [comment]
Closing due to lack of response. `VM exception etc` usually means something in your Solidity code is throwing a legitimate error.
