### ISSUE TITLE
"truffle init" get Error: Error making request. Please check the format of the requested resource: https://raw.githubusercontent.com/truffle-box/bare-box/master/truffle.js

### ISSUE THREAD

**Issue by daneric** [trufflesuite/truffle#766]
use "truffle init" command, and get error:
```
truffle init
Downloading...
Error: Error making request. Please check the format of the requested resource: https://raw.githubusercontent.com/truffle-box/bare-box/master/truffle.js
    at Request._callback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:314206:23)
    at self.callback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:285576:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:286268:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
```

I am using truffle 4.0.5 on mac 10.13.2

**Comment by cgewecke** [comment]
@daneric, @gnidan inserted an error logging line to debug this problem in the latest Truffle release `4.0.6`. If you have a chance could you install it, try again, and report the (hopefully different) error you see?

**Comment by gz65555** [comment]
I got the same problem. I am using truffle 4.0.6 on windows 10.

**Comment by ben-nyllabs** [comment]
Same error with v `4.0.6` on osx 10.12.6
`Downloading...
Error: Error making request to https://raw.githubusercontent.com/truffle-box/bare-box/master/truffle.js. Got error: self signed certificate in certificate chain. Please check the format of the requested resource.
    at Request._callback (/Users/bsaphier/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/truffle-box/lib/utils/unbox.js:42:1)
    at self.callback (/Users/bsaphier/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/request/request.js:186:1)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/Users/bsaphier/.nvm/versions/node/v8.9.4/lib/node_modules/truffle/build/webpack:/~/request/request.js:878:1)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)`

**Comment by cgewecke** [comment]
@ben-nyllabs The error is: `self signed certificate in certificate chain.` Looking around various Github threads it seems like it might be firewall related. Is there anything about your local environment that would cause it to fake SSL certs? 

Possibly helpful discussion at this [issue](https://github.com/MarkEdmondson1234/googleAnalyticsR/issues/123).

**Comment by lazaridiscom** [comment]
@gnidan (trufflesuite/truffle-core/issues/108 and  trufflesuite/truffle-core/issues/111)

**Comment by ben-nyllabs** [comment]
@cgewecke YES, there is! Should have been obvious, thank you! I just manually created the files/folders that `truffle init` makes, which only took like 30 seconds anyways... and now all is good

**Comment by cgewecke** [comment]
@daneric It's now clear this error results from local network permissions / behavior. @lazaridiscom has suggested we stop depending on network connectivity to manage `truffle init` and we all agree that's probably the best remedy. Tracking this problem at #108 and closing here. 

Thanks for reporting,

**Comment by 0pay** [comment]
Same error on Windows 7
D:\DOC_ANT\_CRY\ETHEREUM\TEST\casino-ethereum>truffle init
Downloading...
Error: Error making request to https://raw.githubusercontent.com/truffle-box/bare-box/master/truffle.js. Got error: connect ETIMEDOUT 151.101.0.133:443. Please check the format of the requested resource.
    at Request._callback (D:\DOC_ANT\_CRY\ETHEREUM\SOFTWARE\NODEJS\node_modules\truffle\build\webpack:\~\truffle-box\lib\utils\unbox.js:42:1)
    at self.callback (D:\DOC_ANT\_CRY\ETHEREUM\SOFTWARE\NODEJS\node_modules\truffle\build\webpack:\~\request\request.js:186:1)
    at Request.emit (events.js:160:13)
    at Request.onRequestError (D:\DOC_ANT\_CRY\ETHEREUM\SOFTWARE\NODEJS\node_modules\truffle\build\webpack:\~\request\request.js:878:1)
    at ClientRequest.emit (events.js:160:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:160:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)

Would you explain to me how to solve?
Thanks

**Comment by cgewecke** [comment]
@0pay In your case the error looks different - the connection timed out which suggests you  weren't able to connect to GitHub because of .a weak internet connection or your computer can't reach Github for some other reason. Could you verify that you are able to clone a GitHub repository at the command line (outside of truffle) by running:
```
git clone https://github.com/trufflesuite/truffle-init-bare.git
```

It's also possible you would see this error if you are behind a proxy / vpn.

**Comment by 0pay** [comment]
@cgewecke 
I've done and this is the result
Cloning into 'truffle-init-bare'...
fatal: unable to access 'https://github.com/trufflesuite/truffle-init-bare.git/': Received HTTP code 407 from proxy after CONNECT

I 'm behind a proxy.
How can I manage this problem?

**Comment by lazaridiscom** [comment]
try https://github.com/trufflesuite/truffle-init-bare/archive/master.zip

after this, I guess you have to move before the proxy.

**Comment by 0pay** [comment]
@lazaridiscom 
what is it?
How can I manage that?
Thanks

**Comment by lazaridiscom** [comment]
try the zip file. Sorry, I cannot help more (proxy brings problems, and I've no experience with this)

**Comment by 0pay** [comment]
I' ve tried to compile launching the command
truffle compile
but I received the the Jscript runtime error
module is undefined
800A1391

**Comment by lazaridiscom** [comment]
Please try getting help here: https://gitter.im/ConsenSys/truffle

**Comment by cgewecke** [comment]
@0pay There's a note on StackExchange [here](https://stackoverflow.com/questions/44110165/error-on-doing-truffle-init) which suggests you can get around this by setting local environment variables that ask the `request` module not to proxy / tunnel certain calls. More on that [here](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables). 

You can also just fetch the zip as @lazaridiscom has advised or clone `truffle-init-bare` as suggested [here](https://ethereum.stackexchange.com/questions/19718/how-to-manually-initialize-a-truffle-project-truffle-init)

**Comment by sugalivijaychari** [comment]
I also got the same error. and there is fishy about my local environment that would cause it to fake SSL certs. how could i resolve that?

E:\solidity-experiments>truffle init
Downloading...
Error: Error making request to https://raw.githubusercontent.com/truffle-box/bare-box/master/truffle.js. Got error: unable to verify the first certificate. Please check the format of the requested resource.
    at Request._callback (C:\Users\Vijay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-box\lib\utils\unbox.js:45:1)
    at self.callback (C:\Users\Vijay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request\request.js:186:1)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (C:\Users\Vijay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request\request.js:878:1)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

E:\solidity-experiments>truffle init

**Comment by cgewecke** [comment]
@sugalivijaychari If you're behind a firewall that limits your git access, you can download the init template to your desktop via the browser by clicking this link:

https://github.com/trufflesuite/truffle-init-bare/archive/master.zip

**Comment by leapming** [comment]
https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request
truffle init uses request to check the url availability, which throw an error as the above stackoverflow thread mentioned

**Comment by cantaloupeJinJin** [comment]
I got the same problem   when I use "truffle init " commond. I am using truffle5.0 on ubuntu16.
Downloading...
Error: Truffle Box at URL https://github.com/truffle-box/bare-box.git doesn't exist. If you believe this is an error, please contact Truffle support.
    at Request._callback (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-box/lib/utils/unbox.js:50:1)
    at Request.self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:185:1)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:1157:1)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:1079:1)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by eggplantzzz** [comment]
@cantaloupeJinJin I think there is currently something wrong with `truffle init` in version 4. If you upgrade to version 5 it should fix the problem.
```
npm uninstall -g truffle
npm i -g truffle
```

**Comment by cantaloupeJinJin** [comment]
> @cantaloupeJinJin I think there is currently something wrong with `truffle init` in version 4. If you upgrade to version 5 it should fix the problem.
> 
> ```
> npm uninstall -g truffle
> npm i -g truffle
> ```I used `npm uninstall -g truffle` ,then I use  `truffle version` to check,but the truffle doesn't be uninstall,
`jinjin@jinjin-virtual-machine:~$ npm uninstall -g Truffle
up to date in 0.045s
jinjin@jinjin-virtual-machine:~$ truffle version
Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)
`  How could I solve the problem?
Thanks

**Comment by gnidan** [comment]
@cantaloupeJinJin check your capitalization, that might be the problem.

**Comment by cantaloupeJinJin** [comment]
@gnidan sorry,I  wrote a wrong  word ,actually I use it like this.
![jinjin](https://user-images.githubusercontent.com/32841921/50432216-32052900-090b-11e9-8372-1b160835dd14.png)

**Comment by wanching** [comment]
@cantaloupeJinJin
I got this error when I use `truffle init`:
```
Downloading...
Error: Error making request to https://raw.githubusercontent.com/truffle-box/bare-box/master/truffle.js. Got error: connect ETIMEDOUT 10.0.0.1:443. Please check the format of the requested resource.
    at Request._callback (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-box/lib/utils/unbox.js:45:1)
    at self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:185:1)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:877:1)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
I upgrade to 4.1.15 and it works fine, it seems that 4.1.14 has some bugs, maybe you can try too.
```
npm uninstall -g truffle // If you already have truffle installed
npm install -g truffle@4.1.15
```
https://github.com/trufflesuite/truffle/releases

**Comment by loo41** [comment]
- i try to upgrade version，but not resolve this problem.
- i try to ping the address, but no response.
- i try to vpn, but invalid.
```
√ Preparing to download
× Downloading
RequestError: Error: connect ETIMEDOUT 69.171.234.48:443
Truffle v5.0.43 (core: 5.0.43)
Node v10.16.3
```
```
正在 Ping 69.171.234.48 具有 32 字节的数据:
请求超时。
请求超时。
请求超时。
```

**Comment by kroim** [comment]
Starting unbox...
=================

✔ Preparing to download box
✖ Downloading
Unbox failed!
✖ Downloading
Unbox failed!
RequestError: Error: connect ECONNREFUSED 151.101.228.133:443
    at new RequestError (/usr/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/errors.js:14:1)
    at Request.plumbing.callback (/usr/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:87:1)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:46:1)
    at self.callback (/usr/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:185:1)
    at Request.emit (events.js:223:5)
    at Request.onRequestError (/usr/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:881:1)
    at ClientRequest.emit (events.js:223:5)
    at TLSSocket.socketErrorListener (_http_client.js:415:9)
    at TLSSocket.emit (events.js:223:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Truffle v5.1.13 (core: 5.1.13)
Node v12.15.0

**Comment by kroim** [comment]
I solved this error using "sudo npm install -g request"

**Comment by kroim** [comment]
Or you can use "sudo truffle init"

**Comment by Dwgoing** [comment]
> # Starting unbox...
> ✔ Preparing to download box
> ✖ Downloading
> Unbox failed!
> ✖ Downloading
> Unbox failed!
> RequestError: Error: connect ECONNREFUSED 151.101.228.133:443
> at new RequestError (/usr/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/errors.js:14:1)
> at Request.plumbing.callback (/usr/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:87:1)
> at Request.RP$callback [as _callback] (/usr/lib/node_modules/truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:46:1)
> at self.callback (/usr/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:185:1)
> at Request.emit (events.js:223:5)
> at Request.onRequestError (/usr/lib/node_modules/truffle/build/webpack:/node_modules/request/request.js:881:1)
> at ClientRequest.emit (events.js:223:5)
> at TLSSocket.socketErrorListener (_http_client.js:415:9)
> at TLSSocket.emit (events.js:223:5)
> at emitErrorNT (internal/streams/destroy.js:92:8)
> at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
> at processTicksAndRejections (internal/process/task_queues.js:81:21)
> Truffle v5.1.13 (core: 5.1.13)
> Node v12.15.0

i got same error. but i can not solve with your answer

**Comment by kroim** [comment]
If you got fails from "sudo npm install -g request" and "sudo truffle init", you can get success from 
![image](https://user-images.githubusercontent.com/33049672/75699003-a9da9a80-5cea-11ea-82e4-5afae8d5610b.png)
I solved from this when I got fails from the 2 cases all.

**Comment by Dwgoing** [comment]
> @Dwgoing, If you got fails from "sudo npm install -g request" and "sudo truffle init", you can get success from
> ![image](https://user-images.githubusercontent.com/33049672/75699003-a9da9a80-5cea-11ea-82e4-5afae8d5610b.png)
> I solved from this when I got fails from the 2 cases all.

i will have a try again,thanks

**Comment by BITEEEE** [comment]
> > @Dwgoing, If you got fails from "sudo npm install -g request" and "sudo truffle init", you can get success from
> > ![image](https://user-images.githubusercontent.com/33049672/75699003-a9da9a80-5cea-11ea-82e4-5afae8d5610b.png)
> > I solved from this when I got fails from the 2 cases all.
> 
> i will have a try again,thanks

i got same error. but i can not solve with your two method.
