### ISSUE TITLE
Error: unknown account

### ISSUE THREAD

**Issue by inzig** [trufflesuite/truffle#767]
Hello guys, i am trying to deploy my smart contract on live network, i have successfully deployed the same contract on rinkeby but facing error
while on live network, here is the detail
1 - Account balance 0.10000 ethers
2 - geth command
geth --rpc --rpcapi db,eth,net,web3,personal --unlock="0x1C11f6b1A2d1c0b00ad4145eb067184736EB973f"
3 - truffle js
"live": {
network_id: 1,
host: "127.0.0.1",
port: 8545, // Different than the default below
from: "0x1C11f6b1A2d1c0b00ad4145eb067184736EB973f",
gas: 4612388
}
4 - Error
truffle migrate --network liveUsing network 'live'.

Running migration: 1_initial_migration.js
Deploying Migrations...
... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: unknown account
at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
at /usr/lib/node_modules/truffle/build/cli.bundled.js:331156:36
at /usr/lib/node_modules/truffle/build/cli.bundled.js:175492:11
at /usr/lib/node_modules/truffle/build/cli.bundled.js:314196:9
at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:70564:24)
at emitNone (events.js:91:20)

OS: Linux
Node: 6.2
npm: 3.10

**Comment by inzig** [comment]
Now facing the same issue on rinkeby network as well

**Comment by cgewecke** [comment]
@inzig This looks like a problem with unlocking accounts at Geth. Could you look at [their wiki](https://github.com/ethereum/go-ethereum/wiki/Managing-your-accounts) for help and verify `0x1C11f6b1A2d1c0b00ad4145eb067184736EB973f` is known to your Geth client. 

You can do this by launching geth and running the following in a separate terminal tab:
```
geth attach http://127.0.0.1:8545
...
> personal.listAccounts
```

Closing because this seems like it might not be a Truffle issue, but please re-open if you discover otherwise.
