### ISSUE TITLE
Geth 1.8.1 and truffle 4.0.6 migrate is giving errors

### ISSUE THREAD

**Issue by marshaln** [trufflesuite/truffle#816]
unable to deploy/migrate contracts on geth 1.8.1 private network with truffle 4.0.6 version. getting following error

Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: unknown transaction
```
    at Object.InvalidResponse (C:\Users\Marshal\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\errors.js:38:1)
    at C:\Users\Marshal\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1
    at C:\Users\Marshal\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-migrate\index.js:225:1
    at C:\Users\Marshal\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-provider\wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (C:\Users\Marshal\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\Marshal\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (C:\Users\Marshal\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\Marshal\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
    at IncomingMessage.<anonymous> (C:\Users\Marshal\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
    at emitNone (events.js:111:20)
```

**Comment by cgewecke** [comment]
@marshain - This is a known issue being tracked at #721. We'll be publishing [a fix](https://github.com/trufflesuite/truffle-contract/pull/99) for it early next week. 

Thanks for reporting - your issue title is more current than #271's  - but closing as duplicate.
