### ISSUE TITLE
The contract code couldn't be stored, please check your gas amount

### ISSUE THREAD

**Issue by freshonline** [trufflesuite/truffle#817]
I compile this exemple:
http://truffleframework.com/tutorials/robust-smart-contracts-with-openzeppelin
```
truffle migrate
Using network 'development'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0x789aea77d8e99503932be722ac92ead36848d8380c9532a8649b4b73addd1241
  Migrations: 0x0fb1f6c28fc2993289749fc92ca8361c154ef963
Saving successful migration to network...
  ... 0x5123b3558f4ed72b9a1706864ec91087d50603a90f968d7f6ec1549f07c2abdb
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying TutorialToken...
  ... 0x418bcaf91e66968e83dbd5457e5d143d61751ed201e1ddf1603cc489cbdc477b
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:147:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
```
```
/home/testnet/go-ethereum-1.7.3/build/bin/geth --rpc --port 30304 --rpcport 8599 --networkid 11 --rpcapi db,eth,web3,net,admin,miner,personal --cache 1024 --maxpeers 25 --datadir /home/testnet/.ethereum --keystore /home/testnet/.ethereum/keystore --nousb --testnet --mine --minerthreads 1 --unlock 0xC1320531dF2612B85e6FEDFd4d6358ed711bbe66 --password /home/testnet/pass
```
truffle.js:
```
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // for more about customizing your Truffle configuration!
  networks: {
    development: {
      host: "127.0.0.1",
      port: 8599,
      network_id: 3,
      from: "0xC1320531dF2612B85e6FEDFd4d6358ed711bbe66",
      gas: 1000000,
      gasPrice: 10000000000,
    }
  }
};

```
genesis.json:
```
{
  "config": {
    "chainId": 11,
    "homesteadBlock": 0,
    "eip155Block": 0,
    "eip158Block": 0
  },
  "nonce": "0x0000000000000033",
  "timestamp": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x8000000",
  "difficulty": "0x100",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x3333333333333333333333333333333333333333",
  "alloc": {}
}
```

    Operating System: Ubuntu 16.04.3 LTS
    Truffle v4.0.6 (core: 4.0.6)
    Solidity v0.4.19 (solc-js)
    Ethereum client: go-ethereum-1.7.3
    node version: v9.4.0
    npm version: 5.6.0

**Comment by cgewecke** [comment]
@freshonline The the chainID in the genesis should be the same as the network ID. There's a short guide to setting up the geth client for Ropsten [here](https://medium.com/@crissimrobert/a-guide-to-ropsten-testnet-setup-f8952d615417) you might find helpful. Otherwise it looks like you're close! Good work.

**Comment by freshonline** [comment]
OK, Thank you.
truffle.js:
```
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // for more about customizing your Truffle configuration!
  networks: {
    development: {
      host: "127.0.0.1",
      port: 8599,
      network_id: 11,
      from: "0xC1320531dF2612B85e6FEDFd4d6358ed711bbe66",
      gas: 1000000,
      gasPrice: 10000000000,
    }
  }
};
```
Have same result:
```
truffle compile
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/TutorialToken.sol...
Compiling zeppelin-solidity/contracts/math/SafeMath.sol...
Compiling zeppelin-solidity/contracts/token/ERC20/BasicToken.sol...
Compiling zeppelin-solidity/contracts/token/ERC20/ERC20.sol...
Compiling zeppelin-solidity/contracts/token/ERC20/ERC20Basic.sol...
Compiling zeppelin-solidity/contracts/token/ERC20/StandardToken.sol...
Writing artifacts to ./build/contracts

testnet@e3:~/oz-workspace$ truffle migrate
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x288e4497b2ade61618629450f636e54f955aa88ddbdf9a83d5fddad3f2b0ea4a
  Migrations: 0x1dd4e293cbf63593a416ba3a7fc62bcba46c6f96
Saving successful migration to network...
  ... 0xab002e3027f5224939acd0389d5313b43482bf91960c63ef3337508d8eff9125
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying TutorialToken...
  ... 0x5395c96f94fb3343c75f51ca81c4ba3db625e240c7535815094b512d3b4d9f74
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:147:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
```

**Comment by cgewecke** [comment]
@freshonline Could you try removing the **`--testnet`**  option on your Geth command? This was mentioned when they responded to your question at `go-ethereum`. That option asks Geth to connect to  **Ropsten** which has  **ChainID 3**. You seem to want to run a private network but are trying to connect to the public testnet.  

If you want to connect to Ropsten, AKA `--testnet`, remove all references to chainID or network 11 and start again by syncing your chain to Ropsten following the guide linked to above.

**Comment by cgewecke** [comment]
@freshonline I'm going to close this because we're going around a circles a little. . . .for the next issue you open could please look through the various suggestions you've been given and try make sure everything's in order. Thanks so much and good luck 😄.
