### ISSUE TITLE
TypeError: contract.detectNetwork is not a function

### ISSUE THREAD

**Issue by neilrjones** [trufflesuite/truffle#844]
- [ x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Trying to deploy a contract with constructor parameters to a private network.  Contracts without parameters deploy with no problem

## Steps to Reproduce

truffle.cmd migrate --reset

## Expected Behavior

Contract migrated and deployed

## Actual Results

truffle.cmd migrate --reset
Using network 'development'.

Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0xdd72b111135e5692bfd8c54a46eede53471ff6b2fbc9ab643fbb62e318825c5e
  Migrations: 0x6003fccaaf4f67b3c8419c3201ba40983753f370
Saving successful migration to network...
  ... 0x814fecd2ae043c5957e1ea0eecd211de6bc36d087da80b99378125af9d07581f
Saving artifacts...
Running migration: 2_d.js
Error encountered, bailing. Network state unknown. Review successful transactions manually.
TypeError: contract.detectNetwork is not a function
    at C:\Users\neilrjones\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-deployer\src\actions\deploy.js:6:1
    at C:\Users\neilrjones\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-deployer\src\actions\deploymany.js:15:1
    at Array.map (<anonymous>)
    at C:\Users\neilrjones\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-deployer\src\actions\deploymany.js:5:1
    at C:\Users\neilrjones\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-deployer\src\deferredchain.js:20:1
    at <anonymous>

## Environment

* Operating System: 
Windows 10
* Ethereum client:
Geth
Version: 1.7.3-stable
Git Commit: 4bb3c89d44e372e6a9ab85a8be0c9345265c763a
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9
Operating System: windows
GOPATH=
GOROOT=C:\tools\go

* Truffle version (`truffle version`):Truffle v4.0.6 (core: 4.0.6) Solidity v0.4.19 (solc-js)
* node version (`node --version`):
* npm version (`npm --version`): 5.5.1

2_deploy.js
/* eslint-disable */
var Owned = artifacts.require('Owned');
var SouSouMain = artifacts.require('SouSouMain');

require('dotenv').config();
var Web3 = require('web3');

if (typeof web3 !== 'undefined') {
  web3 = new Web3(web3.currentProvider);
} else {
  web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:8545'));
}
let softCap = 5000000000000000000;
let hardCap = 100000000000000000000;
let startTimestamp = Math.floor(Date.now() / 1000);
const endTime = startTimestamp + 86400 * 20; // 20 days
const oneEth = 1000000000000000000;
const minCap = 2000000000000000000;
const maxCap = 5000000000000000000;

module.exports = function(deployer, network, accounts) {
  var fundsWallet = accounts[0];
  var owner = accounts[0];
  var sousouId = 1;
  var cycles = 12;
  var durationSeconds = 4 * 7 * 24 * 60 * 60; // 4 weeks
  var numSubGroups = 0;
  var tokenIco = '0x0';

  deployer.deploy([
    SouSouMain,
    owner,
    sousouId,
    cycles,
    durationSeconds,
    numSubGroups
  ]);
};

truffle.js
require('babel-register');
require('babel-polyfill');

module.exports = {
  networks: {
    development: {
      host: '127.0.0.1',
      port: 8545,
      network_id: '*', // Match any network id
      from: '0x96e59edfbf5e4f92f682f740d4cba5b553520347', // eslint-disable-line
      gas: 2900000
    },
    private: {
      host: '127.0.0.1',
      port: 8545,
      network_id: '*', // Match any network id
      from: '0x96e59edfbf5e4f92f682f740d4cba5b553520347', // eslint-disable-line
      gas: 6700000, // 2900000
      gasPrice: 400000000000
    },
    rinkeby: {
      host: 'localhost', // eslint-disable-line
      port: 8545,
      from: '0x96e59edfbf5e4f92f682f740d4cba5b553520347', // eslint-disable-line
      network_id: 4,
      gas: 4612388, // Gas limit used for deploys
      gasPrice: 100000000000
    },
    ropsten: {
      host: 'localhost', // eslint-disable-line
      port: 8545,
      from: '0x96e59edfbf5e4f92f682f740d4cba5b553520347', // eslint-disable-line
      network_id: '3'
    }
  },
  mocha: {
    useColors: true,
    timeout: 0
  },
  solc: { optimizer: { enabled: true, runs: 200 } }
};

**Comment by neilrjones** [comment]
I believe we can close this issue.  Looks like Truffle does not like the [] when there is only one contract being deployed.

Change:
deployer.deploy([
SouSouMain,
owner,
sousouId,
cycles,
durationSeconds,
numSubGroups
]);
to:
deployer.deploy(
SouSouMain,
owner,
sousouId,
cycles,
durationSeconds,
numSubGroups
);

**Comment by neilrjones** [comment]
By the way,
Truffle does not seem to have a problem with the [] if no constructor parameters are passed.
deployer.deploy([SouSouFundsMet]);

Works with no problem but 
deployer.deploy([SouSouMain,owner,sousouId,cycles,durationSeconds,numSubGroups]);

Does not.
