### ISSUE TITLE
Reference Error - not defined

### ISSUE THREAD

**Issue by ArranMcC** [trufflesuite/truffle#943]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

truffle(development)> Election.deployed().then(function(instance) { app = instance })
ReferenceError: Election is not defined
truffle(development)> app.address
ReferenceError: app is not defined

Not sure why I'm receiving reference errors. No one replied on Gitter, and a Google search offered no solutions. 

## Environment

* Operating System: Windows 10
* Truffle version (`truffle version`): 4.1.8

**Comment by cgewecke** [comment]
@ArranMcC To use `deployed` you'll need to run `migrate` first. This deploys your contracts to the test chain managed by the `develop` shell. The [metacoin box](https://github.com/truffle-box/metacoin-box) is a working example you might find helpful, and check out the [migrations documentation](http://truffleframework.com/docs/getting_started/migrations#running-migrations) for help on writing deployment scripts:

```shell
$ mkdir metacoin
$ cd metacoin
$ truffle unbox metacoin
$ truffle develop

# ..... client launches ....

truffle(develop)> MetaCoin.deployed()
ReferenceError: MetaCoin is not defined . # <--- Your error
truffle(develop)> migrate                 # <--- Run `migrate` 
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...

# .... etc ....

Writing artifacts to ./build/contracts

Using network 'develop'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x4cb1916eb9734e8622d8e49a9a1a96c8338f8065f9ccee3963ff9dbc67fc8ae0
  Migrations: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
Saving successful migration to network...
  ... 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956

# ..... etc .....

truffle(develop)> MetaCoin.deployed()
TruffleContract {
  constructor: 
   { [Function: TruffleContract]
     _static_methods: 
      { setProvider: [Function: setProvider],   
```

**Comment by salmanahmad3333** [comment]
> Thanks! I think it was just due to truffle not being unboxed into an empty directory, something which the tutorials I was following didn't mention as they maybe thought it was obvious.

Please tell me how you resolved the issue. I have the same issue.

**Comment by sreekanth2474** [comment]
> @ArranMcC To use `deployed` you'll need to run `migrate` first. This deploys your contracts to the test chain managed by the `develop` shell. The [metacoin box](https://github.com/truffle-box/metacoin-box) is a working example you might find helpful, and check out the [migrations documentation](http://truffleframework.com/docs/getting_started/migrations#running-migrations) for help on writing deployment scripts:
> 
> ```shell
> $ mkdir metacoin
> $ cd metacoin
> $ truffle unbox metacoin
> $ truffle develop
> 
> # ..... client launches ....
> 
> truffle(develop)> MetaCoin.deployed()
> ReferenceError: MetaCoin is not defined . # <--- Your error
> truffle(develop)> migrate                 # <--- Run `migrate` 
> Compiling ./contracts/ConvertLib.sol...
> Compiling ./contracts/MetaCoin.sol...
> Compiling ./contracts/Migrations.sol...
> 
> # .... etc ....
> 
> Writing artifacts to ./build/contracts
> 
> Using network 'develop'.
> 
> Running migration: 1_initial_migration.js
>   Deploying Migrations...
>   ... 0x4cb1916eb9734e8622d8e49a9a1a96c8338f8065f9ccee3963ff9dbc67fc8ae0
>   Migrations: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
> Saving successful migration to network...
>   ... 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
> 
> # ..... etc .....
> 
> truffle(develop)> MetaCoin.deployed()
> TruffleContract {
>   constructor: 
>    { [Function: TruffleContract]
>      _static_methods: 
>       { setProvider: [Function: setProvider],   
> ```

Thanks! This helped

**Comment by sreekanth2474** [comment]
> @ArranMcC To use `deployed` you'll need to run `migrate` first. This deploys your contracts to the test chain managed by the `develop` shell. The [metacoin box](https://github.com/truffle-box/metacoin-box) is a working example you might find helpful, and check out the [migrations documentation](http://truffleframework.com/docs/getting_started/migrations#running-migrations) for help on writing deployment scripts:
> 
> ```shell
> $ mkdir metacoin
> $ cd metacoin
> $ truffle unbox metacoin
> $ truffle develop
> 
> # ..... client launches ....
> 
> truffle(develop)> MetaCoin.deployed()
> ReferenceError: MetaCoin is not defined . # <--- Your error
> truffle(develop)> migrate                 # <--- Run `migrate` 
> Compiling ./contracts/ConvertLib.sol...
> Compiling ./contracts/MetaCoin.sol...
> Compiling ./contracts/Migrations.sol...
> 
> # .... etc ....
> 
> Writing artifacts to ./build/contracts
> 
> Using network 'develop'.
> 
> Running migration: 1_initial_migration.js
>   Deploying Migrations...
>   ... 0x4cb1916eb9734e8622d8e49a9a1a96c8338f8065f9ccee3963ff9dbc67fc8ae0
>   Migrations: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
> Saving successful migration to network...
>   ... 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
> 
> # ..... etc .....
> 
> truffle(develop)> MetaCoin.deployed()
> TruffleContract {
>   constructor: 
>    { [Function: TruffleContract]
>      _static_methods: 
>       { setProvider: [Function: setProvider],   
> ```

**Comment by sreekanth2474** [comment]
> @ArranMcC To use `deployed` you'll need to run `migrate` first. This deploys your contracts to the test chain managed by the `develop` shell. The [metacoin box](https://github.com/truffle-box/metacoin-box) is a working example you might find helpful, and check out the [migrations documentation](http://truffleframework.com/docs/getting_started/migrations#running-migrations) for help on writing deployment scripts:
> 
> ```shell
> $ mkdir metacoin
> $ cd metacoin
> $ truffle unbox metacoin
> $ truffle develop
> 
> # ..... client launches ....
> 
> truffle(develop)> MetaCoin.deployed()
> ReferenceError: MetaCoin is not defined . # <--- Your error
> truffle(develop)> migrate                 # <--- Run `migrate` 
> Compiling ./contracts/ConvertLib.sol...
> Compiling ./contracts/MetaCoin.sol...
> Compiling ./contracts/Migrations.sol...
> 
> # .... etc ....
> 
> Writing artifacts to ./build/contracts
> 
> Using network 'develop'.
> 
> Running migration: 1_initial_migration.js
>   Deploying Migrations...
>   ... 0x4cb1916eb9734e8622d8e49a9a1a96c8338f8065f9ccee3963ff9dbc67fc8ae0
>   Migrations: 0x8cdaf0cd259887258bc13a92c0a6da92698644c0
> Saving successful migration to network...
>   ... 0xd7bc86d31bee32fa3988f1c1eabce403a1b5d570340a3a9cdba53a472ee8c956
> 
> # ..... etc .....
> 
> truffle(develop)> MetaCoin.deployed()
> TruffleContract {
>   constructor: 
>    { [Function: TruffleContract]
>      _static_methods: 
>       { setProvider: [Function: setProvider],   
> ```

Thanks! This helped.

**Comment by breakpointer** [comment]
I'm getting this issue as well but with my own contracts. I have run `migrate`, the console says it migrated my contracts, yet trying `<ContractName>.deployed()` throws a `ReferenceError`
```
   Replacing 'BootlegTraderApp'
   ----------------------------
   > transaction hash:    0xede83c2acbb7eb4dd835a1439e5029b4d5f14383dac1748d89be583acbadfcec
   > Blocks: 0            Seconds: 0
   > contract address:    0x8F43fb1eC19cE48642ec93901EA6B495cCf7DF6f
   > account:             0x753597F2393CE1bDB1Cd2ac3e9E91294f0c9098C
   > balance:             99.73966424
   > gas used:            599805
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.0119961 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.08388224 ETH


Summary
=======
> Total deployments:   3
> Final cost:          0.08934676 ETH

truffle(develop)> migrate
Network up to date.
truffle(develop)> BootlegTraderApp.deployed()
evalmachine.<anonymous>:0
BootlegTraderApp.deployed()
^

ReferenceError: BootlegTraderApp is not defined
    at evalmachine.<anonymous>:0:1
    at sigintHandlersWrap (vm.js:262:15)
    at Script.runInContext (vm.js:104:14)
    at runScript (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:391065:14)
    at Console.interpret (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:391079:19)
    at ReplManager.interpret (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:392005:18)
    at bound (domain.js:395:14)
    at REPLServer.runBound [as eval] (domain.js:408:12)
    at REPLServer.onLine (repl.js:639:10)
    at REPLServer.emit (events.js:189:13)
```
Is there a `require` step I'm missing? I don't see [any mention in the docs](https://truffleframework.com/docs/truffle/getting-started/interacting-with-your-contracts)

**Comment by breakpointer** [comment]
Running `networks` shows that it's there too... yet... still I get a `ReferenceError`
```
truffle(develop)> networks

Network: develop (id: 4447)
  BootlegToken: 0x6802091EdaA4Bf4e23AB24B635ef549a070C7bC6
  BootlegTraderApp: 0x8F43fb1eC19cE48642ec93901EA6B495cCf7DF6f
  Migrations: 0x971e251E7E7d26fF0C9fB100026348Ea542DB74f

```
...
```
truffle(develop)> BootlegTraderApp.deployed()
evalmachine.<anonymous>:0
BootlegTraderApp.deployed()
^

ReferenceError: BootlegTraderApp is not defined
    at evalmachine.<anonymous>:0:1
    at sigintHandlersWrap (vm.js:262:15)
    at Script.runInContext (vm.js:104:14)
    at runScript (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:391065:14)
    at Console.interpret (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:391079:19)
    at ReplManager.interpret (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:392005:18)
    at bound (domain.js:395:14)
    at REPLServer.runBound [as eval] (domain.js:408:12)
    at REPLServer.onLine (repl.js:639:10)
    at REPLServer.emit (events.js:189:13)
```
Very strange.

**Comment by CruzMolina** [comment]
Hey @breakpointer , which version of truffle are you using?

**Comment by breakpointer** [comment]
Hi @CruzMolina, here are the versions. Thanks for following up.
```
truffle(develop)> version
Truffle v5.0.4 (core: 5.0.4)
Solidity - 0.5.4 (solc-js)
Node v10.15.1
truffle(develo
```

**Comment by CruzMolina** [comment]
Huh, unable to reproduce on my end. Is the cause of this related to the comment you left in the other issue (unboxing in a different directory than you expected)?

**Comment by breakpointer** [comment]
Yeah, I'm unable to reproduce now on my end either. I'm guessing the actions I took to resolve the issue was to kill/restart the `truffle develop` console a couple times. 

This is unrelated to my other comment about the unboxing experience.

**Comment by jingyadong** [comment]
> Yeah, I'm unable to reproduce now on my end either. I'm guessing the actions I took to resolve the issue was to kill/restart the `truffle develop` console a couple times.
> 
> This is unrelated to my other comment about the unboxing experience.

I have the same problem with you. Have you solved it?

**Comment by 09Bleyle** [comment]
Hi , having  a similar problem did anyone solve it?

**Comment by shashanksinghthakur** [comment]
Hi I am having a similar problem 
Uncaught ReferenceError: TokenFarm is not defined
    at evalmachine.<anonymous>:1:9

please help

**Comment by miahdouble07** [comment]
> Dont know if you guys figured this out but for anyone else:
Try running **truffle migrate** in the directory folder first. 
Then after you **truffle develop**/**truffle console** try **let instance = await Scores.deployed()**
 Worked for me!

**Comment by miahdouble07** [comment]
Worked perfectly! Thank you! 

> @ArranMcC To use `deployed` you'll need to run `migrate` first. This deploys your contracts to the test chain managed by the `develop` shell. The [metacoin box](https://github.com/truffle-box/metacoin-box) is a working example you might find helpful, and check out the [migrations documentation](http://truffleframework.com/docs/getting_started/migrations#running-migrations) for help on writing deployment scripts:
>
