### ISSUE TITLE
truffle test:Unexpected identifier

### ISSUE THREAD

**Issue by zhuimengshaonian66** [trufflesuite/truffle#944]
everything is ok,but when i run truffle test , the problrm:: so sad i cant solve it   what happend??
even i write nothing in the test floder

 truffle(development)> truffle test
SyntaxError: Unexpected identifier
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.emit (events.js:211:7)
    at emitOne (events.js:116:13)
    at REPLServer.onLine (repl.js:468:10)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at bound (domain.js:301:14)
    at ReplManager.interpret (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-core/lib/repl.js:119:1)
    at Console.interpret (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-core/lib/console.js:164:1)
    at Object.runInContext (vm.js:119:10)
    at createScript (vm.js:80:10)

* Operating System: ubuntu 16.04
* testrpc:  6.0.3
* Truffle version (`truffle version`): 4.1.7
* node version (`node --version`):  v8.11.1
* npm version (`npm --version`): 5.8.0

**Comment by weijunlee** [comment]
Do you find the reason of the problerm? Could you tell me what I need to do. Thanks very much.
