### ISSUE TITLE
truffle unbox webpack is making Error: Error making request

### ISSUE THREAD

**Issue by dharmeshnirmal** [trufflesuite/truffle#961]
- [ ] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

Not able to run $truffle unbox webpack

## Steps to Reproduce

Run $truffle unbox webpack

## Expected Behavior

It should run without error

## Actual Results

Downloading...
Error: Error making request to https://raw.githubusercontent.com/truffle-box/webpack-box/master/truffle.js. Got error: unable to get local issuer certificate. Please check the format of the requested resource.
    at Request._callback (C:\Users\E055362\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-box\lib\utils\unbox.js:45:1)
    at self.callback (C:\Users\E055362\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request\request.js:185:1)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (C:\Users\E055362\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request\request.js:877:1)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)

## Environment

* Operating System: Window 10 Ent.
* Ethereum client:
* Truffle version (`truffle version`): v4.1.8 (core: 4.1.9)
* node version (`node --version`): v8.11.2
* npm version (`npm --version`): 5.6.0

**Comment by dharmeshnirmal** [comment]
@cgewecke Yes I am behind a proxy. Also I am new for npm and all can So I am not able to figure out exact solution. Can you please help me to find it.

**Comment by cgewecke** [comment]
@dharmeshnirmal The simplest thing might be to clone [the repository](https://github.com/truffle-box/webpack-box) you want using `git clone`. Then:
```
cd webpack-box
rm -rf .git # Remove the .git record 
npm install
```

The other option is to look at the `request` module's guide for [controlling proxy behavior with environment variables](https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables) and do whatever is appropriate for your system.
