### ISSUE TITLE
VM Exception while processing transaction: revert

### ISSUE THREAD

**Issue by NatalieChin80** [trufflesuite/truffle#965]
- [x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

I have the exact same code, build, `npm modules`, truffle environment, and ganache on two MBP's. One MBP is running OS X El Capitan, the other is running OS X High Sierra, and tests are running on successfully on the former and not the latter. 

## Steps to Reproduce

1. Clone the repo: https://github.com/STKtoken/STK-smart-contracts on branch `develop` 
2. Run `npm install` 
3. Open Ganache Desktop Client 
4. Run `truffle test` 

## Expected Behavior

Both laptops running consistent tests. 

## Actual Results

Tests are successfully passing on one laptop. The other one has the following output. 

```
  Contract: STKToken
    ✓ Should have 1 billion tokens in first account
    ✓ Should have symbol as STK

  Contract: STKChannelClosing
    ✓ Should deposit 50 tokens to the stkchannel (67ms)
    ✓ Should fail when user tries to  close the channel with a valid signature but amount is above the deposited amount
    ✓ Should fail when user tries to close the channel with a self signed signature
    ✓ Should fail when non-channel participant tries to close the channel with a valid signature
    ✓ Should fail when user tries to close channel with a signature signed by someone else (invalid signature)
    1) Should allow user to close the channel with a valid signature
    > No events were emitted
    ✓ Should fail when Channel recipient contests the closing of the channel but the amount is above the deposited amount (107ms)
    2) Should allow channel recipient to contest the closing of the channel
    > No events were emitted
    ✓ Should not be able to close the channel after it has already been closed
    ✓ Should not be able to update the channel once closed as closing address (122ms)
    ✓ Should not be able to update channel with lower nonce value  (113ms)
    3) Should be able to update the state of the channel with a higher nonce as non-closing address
    > No events were emitted
    ✓ Should fail when we try to settle the address before the time period is expired
waiting for 10 blocks
estimated gas cost of settling the channel: 36568
    ✓ Should transfer funds to user once channel has settled (2655ms)
    ✓ Should be able to reset the state of the channel after settling (95ms)
    4) Should be able to have token remain in the channel after settling

    Events emitted during test:
    ---------------------------

    Approval(_owner: <indexed>, _spender: <indexed>, _value: 100)
    Transfer(_from: <indexed>, _to: <indexed>, _value: 100)

    ---------------------------

  Contract: STKChannel
    ✓ STK Channel is deployed
    ✓ Should have STK channel user account as the first account
    ✓ Should have second account as Recipient account
    ✓ Should have Channel expiry time as 10
    ✓ Should Deposit 50 tokens to the stkchannel (66ms)
    ✓ Should close the channel without a signature


  20 passing (4s)
  4 failing

  1) Contract: STKChannelClosing Should allow user to close the channel with a valid signature:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) Contract: STKChannelClosing Should allow channel recipient to contest the closing of the channel :
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  3) Contract: STKChannelClosing Should be able to update the state of the channel with a higher nonce as non-closing address:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  4) Contract: STKChannelClosing Should be able to have token remain in the channel after settling:
     Error: VM Exception while processing transaction: revert
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1056:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

## Environment

* Operating System: Laptop 1 (OS X High Sierra), Laptop 2 (OS X El Capitan) 
* Ethereum Client: Ganache 1.0.2 
* Truffle version (`truffle version`): `Truffle v4.1.8 (core: 4.1.8)` on both laptops 
* node version (`node --version`): `v8.9.3` on both laptops 
* npm version (`npm --version`): `6.0.1` on both laptops

**Comment by cgewecke** [comment]
Hi @NatalieChin80, thanks for such a clear report and for linking to your repository. 

It looks like Zeppelin's `assertRevert` function might be invoked incorrectly in the STKChannelClosing tests, causing weird async failures. And one of your computers might be super fast, one a little slow.

**Example STKChannelClosing test:**
```javascript 
it('Should fail when user tries to close channel with a signature signed by someone else (invalid signature)',async()=>
  {
      const nonce = 1;
      const amount = 2;
      const cryptoParams = closingHelper.getClosingParameters(nonce,amount,STKChannel.address,nonChannelPart);
      const channel = await STKChannel.deployed();
      try
      {
          await channel.close(nonce,amount,cryptoParams.v,cryptoParams.r,cryptoParams.s)
          assert.fail('The signature should have caused an exception to be thrown');
      }
      catch(error)
      {
         // `assertRevert` is async & expects promise as an arg?
         // It's also been rewritten in the `helpers` code? (See below) 
        assertRevert(error); 
  })
```

**Example test from zeppelin-solidity**
```javascript
it('can not perform normal process in pause', async function () {
    let Pausable = await PausableMock.new();
    await Pausable.pause();
    let count0 = await Pausable.count();
    assert.equal(count0, 0);

    await assertRevert(Pausable.normalProcess());   // Is `awaited`, gets promise as arg
    let count1 = await Pausable.count();
    assert.equal(count1, 0);
});
```

**zeppelin-solidity's assertRevert** (yours has been modified....)
```javascript
module.exports = async promise => {
  try {
    await promise;
    assert.fail('Expected revert not received');
  } catch (error) {
    const revertFound = error.message.search('revert') >= 0;
    assert(revertFound, `Expected "revert", got ${error} instead`);
  }
};
```

**Comment by cgewecke** [comment]
@NatalieChin80 Closing because this looks like an issue with how you're handling error case promises in your tests. Please feel free to ping if the suggestions above don't resolve.

**Comment by NatalieChin80** [comment]
Hello @cgewecke - just a quick update. After a few additional days of debugging, I actually found out the error wasn't related to the way the assert is called. Rather, the assert for the hash for the signer address was always incorrect, as it was originally hardcoded into one of the tests (I've been trying to find a way around this) - thus, the require for the signer kept breaking. I appreciate you taking the time to try to help me figure out what was wrong - thanks!

**Comment by cgewecke** [comment]
Oh good! Thanks for the update @NatalieChin80.
