### ISSUE TITLE
Error making request to https://raw.githubusercontent.com/truffle-box/bare-box/master/truffle.js

### ISSUE THREAD

**Issue by sugalivijaychari** [trufflesuite/truffle#992]
I am a beginner. I started testrpc and after truffle. I got error as below. Please help me out of this.

 E:\solidity-experiments>truffle init
Downloading...
Error: Error making request to https://raw.githubusercontent.com/truffle-box/bare-box/master/truffle.js. Got error: unable to verify the first certificate. Please check the format of the requested resource.
    at Request._callback (C:\Users\Vijay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\truffle-box\lib\utils\unbox.js:45:1)
    at self.callback (C:\Users\Vijay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request\request.js:186:1)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (C:\Users\Vijay\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request\request.js:878:1)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

E:\solidity-experiments>truffle init

**Comment by cgewecke** [comment]
Hi @sugalivijaychari 

Thanks for opening. Have [responded](https://github.com/trufflesuite/truffle/issues/766#issuecomment-395449996) to your other report at #766. 

Closing as duplicate.
